import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentAttackGroup, passBattleGroup, passDamageGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro compatibility harness battle windows", () => {
  it("runs scripted battle-window fixtures against the TypeScript engine", () => {
    const battleCards: DuelCardData[] = [
      { code: "100", name: "Fixture Attacker", kind: "monster", attack: 1800, defense: 1200 },
      { code: "300", name: "Fixture Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Fixture Defender", kind: "monster", attack: 1500, defense: 1600 },
    ];
    const fixtures: ScriptedDuelFixture[] = [
      {
        name: "direct attack pass fixture",
        options: { seed: 41, startingHandSize: 2 },
        decks: {
          0: { main: ["100", "300"] },
          1: { main: ["400", "400"] },
        },
        setup: {
          moveCards: [{ player: 0, code: "100", from: "hand", to: "monsterZone", position: "faceUpAttack" }],
        },
        responses: [
          makeScriptedStep(makeResponseSelector("changePhase", 0, { phase: "battle" })),
          makeScriptedStep(makeResponseSelector("declareAttack", 0, { attackerUid: "p0-deck-100-0" }), {
            after: {
              source: "edopro",
              windowId: 2,
              waitingFor: 1,
              phase: "battle",
              battleStep: "attack",
              battleWindow: {
                id: 1,
                kind: "attackNegationResponse",
                step: "attack",
                attackerUid: "p0-deck-100-0",
                responsePlayer: 1,
                attackNegated: false,
              },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [{ type: "passAttack", player: 1, windowId: 2, windowKind: "battle", count: 1 }],
              legalActionGroups: [passBattleGroup(1, "passAttack", 1, 2)],
              absentLegalActions: [{ type: "passDamage", player: 1 }],
              absentLegalActionGroups: [
                {
                  player: 1,
                  label: "Pass",
                  actions: [{ type: "passDamage", player: 1 }],
                },
              ],
            },
          }),
          makeScriptedStep(makeResponseSelector("passAttack", 1), {
            snapshotRestore: true,
            before: {
              source: "edopro",
              windowId: 2,
              waitingFor: 1,
              battleStep: "attack",
              battleWindow: {
                id: 1,
                kind: "attackNegationResponse",
                step: "attack",
                attackerUid: "p0-deck-100-0",
                responsePlayer: 1,
                attackNegated: false,
              },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [{ type: "passAttack", player: 1, windowId: 2, windowKind: "battle", count: 1 }],
              legalActionGroups: [passBattleGroup(1, "passAttack", 1, 2)],
            },
          }),
          makeScriptedStep(makeResponseSelector("passAttack", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1), {
            snapshotRestore: true,
            before: {
              source: "edopro",
              battleStep: "damage",
              battleWindow: {
                kind: "startDamageStep",
                step: "damage",
                attackerUid: "p0-deck-100-0",
                responsePlayer: 1,
                attackNegated: false,
              },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [{ type: "passDamage", player: 1, windowKind: "battle", count: 1 }],
              legalActionGroups: [passDamageGroup(1)],
            },
          }),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1), {
            snapshotRestore: true,
            before: {
              source: "edopro",
              battleStep: "damage",
              battleWindow: {
                kind: "beforeDamageCalculation",
                step: "damage",
                attackerUid: "p0-deck-100-0",
                responsePlayer: 1,
                attackNegated: false,
              },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [{ type: "passDamage", player: 1, windowKind: "battle", count: 1 }],
              legalActionGroups: [passDamageGroup(1)],
            },
          }),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1), {
            snapshotRestore: true,
            before: {
              source: "edopro",
              battleStep: "damageCalculation",
              battleWindow: {
                kind: "duringDamageCalculation",
                step: "damageCalculation",
                attackerUid: "p0-deck-100-0",
                responsePlayer: 1,
                attackNegated: false,
              },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [{ type: "passDamage", player: 1, windowKind: "battle", count: 1 }],
              legalActionGroups: [passDamageGroup(1)],
            },
          }),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1), {
            snapshotRestore: true,
            before: {
              source: "edopro",
              battleStep: "damage",
              battleWindow: {
                kind: "afterDamageCalculation",
                step: "damage",
                attackerUid: "p0-deck-100-0",
                responsePlayer: 1,
                attackNegated: false,
              },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [{ type: "passDamage", player: 1, windowKind: "battle", count: 1 }],
              legalActionGroups: [passDamageGroup(1)],
            },
          }),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1), {
            snapshotRestore: true,
            before: {
              source: "edopro",
              battleStep: "damage",
              battleWindow: {
                kind: "endDamageStep",
                step: "damage",
                attackerUid: "p0-deck-100-0",
                responsePlayer: 1,
                attackNegated: false,
              },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [{ type: "passDamage", player: 1, windowKind: "battle", count: 1 }],
              legalActionGroups: [passDamageGroup(1)],
            },
          }),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
        ],
        expected: {
          source: "edopro",
          phase: "battle",
          waitingFor: 0,
          lifePoints: { 1: 6200 },
          pendingBattle: false,
          currentAttack: false,
          battleWindow: null,
          chain: [],
          pendingTriggers: [],
          prompt: null,
          legalActions: [{ type: "changePhase", player: 0, phase: "main2", count: 1 }],
          legalActionGroups: [turnGroup()],
          absentLegalActions: [{ type: "declareAttack", player: 0, attackerUid: "p0-deck-100-0" }],
          absentLegalActionGroups: [absentAttackGroup("p0-deck-100-0")],
          locations: { monsterZone: ["100"] },
          logIncludes: ["Direct attack"],
        },
      },
      {
        name: "attack window quick fixture",
        options: { seed: 42, startingHandSize: 2 },
        decks: {
          0: { main: ["100", "300"] },
          1: { main: ["400", "400"] },
        },
        setup: {
          moveCards: [{ player: 0, code: "100", from: "hand", to: "monsterZone", position: "faceUpAttack" }],
          effects: [
            {
              id: "fixture-attack-window-quick",
              player: 0,
              code: "300",
              location: "hand",
              event: "quick",
              range: ["hand"],
              oncePerTurn: true,
              logMessage: "Fixture attack-window quick resolved",
            },
          ],
        },
        responses: [
          makeScriptedStep(makeResponseSelector("changePhase", 0, { phase: "battle" })),
          makeScriptedStep(makeResponseSelector("declareAttack", 0, { attackerUid: "p0-deck-100-0" })),
          makeScriptedStep(makeResponseSelector("passAttack", 1)),
          makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-attack-window-quick" })),
          makeScriptedStep(makeResponseSelector("passAttack", 1)),
          makeScriptedStep(makeResponseSelector("passAttack", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
        ],
        expected: {
          source: "edopro",
          phase: "battle",
          waitingFor: 0,
          lifePoints: { 1: 6200 },
          pendingBattle: false,
          currentAttack: false,
          battleWindow: null,
          chain: [],
          pendingTriggers: [],
          prompt: null,
          legalActions: [{ type: "changePhase", player: 0, phase: "main2", count: 1 }],
          absentLegalActions: [{ type: "declareAttack", player: 0, attackerUid: "p0-deck-100-0" }],
          locations: { monsterZone: ["100"] },
          logIncludes: ["Fixture attack-window quick resolved", "Direct attack"],
        },
      },
      {
        name: "damage window quick fixture",
        options: { seed: 43, startingHandSize: 2 },
        decks: {
          0: { main: ["100", "300"] },
          1: { main: ["400", "400"] },
        },
        setup: {
          moveCards: [{ player: 0, code: "100", from: "hand", to: "monsterZone", position: "faceUpAttack" }],
          effects: [
            {
              id: "fixture-damage-step-quick",
              player: 0,
              code: "300",
              location: "hand",
              event: "quick",
              range: ["hand"],
              oncePerTurn: true,
              property: 0x4000,
              logMessage: "Fixture damage-step quick resolved",
            },
            {
              id: "fixture-damage-calculation-quick",
              player: 0,
              code: "300",
              location: "hand",
              event: "quick",
              range: ["hand"],
              oncePerTurn: true,
              property: 0x8000,
              logMessage: "Fixture damage-calculation quick resolved",
            },
          ],
        },
        responses: [
          makeScriptedStep(makeResponseSelector("changePhase", 0, { phase: "battle" })),
          makeScriptedStep(makeResponseSelector("declareAttack", 0, { attackerUid: "p0-deck-100-0" })),
          makeScriptedStep(makeResponseSelector("passAttack", 1)),
          makeScriptedStep(makeResponseSelector("passAttack", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-damage-step-quick" })),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-damage-calculation-quick" })),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
        ],
        expected: {
          source: "edopro",
          phase: "battle",
          waitingFor: 0,
          lifePoints: { 1: 6200 },
          pendingBattle: false,
          currentAttack: false,
          battleWindow: null,
          chain: [],
          pendingTriggers: [],
          prompt: null,
          legalActions: [{ type: "changePhase", player: 0, phase: "main2", count: 1 }],
          absentLegalActions: [{ type: "declareAttack", player: 0, attackerUid: "p0-deck-100-0" }],
          locations: { monsterZone: ["100"] },
          logIncludes: ["Fixture damage-step quick resolved", "Fixture damage-calculation quick resolved", "Direct attack"],
        },
      },
      {
        name: "replay decision after target leaves fixture",
        options: { seed: 44, startingHandSize: 2 },
        decks: {
          0: { main: ["100", "300"] },
          1: { main: ["400", "400"] },
        },
        setup: {
          moveCards: [
            { player: 0, code: "100", from: "hand", to: "monsterZone", position: "faceUpAttack" },
            { player: 1, code: "400", from: "hand", to: "monsterZone", position: "faceUpAttack" },
          ],
          effects: [
            {
              id: "fixture-remove-target-before-damage",
              player: 0,
              code: "300",
              location: "hand",
              event: "quick",
              range: ["hand"],
              oncePerTurn: true,
              moveCardsOnResolve: [{ player: 1, code: "400", from: "monsterZone", to: "graveyard" }],
              logMessage: "Fixture target left before damage",
            },
          ],
        },
        responses: [
          makeScriptedStep(makeResponseSelector("changePhase", 0, { phase: "battle" })),
          makeScriptedStep(makeResponseSelector("declareAttack", 0, { attackerUid: "p0-deck-100-0", targetUid: "p1-deck-400-1" })),
          makeScriptedStep(makeResponseSelector("passAttack", 1)),
          makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-remove-target-before-damage" })),
          makeScriptedStep(makeResponseSelector("passAttack", 1)),
          makeScriptedStep(makeResponseSelector("passAttack", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0), {
            after: {
              source: "edopro",
              battleStep: "attack",
              battleWindow: {
                kind: "replayDecision",
                step: "attack",
                attackerUid: "p0-deck-100-0",
                responsePlayer: 0,
                attackNegated: false,
              },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [
                { type: "cancelAttack", player: 0, windowId: 16, windowKind: "battle", attackerUid: "p0-deck-100-0", count: 1 },
                { type: "replayAttack", player: 0, windowId: 16, windowKind: "battle", attackerUid: "p0-deck-100-0", count: 1 },
              ],
              absentLegalActions: [{ type: "passDamage", player: 0 }],
              logIncludes: ["Replay decision pending"],
            },
          }),
          makeScriptedStep(makeResponseSelector("cancelAttack", 0, { attackerUid: "p0-deck-100-0" }), {
            snapshotRestore: true,
            before: {
              source: "edopro",
              battleWindow: {
                kind: "replayDecision",
                step: "attack",
                attackerUid: "p0-deck-100-0",
                responsePlayer: 0,
              },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [{ type: "cancelAttack", player: 0, windowId: 16, windowKind: "battle", attackerUid: "p0-deck-100-0", count: 1 }],
            },
          }),
        ],
        expected: {
          source: "edopro",
          phase: "battle",
          waitingFor: 0,
          lifePoints: { 1: 8000 },
          pendingBattle: false,
          currentAttack: false,
          battleWindow: null,
          chain: [],
          pendingTriggers: [],
          prompt: null,
          legalActions: [{ type: "changePhase", player: 0, phase: "main2", count: 1 }],
          absentLegalActions: [{ type: "declareAttack", player: 0, attackerUid: "p0-deck-100-0" }],
          attacksDeclared: ["p0-deck-100-0"],
          attackCanceledUids: [],
          attackedTargetUids: ["p1-deck-400-1"],
          battlePairs: [{ attackerUid: "p0-deck-100-0", targetUid: "p1-deck-400-1" }],
          locations: { monsterZone: ["100"], graveyard: ["400"] },
          locationCounts: { monsterZone: { "100": 1 }, graveyard: { "400": 1 } },
          cards: [
            { uid: "p0-deck-100-0", location: "monsterZone", controller: 0 },
            { uid: "p1-deck-400-1", location: "graveyard", controller: 1 },
          ],
          logIncludes: ["Fixture target left before damage", "Replay decision pending", "Canceled replay attack"],
        },
      },
      {
        name: "replay decision after target count changes fixture",
        options: { seed: 45, startingHandSize: 3 },
        decks: {
          0: { main: ["100", "300", "300"] },
          1: { main: ["400", "400", "400"] },
        },
        setup: {
          moveCards: [
            { player: 0, code: "100", from: "hand", to: "monsterZone", position: "faceUpAttack" },
            { player: 1, code: "400", from: "hand", to: "monsterZone", position: "faceUpAttack" },
          ],
          effects: [
            {
              id: "fixture-add-target-before-damage",
              player: 0,
              code: "300",
              location: "hand",
              event: "quick",
              range: ["hand"],
              oncePerTurn: true,
              moveCardsOnResolve: [{ player: 1, code: "400", from: "hand", to: "monsterZone", position: "faceUpAttack" }],
              logMessage: "Fixture target count changed before damage",
            },
          ],
        },
        responses: [
          makeScriptedStep(makeResponseSelector("changePhase", 0, { phase: "battle" })),
          makeScriptedStep(makeResponseSelector("declareAttack", 0, { attackerUid: "p0-deck-100-0", targetUid: "p1-deck-400-2" })),
          makeScriptedStep(makeResponseSelector("passAttack", 1)),
          makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-add-target-before-damage" })),
          makeScriptedStep(makeResponseSelector("passAttack", 1)),
          makeScriptedStep(makeResponseSelector("passAttack", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0), {
            after: {
              source: "edopro",
              battleWindow: {
                kind: "replayDecision",
                step: "attack",
                attackerUid: "p0-deck-100-0",
                responsePlayer: 0,
              },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [
                { type: "cancelAttack", player: 0, windowId: 16, windowKind: "battle", attackerUid: "p0-deck-100-0", count: 1 },
                { type: "replayAttack", player: 0, windowId: 16, windowKind: "battle", attackerUid: "p0-deck-100-0", targetUid: "p1-deck-400-2", count: 1 },
                { type: "replayAttack", player: 0, windowId: 16, windowKind: "battle", attackerUid: "p0-deck-100-0", targetUid: "p1-deck-400-1", count: 1 },
              ],
              logIncludes: ["Replay decision pending"],
            },
          }),
          makeScriptedStep(makeResponseSelector("replayAttack", 0, { attackerUid: "p0-deck-100-0", targetUid: "p1-deck-400-1" }), {
            snapshotRestore: true,
            before: {
              source: "edopro",
              battleWindow: { kind: "replayDecision", step: "attack", attackerUid: "p0-deck-100-0", responsePlayer: 0 },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [{ type: "replayAttack", player: 0, windowId: 16, windowKind: "battle", attackerUid: "p0-deck-100-0", targetUid: "p1-deck-400-1", count: 1 }],
            },
            after: {
              source: "edopro",
              battleWindow: {
                kind: "attackNegationResponse",
                step: "attack",
                attackerUid: "p0-deck-100-0",
                targetUid: "p1-deck-400-1",
                responsePlayer: 1,
              },
              pendingBattle: true,
              currentAttack: true,
              legalActions: [{ type: "passAttack", player: 1, count: 1 }],
              logIncludes: ["Replayed attack on Fixture Defender"],
            },
          }),
          makeScriptedStep(makeResponseSelector("passAttack", 1)),
          makeScriptedStep(makeResponseSelector("passAttack", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
          makeScriptedStep(makeResponseSelector("passDamage", 1)),
          makeScriptedStep(makeResponseSelector("passDamage", 0)),
        ],
        expected: {
          source: "edopro",
          phase: "battle",
          waitingFor: 0,
          lifePoints: { 1: 7700 },
          pendingBattle: false,
          currentAttack: false,
          battleWindow: null,
          chain: [],
          pendingTriggers: [],
          prompt: null,
          legalActions: [{ type: "changePhase", player: 0, phase: "main2", count: 1 }],
          absentLegalActions: [{ type: "declareAttack", player: 0, attackerUid: "p0-deck-100-0" }],
          attacksDeclared: ["p0-deck-100-0"],
          attackCanceledUids: [],
          attackedTargetUids: ["p1-deck-400-2", "p1-deck-400-1"],
          battlePairs: [
            { attackerUid: "p0-deck-100-0", targetUid: "p1-deck-400-2" },
            { attackerUid: "p0-deck-100-0", targetUid: "p1-deck-400-1" },
          ],
          locations: { monsterZone: ["100", "400"], graveyard: ["400"] },
          locationCounts: { monsterZone: { "100": 1, "400": 1 }, graveyard: { "400": 1 } },
          cards: [
            { uid: "p0-deck-100-0", location: "monsterZone", controller: 0 },
            { uid: "p1-deck-400-2", location: "monsterZone", controller: 1 },
            { uid: "p1-deck-400-1", location: "graveyard", controller: 1 },
          ],
          logIncludes: ["Fixture target count changed before damage", "Replay decision pending", "Replayed attack on Fixture Defender"],
        },
      },
    ];

    for (const fixture of fixtures) {
      expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(battleCards) })).toEqual({ ok: true, failures: [] });
    }
  });
});
