import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  openEffectGroup,
  summonGroup,
  triggerActivationGroup,
  triggerDeclineGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution opponent same-bucket optional decline pass-handoff opponent-response until-chain-end limit fixture", () => {
  it("keeps until-chain-end limits after the opponent responds from a restored opponent optional decline-first handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Opponent Optional Decline Handoff Until Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Opponent Optional Decline Handoff Until Turn Blocked Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Opponent Optional Decline Handoff Until Turn Optional", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Opponent Optional Decline Handoff Until First Opponent", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Opponent Optional Decline Handoff Until Second Opponent", kind: "monster", attack: 1200, defense: 1200 },
      { code: "700", name: "Opponent Optional Decline Handoff Until Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Optional Decline Handoff Until Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Opponent Optional Decline Handoff Until Opponent Chain Limiter", kind: "monster", attack: 1600, defense: 1000 },
      { code: "950", name: "Opponent Optional Decline Handoff Until Opponent Followup", kind: "monster", attack: 1300, defense: 1300 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution opponent same-bucket optional decline pass-handoff opponent-response until-chain-end limit fixture",
      options: { seed: 398, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "700", "800"] },
        1: { main: ["400", "500", "900", "950", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-chain-resolution-opponent-optional-decline-handoff-until-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 1, code: "900", from: "hand", to: "graveyard" },
              { player: 1, code: "950", from: "hand", to: "graveyard" },
            ],
            logMessage: "Chain resolution opponent optional decline handoff until starter resolved",
          },
          {
            id: "fixture-chain-resolution-turn-optional-decline-handoff-until",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain resolution turn optional decline handoff until should not resolve",
          },
          {
            id: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain resolution first opponent optional decline handoff until resolved",
          },
          {
            id: "fixture-chain-resolution-second-opponent-optional-decline-handoff-until",
            player: 1,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain resolution second opponent optional decline handoff until should not resolve",
          },
          {
            id: "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Chain resolution opponent optional decline handoff until turn blocked should not resolve",
          },
          {
            id: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter",
            player: 1,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 1 },
            logMessage: "Chain resolution opponent optional decline handoff until opponent chain limiter resolved",
          },
          {
            id: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-followup",
            player: 1,
            code: "950",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Chain resolution opponent optional decline handoff until opponent followup should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-chain-resolution-turn-optional-decline-handoff-until" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps turn optional decline priority restorable before restored opponent same-bucket optional until-chain-end handoff begins",
            phase: "main1",
            windowId: 1,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [
              { player: 0, effectId: "fixture-chain-resolution-turn-optional-decline-handoff-until", eventName: "sentToGraveyard", triggerBucket: "turnOptional", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional-decline-handoff-until", triggerBucket: "turnOptional", count: 1 },
              { type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional-decline-handoff-until", triggerBucket: "turnOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(0, "fixture-chain-resolution-turn-optional-decline-handoff-until", "turnOptional", 1, 1),
              triggerDeclineGroup(0, "fixture-chain-resolution-turn-optional-decline-handoff-until", "turnOptional", 1, 1),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter" },
              { type: "activateTrigger", player: 1, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked", 1, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter", 1, "triggerBucket"),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", "opponentOptional", 1, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "800", "400", "500", "800"] },
            logIncludes: ["Chain resolution opponent optional decline handoff until starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro restores opponent same-bucket optional trigger ordering before pass-handoff decline-first until-chain-end response checks",
            phase: "main1",
            windowId: 2,
            windowKind: "triggerBucket",
            waitingFor: 1,
            chain: [],
            pendingTriggers: [
              { player: 1, effectId: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
            ],
            pendingTriggerBuckets: [{ player: 1, triggerBucket: "opponentOptional" }],
            triggerOrderPrompt: { type: "orderTriggers", player: 1, triggerBucket: "opponentOptional" },
            legalActionCounts: { 0: 0, 1: 4 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", triggerBucket: "opponentOptional", count: 1 },
              { type: "declineTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", triggerBucket: "opponentOptional", count: 1 },
              { type: "activateTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", triggerBucket: "opponentOptional", count: 1 },
              { type: "declineTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", triggerBucket: "opponentOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(1, "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", "opponentOptional", 1, 2),
              triggerDeclineGroup(1, "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", "opponentOptional", 1, 2),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked" },
              { type: "activateEffect", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked", 2, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter", 2, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "800", "400", "500", "800"] },
            logIncludes: ["Chain resolution opponent optional decline handoff until starter resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("declineTrigger", 1, { effectId: "fixture-chain-resolution-second-opponent-optional-decline-handoff-until" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until" })),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps turn-player chain-response priority restorable before opponent optional until-chain-end handoff",
            phase: "main1",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 1, effectId: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" }],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked", 1, 4),
              chainPassGroup(0, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter" },
              { type: "activateTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter", 4),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", "opponentOptional", 4, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "800", "400", "500", "800"] },
            logIncludes: ["Chain resolution opponent optional decline handoff until starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro hands restored opponent optional trigger-chain responses to the opponent before the opponent's SetChainLimitTillChainEnd handoff response",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 1, effectId: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" }],
            chainPasses: [0],
            legalActionCounts: { 0: 0, 1: 3 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter", count: 1 },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 5,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter", count: 1 },
                  { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-followup", count: 1 },
                ],
              },
              chainPassGroup(1, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked" },
              { type: "activateTrigger", player: 1, windowId: 5, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked", 5),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", "opponentOptional", 5, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "800", "400", "500", "800"] },
            logIncludes: ["Chain resolution opponent optional decline handoff until starter resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps opponent optional handoff response choices restorable before until-chain-end limits apply",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 1, effectId: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" }],
            chainPasses: [0],
            legalActionCounts: { 0: 0, 1: 3 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter", count: 1 },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 5,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter", count: 1 },
                  { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-followup", count: 1 },
                ],
              },
              chainPassGroup(1, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked" },
              { type: "activateTrigger", player: 1, windowId: 5, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked", 5),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", "opponentOptional", 5, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "800", "400", "500", "800"] },
            logIncludes: ["Chain resolution opponent optional decline handoff until starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro applies SetChainLimitTillChainEnd restrictions after an opponent responds from a restored opponent optional SEGOC handoff",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 1, effectId: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter", sourceUid: "p1-deck-900-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-followup", 1, 6),
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter" },
              { type: "activateTrigger", player: 1, windowId: 6, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked", 6),
              absentChainEffectGroup(1, "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter", 6),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", "opponentOptional", 6, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "800", "400", "500", "800"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the restored opponent optional decline-first handoff SetChainLimitTillChainEnd window restorable before the allowed opponent passes",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 1, effectId: "fixture-chain-resolution-first-opponent-optional-decline-handoff-until", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter", sourceUid: "p1-deck-900-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-followup", 1, 6),
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter" },
              { type: "activateTrigger", player: 1, windowId: 6, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-chain-resolution-opponent-optional-decline-handoff-until-turn-blocked", 6),
              absentChainEffectGroup(1, "fixture-chain-resolution-opponent-optional-decline-handoff-until-opponent-chain-limiter", 6),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-second-opponent-optional-decline-handoff-until", "opponentOptional", 6, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "800", "400", "500", "800"] },
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears until-chain-end limits and resolves restored opponent optional decline-first handoff chains after the allowed opponent passes",
        phase: "main1",
        windowId: 7,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-chain-resolution-opponent-optional-decline-handoff-until-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 7, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 7, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          openEffectGroup(0, "fixture-chain-resolution-opponent-optional-decline-handoff-until-starter", 1, 7),
          summonGroup(
            [
              { type: "normalSummon", player: 0, code: "100", location: "hand" },
              { type: "setMonster", player: 0, code: "100", location: "hand" },
              { type: "normalSummon", player: 0, code: "300", location: "hand" },
              { type: "setMonster", player: 0, code: "300", location: "hand" },
              { type: "normalSummon", player: 0, code: "800", location: "hand" },
              { type: "setMonster", player: 0, code: "800", location: "hand" },
            ],
            1,
            7,
          ),
          turnGroup(7),
        ],
        locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "800", "400", "500", "800"] },
        logIncludes: [
          "Chain resolution opponent optional decline handoff until opponent chain limiter resolved",
          "Chain resolution first opponent optional decline handoff until resolved",
          "Chain resolution opponent optional decline handoff until starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
