import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentTriggerActivationGroup, summonGroup, triggerActivationGroup, triggerDeclineGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution SEGOC bucket fixture", () => {
  it("orders cross-player trigger buckets after an effect chain creates the trigger event", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "300", name: "Chain Resolution Turn Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Chain Resolution Opponent Mandatory", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Chain Resolution Turn Optional", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Chain Resolution Opponent Optional", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Chain Resolution Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Filler", kind: "monster", attack: 800, defense: 800 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution segoc trigger bucket fixture",
      options: { seed: 283, startingHandSize: 4 },
      decks: {
        0: { main: ["100", "300", "500", "700"] },
        1: { main: ["400", "600", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-chain-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [{ player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" }],
            logMessage: "Chain resolution starter resolved",
          },
          {
            id: "fixture-chain-resolution-turn-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            optional: false,
            range: ["hand"],
            logMessage: "Chain resolution turn mandatory resolved",
          },
          {
            id: "fixture-chain-resolution-opponent-mandatory",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            optional: false,
            range: ["hand"],
            logMessage: "Chain resolution opponent mandatory resolved",
          },
          {
            id: "fixture-chain-resolution-turn-optional",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            range: ["hand"],
            logMessage: "Chain resolution turn optional resolved",
          },
          {
            id: "fixture-chain-resolution-opponent-optional",
            player: 1,
            code: "600",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            range: ["hand"],
            logMessage: "Chain resolution opponent optional resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-resolution-starter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps initial open priority restorable before an effect chain creates cross-player SEGOC buckets",
            phase: "main1",
            windowId: 0,
            windowKind: "open",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 11, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-chain-resolution-starter", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "700", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "700", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-chain-resolution-starter", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "300", location: "hand" },
                { type: "normalSummon", player: 0, code: "500", location: "hand" },
                { type: "normalSummon", player: 0, code: "700", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "300", location: "hand" },
                { type: "setMonster", player: 0, code: "500", location: "hand" },
                { type: "setMonster", player: 0, code: "700", location: "hand" },
              ], 1, 0),
              turnGroup(0),
            ],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-chain-resolution-turn-mandatory" },
              { type: "activateTrigger", player: 1, windowId: 0, windowKind: "open", effectId: "fixture-chain-resolution-opponent-mandatory" },
              { type: "activateTrigger", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-chain-resolution-turn-optional" },
              { type: "activateTrigger", player: 1, windowId: 0, windowKind: "open", effectId: "fixture-chain-resolution-opponent-optional" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-chain-resolution-turn-mandatory", "turnMandatory", 0, "open"),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-opponent-mandatory", "opponentMandatory", 0, "open"),
              absentTriggerActivationGroup(0, "fixture-chain-resolution-turn-optional", "turnOptional", 0, "open"),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-opponent-optional", "opponentOptional", 0, "open"),
            ],
            locations: { hand: ["100", "300", "500", "700", "400", "600", "800", "800"] },
          },
          after: {
            source: "edopro",
            note: "EDOPro builds SEGOC buckets from trigger events created while an effect chain resolves",
            phase: "main1",
            windowId: 1,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [
              { player: 0, effectId: "fixture-chain-resolution-turn-mandatory", eventName: "sentToGraveyard", triggerBucket: "turnMandatory", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-mandatory", eventName: "sentToGraveyard", triggerBucket: "opponentMandatory", eventCardUid: "p0-deck-700-3" },
              { player: 0, effectId: "fixture-chain-resolution-turn-optional", eventName: "sentToGraveyard", triggerBucket: "turnOptional", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-optional", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-3" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnMandatory" },
              { player: 1, triggerBucket: "opponentMandatory" },
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-mandatory", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-chain-resolution-turn-mandatory", "turnMandatory", 1, 1)],
            absentLegalActions: [
              { type: "activateTrigger", player: 1, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-mandatory", triggerBucket: "opponentMandatory" },
              { type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional" },
              { type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-mandatory", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(1, "fixture-chain-resolution-opponent-mandatory", "opponentMandatory", 1, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-chain-resolution-turn-optional", "turnOptional", 1, "triggerBucket"),
              {
                player: 0,
                label: "Trigger Declines",
                windowId: 1,
                windowKind: "triggerBucket",
                triggerBucket: { player: 0, triggerBucket: "turnMandatory" },
                actions: [{ type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-mandatory" }],
              },
            ],
            locations: { graveyard: ["700"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            logIncludes: ["Chain resolution starter resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-resolution-turn-mandatory" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the turn-player mandatory trigger bucket restorable before advancing to opponent mandatory triggers",
            phase: "main1",
            windowId: 1,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [
              { player: 0, effectId: "fixture-chain-resolution-turn-mandatory", eventName: "sentToGraveyard", triggerBucket: "turnMandatory", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-mandatory", eventName: "sentToGraveyard", triggerBucket: "opponentMandatory", eventCardUid: "p0-deck-700-3" },
              { player: 0, effectId: "fixture-chain-resolution-turn-optional", eventName: "sentToGraveyard", triggerBucket: "turnOptional", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-optional", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-3" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnMandatory" },
              { player: 1, triggerBucket: "opponentMandatory" },
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-mandatory", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-chain-resolution-turn-mandatory", "turnMandatory", 1, 1)],
            absentLegalActions: [
              { type: "activateTrigger", player: 1, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-mandatory", triggerBucket: "opponentMandatory" },
              { type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional" },
              { type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-mandatory", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(1, "fixture-chain-resolution-opponent-mandatory", "opponentMandatory", 1, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-chain-resolution-turn-optional", "turnOptional", 1, "triggerBucket"),
              {
                player: 0,
                label: "Trigger Declines",
                windowId: 1,
                windowKind: "triggerBucket",
                triggerBucket: { player: 0, triggerBucket: "turnMandatory" },
                actions: [{ type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-mandatory" }],
              },
            ],
            locations: { graveyard: ["700"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            logIncludes: ["Chain resolution starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro advances from turn mandatory to non-turn mandatory after the first trigger is placed on chain",
            windowId: 2,
            windowKind: "triggerBucket",
            waitingFor: 1,
            chain: [{ player: 0, effectId: "fixture-chain-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" }],
            pendingTriggers: [
              { player: 1, effectId: "fixture-chain-resolution-opponent-mandatory", triggerBucket: "opponentMandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 0, effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
            ],
            pendingTriggerBuckets: [
              { player: 1, triggerBucket: "opponentMandatory" },
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 0, 1: 1 },
            legalActionGroupCounts: { 0: 0, 1: 1 },
            legalActions: [{ type: "activateTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-mandatory", triggerBucket: "opponentMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(1, "fixture-chain-resolution-opponent-mandatory", "opponentMandatory", 1, 2)],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional" },
              { type: "declineTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-mandatory", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-chain-resolution-turn-optional", "turnOptional", 2, "triggerBucket"),
              {
                player: 1,
                label: "Trigger Declines",
                windowId: 2,
                windowKind: "triggerBucket",
                triggerBucket: { player: 1, triggerBucket: "opponentMandatory" },
                actions: [{ type: "declineTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-mandatory" }],
              },
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-chain-resolution-opponent-mandatory" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps opponent mandatory trigger priority restorable before optional buckets are exposed",
            windowId: 2,
            windowKind: "triggerBucket",
            waitingFor: 1,
            chain: [{ player: 0, effectId: "fixture-chain-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" }],
            pendingTriggers: [
              { player: 1, effectId: "fixture-chain-resolution-opponent-mandatory", triggerBucket: "opponentMandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 0, effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
            ],
            pendingTriggerBuckets: [
              { player: 1, triggerBucket: "opponentMandatory" },
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 0, 1: 1 },
            legalActionGroupCounts: { 0: 0, 1: 1 },
            legalActions: [{ type: "activateTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-mandatory", triggerBucket: "opponentMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(1, "fixture-chain-resolution-opponent-mandatory", "opponentMandatory", 1, 2)],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional" },
              { type: "declineTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-mandatory", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-chain-resolution-turn-optional", "turnOptional", 2, "triggerBucket"),
              {
                player: 1,
                label: "Trigger Declines",
                windowId: 2,
                windowKind: "triggerBucket",
                triggerBucket: { player: 1, triggerBucket: "opponentMandatory" },
                actions: [{ type: "declineTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-mandatory" }],
              },
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro presents turn-player optional triggers before opponent optional triggers after mandatory buckets are consumed",
            windowId: 3,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
            ],
            pendingTriggers: [
              { player: 0, effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateTrigger", player: 0, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional", count: 1 },
              { type: "declineTrigger", player: 0, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(0, "fixture-chain-resolution-turn-optional", "turnOptional", 1, 3),
              triggerDeclineGroup(0, "fixture-chain-resolution-turn-optional", "turnOptional", 1, 3),
            ],
            absentLegalActions: [{ type: "activateTrigger", player: 1, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional" }],
            absentLegalActionGroups: [absentTriggerActivationGroup(1, "fixture-chain-resolution-opponent-optional", "opponentOptional", 3, "triggerBucket")],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-resolution-turn-optional" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps turn-player optional trigger priority restorable before handing optional priority to the opponent",
            windowId: 3,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
            ],
            pendingTriggers: [
              { player: 0, effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateTrigger", player: 0, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional", count: 1 },
              { type: "declineTrigger", player: 0, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(0, "fixture-chain-resolution-turn-optional", "turnOptional", 1, 3),
              triggerDeclineGroup(0, "fixture-chain-resolution-turn-optional", "turnOptional", 1, 3),
            ],
            absentLegalActions: [{ type: "activateTrigger", player: 1, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional" }],
            absentLegalActionGroups: [absentTriggerActivationGroup(1, "fixture-chain-resolution-opponent-optional", "opponentOptional", 3, "triggerBucket")],
          },
          after: {
            source: "edopro",
            note: "EDOPro advances to opponent optional triggers only after the turn-player optional bucket is consumed",
            windowId: 4,
            windowKind: "triggerBucket",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-chain-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 0, effectId: "fixture-chain-resolution-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
            ],
            pendingTriggers: [{ player: 1, effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" }],
            pendingTriggerBuckets: [{ player: 1, triggerBucket: "opponentOptional" }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional", count: 1 },
              { type: "declineTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(1, "fixture-chain-resolution-opponent-optional", "opponentOptional", 1, 4),
              triggerDeclineGroup(1, "fixture-chain-resolution-opponent-optional", "opponentOptional", 1, 4),
            ],
            absentLegalActions: [{ type: "activateTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional" }],
            absentLegalActionGroups: [absentTriggerActivationGroup(0, "fixture-chain-resolution-turn-optional", "turnOptional", 4, "triggerBucket")],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-chain-resolution-opponent-optional" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps opponent optional trigger priority restorable before resolving the selected SEGOC trigger chain",
            windowId: 4,
            windowKind: "triggerBucket",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-chain-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 0, effectId: "fixture-chain-resolution-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
            ],
            pendingTriggers: [{ player: 1, effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" }],
            pendingTriggerBuckets: [{ player: 1, triggerBucket: "opponentOptional" }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional", count: 1 },
              { type: "declineTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-opponent-optional", triggerBucket: "opponentOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(1, "fixture-chain-resolution-opponent-optional", "opponentOptional", 1, 4),
              triggerDeclineGroup(1, "fixture-chain-resolution-opponent-optional", "opponentOptional", 1, 4),
            ],
            absentLegalActions: [{ type: "activateTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-turn-optional", triggerBucket: "turnOptional" }],
            absentLegalActionGroups: [absentTriggerActivationGroup(0, "fixture-chain-resolution-turn-optional", "turnOptional", 4, "triggerBucket")],
          },
          after: {
            source: "edopro",
            note: "EDOPro resolves the selected chain-resolution SEGOC trigger chain and returns to turn-player open priority",
            windowId: 5,
            windowKind: "open",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 9, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-chain-resolution-starter", count: 1 },
              { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 5, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 5, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 5,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-chain-resolution-starter", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "300", location: "hand" },
                { type: "normalSummon", player: 0, code: "500", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "300", location: "hand" },
                { type: "setMonster", player: 0, code: "500", location: "hand" },
              ], 1, 5),
              turnGroup(5),
            ],
            locations: { graveyard: ["700"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            logIncludes: [
              "Chain resolution opponent optional resolved",
              "Chain resolution turn optional resolved",
              "Chain resolution opponent mandatory resolved",
              "Chain resolution turn mandatory resolved",
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro final state preserves chain-created SEGOC ordering through mandatory and optional trigger buckets",
        phase: "main1",
        windowId: 5,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-chain-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 5, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 5, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 5,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-chain-resolution-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
          ], 1, 5),
          turnGroup(5),
        ],
        locations: { graveyard: ["700"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
        logIncludes: [
          "Chain resolution starter resolved",
          "Chain resolution opponent optional resolved",
          "Chain resolution turn optional resolved",
          "Chain resolution opponent mandatory resolved",
          "Chain resolution turn mandatory resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
