import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  triggerActivationGroup,
  triggerDeclineGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution SEGOC pass handoff chain fixture", () => {
  it("opens opponent responses after the trigger player chains from chain-created SEGOC pass handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Handoff Chain Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Turn Chain Handoff Chain Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Chain Handoff Chain Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Opponent Chain Handoff Chain Quick", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Chain Handoff Chain Optional", kind: "monster", attack: 1200, defense: 1200 },
      { code: "700", name: "Chain Handoff Chain Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Filler", kind: "monster", attack: 800, defense: 800 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution segoc pass handoff chain fixture",
      options: { seed: 288, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "500", "700"] },
        1: { main: ["400", "800", "800", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-chain-handoff-chain-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 1, code: "400", from: "hand", to: "graveyard" },
            ],
            logMessage: "Chain handoff chain starter resolved",
          },
          {
            id: "fixture-chain-handoff-chain-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Chain handoff chain mandatory should not resolve yet",
          },
          {
            id: "fixture-chain-handoff-chain-optional",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain handoff chain optional should not resolve yet",
          },
          {
            id: "fixture-chain-handoff-chain-turn-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Turn quick after chain-created SEGOC handoff chain should not resolve yet",
          },
          {
            id: "fixture-chain-handoff-chain-opponent-quick",
            player: 1,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Opponent quick after chain-created SEGOC handoff chain should not resolve yet",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-handoff-chain-starter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps initial open priority restorable before chain-created SEGOC pass handoff begins",
            phase: "main1",
            windowId: 0,
            windowKind: "open",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 13, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-chain-handoff-chain-starter", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "200", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "700", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "200", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "700", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-chain-handoff-chain-starter", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "200", location: "hand" },
                { type: "normalSummon", player: 0, code: "300", location: "hand" },
                { type: "normalSummon", player: 0, code: "500", location: "hand" },
                { type: "normalSummon", player: 0, code: "700", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "200", location: "hand" },
                { type: "setMonster", player: 0, code: "300", location: "hand" },
                { type: "setMonster", player: 0, code: "500", location: "hand" },
                { type: "setMonster", player: 0, code: "700", location: "hand" },
              ], 1, 0),
              turnGroup(0),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-chain-handoff-chain-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "fixture-chain-handoff-chain-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-chain-handoff-chain-mandatory" },
              { type: "activateTrigger", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-chain-handoff-chain-optional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-handoff-chain-turn-quick", 0, "open"),
              absentWindowEffectGroup(1, "fixture-chain-handoff-chain-opponent-quick", 0, "open"),
              absentTriggerActivationGroup(0, "fixture-chain-handoff-chain-mandatory", "turnMandatory", 0, "open"),
              absentTriggerActivationGroup(0, "fixture-chain-handoff-chain-optional", "turnOptional", 0, "open"),
            ],
            locations: { hand: ["100", "200", "300", "500", "700", "400", "800", "800", "800", "800"] },
          },
          after: {
            source: "edopro",
            note: "EDOPro starts chain-created SEGOC trigger selection before exposing fast responses",
            windowId: 1,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [
              { player: 0, effectId: "fixture-chain-handoff-chain-mandatory", eventName: "sentToGraveyard", triggerBucket: "turnMandatory", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-chain-optional", eventName: "sentToGraveyard", triggerBucket: "turnOptional", eventCardUid: "p0-deck-700-4" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnMandatory" },
              { player: 0, triggerBucket: "turnOptional" },
            ],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-mandatory", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-chain-handoff-chain-mandatory", "turnMandatory", 1, 1)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-optional", triggerBucket: "turnOptional" },
              { type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-mandatory", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-handoff-chain-turn-quick", 1, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-chain-handoff-chain-opponent-quick", 1, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-chain-handoff-chain-optional", "turnOptional", 1, "triggerBucket"),
              {
                player: 0,
                label: "Trigger Declines",
                windowId: 1,
                windowKind: "triggerBucket",
                triggerBucket: { player: 0, triggerBucket: "turnMandatory" },
                actions: [{ type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-mandatory" }],
              },
            ],
            locations: { graveyard: ["700", "200", "400"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
            logIncludes: ["Chain handoff chain starter resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-handoff-chain-mandatory" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps chain-created mandatory SEGOC priority restorable before optional triggers are exposed",
            windowId: 1,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [
              { player: 0, effectId: "fixture-chain-handoff-chain-mandatory", eventName: "sentToGraveyard", triggerBucket: "turnMandatory", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-chain-optional", eventName: "sentToGraveyard", triggerBucket: "turnOptional", eventCardUid: "p0-deck-700-4" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnMandatory" },
              { player: 0, triggerBucket: "turnOptional" },
            ],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-mandatory", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-chain-handoff-chain-mandatory", "turnMandatory", 1, 1)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-optional", triggerBucket: "turnOptional" },
              { type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-mandatory", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-handoff-chain-turn-quick", 1, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-chain-handoff-chain-opponent-quick", 1, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-chain-handoff-chain-optional", "turnOptional", 1, "triggerBucket"),
              {
                player: 0,
                label: "Trigger Declines",
                windowId: 1,
                windowKind: "triggerBucket",
                triggerBucket: { player: 0, triggerBucket: "turnMandatory" },
                actions: [{ type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-mandatory" }],
              },
            ],
            locations: { graveyard: ["700", "200", "400"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
            logIncludes: ["Chain handoff chain starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro keeps same-event optional trigger selection ahead of chain responses after the mandatory trigger is chosen",
            windowId: 2,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [{ player: 0, effectId: "fixture-chain-handoff-chain-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" }],
            pendingTriggers: [{ player: 0, effectId: "fixture-chain-handoff-chain-optional", triggerBucket: "turnOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" }],
            pendingTriggerBuckets: [{ player: 0, triggerBucket: "turnOptional" }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-optional", triggerBucket: "turnOptional", count: 1 },
              { type: "declineTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-optional", triggerBucket: "turnOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(0, "fixture-chain-handoff-chain-optional", "turnOptional", 1, 2),
              triggerDeclineGroup(0, "fixture-chain-handoff-chain-optional", "turnOptional", 1, 2),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-opponent-quick" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-handoff-chain-turn-quick", 2, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-chain-handoff-chain-opponent-quick", 2, "triggerBucket"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-handoff-chain-optional" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps chain-created optional SEGOC priority restorable before chain responses open",
            windowId: 2,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [{ player: 0, effectId: "fixture-chain-handoff-chain-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" }],
            pendingTriggers: [{ player: 0, effectId: "fixture-chain-handoff-chain-optional", triggerBucket: "turnOptional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" }],
            pendingTriggerBuckets: [{ player: 0, triggerBucket: "turnOptional" }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-optional", triggerBucket: "turnOptional", count: 1 },
              { type: "declineTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-optional", triggerBucket: "turnOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(0, "fixture-chain-handoff-chain-optional", "turnOptional", 1, 2),
              triggerDeclineGroup(0, "fixture-chain-handoff-chain-optional", "turnOptional", 1, 2),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-chain-opponent-quick" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-handoff-chain-turn-quick", 2, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-chain-handoff-chain-opponent-quick", 2, "triggerBucket"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro gives the opponent first chain-response priority after chain-created SEGOC trigger selection completes",
            windowId: 3,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-chain-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-chain-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 3, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(1, "fixture-chain-handoff-chain-opponent-quick", 1, 3), chainPassGroup(1, 1, 3)],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-turn-quick" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "fixture-chain-handoff-chain-turn-quick", 3)],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps opponent chain-response priority restorable before pass handoff returns priority to the trigger player",
            windowId: 3,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-chain-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-chain-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 3, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(1, "fixture-chain-handoff-chain-opponent-quick", 1, 3), chainPassGroup(1, 1, 3)],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-turn-quick" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "fixture-chain-handoff-chain-turn-quick", 3)],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns chain-created SEGOC response priority to the trigger player after the opponent passes with a response available",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-chain-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-chain-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
            ],
            chainPasses: [1],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(0, "fixture-chain-handoff-chain-turn-quick", 1, 4), chainPassGroup(0, 1, 4)],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-opponent-quick" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "fixture-chain-handoff-chain-opponent-quick", 4)],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-handoff-chain-turn-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps trigger-player chain-response priority restorable before the trigger player chains from pass handoff",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-chain-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-chain-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
            ],
            chainPasses: [1],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(0, "fixture-chain-handoff-chain-turn-quick", 1, 4), chainPassGroup(0, 1, 4)],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-opponent-quick" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "fixture-chain-handoff-chain-opponent-quick", 4)],
          },
          after: {
            source: "edopro",
            note: "EDOPro gives the opponent another chain-response window after the trigger player chains from chain-created SEGOC pass handoff",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-chain-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-chain-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-chain-turn-quick", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(1, "fixture-chain-handoff-chain-opponent-quick", 1, 5), chainPassGroup(1, 1, 5)],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-turn-quick" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "fixture-chain-handoff-chain-turn-quick", 5)],
            locations: { graveyard: ["700", "200", "400"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro keeps the chain-created SEGOC trigger chain pending and reopens opponent response priority after the trigger player chains from pass handoff",
        phase: "main1",
        windowId: 5,
        windowKind: "chainResponse",
        waitingFor: 1,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [
          { player: 0, effectId: "fixture-chain-handoff-chain-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
          { player: 0, effectId: "fixture-chain-handoff-chain-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
          { player: 0, effectId: "fixture-chain-handoff-chain-turn-quick", sourceUid: "p0-deck-200-1" },
        ],
        chainPasses: [],
        legalActionCounts: { 0: 0, 1: 2 },
        legalActionGroupCounts: { 0: 0, 1: 2 },
        legalActions: [
          { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-opponent-quick", count: 1 },
          { type: "passChain", player: 1, windowId: 5, windowKind: "chainResponse", count: 1 },
        ],
        legalActionGroups: [chainEffectGroup(1, "fixture-chain-handoff-chain-opponent-quick", 1, 5), chainPassGroup(1, 1, 5)],
        absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-handoff-chain-turn-quick" }],
        absentLegalActionGroups: [absentChainEffectGroup(0, "fixture-chain-handoff-chain-turn-quick", 5)],
        locations: { graveyard: ["700", "200", "400"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
        logIncludes: ["Chain handoff chain starter resolved"],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
