import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentSummonGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity Pendulum Summon open fast-effect chain fixture", () => {
  it("opens opponent chain responses after a triggerless Pendulum Summon open fast effect", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Open Fast Pendulum Chain Low Scale", kind: "monster", typeFlags: 0x1000001, level: 4, leftScale: 1, rightScale: 1, attack: 1000, defense: 1000 },
      { code: "200", name: "Open Fast Pendulum Chain High Scale", kind: "monster", typeFlags: 0x1000001, level: 4, leftScale: 8, rightScale: 8, attack: 1000, defense: 1000 },
      { code: "300", name: "Open Fast Pendulum Chain Candidate", kind: "monster", typeFlags: 0x1000001, level: 4, attack: 1500, defense: 1500 },
      { code: "400", name: "Turn Pendulum Chain Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Opponent Pendulum Chain Response", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Opponent Pendulum Chain Open Quick", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "pendulum summon open fast chain-response fixture",
      options: { seed: 371, startingHandSize: 4 },
      decks: {
        0: { main: ["100", "200", "300", "400"] },
        1: { main: ["500", "600", "500"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "100", from: "hand", to: "spellTrapZone" },
          { player: 0, code: "200", from: "hand", to: "spellTrapZone" },
          { player: 0, code: "400", from: "hand", to: "graveyard" },
          { player: 1, code: "500", from: "hand", to: "graveyard" },
          { player: 1, code: "600", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "pendulum-summon-turn-open-chain-quick",
            player: 0,
            code: "400",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Turn open quick after Pendulum Summon chain resolved",
          },
          {
            id: "pendulum-summon-opponent-chain-response-quick",
            player: 1,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Opponent chain quick after Pendulum Summon should not resolve",
          },
          {
            id: "pendulum-summon-opponent-open-chain-filtered",
            player: 1,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "open",
            logMessage: "Opponent open quick after Pendulum Summon chain should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep({ type: "pendulumSummon", player: 0, summonUids: ["p0-deck-300-2"], label: "Pendulum Summon selected open fast chain candidate" }, {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro exposes Pendulum Summons beside turn-player open fast effects before the Pendulum Summon is performed",
            phase: "main1",
            windowId: 0,
            windowKind: "open",
            waitingFor: 0,
            legalActionCounts: { 0: 6, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "pendulum-summon-turn-open-chain-quick", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "pendulumSummon", player: 0, windowId: 0, windowKind: "open", summonUids: ["p0-deck-300-2"], count: 1 },
              { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "pendulum-summon-turn-open-chain-quick", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "300", location: "hand" },
                { type: "setMonster", player: 0, code: "300", location: "hand" },
                { type: "pendulumSummon", player: 0, summonUids: ["p0-deck-300-2"] },
              ], 1, 0),
              turnGroup(0),
            ],
            locations: { spellTrapZone: ["100", "200"], hand: ["300"], graveyard: ["400", "500", "600"] },
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "pendulum-summon-opponent-chain-response-quick" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "pendulum-summon-opponent-open-chain-filtered" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(1, "pendulum-summon-opponent-chain-response-quick", 0, "open"),
              absentWindowEffectGroup(1, "pendulum-summon-opponent-open-chain-filtered", 0, "open"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns triggerless Pendulum Summons to turn-player open priority with that player's open fast effects available",
            phase: "main1",
            windowId: 1,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            chain: [],
            chainPasses: [],
            locations: { monsterZone: ["300"], spellTrapZone: ["100", "200"], graveyard: ["400", "500", "600"] },
            cards: [{ uid: "p0-deck-300-2", code: "300", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "pendulum-summon-turn-open-chain-quick", count: 1 },
              { type: "changePhase", player: 0, windowId: 1, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 1, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 1,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "pendulum-summon-turn-open-chain-quick", count: 1 }],
              },
              turnGroup(1),
            ],
            absentLegalActions: [
              { type: "pendulumSummon", player: 0, windowId: 1, windowKind: "open", summonUids: ["p0-deck-300-2"] },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "pendulum-summon-opponent-chain-response-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "pendulum-summon-opponent-open-chain-filtered" },
            ],
            absentLegalActionGroups: [
              absentSummonGroup({ type: "pendulumSummon", player: 0, summonUids: ["p0-deck-300-2"] }, 1),
              absentWindowEffectGroup(1, "pendulum-summon-opponent-chain-response-quick", 1, "open"),
              absentWindowEffectGroup(1, "pendulum-summon-opponent-open-chain-filtered", 1, "open"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "pendulum-summon-turn-open-chain-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves post-Pendulum-Summon turn-player open priority before a fast effect starts a chain",
            phase: "main1",
            windowId: 1,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            chain: [],
            chainPasses: [],
            locations: { monsterZone: ["300"], spellTrapZone: ["100", "200"], graveyard: ["400", "500", "600"] },
            cards: [{ uid: "p0-deck-300-2", code: "300", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "pendulum-summon-turn-open-chain-quick", count: 1 },
              { type: "changePhase", player: 0, windowId: 1, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 1, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 1,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "pendulum-summon-turn-open-chain-quick", count: 1 }],
              },
              turnGroup(1),
            ],
            absentLegalActions: [
              { type: "pendulumSummon", player: 0, windowId: 1, windowKind: "open", summonUids: ["p0-deck-300-2"] },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "pendulum-summon-opponent-chain-response-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "pendulum-summon-opponent-open-chain-filtered" },
            ],
            absentLegalActionGroups: [
              absentSummonGroup({ type: "pendulumSummon", player: 0, summonUids: ["p0-deck-300-2"] }, 1),
              absentWindowEffectGroup(1, "pendulum-summon-opponent-chain-response-quick", 1, "open"),
              absentWindowEffectGroup(1, "pendulum-summon-opponent-open-chain-filtered", 1, "open"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro gives the opponent chain-response priority after a post-Pendulum-Summon open fast effect starts a chain",
            phase: "main1",
            windowId: 2,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            chain: [{ player: 0, effectId: "pendulum-summon-turn-open-chain-quick", sourceUid: "p0-deck-400-3" }],
            chainPasses: [],
            locations: { monsterZone: ["300"], spellTrapZone: ["100", "200"], graveyard: ["400", "500", "600"] },
            cards: [{ uid: "p0-deck-300-2", code: "300", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 2, windowKind: "chainResponse", effectId: "pendulum-summon-opponent-chain-response-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 2, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "pendulum-summon-opponent-chain-response-quick", 1, 2),
              chainPassGroup(1, 1, 2),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 2, windowKind: "chainResponse", effectId: "pendulum-summon-opponent-open-chain-filtered" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "pendulum-summon-opponent-open-chain-filtered", 2)],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent chain-response priority before passing the post-Pendulum-Summon fast-effect chain",
            phase: "main1",
            windowId: 2,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            chain: [{ player: 0, effectId: "pendulum-summon-turn-open-chain-quick", sourceUid: "p0-deck-400-3" }],
            chainPasses: [],
            locations: { monsterZone: ["300"], spellTrapZone: ["100", "200"], graveyard: ["400", "500", "600"] },
            cards: [{ uid: "p0-deck-300-2", code: "300", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 2, windowKind: "chainResponse", effectId: "pendulum-summon-opponent-chain-response-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 2, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "pendulum-summon-opponent-chain-response-quick", 1, 2),
              chainPassGroup(1, 1, 2),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 2, windowKind: "chainResponse", effectId: "pendulum-summon-opponent-open-chain-filtered" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "pendulum-summon-opponent-open-chain-filtered", 2)],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro keeps turn-player open priority after resolving a post-Pendulum-Summon open fast-effect chain",
        phase: "main1",
        windowId: 3,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        chain: [],
        chainPasses: [],
        locations: { monsterZone: ["300"], spellTrapZone: ["100", "200"], graveyard: ["400", "500", "600"] },
        cards: [{ uid: "p0-deck-300-2", code: "300", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
        legalActionCounts: { 0: 2, 1: 0 },
        legalActionGroupCounts: { 0: 1, 1: 0 },
        legalActions: [
          { type: "changePhase", player: 0, windowId: 3, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 3, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [turnGroup(3)],
        absentLegalActions: [
          { type: "pendulumSummon", player: 0, windowId: 3, windowKind: "open", summonUids: ["p0-deck-300-2"] },
          { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "pendulum-summon-turn-open-chain-quick" },
          { type: "activateEffect", player: 1, windowId: 3, windowKind: "open", effectId: "pendulum-summon-opponent-chain-response-quick" },
          { type: "activateEffect", player: 1, windowId: 3, windowKind: "open", effectId: "pendulum-summon-opponent-open-chain-filtered" },
        ],
        absentLegalActionGroups: [
          absentSummonGroup({ type: "pendulumSummon", player: 0, summonUids: ["p0-deck-300-2"] }, 3),
          absentWindowEffectGroup(0, "pendulum-summon-turn-open-chain-quick", 3, "open"),
          absentWindowEffectGroup(1, "pendulum-summon-opponent-chain-response-quick", 3, "open"),
          absentWindowEffectGroup(1, "pendulum-summon-opponent-open-chain-filtered", 3, "open"),
        ],
        logIncludes: ["Turn open quick after Pendulum Summon chain resolved"],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
