import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentSummonGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity post-Flip-Summon open fast-effect pass handoff opponent response turn response resolution fixture", () => {
  it("resolves turn-player responses after the opponent has no remaining post-Flip-Summon handoff response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Post Flip Summon Opponent Response Flippable Monster", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Post Flip Summon Opponent Response Turn Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Post Flip Summon Opponent Response First Turn Chain Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Post Flip Summon Opponent Response Second Turn Chain Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Post Flip Summon Opponent Response Opponent First Chain Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Post Flip Summon Opponent Response Opponent Second Chain Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "800", name: "Post Flip Summon Opponent Response Opponent Third Chain Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "900", name: "Post Flip Summon Opponent Response Opponent Open Quick", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "post flip summon open fast pass handoff opponent response turn response resolution fixture",
      options: { seed: 449, startingHandSize: 4 },
      decks: {
        0: { main: ["100", "300", "600", "700"] },
        1: { main: ["400", "500", "800", "900"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "100", from: "hand", to: "monsterZone", position: "faceDownDefense" },
          { player: 0, code: "300", from: "hand", to: "graveyard" },
          { player: 0, code: "600", from: "hand", to: "graveyard" },
          { player: 0, code: "700", from: "hand", to: "graveyard" },
          { player: 1, code: "400", from: "hand", to: "graveyard" },
          { player: 1, code: "500", from: "hand", to: "graveyard" },
          { player: 1, code: "800", from: "hand", to: "graveyard" },
          { player: 1, code: "900", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "post-flip-summon-opponent-response-turn-open-quick",
            player: 0,
            code: "300",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "open",
            oncePerTurn: true,
            logMessage: "Post Flip Summon opponent response turn open quick resolved",
          },
          {
            id: "post-flip-summon-opponent-response-first-turn-chain-quick",
            player: 0,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Post Flip Summon opponent response first turn chain quick resolved",
          },
          {
            id: "post-flip-summon-opponent-response-second-turn-chain-quick",
            player: 0,
            code: "700",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Post Flip Summon opponent response second turn chain quick resolved",
          },
          {
            id: "post-flip-summon-opponent-response-opponent-first-chain-quick",
            player: 1,
            code: "400",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Post Flip Summon opponent response opponent first chain quick resolved",
          },
          {
            id: "post-flip-summon-opponent-response-opponent-second-chain-quick",
            player: 1,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Post Flip Summon opponent response opponent second chain quick resolved",
          },
          {
            id: "post-flip-summon-opponent-response-opponent-third-chain-quick",
            player: 1,
            code: "800",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Post Flip Summon opponent response opponent third chain quick resolved",
          },
          {
            id: "post-flip-summon-opponent-response-opponent-open-quick",
            player: 1,
            code: "900",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "open",
            logMessage: "Post Flip Summon opponent response opponent open quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("flipSummon", 0, { code: "100", location: "monsterZone" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro exposes Flip Summon actions beside turn-player open fast effects before the opponent-response resolution fixture begins",
            phase: "main1",
            windowId: 0,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400", "500", "800", "900"] },
            cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceDownDefense", faceUp: false }],
            legalActionCounts: { 0: 4, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-flip-summon-opponent-response-turn-open-quick", count: 1 },
              { type: "flipSummon", player: 0, windowId: 0, windowKind: "open", code: "100", location: "monsterZone", count: 1 },
              { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-flip-summon-opponent-response-turn-open-quick", count: 1 }],
              },
              summonGroup([{ type: "flipSummon", player: 0, code: "100", location: "monsterZone" }], 1, 0),
              turnGroup(0),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-flip-summon-opponent-response-first-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-flip-summon-opponent-response-second-turn-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "post-flip-summon-opponent-response-opponent-first-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "post-flip-summon-opponent-response-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "post-flip-summon-opponent-response-first-turn-chain-quick", 0, "open"),
              absentWindowEffectGroup(0, "post-flip-summon-opponent-response-second-turn-chain-quick", 0, "open"),
              absentWindowEffectGroup(1, "post-flip-summon-opponent-response-opponent-first-chain-quick", 0, "open"),
              absentWindowEffectGroup(1, "post-flip-summon-opponent-response-opponent-open-quick", 0, "open"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns triggerless Flip Summons to turn-player open fast-effect priority before post-Flip-Summon handoff chains can begin",
            phase: "main1",
            windowId: 1,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400", "500", "800", "900"] },
            cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-flip-summon-opponent-response-turn-open-quick", count: 1 },
              { type: "changePhase", player: 0, windowId: 1, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 1, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 1,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-flip-summon-opponent-response-turn-open-quick", count: 1 }],
              },
              turnGroup(1),
            ],
            absentLegalActions: [
              { type: "flipSummon", player: 0, windowId: 1, windowKind: "open", code: "100", location: "monsterZone" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-flip-summon-opponent-response-first-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-flip-summon-opponent-response-second-turn-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "post-flip-summon-opponent-response-opponent-first-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "post-flip-summon-opponent-response-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentSummonGroup({ type: "flipSummon", player: 0, code: "100", location: "monsterZone" }, 1),
              absentWindowEffectGroup(0, "post-flip-summon-opponent-response-first-turn-chain-quick", 1, "open"),
              absentWindowEffectGroup(0, "post-flip-summon-opponent-response-second-turn-chain-quick", 1, "open"),
              absentWindowEffectGroup(1, "post-flip-summon-opponent-response-opponent-first-chain-quick", 1, "open"),
              absentWindowEffectGroup(1, "post-flip-summon-opponent-response-opponent-open-quick", 1, "open"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "post-flip-summon-opponent-response-turn-open-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "post-flip-summon-opponent-response-opponent-first-chain-quick" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "post-flip-summon-opponent-response-opponent-second-chain-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "post-flip-summon-opponent-response-first-turn-chain-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "post-flip-summon-opponent-response-opponent-third-chain-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent priority before the final post-Flip-Summon opponent response",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "post-flip-summon-opponent-response-turn-open-quick", sourceUid: "p0-deck-300-1" },
              { player: 1, effectId: "post-flip-summon-opponent-response-opponent-first-chain-quick", sourceUid: "p1-deck-400-0" },
              { player: 1, effectId: "post-flip-summon-opponent-response-opponent-second-chain-quick", sourceUid: "p1-deck-500-1" },
              { player: 0, effectId: "post-flip-summon-opponent-response-first-turn-chain-quick", sourceUid: "p0-deck-600-2" },
            ],
            chainPasses: [],
            locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400", "500", "800", "900"] },
            cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-third-chain-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "post-flip-summon-opponent-response-opponent-third-chain-quick", 1, 6),
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-first-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-second-turn-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-first-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-second-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-flip-summon-opponent-response-turn-open-quick", 6),
              absentChainEffectGroup(0, "post-flip-summon-opponent-response-first-turn-chain-quick", 6),
              absentChainEffectGroup(0, "post-flip-summon-opponent-response-second-turn-chain-quick", 6),
              absentChainEffectGroup(1, "post-flip-summon-opponent-response-opponent-first-chain-quick", 6),
              absentChainEffectGroup(1, "post-flip-summon-opponent-response-opponent-second-chain-quick", 6),
              absentWindowEffectGroup(1, "post-flip-summon-opponent-response-opponent-open-quick", 6, "chainResponse"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns post-Flip-Summon handoff response priority to the turn player after the opponent uses the response window reopened by the turn player's response",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "post-flip-summon-opponent-response-turn-open-quick", sourceUid: "p0-deck-300-1" },
              { player: 1, effectId: "post-flip-summon-opponent-response-opponent-first-chain-quick", sourceUid: "p1-deck-400-0" },
              { player: 1, effectId: "post-flip-summon-opponent-response-opponent-second-chain-quick", sourceUid: "p1-deck-500-1" },
              { player: 0, effectId: "post-flip-summon-opponent-response-first-turn-chain-quick", sourceUid: "p0-deck-600-2" },
              { player: 1, effectId: "post-flip-summon-opponent-response-opponent-third-chain-quick", sourceUid: "p1-deck-800-2" },
            ],
            chainPasses: [],
            locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400", "500", "800", "900"] },
            cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-second-turn-chain-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "post-flip-summon-opponent-response-second-turn-chain-quick", 1, 7),
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-first-turn-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-first-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-second-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-third-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-flip-summon-opponent-response-turn-open-quick", 7),
              absentChainEffectGroup(0, "post-flip-summon-opponent-response-first-turn-chain-quick", 7),
              absentChainEffectGroup(1, "post-flip-summon-opponent-response-opponent-first-chain-quick", 7),
              absentChainEffectGroup(1, "post-flip-summon-opponent-response-opponent-second-chain-quick", 7),
              absentChainEffectGroup(1, "post-flip-summon-opponent-response-opponent-third-chain-quick", 7),
              absentWindowEffectGroup(1, "post-flip-summon-opponent-response-opponent-open-quick", 7, "chainResponse"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "post-flip-summon-opponent-response-second-turn-chain-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player priority before the final post-Flip-Summon turn response resolves the chain",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "post-flip-summon-opponent-response-turn-open-quick", sourceUid: "p0-deck-300-1" },
              { player: 1, effectId: "post-flip-summon-opponent-response-opponent-first-chain-quick", sourceUid: "p1-deck-400-0" },
              { player: 1, effectId: "post-flip-summon-opponent-response-opponent-second-chain-quick", sourceUid: "p1-deck-500-1" },
              { player: 0, effectId: "post-flip-summon-opponent-response-first-turn-chain-quick", sourceUid: "p0-deck-600-2" },
              { player: 1, effectId: "post-flip-summon-opponent-response-opponent-third-chain-quick", sourceUid: "p1-deck-800-2" },
            ],
            chainPasses: [],
            locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400", "500", "800", "900"] },
            cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-second-turn-chain-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "post-flip-summon-opponent-response-second-turn-chain-quick", 1, 7),
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-first-turn-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-first-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-second-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-third-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-flip-summon-opponent-response-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-flip-summon-opponent-response-turn-open-quick", 7),
              absentChainEffectGroup(0, "post-flip-summon-opponent-response-first-turn-chain-quick", 7),
              absentChainEffectGroup(1, "post-flip-summon-opponent-response-opponent-first-chain-quick", 7),
              absentChainEffectGroup(1, "post-flip-summon-opponent-response-opponent-second-chain-quick", 7),
              absentChainEffectGroup(1, "post-flip-summon-opponent-response-opponent-third-chain-quick", 7),
              absentWindowEffectGroup(1, "post-flip-summon-opponent-response-opponent-open-quick", 7, "chainResponse"),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves post-Flip-Summon handoff chains after the turn player responds from the window reopened by the opponent's final handoff response",
        phase: "main1",
        windowId: 8,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400", "500", "800", "900"] },
        cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
        legalActionCounts: { 0: 2, 1: 0 },
        legalActionGroupCounts: { 0: 1, 1: 0 },
        legalActions: [
          { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [turnGroup(8)],
        absentLegalActions: [
          { type: "flipSummon", player: 0, windowId: 8, windowKind: "open", code: "100", location: "monsterZone" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "post-flip-summon-opponent-response-turn-open-quick" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "post-flip-summon-opponent-response-first-turn-chain-quick" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "post-flip-summon-opponent-response-second-turn-chain-quick" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "post-flip-summon-opponent-response-opponent-first-chain-quick" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "post-flip-summon-opponent-response-opponent-second-chain-quick" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "post-flip-summon-opponent-response-opponent-third-chain-quick" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "post-flip-summon-opponent-response-opponent-open-quick" },
        ],
        absentLegalActionGroups: [
          absentSummonGroup({ type: "flipSummon", player: 0, code: "100", location: "monsterZone" }, 8),
          absentWindowEffectGroup(0, "post-flip-summon-opponent-response-turn-open-quick", 8, "open"),
          absentWindowEffectGroup(0, "post-flip-summon-opponent-response-first-turn-chain-quick", 8, "open"),
          absentWindowEffectGroup(0, "post-flip-summon-opponent-response-second-turn-chain-quick", 8, "open"),
          absentWindowEffectGroup(1, "post-flip-summon-opponent-response-opponent-first-chain-quick", 8, "open"),
          absentWindowEffectGroup(1, "post-flip-summon-opponent-response-opponent-second-chain-quick", 8, "open"),
          absentWindowEffectGroup(1, "post-flip-summon-opponent-response-opponent-third-chain-quick", 8, "open"),
          absentWindowEffectGroup(1, "post-flip-summon-opponent-response-opponent-open-quick", 8, "open"),
        ],
        logIncludes: [
          "Post Flip Summon opponent response second turn chain quick resolved",
          "Post Flip Summon opponent response opponent third chain quick resolved",
          "Post Flip Summon opponent response first turn chain quick resolved",
          "Post Flip Summon opponent response opponent second chain quick resolved",
          "Post Flip Summon opponent response opponent first chain quick resolved",
          "Post Flip Summon opponent response turn open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
