import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentSummonGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity post-Pendulum-Summon open fast-effect pass handoff pass resolution fixture", () => {
  it("resolves a post-Pendulum-Summon open fast-effect chain when both players pass after the handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Post Pendulum Summon Pass Resolution Low Scale", kind: "monster", typeFlags: 0x1000001, level: 4, leftScale: 1, rightScale: 1, attack: 1000, defense: 1000 },
      { code: "200", name: "Post Pendulum Summon Pass Resolution High Scale", kind: "monster", typeFlags: 0x1000001, level: 4, leftScale: 8, rightScale: 8, attack: 1000, defense: 1000 },
      { code: "300", name: "Post Pendulum Summon Pass Resolution Candidate", kind: "monster", typeFlags: 0x1000001, level: 4, attack: 1500, defense: 1500 },
      { code: "400", name: "Post Pendulum Summon Pass Resolution Turn Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Post Pendulum Summon Pass Resolution Turn Chain Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Post Pendulum Summon Pass Resolution Opponent Chain Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Post Pendulum Summon Pass Resolution Opponent Open Quick", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "post pendulum summon open fast pass handoff pass resolution fixture",
      options: { seed: 466, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "400", "700"] },
        1: { main: ["500", "600"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "100", from: "hand", to: "spellTrapZone" },
          { player: 0, code: "200", from: "hand", to: "spellTrapZone" },
          { player: 0, code: "400", from: "hand", to: "graveyard" },
          { player: 0, code: "700", from: "hand", to: "graveyard" },
          { player: 1, code: "500", from: "hand", to: "graveyard" },
          { player: 1, code: "600", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "post-pendulum-summon-pass-resolution-turn-open-quick",
            player: 0,
            code: "400",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "open",
            oncePerTurn: true,
            logMessage: "Post Pendulum Summon pass resolution turn open quick resolved",
          },
          {
            id: "post-pendulum-summon-pass-resolution-turn-chain-quick",
            player: 0,
            code: "700",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Post Pendulum Summon pass resolution turn chain quick should not resolve",
          },
          {
            id: "post-pendulum-summon-pass-resolution-opponent-chain-quick",
            player: 1,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Post Pendulum Summon pass resolution opponent chain quick should not resolve",
          },
          {
            id: "post-pendulum-summon-pass-resolution-opponent-open-quick",
            player: 1,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "open",
            logMessage: "Post Pendulum Summon pass resolution opponent open quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep({ type: "pendulumSummon", player: 0, summonUids: ["p0-deck-300-2"], label: "Pendulum Summon selected handoff candidate" }, {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro exposes Pendulum Summons beside turn-player open fast effects before the Pendulum Summon is performed",
            phase: "main1",
            windowId: 0,
            windowKind: "open",
            waitingFor: 0,
            legalActionCounts: { 0: 6, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-turn-open-quick", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "pendulumSummon", player: 0, windowId: 0, windowKind: "open", summonUids: ["p0-deck-300-2"], count: 1 },
              { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-turn-open-quick", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "300", location: "hand" },
                { type: "setMonster", player: 0, code: "300", location: "hand" },
                { type: "pendulumSummon", player: 0, summonUids: ["p0-deck-300-2"] },
              ], 1, 0),
              turnGroup(0),
            ],
            locations: { spellTrapZone: ["100", "200"], hand: ["300"], graveyard: ["400", "700", "500", "600"] },
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-turn-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-opponent-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "post-pendulum-summon-pass-resolution-turn-chain-quick", 0, "open"),
              absentWindowEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-chain-quick", 0, "open"),
              absentWindowEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-open-quick", 0, "open"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns triggerless Pendulum Summons to turn-player open fast-effect priority before post-Pendulum-Summon handoff chains can begin",
            phase: "main1",
            windowId: 1,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            locations: { monsterZone: ["300"], spellTrapZone: ["100", "200"], graveyard: ["400", "700", "500", "600"] },
            cards: [{ uid: "p0-deck-300-2", code: "300", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-turn-open-quick", count: 1 },
              { type: "changePhase", player: 0, windowId: 1, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 1, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 1,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-turn-open-quick", count: 1 }],
              },
              turnGroup(1),
            ],
            absentLegalActions: [
              { type: "pendulumSummon", player: 0, windowId: 1, windowKind: "open", summonUids: ["p0-deck-300-2"] },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-turn-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-opponent-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentSummonGroup({ type: "pendulumSummon", player: 0, summonUids: ["p0-deck-300-2"] }, 1),
              absentWindowEffectGroup(0, "post-pendulum-summon-pass-resolution-turn-chain-quick", 1, "open"),
              absentWindowEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-chain-quick", 1, "open"),
              absentWindowEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-open-quick", 1, "open"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "post-pendulum-summon-pass-resolution-turn-open-quick" })),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent priority before passing the post-Pendulum-Summon pass-resolution response window",
            phase: "main1",
            windowId: 2,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 0, effectId: "post-pendulum-summon-pass-resolution-turn-open-quick", sourceUid: "p0-deck-400-3" }],
            chainPasses: [],
            locations: { monsterZone: ["300"], spellTrapZone: ["100", "200"], graveyard: ["400", "700", "500", "600"] },
            cards: [{ uid: "p0-deck-300-2", code: "300", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 2, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-opponent-chain-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 2, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-chain-quick", 1, 2),
              chainPassGroup(1, 1, 2),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 2, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 2, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-turn-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 2, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-pendulum-summon-pass-resolution-turn-open-quick", 2),
              absentChainEffectGroup(0, "post-pendulum-summon-pass-resolution-turn-chain-quick", 2),
              absentWindowEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-open-quick", 2, "chainResponse"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro reopens turn-player chain-only responses after the opponent passes a post-Pendulum-Summon open fast-effect chain",
            phase: "main1",
            windowId: 3,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 0, effectId: "post-pendulum-summon-pass-resolution-turn-open-quick", sourceUid: "p0-deck-400-3" }],
            chainPasses: [1],
            locations: { monsterZone: ["300"], spellTrapZone: ["100", "200"], graveyard: ["400", "700", "500", "600"] },
            cards: [{ uid: "p0-deck-300-2", code: "300", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-turn-chain-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 3, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "post-pendulum-summon-pass-resolution-turn-chain-quick", 1, 3),
              chainPassGroup(0, 1, 3),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-turn-open-quick" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-opponent-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-pendulum-summon-pass-resolution-turn-open-quick", 3),
              absentChainEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-chain-quick", 3),
              absentWindowEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-open-quick", 3, "chainResponse"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player pass-handoff priority before resolving the post-Pendulum-Summon pass-resolution chain",
            phase: "main1",
            windowId: 3,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 0, effectId: "post-pendulum-summon-pass-resolution-turn-open-quick", sourceUid: "p0-deck-400-3" }],
            chainPasses: [1],
            locations: { monsterZone: ["300"], spellTrapZone: ["100", "200"], graveyard: ["400", "700", "500", "600"] },
            cards: [{ uid: "p0-deck-300-2", code: "300", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-turn-chain-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 3, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "post-pendulum-summon-pass-resolution-turn-chain-quick", 1, 3),
              chainPassGroup(0, 1, 3),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-turn-open-quick" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-opponent-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "post-pendulum-summon-pass-resolution-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-pendulum-summon-pass-resolution-turn-open-quick", 3),
              absentChainEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-chain-quick", 3),
              absentWindowEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-open-quick", 3, "chainResponse"),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves post-Pendulum-Summon pass-handoff chains back to turn-player open priority when both players pass after the handoff",
        phase: "main1",
        windowId: 4,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        locations: { monsterZone: ["300"], spellTrapZone: ["100", "200"], graveyard: ["400", "700", "500", "600"] },
        cards: [{ uid: "p0-deck-300-2", code: "300", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
        legalActionCounts: { 0: 2, 1: 0 },
        legalActionGroupCounts: { 0: 1, 1: 0 },
        legalActions: [
          { type: "changePhase", player: 0, windowId: 4, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 4, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [turnGroup(4)],
        absentLegalActions: [
          { type: "pendulumSummon", player: 0, windowId: 4, windowKind: "open", summonUids: ["p0-deck-300-2"] },
          { type: "activateEffect", player: 0, windowId: 4, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-turn-open-quick" },
          { type: "activateEffect", player: 0, windowId: 4, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-turn-chain-quick" },
          { type: "activateEffect", player: 1, windowId: 4, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-opponent-chain-quick" },
          { type: "activateEffect", player: 1, windowId: 4, windowKind: "open", effectId: "post-pendulum-summon-pass-resolution-opponent-open-quick" },
        ],
        absentLegalActionGroups: [
          absentSummonGroup({ type: "pendulumSummon", player: 0, summonUids: ["p0-deck-300-2"] }, 4),
          absentWindowEffectGroup(0, "post-pendulum-summon-pass-resolution-turn-open-quick", 4, "open"),
          absentWindowEffectGroup(0, "post-pendulum-summon-pass-resolution-turn-chain-quick", 4, "open"),
          absentWindowEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-chain-quick", 4, "open"),
          absentWindowEffectGroup(1, "post-pendulum-summon-pass-resolution-opponent-open-quick", 4, "open"),
        ],
        logIncludes: ["Post Pendulum Summon pass resolution turn open quick resolved"],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
