import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution SEGOC pass-handoff turn-response opponent-response resolution fixture", () => {
  it("resolves after the opponent responds to the trigger player's final handoff response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Handoff Turn Opponent Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Chain Handoff Turn Opponent Resolution First Turn Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Chain Handoff Turn Opponent Resolution Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Chain Handoff Turn Opponent Resolution First Opponent Quick", kind: "monster", attack: 1500, defense: 1600 },
      { code: "450", name: "Chain Handoff Turn Opponent Resolution Second Opponent Quick", kind: "monster", attack: 1300, defense: 1300 },
      { code: "500", name: "Chain Handoff Turn Opponent Resolution Optional", kind: "monster", attack: 1200, defense: 1200 },
      { code: "700", name: "Chain Handoff Turn Opponent Resolution Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Chain Handoff Turn Opponent Resolution Second Turn Quick", kind: "monster", attack: 1600, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution segoc pass handoff turn-response opponent-response resolution fixture",
      options: { seed: 370, startingHandSize: 6 },
      decks: {
        0: { main: ["100", "200", "300", "500", "700", "900"] },
        1: { main: ["400", "450", "800", "800", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-chain-handoff-turn-opponent-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "900", from: "hand", to: "graveyard" },
              { player: 1, code: "400", from: "hand", to: "graveyard" },
              { player: 1, code: "450", from: "hand", to: "graveyard" },
            ],
            logMessage: "Chain handoff turn opponent resolution starter resolved",
          },
          {
            id: "fixture-chain-handoff-turn-opponent-resolution-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Chain handoff turn opponent resolution mandatory resolved",
          },
          {
            id: "fixture-chain-handoff-turn-opponent-resolution-optional",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain handoff turn opponent resolution optional resolved",
          },
          {
            id: "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain handoff turn opponent resolution first turn quick resolved",
          },
          {
            id: "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick",
            player: 1,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain handoff turn opponent resolution first opponent quick resolved",
          },
          {
            id: "fixture-chain-handoff-turn-opponent-resolution-second-opponent-quick",
            player: 1,
            code: "450",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain handoff turn opponent resolution second opponent quick resolved",
          },
          {
            id: "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick",
            player: 0,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain handoff turn opponent resolution second turn quick resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-handoff-turn-opponent-resolution-starter" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-handoff-turn-opponent-resolution-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-handoff-turn-opponent-resolution-optional" })),
        makeScriptedStep(makeResponseSelector("passChain", 1)),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the trigger player's reopened response window restorable before the final turn-player handoff response",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-turn-opponent-resolution-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-turn-opponent-resolution-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick", sourceUid: "p0-deck-200-1" },
              { player: 1, effectId: "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick", sourceUid: "p1-deck-400-0" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick", 1, 6),
              chainPassGroup(0, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick", 6),
              absentChainEffectGroup(1, "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick", 6),
            ],
            locations: { graveyard: ["700", "200", "900", "400", "450"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
            logIncludes: ["Chain handoff turn opponent resolution starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro gives the opponent another chain-response window after the trigger player's final handoff response",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-turn-opponent-resolution-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-turn-opponent-resolution-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick", sourceUid: "p0-deck-200-1" },
              { player: 1, effectId: "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick", sourceUid: "p1-deck-400-0" },
              { player: 0, effectId: "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick", sourceUid: "p0-deck-900-5" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-handoff-turn-opponent-resolution-second-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-chain-handoff-turn-opponent-resolution-second-opponent-quick", 1, 7),
              chainPassGroup(1, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick" },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 7, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-turn-opponent-resolution-optional", triggerBucket: "turnOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick", 7),
              absentChainEffectGroup(0, "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick", 7),
              absentChainEffectGroup(1, "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick", 7),
              absentTriggerActivationGroup(0, "fixture-chain-handoff-turn-opponent-resolution-optional", "turnOptional", 7, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900", "400", "450"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-handoff-turn-opponent-resolution-second-opponent-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the pass-handoff turn-response opponent-response resolution window restorable before the final opponent response",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-turn-opponent-resolution-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-turn-opponent-resolution-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick", sourceUid: "p0-deck-200-1" },
              { player: 1, effectId: "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick", sourceUid: "p1-deck-400-0" },
              { player: 0, effectId: "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick", sourceUid: "p0-deck-900-5" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-handoff-turn-opponent-resolution-second-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-chain-handoff-turn-opponent-resolution-second-opponent-quick", 1, 7),
              chainPassGroup(1, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick" },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 7, windowKind: "triggerBucket", effectId: "fixture-chain-handoff-turn-opponent-resolution-optional", triggerBucket: "turnOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick", 7),
              absentChainEffectGroup(0, "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick", 7),
              absentChainEffectGroup(1, "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick", 7),
              absentTriggerActivationGroup(0, "fixture-chain-handoff-turn-opponent-resolution-optional", "turnOptional", 7, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900", "400", "450"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves the chain-created SEGOC trigger chain after the opponent answers the trigger player's final handoff response",
        phase: "main1",
        windowId: 8,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-handoff-turn-opponent-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 8,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-handoff-turn-opponent-resolution-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
          ], 1, 8),
          turnGroup(8),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "fixture-chain-handoff-turn-opponent-resolution-second-opponent-quick" },
          { type: "activateTrigger", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-handoff-turn-opponent-resolution-optional" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-handoff-turn-opponent-resolution-first-turn-quick", 8, "open"),
          absentWindowEffectGroup(0, "fixture-chain-handoff-turn-opponent-resolution-second-turn-quick", 8, "open"),
          absentWindowEffectGroup(1, "fixture-chain-handoff-turn-opponent-resolution-first-opponent-quick", 8, "open"),
          absentWindowEffectGroup(1, "fixture-chain-handoff-turn-opponent-resolution-second-opponent-quick", 8, "open"),
          absentTriggerActivationGroup(0, "fixture-chain-handoff-turn-opponent-resolution-optional", "turnOptional", 8, "open"),
        ],
        locations: { graveyard: ["700", "200", "900", "400", "450"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
        logIncludes: [
          "Chain handoff turn opponent resolution starter resolved",
          "Chain handoff turn opponent resolution second opponent quick resolved",
          "Chain handoff turn opponent resolution second turn quick resolved",
          "Chain handoff turn opponent resolution first opponent quick resolved",
          "Chain handoff turn opponent resolution first turn quick resolved",
          "Chain handoff turn opponent resolution optional resolved",
          "Chain handoff turn opponent resolution mandatory resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
