import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentSummonGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity post-Synchro-Summon open fast-effect handoff opponent-response until-chain-end limit fixture", () => {
  it("keeps until-chain-end limits after the opponent responds to a post-Synchro-Summon turn-response handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Post Synchro Opponent Response Until Tuner", kind: "monster", typeFlags: 0x1001, attack: 1000, defense: 1000 },
      { code: "200", name: "Post Synchro Opponent Response Until Non-Tuner", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Post Synchro Opponent Response Until Turn Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Post Synchro Opponent Response Until Turn First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "990", name: "Post Synchro Opponent Response Until Turn Blocked Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Post Synchro Opponent Response Until Opponent First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Post Synchro Opponent Response Until Opponent Second Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "800", name: "Post Synchro Opponent Response Until Opponent Chain Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Post Synchro Opponent Response Until Opponent Followup Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "950", name: "Post Synchro Opponent Response Until Opponent Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "900", name: "Post Synchro Opponent Response Until Synchro Monster", kind: "extra", synchroMaterials: { tuner: "100", nonTuners: ["200"] }, attack: 2000, defense: 2000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "post synchro summon open fast pass handoff opponent response until-chain-end limit fixture",
      options: { seed: 512, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "600", "990"], extra: ["900"] },
        1: { main: ["400", "500", "800", "700", "950"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "100", from: "hand", to: "monsterZone", position: "faceUpAttack" },
          { player: 0, code: "200", from: "hand", to: "monsterZone", position: "faceUpAttack" },
          { player: 0, code: "300", from: "hand", to: "graveyard" },
          { player: 0, code: "600", from: "hand", to: "graveyard" },
          { player: 0, code: "990", from: "hand", to: "graveyard" },
          { player: 1, code: "400", from: "hand", to: "graveyard" },
          { player: 1, code: "500", from: "hand", to: "graveyard" },
          { player: 1, code: "800", from: "hand", to: "graveyard" },
          { player: 1, code: "700", from: "hand", to: "graveyard" },
          { player: 1, code: "950", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "post-synchro-summon-handoff-opponent-response-until-turn-open-quick",
            player: 0,
            code: "300",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "open",
            oncePerTurn: true,
            logMessage: "Post Synchro Summon handoff opponent-response until turn open quick resolved",
          },
          {
            id: "post-synchro-summon-handoff-opponent-response-until-turn-first",
            player: 0,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Post Synchro Summon handoff opponent-response until turn first quick resolved",
          },
          {
            id: "post-synchro-summon-handoff-opponent-response-until-turn-blocked",
            player: 0,
            code: "990",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Post Synchro Summon handoff opponent-response until turn blocked quick should not resolve",
          },
          {
            id: "post-synchro-summon-handoff-opponent-response-until-opponent-first",
            player: 1,
            code: "400",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Post Synchro Summon handoff opponent-response until opponent first quick resolved",
          },
          {
            id: "post-synchro-summon-handoff-opponent-response-until-opponent-second",
            player: 1,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Post Synchro Summon handoff opponent-response until opponent second quick resolved",
          },
          {
            id: "post-synchro-summon-handoff-opponent-response-until-opponent-chain-limiter",
            player: 1,
            code: "800",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 1 },
            logMessage: "Post Synchro Summon handoff opponent-response until opponent chain limiter resolved",
          },
          {
            id: "post-synchro-summon-handoff-opponent-response-until-opponent-followup",
            player: 1,
            code: "700",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Post Synchro Summon handoff opponent-response until opponent followup should not resolve",
          },
          {
            id: "post-synchro-summon-handoff-opponent-response-until-opponent-open",
            player: 1,
            code: "950",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "open",
            logMessage: "Post Synchro Summon handoff opponent-response until opponent open quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("synchroSummon", 0, { code: "900", location: "extraDeck", materialUids: ["p0-deck-100-0", "p0-deck-200-1"] })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "post-synchro-summon-handoff-opponent-response-until-turn-open-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-first" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-second" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "post-synchro-summon-handoff-opponent-response-until-turn-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-chain-limiter" }), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro applies SetChainLimitTillChainEnd restrictions after the opponent responds from a post-Synchro-Summon response window reopened by the turn player's answer",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "post-synchro-summon-handoff-opponent-response-until-turn-open-quick", sourceUid: "p0-deck-300-2" },
              { player: 1, effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-first", sourceUid: "p1-deck-400-0" },
              { player: 1, effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-second", sourceUid: "p1-deck-500-1" },
              { player: 0, effectId: "post-synchro-summon-handoff-opponent-response-until-turn-first", sourceUid: "p0-deck-600-3" },
              { player: 1, effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-chain-limiter", sourceUid: "p1-deck-800-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "600", "990", "400", "500", "800", "700", "950"] },
            cards: [
              { uid: "p0-extraDeck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
              { uid: "p0-deck-100-0", code: "100", location: "graveyard" },
              { uid: "p0-deck-200-1", code: "200", location: "graveyard" },
            ],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "post-synchro-summon-handoff-opponent-response-until-opponent-followup", 1, 7),
              chainPassGroup(1, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "post-synchro-summon-handoff-opponent-response-until-turn-blocked" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-chain-limiter" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-synchro-summon-handoff-opponent-response-until-turn-blocked", 7),
              absentChainEffectGroup(1, "post-synchro-summon-handoff-opponent-response-until-opponent-chain-limiter", 7),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the post-Synchro-Summon opponent-response SetChainLimitTillChainEnd window restorable before the allowed opponent passes",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "post-synchro-summon-handoff-opponent-response-until-turn-open-quick", sourceUid: "p0-deck-300-2" },
              { player: 1, effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-first", sourceUid: "p1-deck-400-0" },
              { player: 1, effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-second", sourceUid: "p1-deck-500-1" },
              { player: 0, effectId: "post-synchro-summon-handoff-opponent-response-until-turn-first", sourceUid: "p0-deck-600-3" },
              { player: 1, effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-chain-limiter", sourceUid: "p1-deck-800-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "600", "990", "400", "500", "800", "700", "950"] },
            cards: [
              { uid: "p0-extraDeck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
              { uid: "p0-deck-100-0", code: "100", location: "graveyard" },
              { uid: "p0-deck-200-1", code: "200", location: "graveyard" },
            ],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "post-synchro-summon-handoff-opponent-response-until-opponent-followup", 1, 7),
              chainPassGroup(1, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "post-synchro-summon-handoff-opponent-response-until-turn-blocked" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-chain-limiter" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-synchro-summon-handoff-opponent-response-until-turn-blocked", 7),
              absentChainEffectGroup(1, "post-synchro-summon-handoff-opponent-response-until-opponent-chain-limiter", 7),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears until-chain-end limits and returns post-Synchro-Summon opponent-response handoff chains to turn-player open priority after the allowed opponent passes",
        phase: "main1",
        windowId: 8,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "600", "990", "400", "500", "800", "700", "950"] },
        cards: [
          { uid: "p0-extraDeck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
          { uid: "p0-deck-100-0", code: "100", location: "graveyard" },
          { uid: "p0-deck-200-1", code: "200", location: "graveyard" },
        ],
        legalActionCounts: { 0: 2, 1: 0 },
        legalActionGroupCounts: { 0: 1, 1: 0 },
        legalActions: [
          { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [turnGroup(8)],
        absentLegalActions: [
          { type: "synchroSummon", player: 0, windowId: 8, windowKind: "open", code: "900", location: "extraDeck" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "post-synchro-summon-handoff-opponent-response-until-turn-open-quick" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "post-synchro-summon-handoff-opponent-response-until-turn-first" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "post-synchro-summon-handoff-opponent-response-until-turn-blocked" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-second" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-chain-limiter" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-followup" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "post-synchro-summon-handoff-opponent-response-until-opponent-open" },
        ],
        absentLegalActionGroups: [
          absentSummonGroup({ type: "synchroSummon", player: 0, code: "900", location: "extraDeck" }, 8),
          absentWindowEffectGroup(0, "post-synchro-summon-handoff-opponent-response-until-turn-open-quick", 8, "open"),
          absentWindowEffectGroup(0, "post-synchro-summon-handoff-opponent-response-until-turn-first", 8, "open"),
          absentWindowEffectGroup(0, "post-synchro-summon-handoff-opponent-response-until-turn-blocked", 8, "open"),
          absentWindowEffectGroup(1, "post-synchro-summon-handoff-opponent-response-until-opponent-first", 8, "open"),
          absentWindowEffectGroup(1, "post-synchro-summon-handoff-opponent-response-until-opponent-second", 8, "open"),
          absentWindowEffectGroup(1, "post-synchro-summon-handoff-opponent-response-until-opponent-chain-limiter", 8, "open"),
          absentWindowEffectGroup(1, "post-synchro-summon-handoff-opponent-response-until-opponent-followup", 8, "open"),
          absentWindowEffectGroup(1, "post-synchro-summon-handoff-opponent-response-until-opponent-open", 8, "open"),
        ],
        logIncludes: [
          "Post Synchro Summon handoff opponent-response until opponent chain limiter resolved",
          "Post Synchro Summon handoff opponent-response until turn first quick resolved",
          "Post Synchro Summon handoff opponent-response until opponent second quick resolved",
          "Post Synchro Summon handoff opponent-response until opponent first quick resolved",
          "Post Synchro Summon handoff opponent-response until turn open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
