import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, chainEffectGroup, chainPassGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution cross-player SEGOC pass-handoff opponent-response until-chain-end limit fixture", () => {
  it("keeps until-chain-end limits after the opponent responds to a cross-player chain-created SEGOC pass handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Cross Handoff Until Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Cross Handoff Until Turn Blocked Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Cross Handoff Until Turn Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Cross Handoff Until Opponent Mandatory", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Cross Handoff Until Turn Optional", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Cross Handoff Until Opponent Optional", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Cross Handoff Until Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Cross Handoff Until Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Cross Handoff Until Opponent Chain Limiter", kind: "monster", attack: 1600, defense: 1000 },
      { code: "950", name: "Cross Handoff Until Opponent Followup", kind: "monster", attack: 1300, defense: 1300 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution cross-player segoc pass handoff opponent response until-chain-end limit fixture",
      options: { seed: 392, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "500", "700"] },
        1: { main: ["400", "600", "900", "950", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-cross-handoff-until-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            oncePerTurn: true,
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 1, code: "900", from: "hand", to: "graveyard" },
              { player: 1, code: "950", from: "hand", to: "graveyard" },
            ],
            logMessage: "Cross handoff until starter resolved",
          },
          {
            id: "fixture-cross-handoff-until-turn-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Cross handoff until turn mandatory resolved",
          },
          {
            id: "fixture-cross-handoff-until-opponent-mandatory",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Cross handoff until opponent mandatory resolved",
          },
          {
            id: "fixture-cross-handoff-until-turn-optional",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Cross handoff until turn optional resolved",
          },
          {
            id: "fixture-cross-handoff-until-opponent-optional",
            player: 1,
            code: "600",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Cross handoff until opponent optional resolved",
          },
          {
            id: "fixture-cross-handoff-until-turn-blocked",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Cross handoff until turn blocked should not resolve",
          },
          {
            id: "fixture-cross-handoff-until-opponent-chain-limiter",
            player: 1,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 1 },
            logMessage: "Cross handoff until opponent chain limiter resolved",
          },
          {
            id: "fixture-cross-handoff-until-opponent-followup",
            player: 1,
            code: "950",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Cross handoff until opponent followup should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-handoff-until-starter" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-handoff-until-turn-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-handoff-until-opponent-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-handoff-until-turn-optional" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-handoff-until-opponent-optional" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-cross-handoff-until-opponent-chain-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the cross-player SEGOC opponent-response handoff window restorable before the opponent applies an until-chain-end limit",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-until-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-until-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-cross-handoff-until-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-until-opponent-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [0],
            chainLimits: [],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "500", "400", "600", "800"] },
            legalActionCounts: { 0: 0, 1: 3 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-handoff-until-opponent-chain-limiter", count: 1 },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-handoff-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 6,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-handoff-until-opponent-chain-limiter", count: 1 },
                  { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-handoff-until-opponent-followup", count: 1 },
                ],
              },
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-handoff-until-turn-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "fixture-cross-handoff-until-turn-blocked", 6)],
          },
          after: {
            source: "edopro",
            note: "EDOPro applies SetChainLimitTillChainEnd restrictions when the opponent responds from a cross-player chain-created SEGOC pass-handoff window",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-until-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-until-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-cross-handoff-until-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-until-opponent-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-until-opponent-chain-limiter", sourceUid: "p1-deck-900-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "500", "400", "600", "800"] },
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-handoff-until-opponent-followup", 1, 7),
              chainPassGroup(1, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-until-turn-blocked" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-until-opponent-chain-limiter" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-handoff-until-turn-blocked", 7),
              absentChainEffectGroup(1, "fixture-cross-handoff-until-opponent-chain-limiter", 7),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the cross-player SEGOC opponent-response SetChainLimitTillChainEnd window restorable before the allowed opponent passes",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-until-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-until-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-cross-handoff-until-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-until-opponent-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-until-opponent-chain-limiter", sourceUid: "p1-deck-900-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "500", "400", "600", "800"] },
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-handoff-until-opponent-followup", 1, 7),
              chainPassGroup(1, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-until-turn-blocked" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-until-opponent-chain-limiter" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-handoff-until-turn-blocked", 7),
              absentChainEffectGroup(1, "fixture-cross-handoff-until-opponent-chain-limiter", 7),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears until-chain-end limits and returns cross-player chain-created SEGOC handoff chains to turn-player open priority after the allowed opponent passes",
        phase: "main1",
        windowId: 8,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "500", "400", "600", "800"] },
        legalActionCounts: { 0: 8, 1: 0 },
        legalActionGroupCounts: { 0: 2, 1: 0 },
        legalActions: [
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Summons",
            windowId: 8,
            windowKind: "open",
            count: 1,
            actions: [
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "500", location: "hand", count: 1 },
            ],
          },
          {
            player: 0,
            label: "Turn",
            windowId: 8,
            windowKind: "open",
            count: 1,
            actions: [
              { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
            ],
          },
        ],
        logIncludes: [
          "Cross handoff until opponent chain limiter resolved",
          "Cross handoff until opponent optional resolved",
          "Cross handoff until turn optional resolved",
          "Cross handoff until opponent mandatory resolved",
          "Cross handoff until turn mandatory resolved",
          "Cross handoff until starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
