import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chainEnded open fast-effect chain-response turn-response resolution fixture", () => {
  it("resolves turn-player responses to direct post-chainEnded opponent responses after the opponent passes", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Ended Direct Turn Response Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Chain Ended Direct Turn Response Resolution Solved Blocker", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Chain Ended Direct Turn Response Resolution Cleanup", kind: "monster", attack: 1500, defense: 1600 },
      { code: "400", name: "Chain Ended Direct Turn Response Resolution Open Quick", kind: "monster", attack: 1200, defense: 1200 },
      { code: "500", name: "Chain Ended Direct Turn Response Resolution Opponent First Chain", kind: "monster", attack: 1100, defense: 1100 },
      { code: "600", name: "Chain Ended Direct Turn Response Resolution Turn Chain", kind: "monster", attack: 900, defense: 900 },
      { code: "700", name: "Chain Ended Direct Turn Response Resolution Opponent Open Quick", kind: "monster", attack: 800, defense: 800 },
      { code: "800", name: "Chain Ended Direct Turn Response Resolution Opponent Second Chain", kind: "monster", attack: 700, defense: 700 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "deferred chain ended open fast chain response turn response resolution fixture",
      options: { seed: 644, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "400", "600"] },
        1: { main: ["500", "800", "700"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "600", from: "hand", to: "graveyard" },
          { player: 1, code: "500", from: "hand", to: "graveyard" },
          { player: 1, code: "800", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "fixture-chain-ended-direct-turn-response-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            logMessage: "Chain ended direct turn response resolution starter resolved",
          },
          {
            id: "fixture-chain-ended-direct-turn-response-resolution-solved-blocker",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainSolved",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain ended direct turn response resolution solved blocker should not resolve",
          },
          {
            id: "fixture-chain-ended-direct-turn-response-resolution-cleanup",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            moveCardsOnResolve: [
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "600", from: "graveyard", to: "hand" },
              { player: 1, code: "500", from: "graveyard", to: "hand" },
              { player: 1, code: "800", from: "graveyard", to: "hand" },
            ],
            logMessage: "Chain ended direct turn response resolution cleanup resolved",
          },
          {
            id: "fixture-chain-ended-direct-turn-response-resolution-open-fast",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended direct turn response resolution open fast resolved",
          },
          {
            id: "fixture-chain-ended-direct-turn-response-resolution-turn-chain",
            player: 0,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct turn response resolution turn chain resolved",
          },
          {
            id: "fixture-chain-ended-direct-turn-response-resolution-opponent-first",
            player: 1,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct turn response resolution opponent first resolved",
          },
          {
            id: "fixture-chain-ended-direct-turn-response-resolution-opponent-open",
            player: 1,
            code: "700",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended direct turn response resolution opponent open should not resolve",
          },
          {
            id: "fixture-chain-ended-direct-turn-response-resolution-opponent-second",
            player: 1,
            code: "800",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct turn response resolution opponent second should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-turn-response-resolution-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-chain-ended-direct-turn-response-resolution-solved-blocker" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-ended-direct-turn-response-resolution-cleanup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-turn-response-resolution-open-fast" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-direct-turn-response-resolution-opponent-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-turn-response-resolution-turn-chain" })),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro restores opponent response priority before resolving a direct post-chainEnded turn response chain",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-direct-turn-response-resolution-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 1, effectId: "fixture-chain-ended-direct-turn-response-resolution-opponent-first", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "fixture-chain-ended-direct-turn-response-resolution-turn-chain", sourceUid: "p0-deck-600-4" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chainLimits: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-turn-response-resolution-opponent-second", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-chain-ended-direct-turn-response-resolution-opponent-second", 1, 6),
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-turn-response-resolution-open-fast" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-turn-response-resolution-turn-chain" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-turn-response-resolution-opponent-first" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-turn-response-resolution-opponent-open" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-direct-turn-response-resolution-open-fast", 6, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-direct-turn-response-resolution-turn-chain", 6),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-turn-response-resolution-opponent-first", 6),
              absentWindowEffectGroup(1, "fixture-chain-ended-direct-turn-response-resolution-opponent-open", 6, "chainResponse"),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves direct post-chainEnded turn response chains after the opponent passes the reopened response window",
        phase: "main1",
        windowId: 7,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chainLimits: [],
        locations: { graveyard: ["200"], hand: ["100", "300", "400", "600", "500", "800", "700"] },
        legalActionCounts: { 0: 11, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-turn-response-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "600", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "600", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 7, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 7, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 7,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-turn-response-resolution-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "400", location: "hand" },
            { type: "normalSummon", player: 0, code: "600", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "400", location: "hand" },
            { type: "setMonster", player: 0, code: "600", location: "hand" },
          ], 1, 7),
          turnGroup(7),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-turn-response-resolution-open-fast" },
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-turn-response-resolution-turn-chain" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-turn-response-resolution-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-turn-response-resolution-opponent-second" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-turn-response-resolution-opponent-open" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-turn-response-resolution-open-fast", 7, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-turn-response-resolution-turn-chain", 7, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-turn-response-resolution-opponent-first", 7, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-turn-response-resolution-opponent-second", 7, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-turn-response-resolution-opponent-open", 7, "open"),
        ],
        logIncludes: [
          "Chain ended direct turn response resolution turn chain resolved",
          "Chain ended direct turn response resolution opponent first resolved",
          "Chain ended direct turn response resolution open fast resolved",
          "Chain ended direct turn response resolution cleanup resolved",
          "Chain ended direct turn response resolution starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
