import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity post-position-change open fast-effect handoff turn-response until-chain-end limit fixture", () => {
  it("keeps until-chain-end limits after the turn player responds to a post-position-change pass handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Post Position Until Change Monster", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Post Position Until Turn Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Post Position Until Turn Chain Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Post Position Until Turn Followup Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Post Position Until Opponent Blocked Quick", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "post position change open fast pass handoff turn response until-chain-end limit fixture",
      options: { seed: 383, startingHandSize: 4 },
      decks: {
        0: { main: ["100", "300", "600", "700"] },
        1: { main: ["400"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "100", from: "hand", to: "monsterZone", position: "faceUpAttack" },
          { player: 0, code: "300", from: "hand", to: "graveyard" },
          { player: 0, code: "600", from: "hand", to: "graveyard" },
          { player: 0, code: "700", from: "hand", to: "graveyard" },
          { player: 1, code: "400", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "post-position-until-turn-open-quick",
            player: 0,
            code: "300",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "open",
            oncePerTurn: true,
            logMessage: "Post position change until turn open quick resolved",
          },
          {
            id: "post-position-until-turn-chain-limiter",
            player: 0,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 0 },
            logMessage: "Post position change until turn chain limiter resolved",
          },
          {
            id: "post-position-until-turn-followup",
            player: 0,
            code: "700",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Post position change until turn followup should not resolve",
          },
          {
            id: "post-position-until-opponent-blocked",
            player: 1,
            code: "400",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Post position change until opponent blocked should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("changePosition", 0, { code: "100", location: "monsterZone", position: "faceUpDefense" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro exposes manual position changes beside turn-player open fast effects before the until-chain-end pass-handoff fixture begins",
            phase: "main1",
            windowId: 0,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            positionsChanged: [],
            locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400"] },
            cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpAttack", faceUp: true }],
            legalActionCounts: { 0: 4, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-position-until-turn-open-quick", count: 1 },
              { type: "changePosition", player: 0, windowId: 0, windowKind: "open", code: "100", location: "monsterZone", position: "faceUpDefense", count: 1 },
              { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-position-until-turn-open-quick", count: 1 }],
              },
              {
                player: 0,
                label: "Actions",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [{ type: "changePosition", player: 0, windowId: 0, windowKind: "open", code: "100", location: "monsterZone", position: "faceUpDefense", count: 1 }],
              },
              turnGroup(0),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-position-until-turn-chain-limiter" },
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-position-until-turn-followup" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "post-position-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "post-position-until-turn-chain-limiter", 0, "open"),
              absentWindowEffectGroup(0, "post-position-until-turn-followup", 0, "open"),
              absentWindowEffectGroup(1, "post-position-until-opponent-blocked", 0, "open"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns manual position changes to turn-player open fast-effect priority before until-chain-end limits can be created",
            phase: "main1",
            windowId: 1,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            chainLimits: [],
            positionsChanged: ["p0-deck-100-0"],
            locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400"] },
            cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpDefense", faceUp: true }],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-position-until-turn-open-quick", count: 1 },
              { type: "changePhase", player: 0, windowId: 1, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 1, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 1,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-position-until-turn-open-quick", count: 1 }],
              },
              turnGroup(1),
            ],
            absentLegalActions: [
              { type: "changePosition", player: 0, uid: "p0-deck-100-0", windowId: 1, windowKind: "open" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-position-until-turn-chain-limiter" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-position-until-turn-followup" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "post-position-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              {
                player: 0,
                label: "Actions",
                windowId: 1,
                windowKind: "open",
                actions: [{ type: "changePosition", player: 0, uid: "p0-deck-100-0", windowId: 1, windowKind: "open" }],
              },
              absentWindowEffectGroup(0, "post-position-until-turn-chain-limiter", 1, "open"),
              absentWindowEffectGroup(0, "post-position-until-turn-followup", 1, "open"),
              absentWindowEffectGroup(1, "post-position-until-opponent-blocked", 1, "open"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "post-position-until-turn-open-quick" })),
        makeScriptedStep(makeResponseSelector("passChain", 1)),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "post-position-until-turn-chain-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player pass-handoff priority before the post-position-change until-chain-end limiter is chained",
            phase: "main1",
            windowId: 3,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 0, effectId: "post-position-until-turn-open-quick", sourceUid: "p0-deck-300-1" }],
            chainPasses: [1],
            chainLimits: [],
            positionsChanged: ["p0-deck-100-0"],
            locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400"] },
            cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpDefense", faceUp: true }],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-position-until-turn-chain-limiter", count: 1 },
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-position-until-turn-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 3, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 3,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-position-until-turn-chain-limiter", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-position-until-turn-followup", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 3),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-position-until-turn-open-quick" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "post-position-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-position-until-turn-open-quick", 3),
              absentChainEffectGroup(1, "post-position-until-opponent-blocked", 3),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro applies SetChainLimitTillChainEnd restrictions when the turn player responds from a post-position-change pass-handoff window",
            phase: "main1",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "post-position-until-turn-open-quick", sourceUid: "p0-deck-300-1" },
              { player: 0, effectId: "post-position-until-turn-chain-limiter", sourceUid: "p0-deck-600-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            positionsChanged: ["p0-deck-100-0"],
            locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400"] },
            cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpDefense", faceUp: true }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-position-until-turn-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "post-position-until-turn-followup", 1, 4),
              chainPassGroup(0, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-position-until-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-position-until-turn-chain-limiter" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "post-position-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-position-until-turn-open-quick", 4),
              absentChainEffectGroup(0, "post-position-until-turn-chain-limiter", 4),
              absentChainEffectGroup(1, "post-position-until-opponent-blocked", 4),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the post-position-change SetChainLimitTillChainEnd response window restorable before the allowed player passes",
            phase: "main1",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "post-position-until-turn-open-quick", sourceUid: "p0-deck-300-1" },
              { player: 0, effectId: "post-position-until-turn-chain-limiter", sourceUid: "p0-deck-600-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            positionsChanged: ["p0-deck-100-0"],
            locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400"] },
            cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpDefense", faceUp: true }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-position-until-turn-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "post-position-until-turn-followup", 1, 4),
              chainPassGroup(0, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-position-until-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-position-until-turn-chain-limiter" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "post-position-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-position-until-turn-open-quick", 4),
              absentChainEffectGroup(0, "post-position-until-turn-chain-limiter", 4),
              absentChainEffectGroup(1, "post-position-until-opponent-blocked", 4),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears until-chain-end limits and returns post-position-change handoff chains to turn-player open priority after the allowed player passes",
        phase: "main1",
        windowId: 5,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        positionsChanged: ["p0-deck-100-0"],
        locations: { monsterZone: ["100"], graveyard: ["300", "600", "700", "400"] },
        cards: [{ uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpDefense", faceUp: true }],
        legalActionCounts: { 0: 2, 1: 0 },
        legalActionGroupCounts: { 0: 1, 1: 0 },
        legalActions: [
          { type: "changePhase", player: 0, windowId: 5, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 5, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [turnGroup(5)],
        absentLegalActions: [
          { type: "changePosition", player: 0, uid: "p0-deck-100-0", windowId: 5, windowKind: "open" },
          { type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "post-position-until-turn-open-quick" },
          { type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "post-position-until-turn-chain-limiter" },
          { type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "post-position-until-turn-followup" },
          { type: "activateEffect", player: 1, windowId: 5, windowKind: "open", effectId: "post-position-until-opponent-blocked" },
        ],
        absentLegalActionGroups: [
          {
            player: 0,
            label: "Actions",
            windowId: 5,
            windowKind: "open",
            actions: [{ type: "changePosition", player: 0, uid: "p0-deck-100-0", windowId: 5, windowKind: "open" }],
          },
          absentWindowEffectGroup(0, "post-position-until-turn-open-quick", 5, "open"),
          absentWindowEffectGroup(0, "post-position-until-turn-chain-limiter", 5, "open"),
          absentWindowEffectGroup(0, "post-position-until-turn-followup", 5, "open"),
          absentWindowEffectGroup(1, "post-position-until-opponent-blocked", 5, "open"),
        ],
        logIncludes: [
          "Post position change until turn chain limiter resolved",
          "Post position change until turn open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
