import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution cross-player SEGOC decline pass handoff turn response fixture", () => {
  it("resolves trigger-player responses after opponent responses to cross-player post-decline handoff chains", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Cross Decline Handoff Turn Response Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Turn Cross Decline Handoff Turn Response First Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Cross Decline Handoff Turn Response Turn Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Cross Decline Handoff Turn Response Opponent Mandatory", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Cross Decline Handoff Turn Response Turn Optional", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Cross Decline Handoff Turn Response Opponent Optional", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Cross Decline Handoff Turn Response Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Opponent Cross Decline Handoff Turn Response Quick", kind: "monster", attack: 1600, defense: 1000 },
      { code: "950", name: "Turn Cross Decline Handoff Turn Response Second Quick", kind: "monster", attack: 1300, defense: 1300 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution cross-player segoc decline pass handoff turn response fixture",
      options: { seed: 324, startingHandSize: 6 },
      decks: {
        0: { main: ["100", "200", "300", "500", "700", "950"] },
        1: { main: ["400", "600", "900", "800", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-cross-decline-handoff-turn-response-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "950", from: "hand", to: "graveyard" },
              { player: 1, code: "900", from: "hand", to: "graveyard" },
            ],
            logMessage: "Cross decline handoff turn response starter resolved",
          },
          {
            id: "fixture-cross-decline-handoff-turn-response-turn-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Cross decline handoff turn response turn mandatory resolved",
          },
          {
            id: "fixture-cross-decline-handoff-turn-response-opponent-mandatory",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Cross decline handoff turn response opponent mandatory resolved",
          },
          {
            id: "fixture-cross-decline-handoff-turn-response-turn-optional",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Cross decline handoff turn response turn optional resolved",
          },
          {
            id: "fixture-cross-decline-handoff-turn-response-opponent-optional",
            player: 1,
            code: "600",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Cross decline handoff turn response opponent optional should not resolve",
          },
          {
            id: "fixture-cross-decline-handoff-turn-response-first-turn-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross decline handoff turn response first turn quick resolved",
          },
          {
            id: "fixture-cross-decline-handoff-turn-response-opponent-quick",
            player: 1,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross decline handoff turn response opponent quick resolved",
          },
          {
            id: "fixture-cross-decline-handoff-turn-response-second-turn-quick",
            player: 0,
            code: "950",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross decline handoff turn response second turn quick resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-decline-handoff-turn-response-starter" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-decline-handoff-turn-response-turn-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-decline-handoff-turn-response-opponent-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-decline-handoff-turn-response-turn-optional" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 1, { effectId: "fixture-cross-decline-handoff-turn-response-opponent-optional" })),
        makeScriptedStep(makeResponseSelector("passChain", 1)),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-decline-handoff-turn-response-first-turn-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-cross-decline-handoff-turn-response-opponent-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the opponent response window restorable before chaining to the trigger player's post-decline handoff link",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-decline-handoff-turn-response-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-turn-response-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-turn-response-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-turn-response-first-turn-quick", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-turn-response-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-decline-handoff-turn-response-opponent-quick", 1, 7),
              chainPassGroup(1, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-turn-response-first-turn-quick" },
              { type: "activateTrigger", player: 1, windowId: 7, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-turn-response-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-decline-handoff-turn-response-first-turn-quick", 7),
              absentTriggerActivationGroup(1, "fixture-cross-decline-handoff-turn-response-opponent-optional", "opponentOptional", 7, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "950", "900"], hand: ["100", "300", "500", "400", "600", "800", "800", "800"] },
          },
          after: {
            source: "edopro",
            note: "EDOPro gives the trigger player another chain-response window after the opponent responds to a cross-player post-decline SEGOC pass-handoff chain",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-decline-handoff-turn-response-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-turn-response-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-turn-response-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-turn-response-first-turn-quick", sourceUid: "p0-deck-200-1" },
              { player: 1, effectId: "fixture-cross-decline-handoff-turn-response-opponent-quick", sourceUid: "p1-deck-900-2" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-turn-response-second-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-decline-handoff-turn-response-second-turn-quick", 1, 8),
              chainPassGroup(0, 1, 8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-turn-response-first-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-turn-response-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 8, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-turn-response-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-decline-handoff-turn-response-first-turn-quick", 8),
              absentChainEffectGroup(1, "fixture-cross-decline-handoff-turn-response-opponent-quick", 8),
              absentTriggerActivationGroup(1, "fixture-cross-decline-handoff-turn-response-opponent-optional", "opponentOptional", 8, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "950", "900"], hand: ["100", "300", "500", "400", "600", "800", "800", "800"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-decline-handoff-turn-response-second-turn-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the trigger-player response window restorable before adding the second turn response to the post-decline handoff chain",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-decline-handoff-turn-response-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-turn-response-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-turn-response-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-turn-response-first-turn-quick", sourceUid: "p0-deck-200-1" },
              { player: 1, effectId: "fixture-cross-decline-handoff-turn-response-opponent-quick", sourceUid: "p1-deck-900-2" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-turn-response-second-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-decline-handoff-turn-response-second-turn-quick", 1, 8),
              chainPassGroup(0, 1, 8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-turn-response-first-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-turn-response-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 8, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-turn-response-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-decline-handoff-turn-response-first-turn-quick", 8),
              absentChainEffectGroup(1, "fixture-cross-decline-handoff-turn-response-opponent-quick", 8),
              absentTriggerActivationGroup(1, "fixture-cross-decline-handoff-turn-response-opponent-optional", "opponentOptional", 8, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "950", "900"], hand: ["100", "300", "500", "400", "600", "800", "800", "800"] },
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves the cross-player post-decline trigger chain after the trigger player responds and the opponent has no remaining response",
        phase: "main1",
        windowId: 9,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-cross-decline-handoff-turn-response-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 9, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 9, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 9,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-cross-decline-handoff-turn-response-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
          ], 1, 9),
          turnGroup(9),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-cross-decline-handoff-turn-response-first-turn-quick" },
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-cross-decline-handoff-turn-response-second-turn-quick" },
          { type: "activateEffect", player: 1, windowId: 9, windowKind: "open", effectId: "fixture-cross-decline-handoff-turn-response-opponent-quick" },
          { type: "activateTrigger", player: 1, windowId: 9, windowKind: "open", effectId: "fixture-cross-decline-handoff-turn-response-opponent-optional" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-cross-decline-handoff-turn-response-first-turn-quick", 9, "open"),
          absentWindowEffectGroup(0, "fixture-cross-decline-handoff-turn-response-second-turn-quick", 9, "open"),
          absentWindowEffectGroup(1, "fixture-cross-decline-handoff-turn-response-opponent-quick", 9, "open"),
          absentTriggerActivationGroup(1, "fixture-cross-decline-handoff-turn-response-opponent-optional", "opponentOptional", 9, "open"),
        ],
        locations: { graveyard: ["700", "200", "950", "900"], hand: ["100", "300", "500", "400", "600", "800", "800", "800"] },
        logIncludes: [
          "Cross decline handoff turn response starter resolved",
          "Cross decline handoff turn response second turn quick resolved",
          "Cross decline handoff turn response opponent quick resolved",
          "Cross decline handoff turn response first turn quick resolved",
          "Cross decline handoff turn response turn optional resolved",
          "Cross decline handoff turn response opponent mandatory resolved",
          "Cross decline handoff turn response turn mandatory resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
