import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity Main Phase 2 chain-response pass-handoff until-chain-end limit fixture", () => {
  it("keeps until-chain-end limits after the opponent chains from a Main Phase 2 chain-response handoff", () => {
    const cards: DuelCardData[] = [
      { code: "110", name: "Main2 Response Handoff Until Turn Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "130", name: "Main2 Response Handoff Until Turn Blocked Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "140", name: "Main2 Response Handoff Until Turn Filler", kind: "monster", attack: 1000, defense: 1000 },
      { code: "210", name: "Main2 Response Handoff Until Opponent First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "230", name: "Main2 Response Handoff Until Opponent Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "240", name: "Main2 Response Handoff Until Opponent Followup", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "main2 chain-response pass-handoff until-chain-end limit fixture",
      options: { seed: 293, startingHandSize: 3 },
      decks: {
        0: { main: ["110", "130", "140"] },
        1: { main: ["210", "230", "240"] },
      },
      setup: {
        effects: [
          {
            id: "main2-response-handoff-until-turn-open-quick",
            player: 0,
            code: "110",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            oncePerTurn: true,
            logMessage: "Main2 response handoff until turn open quick resolved",
          },
          {
            id: "main2-response-handoff-until-turn-blocked",
            player: 0,
            code: "130",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Main2 response handoff until turn blocked quick should not resolve",
          },
          {
            id: "main2-response-handoff-until-opponent-first",
            player: 1,
            code: "210",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Main2 response handoff until opponent first quick resolved",
          },
          {
            id: "main2-response-handoff-until-opponent-limiter",
            player: 1,
            code: "230",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 1 },
            logMessage: "Main2 response handoff until opponent limiter resolved",
          },
          {
            id: "main2-response-handoff-until-opponent-followup",
            player: 1,
            code: "240",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Main2 response handoff until opponent followup should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("changePhase", 0, { phase: "battle" })),
        makeScriptedStep(makeResponseSelector("changePhase", 0, { phase: "main2" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "main2-response-handoff-until-turn-open-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "main2-response-handoff-until-opponent-first" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "main2-response-handoff-until-opponent-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps Main Phase 2 chain-response handoff priority restorable before the opponent applies an until-chain-end limit",
            phase: "main2",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "main2-response-handoff-until-turn-open-quick", sourceUid: "p0-deck-110-0" },
              { player: 1, effectId: "main2-response-handoff-until-opponent-first", sourceUid: "p1-deck-210-0" },
            ],
            chainPasses: [0],
            chainLimits: [],
            legalActionCounts: { 0: 0, 1: 3 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "main2-response-handoff-until-opponent-limiter", count: 1 },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "main2-response-handoff-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 5,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "main2-response-handoff-until-opponent-limiter", count: 1 },
                  { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "main2-response-handoff-until-opponent-followup", count: 1 },
                ],
              },
              chainPassGroup(1, 1, 5),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "main2-response-handoff-until-turn-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "main2-response-handoff-until-turn-blocked", 5)],
          },
          after: {
            source: "edopro",
            note: "EDOPro keeps Main Phase 2 active and applies SetChainLimitTillChainEnd restrictions after the opponent chains from a chain-response pass handoff",
            phase: "main2",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "main2-response-handoff-until-turn-open-quick", sourceUid: "p0-deck-110-0" },
              { player: 1, effectId: "main2-response-handoff-until-opponent-first", sourceUid: "p1-deck-210-0" },
              { player: 1, effectId: "main2-response-handoff-until-opponent-limiter", sourceUid: "p1-deck-230-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "main2-response-handoff-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "main2-response-handoff-until-opponent-followup", 1, 6),
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "main2-response-handoff-until-turn-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "main2-response-handoff-until-turn-blocked", 6)],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the Main Phase 2 chain-response handoff SetChainLimitTillChainEnd window restorable before the allowed opponent passes",
            phase: "main2",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "main2-response-handoff-until-turn-open-quick", sourceUid: "p0-deck-110-0" },
              { player: 1, effectId: "main2-response-handoff-until-opponent-first", sourceUid: "p1-deck-210-0" },
              { player: 1, effectId: "main2-response-handoff-until-opponent-limiter", sourceUid: "p1-deck-230-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "main2-response-handoff-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "main2-response-handoff-until-opponent-followup", 1, 6),
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "main2-response-handoff-until-turn-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "main2-response-handoff-until-turn-blocked", 6)],
          },
          after: {
            source: "edopro",
            note: "EDOPro keeps Main Phase 2 active and clears chain-response handoff SetChainLimitTillChainEnd restrictions after the chain resolves",
            phase: "main2",
            windowId: 7,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 8, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "110", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "130", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "140", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "110", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "130", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "140", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 7, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 7, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              summonGroup([
                { type: "normalSummon", player: 0, code: "110", location: "hand" },
                { type: "normalSummon", player: 0, code: "130", location: "hand" },
                { type: "normalSummon", player: 0, code: "140", location: "hand" },
                { type: "setMonster", player: 0, code: "110", location: "hand" },
                { type: "setMonster", player: 0, code: "130", location: "hand" },
                { type: "setMonster", player: 0, code: "140", location: "hand" },
              ], 1, 7),
              turnGroup(7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "main2-response-handoff-until-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "main2-response-handoff-until-turn-blocked" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "main2-response-handoff-until-opponent-followup" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "main2-response-handoff-until-turn-open-quick", 7, "open"),
              absentWindowEffectGroup(0, "main2-response-handoff-until-turn-blocked", 7, "open"),
              absentWindowEffectGroup(1, "main2-response-handoff-until-opponent-followup", 7, "open"),
            ],
            logIncludes: [
              "Main2 response handoff until opponent limiter resolved",
              "Main2 response handoff until opponent first quick resolved",
              "Main2 response handoff until turn open quick resolved",
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro final state keeps Main Phase 2 active after until-chain-end limits clear from a chain-response handoff chain",
        phase: "main2",
        windowId: 7,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        legalActionCounts: { 0: 8, 1: 0 },
        legalActionGroupCounts: { 0: 2, 1: 0 },
        legalActions: [
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "110", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "130", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "140", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "110", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "130", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "140", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 7, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 7, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          summonGroup([
            { type: "normalSummon", player: 0, code: "110", location: "hand" },
            { type: "normalSummon", player: 0, code: "130", location: "hand" },
            { type: "normalSummon", player: 0, code: "140", location: "hand" },
            { type: "setMonster", player: 0, code: "110", location: "hand" },
            { type: "setMonster", player: 0, code: "130", location: "hand" },
            { type: "setMonster", player: 0, code: "140", location: "hand" },
          ], 1, 7),
          turnGroup(7),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "main2-response-handoff-until-turn-open-quick" },
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "main2-response-handoff-until-turn-blocked" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "main2-response-handoff-until-opponent-followup" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "main2-response-handoff-until-turn-open-quick", 7, "open"),
          absentWindowEffectGroup(0, "main2-response-handoff-until-turn-blocked", 7, "open"),
          absentWindowEffectGroup(1, "main2-response-handoff-until-opponent-followup", 7, "open"),
        ],
        logIncludes: [
          "Main2 response handoff until opponent limiter resolved",
          "Main2 response handoff until opponent first quick resolved",
          "Main2 response handoff until turn open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
