import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  triggerActivationGroup,
  triggerDeclineGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution cross-player SEGOC pass-handoff turn-pass resolution fixture", () => {
  it("resolves cross-player chain-created SEGOC trigger chains after both response players pass", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Cross Handoff Turn Pass Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Turn Cross Handoff Turn Pass Resolution Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Cross Handoff Turn Pass Resolution Turn Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Cross Handoff Turn Pass Resolution Opponent Mandatory", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Cross Handoff Turn Pass Resolution Turn Optional", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Cross Handoff Turn Pass Resolution Opponent Optional", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Cross Handoff Turn Pass Resolution Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Opponent Cross Handoff Turn Pass Resolution Quick", kind: "monster", attack: 1600, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution cross-player segoc pass handoff turn-pass resolution fixture",
      options: { seed: 406, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "500", "700"] },
        1: { main: ["400", "600", "900", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-cross-handoff-turn-pass-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 1, code: "900", from: "hand", to: "graveyard" },
            ],
            logMessage: "Cross handoff turn-pass resolution starter resolved",
          },
          {
            id: "fixture-cross-handoff-turn-pass-resolution-turn-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Cross handoff turn-pass resolution turn mandatory resolved",
          },
          {
            id: "fixture-cross-handoff-turn-pass-resolution-opponent-mandatory",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Cross handoff turn-pass resolution opponent mandatory resolved",
          },
          {
            id: "fixture-cross-handoff-turn-pass-resolution-turn-optional",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Cross handoff turn-pass resolution turn optional resolved",
          },
          {
            id: "fixture-cross-handoff-turn-pass-resolution-opponent-optional",
            player: 1,
            code: "600",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Cross handoff turn-pass resolution opponent optional resolved",
          },
          {
            id: "fixture-cross-handoff-turn-pass-resolution-turn-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross handoff turn-pass resolution turn quick should not resolve",
          },
          {
            id: "fixture-cross-handoff-turn-pass-resolution-opponent-quick",
            player: 1,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross handoff turn-pass resolution opponent quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-handoff-turn-pass-resolution-starter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps initial open priority restorable before cross-player SEGOC pass-handoff trigger queues are created",
            phase: "main1",
            windowId: 0,
            windowKind: "open",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 13, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-starter", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "200", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "700", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "200", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "700", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-starter", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "200", location: "hand" },
                { type: "normalSummon", player: 0, code: "300", location: "hand" },
                { type: "normalSummon", player: 0, code: "500", location: "hand" },
                { type: "normalSummon", player: 0, code: "700", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "200", location: "hand" },
                { type: "setMonster", player: 0, code: "300", location: "hand" },
                { type: "setMonster", player: 0, code: "500", location: "hand" },
                { type: "setMonster", player: 0, code: "700", location: "hand" },
              ], 1, 0),
              turnGroup(0),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-turn-optional" },
              { type: "activateTrigger", player: 1, windowId: 0, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-optional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-handoff-turn-pass-resolution-turn-quick", 0, "open"),
              absentWindowEffectGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-quick", 0, "open"),
              absentTriggerActivationGroup(0, "fixture-cross-handoff-turn-pass-resolution-turn-optional", "turnOptional", 0, "open"),
              absentTriggerActivationGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-optional", "opponentOptional", 0, "open"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro builds cross-player SEGOC buckets from trigger events created while an effect chain resolves before exposing chain responses",
            phase: "main1",
            windowId: 1,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [
              { player: 0, effectId: "fixture-cross-handoff-turn-pass-resolution-turn-mandatory", eventName: "sentToGraveyard", triggerBucket: "turnMandatory", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-mandatory", eventName: "sentToGraveyard", triggerBucket: "opponentMandatory", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-cross-handoff-turn-pass-resolution-turn-optional", eventName: "sentToGraveyard", triggerBucket: "turnOptional", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-optional", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnMandatory" },
              { player: 1, triggerBucket: "opponentMandatory" },
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-turn-mandatory", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-cross-handoff-turn-pass-resolution-turn-mandatory", "turnMandatory", 1, 1)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-mandatory", triggerBucket: "opponentMandatory" },
              { type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-turn-optional", triggerBucket: "turnOptional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-handoff-turn-pass-resolution-turn-quick", 1, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-quick", 1, "triggerBucket"),
              absentTriggerActivationGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-mandatory", "opponentMandatory", 1, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-cross-handoff-turn-pass-resolution-turn-optional", "turnOptional", 1, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            logIncludes: ["Cross handoff turn-pass resolution starter resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-handoff-turn-pass-resolution-turn-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-handoff-turn-pass-resolution-turn-optional" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-optional" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the opponent optional trigger bucket restorable before opening turn-player chain responses",
            windowId: 4,
            windowKind: "triggerBucket",
            waitingFor: 1,
            pendingTriggers: [{ player: 1, effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-optional", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" }],
            pendingTriggerBuckets: [{ player: 1, triggerBucket: "opponentOptional" }],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-turn-pass-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-cross-handoff-turn-pass-resolution-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-optional", triggerBucket: "opponentOptional", count: 1 },
              { type: "declineTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-optional", triggerBucket: "opponentOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-optional", "opponentOptional", 1, 4),
              triggerDeclineGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-optional", "opponentOptional", 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-turn-optional", triggerBucket: "turnOptional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-handoff-turn-pass-resolution-turn-quick", 4, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-quick", 4, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-cross-handoff-turn-pass-resolution-turn-optional", "turnOptional", 4, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
          },
          after: {
            source: "edopro",
            note: "EDOPro opens turn-player chain-response priority after cross-player chain-created SEGOC finishes with an opponent trigger",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-turn-pass-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-cross-handoff-turn-pass-resolution-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-pass-resolution-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-handoff-turn-pass-resolution-turn-quick", 1, 5),
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 5, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-quick", 5),
              absentTriggerActivationGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-optional", "opponentOptional", 5, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps cross-player chain-created SEGOC final pass windows restorable before resolving after both players pass",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-turn-pass-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-cross-handoff-turn-pass-resolution-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [0],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-quick", 1, 6),
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-pass-resolution-turn-quick" },
              { type: "activateTrigger", player: 1, windowId: 6, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-handoff-turn-pass-resolution-turn-quick", 6),
              absentTriggerActivationGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-optional", "opponentOptional", 6, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves cross-player chain-created SEGOC trigger chains after both response players pass the handoff windows",
        phase: "main1",
        windowId: 7,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 7, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 7, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 7,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
          ], 1, 7),
          turnGroup(7),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-turn-quick" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-quick" },
          { type: "activateTrigger", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-turn-optional" },
          { type: "activateTrigger", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-cross-handoff-turn-pass-resolution-opponent-optional" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-cross-handoff-turn-pass-resolution-turn-quick", 7, "open"),
          absentWindowEffectGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-quick", 7, "open"),
          absentTriggerActivationGroup(0, "fixture-cross-handoff-turn-pass-resolution-turn-optional", "turnOptional", 7, "open"),
          absentTriggerActivationGroup(1, "fixture-cross-handoff-turn-pass-resolution-opponent-optional", "opponentOptional", 7, "open"),
        ],
        locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
        logIncludes: [
          "Cross handoff turn-pass resolution starter resolved",
          "Cross handoff turn-pass resolution opponent optional resolved",
          "Cross handoff turn-pass resolution turn optional resolved",
          "Cross handoff turn-pass resolution opponent mandatory resolved",
          "Cross handoff turn-pass resolution turn mandatory resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
