import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity open fast-effect chain-response handoff opponent-response until-chain-end limit fixture", () => {
  it("keeps until-chain-end limits after the opponent responds to an open fast-effect chain-response handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Open Chain Handoff Opponent Response Until Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "200", name: "Open Chain Handoff Opponent Response Until Turn First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Open Chain Handoff Opponent Response Until Opponent First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Open Chain Handoff Opponent Response Until Opponent Second Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Open Chain Handoff Opponent Response Until Opponent Followup", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Open Chain Handoff Opponent Response Until Filler", kind: "monster", attack: 1000, defense: 1000 },
      { code: "800", name: "Open Chain Handoff Opponent Response Until Opponent Chain Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "900", name: "Open Chain Handoff Opponent Response Until Turn Blocked Quick", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "open fast chain-response handoff opponent-response until-chain-end limit fixture",
      options: { seed: 338, startingHandSize: 4 },
      decks: {
        0: { main: ["100", "200", "900", "700"] },
        1: { main: ["300", "500", "800", "600"] },
      },
      setup: {
        effects: [
          {
            id: "open-fast-chain-handoff-opponent-response-until-open-quick",
            player: 0,
            code: "100",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            oncePerTurn: true,
            logMessage: "Open fast chain handoff opponent-response until open quick resolved",
          },
          {
            id: "open-fast-chain-handoff-opponent-response-until-turn-first",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Open fast chain handoff opponent-response until turn first quick resolved",
          },
          {
            id: "open-fast-chain-handoff-opponent-response-until-turn-blocked",
            player: 0,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Open fast chain handoff opponent-response until turn blocked quick should not resolve",
          },
          {
            id: "open-fast-chain-handoff-opponent-response-until-opponent-first",
            player: 1,
            code: "300",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Open fast chain handoff opponent-response until opponent first quick resolved",
          },
          {
            id: "open-fast-chain-handoff-opponent-response-until-opponent-second",
            player: 1,
            code: "500",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Open fast chain handoff opponent-response until opponent second quick resolved",
          },
          {
            id: "open-fast-chain-handoff-opponent-response-until-opponent-chain-limiter",
            player: 1,
            code: "800",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 1 },
            logMessage: "Open fast chain handoff opponent-response until opponent chain limiter resolved",
          },
          {
            id: "open-fast-chain-handoff-opponent-response-until-opponent-followup",
            player: 1,
            code: "600",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Open fast chain handoff opponent-response until opponent followup should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "open-fast-chain-handoff-opponent-response-until-open-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "open-fast-chain-handoff-opponent-response-until-opponent-first" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "open-fast-chain-handoff-opponent-response-until-opponent-second" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "open-fast-chain-handoff-opponent-response-until-turn-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "open-fast-chain-handoff-opponent-response-until-opponent-chain-limiter" }), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro applies SetChainLimitTillChainEnd restrictions after the opponent responds to an open fast-effect chain-response handoff",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "open-fast-chain-handoff-opponent-response-until-open-quick", sourceUid: "p0-deck-100-0" },
              { player: 1, effectId: "open-fast-chain-handoff-opponent-response-until-opponent-first", sourceUid: "p1-deck-300-0" },
              { player: 1, effectId: "open-fast-chain-handoff-opponent-response-until-opponent-second", sourceUid: "p1-deck-500-1" },
              { player: 0, effectId: "open-fast-chain-handoff-opponent-response-until-turn-first", sourceUid: "p0-deck-200-1" },
              { player: 1, effectId: "open-fast-chain-handoff-opponent-response-until-opponent-chain-limiter", sourceUid: "p1-deck-800-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-opponent-response-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "open-fast-chain-handoff-opponent-response-until-opponent-followup", 1, 6),
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-opponent-response-until-turn-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "open-fast-chain-handoff-opponent-response-until-turn-blocked", 6)],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the open fast-effect opponent-response SetChainLimitTillChainEnd response window restorable before the allowed opponent passes",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "open-fast-chain-handoff-opponent-response-until-open-quick", sourceUid: "p0-deck-100-0" },
              { player: 1, effectId: "open-fast-chain-handoff-opponent-response-until-opponent-first", sourceUid: "p1-deck-300-0" },
              { player: 1, effectId: "open-fast-chain-handoff-opponent-response-until-opponent-second", sourceUid: "p1-deck-500-1" },
              { player: 0, effectId: "open-fast-chain-handoff-opponent-response-until-turn-first", sourceUid: "p0-deck-200-1" },
              { player: 1, effectId: "open-fast-chain-handoff-opponent-response-until-opponent-chain-limiter", sourceUid: "p1-deck-800-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-opponent-response-until-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "open-fast-chain-handoff-opponent-response-until-opponent-followup", 1, 6),
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-opponent-response-until-turn-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "open-fast-chain-handoff-opponent-response-until-turn-blocked", 6)],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears SetChainLimitTillChainEnd restrictions and returns to turn-player open priority after the allowed opponent passes the open fast-effect opponent-response handoff chain",
        phase: "main1",
        windowId: 7,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        legalActionCounts: { 0: 10, 1: 0 },
        legalActionGroupCounts: { 0: 2, 1: 0 },
        legalActions: [
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "200", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "200", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 7, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 7, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "200", location: "hand" },
            { type: "normalSummon", player: 0, code: "900", location: "hand" },
            { type: "normalSummon", player: 0, code: "700", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "200", location: "hand" },
            { type: "setMonster", player: 0, code: "900", location: "hand" },
            { type: "setMonster", player: 0, code: "700", location: "hand" },
          ], 1, 7),
          turnGroup(7),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "open-fast-chain-handoff-opponent-response-until-open-quick" },
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "open-fast-chain-handoff-opponent-response-until-turn-first" },
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "open-fast-chain-handoff-opponent-response-until-turn-blocked" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "open-fast-chain-handoff-opponent-response-until-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "open-fast-chain-handoff-opponent-response-until-opponent-second" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "open-fast-chain-handoff-opponent-response-until-opponent-chain-limiter" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "open-fast-chain-handoff-opponent-response-until-opponent-followup" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "open-fast-chain-handoff-opponent-response-until-open-quick", 7, "open"),
          absentWindowEffectGroup(0, "open-fast-chain-handoff-opponent-response-until-turn-first", 7, "open"),
          absentWindowEffectGroup(0, "open-fast-chain-handoff-opponent-response-until-turn-blocked", 7, "open"),
          absentWindowEffectGroup(1, "open-fast-chain-handoff-opponent-response-until-opponent-first", 7, "open"),
          absentWindowEffectGroup(1, "open-fast-chain-handoff-opponent-response-until-opponent-second", 7, "open"),
          absentWindowEffectGroup(1, "open-fast-chain-handoff-opponent-response-until-opponent-chain-limiter", 7, "open"),
          absentWindowEffectGroup(1, "open-fast-chain-handoff-opponent-response-until-opponent-followup", 7, "open"),
        ],
        logIncludes: [
          "Open fast chain handoff opponent-response until opponent chain limiter resolved",
          "Open fast chain handoff opponent-response until turn first quick resolved",
          "Open fast chain handoff opponent-response until opponent second quick resolved",
          "Open fast chain handoff opponent-response until opponent first quick resolved",
          "Open fast chain handoff opponent-response until open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
