import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chainEnded open fast-effect handoff opponent response turn-response until-chain-end limit fixture", () => {
  it("keeps until-chain-end limits after the turn player responds to a post-chainEnded opponent handoff response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Ended Handoff Turn Until Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Chain Ended Handoff Turn Until Solved Blocker", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Chain Ended Handoff Turn Until Cleanup", kind: "monster", attack: 1500, defense: 1600 },
      { code: "400", name: "Chain Ended Handoff Turn Until Open Quick", kind: "monster", attack: 1200, defense: 1200 },
      { code: "500", name: "Chain Ended Handoff Turn Until First Turn Chain", kind: "monster", attack: 1300, defense: 1300 },
      { code: "600", name: "Chain Ended Handoff Turn Until Opponent First Chain", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Chain Ended Handoff Turn Until Limiter", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Chain Ended Handoff Turn Until Followup", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Chain Ended Handoff Turn Until Opponent Blocked", kind: "monster", attack: 700, defense: 700 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "deferred chain ended open fast pass handoff opponent response turn response until-chain-end limit fixture",
      options: { seed: 625, startingHandSize: 7 },
      decks: {
        0: { main: ["100", "200", "300", "400", "500", "700", "800"] },
        1: { main: ["600", "900"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "500", from: "hand", to: "graveyard" },
          { player: 0, code: "700", from: "hand", to: "graveyard" },
          { player: 0, code: "800", from: "hand", to: "graveyard" },
          { player: 1, code: "600", from: "hand", to: "graveyard" },
          { player: 1, code: "900", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "fixture-chain-ended-handoff-turn-until-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            logMessage: "Chain ended handoff turn until starter resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-until-solved-blocker",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainSolved",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain ended handoff turn until solved blocker should not resolve",
          },
          {
            id: "fixture-chain-ended-handoff-turn-until-cleanup",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            moveCardsOnResolve: [
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "500", from: "graveyard", to: "hand" },
              { player: 0, code: "700", from: "graveyard", to: "hand" },
              { player: 0, code: "800", from: "graveyard", to: "hand" },
              { player: 1, code: "600", from: "graveyard", to: "hand" },
              { player: 1, code: "900", from: "graveyard", to: "hand" },
            ],
            logMessage: "Chain ended handoff turn until cleanup resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-until-open-fast",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended handoff turn until open fast resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-until-first-turn-chain",
            player: 0,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff turn until first turn chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-until-limiter",
            player: 0,
            code: "700",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 0 },
            logMessage: "Chain ended handoff turn until limiter resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-until-followup",
            player: 0,
            code: "800",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Chain ended handoff turn until followup should not resolve",
          },
          {
            id: "fixture-chain-ended-handoff-turn-until-opponent-first",
            player: 1,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff turn until opponent first chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-until-opponent-blocked",
            player: 1,
            code: "900",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Chain ended handoff turn until opponent blocked should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-until-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-chain-ended-handoff-turn-until-solved-blocker" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-ended-handoff-turn-until-cleanup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-until-open-fast" })),
        makeScriptedStep(makeResponseSelector("passChain", 1)),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-until-first-turn-chain" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-handoff-turn-until-opponent-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-until-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player priority before the until-chain-end limiter after a post-chainEnded opponent handoff response",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-until-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-until-first-turn-chain", sourceUid: "p0-deck-500-4" },
              { player: 1, effectId: "fixture-chain-ended-handoff-turn-until-opponent-first", sourceUid: "p1-deck-600-0" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "800", "600", "900"] },
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-limiter", count: 1 },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 7,
                windowKind: "chainResponse",
                actions: [
                  { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-limiter", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-followup", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-open-fast" },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-first-turn-chain" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-opponent-first" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-until-open-fast", 7, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-turn-until-first-turn-chain", 7),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-turn-until-opponent-first", 7),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-turn-until-opponent-blocked", 7),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro applies SetChainLimitTillChainEnd restrictions after the turn player responds to a post-chainEnded opponent handoff response",
            phase: "main1",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-until-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-until-first-turn-chain", sourceUid: "p0-deck-500-4" },
              { player: 1, effectId: "fixture-chain-ended-handoff-turn-until-opponent-first", sourceUid: "p1-deck-600-0" },
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-until-limiter", sourceUid: "p0-deck-700-5" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chainLimits: [{ untilChainEnd: true }],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "800", "600", "900"] },
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-ended-handoff-turn-until-followup", 1, 8),
              chainPassGroup(0, 1, 8),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-opponent-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "fixture-chain-ended-handoff-turn-until-opponent-blocked", 8)],
            logIncludes: ["Chain ended handoff turn until cleanup resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the post-chainEnded turn-response SetChainLimitTillChainEnd window restorable before the allowed turn player passes",
            phase: "main1",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-until-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-until-first-turn-chain", sourceUid: "p0-deck-500-4" },
              { player: 1, effectId: "fixture-chain-ended-handoff-turn-until-opponent-first", sourceUid: "p1-deck-600-0" },
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-until-limiter", sourceUid: "p0-deck-700-5" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chainLimits: [{ untilChainEnd: true }],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "800", "600", "900"] },
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-ended-handoff-turn-until-followup", 1, 8),
              chainPassGroup(0, 1, 8),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-until-opponent-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "fixture-chain-ended-handoff-turn-until-opponent-blocked", 8)],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears until-chain-end limits and resolves post-chainEnded handoff chains after the allowed turn player passes",
        phase: "main1",
        windowId: 9,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chainLimits: [],
        locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "800", "600", "900"] },
        legalActionCounts: { 0: 15, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-until-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 9, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 9, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 9,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-until-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "400", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "normalSummon", player: 0, code: "700", location: "hand" },
            { type: "normalSummon", player: 0, code: "800", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "400", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "700", location: "hand" },
            { type: "setMonster", player: 0, code: "800", location: "hand" },
          ], 1, 9),
          turnGroup(9),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-until-open-fast" },
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-until-first-turn-chain" },
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-until-limiter" },
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-until-followup" },
          { type: "activateEffect", player: 1, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-until-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-until-opponent-blocked" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-until-open-fast", 9, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-until-first-turn-chain", 9, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-until-limiter", 9, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-until-followup", 9, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-handoff-turn-until-opponent-first", 9, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-handoff-turn-until-opponent-blocked", 9, "open"),
        ],
        logIncludes: [
          "Chain ended handoff turn until limiter resolved",
          "Chain ended handoff turn until opponent first chain resolved",
          "Chain ended handoff turn until first turn chain resolved",
          "Chain ended handoff turn until open fast resolved",
          "Chain ended handoff turn until cleanup resolved",
          "Chain ended handoff turn until starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
