import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution opponent same-bucket mandatory pass-handoff opponent-response resolution fixture", () => {
  it("resolves after the turn player passes the window reopened by the opponent response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Opponent Mandatory Opponent Response Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Opponent Mandatory Opponent Response Resolution Turn Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Opponent Mandatory Opponent Response Resolution Turn Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Opponent Mandatory Opponent Response Resolution First Opponent", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Opponent Mandatory Opponent Response Resolution Second Opponent", kind: "monster", attack: 1200, defense: 1200 },
      { code: "700", name: "Opponent Mandatory Opponent Response Resolution Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Mandatory Opponent Response Resolution Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Opponent Mandatory Opponent Response Resolution Opponent Quick", kind: "monster", attack: 1600, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution opponent same-bucket mandatory pass-handoff opponent-response resolution fixture",
      options: { seed: 367, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "700", "800"] },
        1: { main: ["400", "500", "900", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-opponent-mandatory-opponent-response-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 1, code: "900", from: "hand", to: "graveyard" },
            ],
            logMessage: "Opponent mandatory opponent-response resolution starter resolved",
          },
          {
            id: "fixture-opponent-mandatory-opponent-response-resolution-turn-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Opponent mandatory opponent-response resolution turn mandatory resolved",
          },
          {
            id: "fixture-opponent-mandatory-opponent-response-resolution-first-opponent",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Opponent mandatory opponent-response resolution first opponent resolved",
          },
          {
            id: "fixture-opponent-mandatory-opponent-response-resolution-second-opponent",
            player: 1,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Opponent mandatory opponent-response resolution second opponent resolved",
          },
          {
            id: "fixture-opponent-mandatory-opponent-response-resolution-turn-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Opponent mandatory opponent-response resolution turn quick should not resolve",
          },
          {
            id: "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick",
            player: 1,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Opponent mandatory opponent-response resolution opponent quick resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-opponent-mandatory-opponent-response-resolution-starter" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-opponent-mandatory-opponent-response-resolution-turn-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-opponent-mandatory-opponent-response-resolution-second-opponent" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-opponent-mandatory-opponent-response-resolution-first-opponent" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps opponent same-bucket mandatory handoff response choices restorable before the opponent chains",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-opponent-mandatory-opponent-response-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-opponent-mandatory-opponent-response-resolution-second-opponent", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-opponent-mandatory-opponent-response-resolution-first-opponent", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
            ],
            chainPasses: [0],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick", 1, 5),
              chainPassGroup(1, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-opponent-mandatory-opponent-response-resolution-turn-quick" },
              { type: "activateTrigger", player: 1, windowId: 5, windowKind: "triggerBucket", effectId: "fixture-opponent-mandatory-opponent-response-resolution-first-opponent", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-opponent-mandatory-opponent-response-resolution-turn-quick", 5),
              absentTriggerActivationGroup(1, "fixture-opponent-mandatory-opponent-response-resolution-first-opponent", "opponentMandatory", 5, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "800", "400", "500", "800", "800"] },
            logIncludes: ["Opponent mandatory opponent-response resolution starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro reopens turn-player responses after an opponent response to restored opponent same-bucket mandatory trigger chains",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-opponent-mandatory-opponent-response-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-opponent-mandatory-opponent-response-resolution-second-opponent", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-opponent-mandatory-opponent-response-resolution-first-opponent", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick", sourceUid: "p1-deck-900-2" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-opponent-mandatory-opponent-response-resolution-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-opponent-mandatory-opponent-response-resolution-turn-quick", 1, 6),
              chainPassGroup(0, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 6, windowKind: "triggerBucket", effectId: "fixture-opponent-mandatory-opponent-response-resolution-first-opponent", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick", 6),
              absentTriggerActivationGroup(1, "fixture-opponent-mandatory-opponent-response-resolution-first-opponent", "opponentMandatory", 6, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "800", "400", "500", "800", "800"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the restored opponent mandatory opponent-response resolution pass window restorable before resolving the chain",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-opponent-mandatory-opponent-response-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-opponent-mandatory-opponent-response-resolution-second-opponent", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-opponent-mandatory-opponent-response-resolution-first-opponent", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick", sourceUid: "p1-deck-900-2" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-opponent-mandatory-opponent-response-resolution-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-opponent-mandatory-opponent-response-resolution-turn-quick", 1, 6),
              chainPassGroup(0, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 6, windowKind: "triggerBucket", effectId: "fixture-opponent-mandatory-opponent-response-resolution-first-opponent", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick", 6),
              absentTriggerActivationGroup(1, "fixture-opponent-mandatory-opponent-response-resolution-first-opponent", "opponentMandatory", 6, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "800", "400", "500", "800", "800"] },
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves restored opponent mandatory handoff chains after the turn player passes the window reopened by the opponent response",
        phase: "main1",
        windowId: 7,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-opponent-mandatory-opponent-response-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 7, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 7, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 7,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-opponent-mandatory-opponent-response-resolution-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "800", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "800", location: "hand" },
          ], 1, 7),
          turnGroup(7),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-opponent-mandatory-opponent-response-resolution-turn-quick" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick" },
          { type: "activateTrigger", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-opponent-mandatory-opponent-response-resolution-turn-mandatory" },
          { type: "activateTrigger", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-opponent-mandatory-opponent-response-resolution-first-opponent" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-opponent-mandatory-opponent-response-resolution-turn-quick", 7, "open"),
          absentWindowEffectGroup(1, "fixture-opponent-mandatory-opponent-response-resolution-opponent-quick", 7, "open"),
          absentTriggerActivationGroup(0, "fixture-opponent-mandatory-opponent-response-resolution-turn-mandatory", "turnMandatory", 7, "open"),
          absentTriggerActivationGroup(1, "fixture-opponent-mandatory-opponent-response-resolution-first-opponent", "opponentMandatory", 7, "open"),
        ],
        locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "800", "400", "500", "800", "800"] },
        logIncludes: [
          "Opponent mandatory opponent-response resolution opponent quick resolved",
          "Opponent mandatory opponent-response resolution first opponent resolved",
          "Opponent mandatory opponent-response resolution second opponent resolved",
          "Opponent mandatory opponent-response resolution turn mandatory resolved",
          "Opponent mandatory opponent-response resolution starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
