import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  triggerActivationGroup,
  triggerDeclineGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution cross-player SEGOC decline pass handoff chain fixture", () => {
  it("opens opponent responses after the trigger player chains from a cross-player post-decline handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Cross Decline Handoff Chain Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Turn Cross Decline Handoff Chain Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Cross Decline Handoff Chain Turn Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Cross Decline Handoff Chain Opponent Mandatory", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Cross Decline Handoff Chain Turn Optional", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Cross Decline Handoff Chain Opponent Optional", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Cross Decline Handoff Chain Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Opponent Cross Decline Handoff Chain Quick", kind: "monster", attack: 1600, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution cross-player segoc decline pass handoff chain fixture",
      options: { seed: 299, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "500", "700"] },
        1: { main: ["400", "600", "900", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-cross-decline-handoff-chain-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 1, code: "900", from: "hand", to: "graveyard" },
            ],
            logMessage: "Cross decline handoff chain starter resolved",
          },
          {
            id: "fixture-cross-decline-handoff-chain-turn-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            optional: false,
            range: ["hand"],
            logMessage: "Cross decline handoff chain turn mandatory should not resolve yet",
          },
          {
            id: "fixture-cross-decline-handoff-chain-opponent-mandatory",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            optional: false,
            range: ["hand"],
            logMessage: "Cross decline handoff chain opponent mandatory should not resolve yet",
          },
          {
            id: "fixture-cross-decline-handoff-chain-turn-optional",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            range: ["hand"],
            logMessage: "Cross decline handoff chain turn optional should not resolve yet",
          },
          {
            id: "fixture-cross-decline-handoff-chain-opponent-optional",
            player: 1,
            code: "600",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            range: ["hand"],
            logMessage: "Cross decline handoff chain opponent optional should not resolve",
          },
          {
            id: "fixture-cross-decline-handoff-chain-turn-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross decline handoff chain turn quick should not resolve yet",
          },
          {
            id: "fixture-cross-decline-handoff-chain-opponent-quick",
            player: 1,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross decline handoff chain opponent quick should not resolve yet",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-decline-handoff-chain-starter" }), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro builds cross-player SEGOC buckets from trigger events created while the starter chain resolves before exposing fast responses",
            phase: "main1",
            windowId: 1,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-mandatory", eventName: "sentToGraveyard", triggerBucket: "turnMandatory", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-mandatory", eventName: "sentToGraveyard", triggerBucket: "opponentMandatory", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-optional", eventName: "sentToGraveyard", triggerBucket: "turnOptional", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-optional", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-4" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnMandatory" },
              { player: 1, triggerBucket: "opponentMandatory" },
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-turn-mandatory", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-cross-decline-handoff-chain-turn-mandatory", "turnMandatory", 1, 1)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-mandatory", triggerBucket: "opponentMandatory" },
              { type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-turn-optional", triggerBucket: "turnOptional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-decline-handoff-chain-turn-quick", 1, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-decline-handoff-chain-opponent-quick", 1, "triggerBucket"),
              absentTriggerActivationGroup(1, "fixture-cross-decline-handoff-chain-opponent-mandatory", "opponentMandatory", 1, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-cross-decline-handoff-chain-turn-optional", "turnOptional", 1, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            logIncludes: ["Cross decline handoff chain starter resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-decline-handoff-chain-turn-mandatory" }), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro advances restored cross-player SEGOC from turn mandatory to opponent mandatory before any fast response",
            phase: "main1",
            windowId: 2,
            windowKind: "triggerBucket",
            waitingFor: 1,
            chain: [{ player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" }],
            chainPasses: [],
            pendingTriggers: [
              { player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-mandatory", eventName: "sentToGraveyard", triggerBucket: "opponentMandatory", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-optional", eventName: "sentToGraveyard", triggerBucket: "turnOptional", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-optional", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-4" },
            ],
            pendingTriggerBuckets: [
              { player: 1, triggerBucket: "opponentMandatory" },
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 0, 1: 1 },
            legalActionGroupCounts: { 0: 0, 1: 1 },
            legalActions: [{ type: "activateTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-mandatory", triggerBucket: "opponentMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(1, "fixture-cross-decline-handoff-chain-opponent-mandatory", "opponentMandatory", 1, 2)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-turn-optional", triggerBucket: "turnOptional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-decline-handoff-chain-turn-quick", 2, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-decline-handoff-chain-opponent-quick", 2, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-cross-decline-handoff-chain-turn-optional", "turnOptional", 2, "triggerBucket"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-decline-handoff-chain-opponent-mandatory" }), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro advances restored cross-player SEGOC from opponent mandatory to turn optional before chain responses",
            phase: "main1",
            windowId: 3,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
            ],
            chainPasses: [],
            pendingTriggers: [
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-optional", eventName: "sentToGraveyard", triggerBucket: "turnOptional", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-optional", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-4" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateTrigger", player: 0, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-turn-optional", triggerBucket: "turnOptional", count: 1 },
              { type: "declineTrigger", player: 0, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-turn-optional", triggerBucket: "turnOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(0, "fixture-cross-decline-handoff-chain-turn-optional", "turnOptional", 1, 3),
              triggerDeclineGroup(0, "fixture-cross-decline-handoff-chain-turn-optional", "turnOptional", 1, 3),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-decline-handoff-chain-turn-quick", 3, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-decline-handoff-chain-opponent-quick", 3, "triggerBucket"),
              absentTriggerActivationGroup(1, "fixture-cross-decline-handoff-chain-opponent-optional", "opponentOptional", 3, "triggerBucket"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-decline-handoff-chain-turn-optional" }), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro keeps restored cross-player SEGOC in the opponent optional bucket before chain responses",
            phase: "main1",
            windowId: 4,
            windowKind: "triggerBucket",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
            ],
            chainPasses: [],
            pendingTriggers: [{ player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-optional", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-4" }],
            pendingTriggerBuckets: [{ player: 1, triggerBucket: "opponentOptional" }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-optional", triggerBucket: "opponentOptional", count: 1 },
              { type: "declineTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-optional", triggerBucket: "opponentOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(1, "fixture-cross-decline-handoff-chain-opponent-optional", "opponentOptional", 1, 4),
              triggerDeclineGroup(1, "fixture-cross-decline-handoff-chain-opponent-optional", "opponentOptional", 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-quick" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-decline-handoff-chain-turn-quick", 4, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-decline-handoff-chain-opponent-quick", 4, "triggerBucket"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("declineTrigger", 1, { effectId: "fixture-cross-decline-handoff-chain-opponent-optional" }), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro opens opponent chain-response priority after the last cross-player SEGOC optional trigger is declined",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-chain-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-decline-handoff-chain-opponent-quick", 1, 5),
              chainPassGroup(1, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-chain-turn-quick" },
              { type: "activateTrigger", player: 1, windowId: 5, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-decline-handoff-chain-turn-quick", 5),
              absentTriggerActivationGroup(1, "fixture-cross-decline-handoff-chain-opponent-optional", "opponentOptional", 5, "triggerBucket"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro restores the post-decline SEGOC chain-response pass handoff to the trigger player before they chain",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
            ],
            chainPasses: [1],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-chain-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-decline-handoff-chain-turn-quick", 1, 6),
              chainPassGroup(0, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-chain-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 6, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-cross-decline-handoff-chain-opponent-quick", 6),
              absentTriggerActivationGroup(1, "fixture-cross-decline-handoff-chain-opponent-optional", "opponentOptional", 6, "triggerBucket"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-decline-handoff-chain-turn-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro allows the trigger player to chain from the restored post-decline SEGOC pass handoff window",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
            ],
            chainPasses: [1],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-chain-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-decline-handoff-chain-turn-quick", 1, 6),
              chainPassGroup(0, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-chain-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 6, windowKind: "triggerBucket", effectId: "fixture-cross-decline-handoff-chain-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-cross-decline-handoff-chain-opponent-quick", 6),
              absentTriggerActivationGroup(1, "fixture-cross-decline-handoff-chain-opponent-optional", "opponentOptional", 6, "triggerBucket"),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro opens opponent response priority after the trigger player chains from a cross-player post-decline SEGOC pass handoff",
        phase: "main1",
        windowId: 7,
        windowKind: "chainResponse",
        waitingFor: 1,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [
          { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
          { player: 1, effectId: "fixture-cross-decline-handoff-chain-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
          { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
          { player: 0, effectId: "fixture-cross-decline-handoff-chain-turn-quick", sourceUid: "p0-deck-200-1" },
        ],
        chainPasses: [],
        legalActionCounts: { 0: 0, 1: 2 },
        legalActionGroupCounts: { 0: 0, 1: 2 },
        legalActions: [
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-chain-opponent-quick", count: 1 },
          { type: "passChain", player: 1, windowId: 7, windowKind: "chainResponse", count: 1 },
        ],
        legalActionGroups: [
          chainEffectGroup(1, "fixture-cross-decline-handoff-chain-opponent-quick", 1, 7),
          chainPassGroup(1, 1, 7),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-decline-handoff-chain-turn-quick" },
          {
            type: "activateTrigger",
            player: 1,
            windowId: 7,
            windowKind: "triggerBucket",
            effectId: "fixture-cross-decline-handoff-chain-opponent-optional",
            triggerBucket: "opponentOptional",
          },
        ],
        absentLegalActionGroups: [
          absentChainEffectGroup(0, "fixture-cross-decline-handoff-chain-turn-quick", 7),
          absentTriggerActivationGroup(1, "fixture-cross-decline-handoff-chain-opponent-optional", "opponentOptional", 7, "triggerBucket"),
        ],
        locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
        logIncludes: ["Cross decline handoff chain starter resolved"],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
