import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentTriggerActivationGroup, chainEffectGroup, chainPassGroup, summonGroup, triggerActivationGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity cross-player chain negated/disabled trigger bucket fixture", () => {
  it("queues deferred chainEnded triggers only after cross-player chainNegated and chainDisabled trigger chains resolve", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Cross Negated Trigger Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Cross Trigger Negator", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Turn Chain Negated Watcher", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Opponent Chain Disabled Watcher", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Deferred Chain Ended Watcher", kind: "monster", attack: 1200, defense: 1200 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "cross-player chain negated disabled trigger bucket before chain ended fixture",
      options: { seed: 615, startingHandSize: 3 },
      decks: {
        0: { main: ["100", "300", "500"] },
        1: { main: ["200", "400"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-cross-negated-trigger-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            logMessage: "Cross negated trigger starter should not resolve",
          },
          {
            id: "fixture-cross-trigger-negator",
            player: 1,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            negateChainEffectOnResolve: "fixture-cross-negated-trigger-starter",
          },
          {
            id: "fixture-cross-chain-negated-turn",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainNegated",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            logMessage: "Cross chain negated turn resolved",
          },
          {
            id: "fixture-cross-chain-disabled-opponent",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainDisabled",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            logMessage: "Cross chain disabled opponent resolved",
          },
          {
            id: "fixture-cross-chain-ended-after-negated-disabled",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            logMessage: "Cross chain ended after negated disabled resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-negated-trigger-starter" }), {
          after: {
            source: "edopro",
            note: "EDOPro opens a chain-response window before the opponent negates the turn player's chain link",
            phase: "main1",
            windowId: 1,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [{ player: 0, effectId: "fixture-cross-negated-trigger-starter" }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "chainResponse", effectId: "fixture-cross-trigger-negator", count: 1 },
              { type: "passChain", player: 1, windowId: 1, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(1, "fixture-cross-trigger-negator", 1, 1), chainPassGroup(1, 1, 1)],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-cross-trigger-negator" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the opponent chain-response negation prompt restorable before mandatory chainNegated and chainDisabled buckets are collected",
            phase: "main1",
            windowId: 1,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [{ player: 0, effectId: "fixture-cross-negated-trigger-starter" }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "chainResponse", effectId: "fixture-cross-trigger-negator", count: 1 },
              { type: "passChain", player: 1, windowId: 1, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(1, "fixture-cross-trigger-negator", 1, 1), chainPassGroup(1, 1, 1)],
          },
          after: {
            source: "edopro",
            note: "EDOPro opens turn-player chainNegated buckets before opponent chainDisabled buckets and defers chainEnded triggers",
            phase: "main1",
            windowId: 2,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [
              { player: 0, effectId: "fixture-cross-chain-negated-turn", eventName: "chainNegated", triggerBucket: "turnMandatory" },
              { player: 1, effectId: "fixture-cross-chain-disabled-opponent", eventName: "chainDisabled", triggerBucket: "opponentMandatory" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnMandatory" },
              { player: 1, triggerBucket: "opponentMandatory" },
            ],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-chain-negated-turn", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-cross-chain-negated-turn", "turnMandatory", 1, 2)],
            absentLegalActions: [
              { type: "activateTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-chain-disabled-opponent", triggerBucket: "opponentMandatory" },
              { type: "activateTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-chain-ended-after-negated-disabled", triggerBucket: "turnMandatory" },
              { type: "declineTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-chain-negated-turn", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(1, "fixture-cross-chain-disabled-opponent", "opponentMandatory", 2, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-cross-chain-ended-after-negated-disabled", "turnMandatory", 2, "triggerBucket"),
              {
                player: 0,
                label: "Trigger Declines",
                windowId: 2,
                windowKind: "triggerBucket",
                triggerBucket: { player: 0, triggerBucket: "turnMandatory" },
                actions: [{ type: "declineTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-chain-negated-turn" }],
              },
            ],
            logIncludes: ["Negated chain true", "fixture-cross-negated-trigger-starter"],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-chain-negated-turn" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the turn-player mandatory chainNegated bucket restorable before its trigger chain resolves",
            phase: "main1",
            windowId: 2,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [
              { player: 0, effectId: "fixture-cross-chain-negated-turn", eventName: "chainNegated", triggerBucket: "turnMandatory" },
              { player: 1, effectId: "fixture-cross-chain-disabled-opponent", eventName: "chainDisabled", triggerBucket: "opponentMandatory" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnMandatory" },
              { player: 1, triggerBucket: "opponentMandatory" },
            ],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-chain-negated-turn", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-cross-chain-negated-turn", "turnMandatory", 1, 2)],
            absentLegalActions: [
              { type: "activateTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-chain-disabled-opponent", triggerBucket: "opponentMandatory" },
              { type: "activateTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-chain-ended-after-negated-disabled", triggerBucket: "turnMandatory" },
              { type: "declineTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-chain-negated-turn", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(1, "fixture-cross-chain-disabled-opponent", "opponentMandatory", 2, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-cross-chain-ended-after-negated-disabled", "turnMandatory", 2, "triggerBucket"),
              {
                player: 0,
                label: "Trigger Declines",
                windowId: 2,
                windowKind: "triggerBucket",
                triggerBucket: { player: 0, triggerBucket: "turnMandatory" },
                actions: [{ type: "declineTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-chain-negated-turn" }],
              },
            ],
            logIncludes: ["Negated chain true", "fixture-cross-negated-trigger-starter"],
          },
          after: {
            source: "edopro",
            note: "EDOPro resolves the selected chainNegated trigger chain before advancing to the separate opponent chainDisabled bucket",
            phase: "main1",
            windowId: 3,
            windowKind: "triggerBucket",
            waitingFor: 1,
            chain: [],
            chainPasses: [],
            pendingTriggers: [{ player: 1, effectId: "fixture-cross-chain-disabled-opponent", eventName: "chainDisabled", triggerBucket: "opponentMandatory" }],
            pendingTriggerBuckets: [{ player: 1, triggerBucket: "opponentMandatory" }],
            legalActionCounts: { 0: 0, 1: 1 },
            legalActionGroupCounts: { 0: 0, 1: 1 },
            legalActions: [{ type: "activateTrigger", player: 1, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-chain-disabled-opponent", triggerBucket: "opponentMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(1, "fixture-cross-chain-disabled-opponent", "opponentMandatory", 1, 3)],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-chain-negated-turn", triggerBucket: "turnMandatory" },
              { type: "activateTrigger", player: 0, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-chain-ended-after-negated-disabled", triggerBucket: "turnMandatory" },
              { type: "declineTrigger", player: 1, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-chain-disabled-opponent", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-cross-chain-negated-turn", "turnMandatory", 3, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-cross-chain-ended-after-negated-disabled", "turnMandatory", 3, "triggerBucket"),
              {
                player: 1,
                label: "Trigger Declines",
                windowId: 3,
                windowKind: "triggerBucket",
                triggerBucket: { player: 1, triggerBucket: "opponentMandatory" },
                actions: [{ type: "declineTrigger", player: 1, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-chain-disabled-opponent" }],
              },
            ],
            logIncludes: ["Cross chain negated turn resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-chain-disabled-opponent" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the opponent mandatory chainDisabled bucket restorable before deferred chainEnded buckets are collected",
            phase: "main1",
            windowId: 3,
            windowKind: "triggerBucket",
            waitingFor: 1,
            chain: [],
            chainPasses: [],
            pendingTriggers: [{ player: 1, effectId: "fixture-cross-chain-disabled-opponent", eventName: "chainDisabled", triggerBucket: "opponentMandatory" }],
            pendingTriggerBuckets: [{ player: 1, triggerBucket: "opponentMandatory" }],
            legalActionCounts: { 0: 0, 1: 1 },
            legalActionGroupCounts: { 0: 0, 1: 1 },
            legalActions: [{ type: "activateTrigger", player: 1, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-chain-disabled-opponent", triggerBucket: "opponentMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(1, "fixture-cross-chain-disabled-opponent", "opponentMandatory", 1, 3)],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-chain-negated-turn", triggerBucket: "turnMandatory" },
              { type: "activateTrigger", player: 0, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-chain-ended-after-negated-disabled", triggerBucket: "turnMandatory" },
              { type: "declineTrigger", player: 1, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-chain-disabled-opponent", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-cross-chain-negated-turn", "turnMandatory", 3, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-cross-chain-ended-after-negated-disabled", "turnMandatory", 3, "triggerBucket"),
              {
                player: 1,
                label: "Trigger Declines",
                windowId: 3,
                windowKind: "triggerBucket",
                triggerBucket: { player: 1, triggerBucket: "opponentMandatory" },
                actions: [{ type: "declineTrigger", player: 1, windowId: 3, windowKind: "triggerBucket", effectId: "fixture-cross-chain-disabled-opponent" }],
              },
            ],
            logIncludes: ["Cross chain negated turn resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro collects deferred chainEnded buckets only after the chainDisabled trigger chain resolves",
            phase: "main1",
            windowId: 4,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [{ player: 0, effectId: "fixture-cross-chain-ended-after-negated-disabled", eventName: "chainEnded", triggerBucket: "turnMandatory" }],
            pendingTriggerBuckets: [{ player: 0, triggerBucket: "turnMandatory" }],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-chain-ended-after-negated-disabled", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-cross-chain-ended-after-negated-disabled", "turnMandatory", 1, 4)],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-chain-negated-turn", triggerBucket: "turnMandatory" },
              { type: "activateTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-chain-disabled-opponent", triggerBucket: "opponentMandatory" },
              { type: "declineTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-chain-ended-after-negated-disabled", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-cross-chain-negated-turn", "turnMandatory", 4, "triggerBucket"),
              absentTriggerActivationGroup(1, "fixture-cross-chain-disabled-opponent", "opponentMandatory", 4, "triggerBucket"),
              {
                player: 0,
                label: "Trigger Declines",
                windowId: 4,
                windowKind: "triggerBucket",
                triggerBucket: { player: 0, triggerBucket: "turnMandatory" },
                actions: [{ type: "declineTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-chain-ended-after-negated-disabled" }],
              },
            ],
            logIncludes: ["Cross chain disabled opponent resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-chain-ended-after-negated-disabled" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the deferred mandatory chainEnded bucket restorable after mandatory negated and disabled trigger chains resolve",
            phase: "main1",
            windowId: 4,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [{ player: 0, effectId: "fixture-cross-chain-ended-after-negated-disabled", eventName: "chainEnded", triggerBucket: "turnMandatory" }],
            pendingTriggerBuckets: [{ player: 0, triggerBucket: "turnMandatory" }],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-chain-ended-after-negated-disabled", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-cross-chain-ended-after-negated-disabled", "turnMandatory", 1, 4)],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-chain-negated-turn", triggerBucket: "turnMandatory" },
              { type: "activateTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-chain-disabled-opponent", triggerBucket: "opponentMandatory" },
              { type: "declineTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-chain-ended-after-negated-disabled", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-cross-chain-negated-turn", "turnMandatory", 4, "triggerBucket"),
              absentTriggerActivationGroup(1, "fixture-cross-chain-disabled-opponent", "opponentMandatory", 4, "triggerBucket"),
              {
                player: 0,
                label: "Trigger Declines",
                windowId: 4,
                windowKind: "triggerBucket",
                triggerBucket: { player: 0, triggerBucket: "turnMandatory" },
                actions: [{ type: "declineTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-cross-chain-ended-after-negated-disabled" }],
              },
            ],
            logIncludes: ["Cross chain disabled opponent resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns to open priority after the deferred chainEnded trigger resolves",
            phase: "main1",
            windowId: 5,
            windowKind: "open",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 9, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-cross-negated-trigger-starter", count: 1 },
              { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 5, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 5, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 5,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-cross-negated-trigger-starter", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "300", location: "hand" },
                { type: "normalSummon", player: 0, code: "500", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "300", location: "hand" },
                { type: "setMonster", player: 0, code: "500", location: "hand" },
              ], 1, 5),
              turnGroup(5),
            ],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-cross-chain-negated-turn" },
              { type: "activateTrigger", player: 1, windowId: 5, windowKind: "open", effectId: "fixture-cross-chain-disabled-opponent" },
              { type: "activateTrigger", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-cross-chain-ended-after-negated-disabled" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-cross-chain-negated-turn", "turnMandatory", 5, "open"),
              absentTriggerActivationGroup(1, "fixture-cross-chain-disabled-opponent", "opponentMandatory", 5, "open"),
              absentTriggerActivationGroup(0, "fixture-cross-chain-ended-after-negated-disabled", "turnMandatory", 5, "open"),
            ],
            logIncludes: ["Cross chain ended after negated disabled resolved"],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro final state resolves cross-player chainNegated and chainDisabled trigger chains before deferred chainEnded buckets",
        phase: "main1",
        windowId: 5,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-cross-negated-trigger-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 5, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 5, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 5, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 5, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 5,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-cross-negated-trigger-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
          ], 1, 5),
          turnGroup(5),
        ],
        absentLegalActions: [
          { type: "activateTrigger", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-cross-chain-negated-turn" },
          { type: "activateTrigger", player: 1, windowId: 5, windowKind: "open", effectId: "fixture-cross-chain-disabled-opponent" },
          { type: "activateTrigger", player: 0, windowId: 5, windowKind: "open", effectId: "fixture-cross-chain-ended-after-negated-disabled" },
        ],
        absentLegalActionGroups: [
          absentTriggerActivationGroup(0, "fixture-cross-chain-negated-turn", "turnMandatory", 5, "open"),
          absentTriggerActivationGroup(1, "fixture-cross-chain-disabled-opponent", "opponentMandatory", 5, "open"),
          absentTriggerActivationGroup(0, "fixture-cross-chain-ended-after-negated-disabled", "turnMandatory", 5, "open"),
        ],
        logIncludes: [
          "Negated chain true",
          "fixture-cross-negated-trigger-starter",
          "Cross chain negated turn resolved",
          "Cross chain disabled opponent resolved",
          "Cross chain ended after negated disabled resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
