import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  openEffectGroup,
  summonGroup,
  triggerActivationGroup,
  triggerDeclineGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution SEGOC turn optional decline pass resolution fixture", () => {
  it("resolves mandatory chain-created SEGOC triggers after both optional buckets are declined and both players pass", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Double Optional Pass Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Turn Double Optional Pass Resolution Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Double Optional Pass Resolution Turn Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Double Optional Pass Resolution Opponent Mandatory", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Double Optional Pass Resolution Turn Optional", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Double Optional Pass Resolution Opponent Optional", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Double Optional Pass Resolution Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Opponent Double Optional Pass Resolution Quick", kind: "monster", attack: 1600, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution segoc turn optional decline pass resolution fixture",
      options: { seed: 307, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "500", "700"] },
        1: { main: ["400", "600", "900", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-double-optional-pass-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 1, code: "900", from: "hand", to: "graveyard" },
            ],
            logMessage: "Double optional pass resolution starter resolved",
          },
          {
            id: "fixture-double-optional-pass-resolution-turn-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Double optional pass resolution turn mandatory resolved",
          },
          {
            id: "fixture-double-optional-pass-resolution-opponent-mandatory",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Double optional pass resolution opponent mandatory resolved",
          },
          {
            id: "fixture-double-optional-pass-resolution-turn-optional",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Double optional pass resolution turn optional should not resolve",
          },
          {
            id: "fixture-double-optional-pass-resolution-opponent-optional",
            player: 1,
            code: "600",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Double optional pass resolution opponent optional should not resolve",
          },
          {
            id: "fixture-double-optional-pass-resolution-turn-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Double optional pass resolution turn quick should not resolve",
          },
          {
            id: "fixture-double-optional-pass-resolution-opponent-quick",
            player: 1,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Double optional pass resolution opponent quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-double-optional-pass-resolution-starter" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-double-optional-pass-resolution-turn-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-double-optional-pass-resolution-opponent-mandatory" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-double-optional-pass-resolution-turn-optional" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 1, { effectId: "fixture-double-optional-pass-resolution-opponent-optional" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps opponent optional decline priority restorable after mandatory SEGOC chain links are selected",
            phase: "main1",
            windowId: 4,
            windowKind: "triggerBucket",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-double-optional-pass-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-double-optional-pass-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [],
            pendingTriggers: [{ player: 1, effectId: "fixture-double-optional-pass-resolution-opponent-optional", eventName: "sentToGraveyard", triggerBucket: "opponentOptional", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" }],
            pendingTriggerBuckets: [{ player: 1, triggerBucket: "opponentOptional" }],
            triggerOrderPrompt: null,
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-double-optional-pass-resolution-opponent-optional", triggerBucket: "opponentOptional", count: 1 },
              { type: "declineTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-double-optional-pass-resolution-opponent-optional", triggerBucket: "opponentOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(1, "fixture-double-optional-pass-resolution-opponent-optional", "opponentOptional", 1, 4),
              triggerDeclineGroup(1, "fixture-double-optional-pass-resolution-opponent-optional", "opponentOptional", 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-double-optional-pass-resolution-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-double-optional-pass-resolution-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-double-optional-pass-resolution-turn-optional", triggerBucket: "turnOptional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-double-optional-pass-resolution-turn-quick", 4, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-double-optional-pass-resolution-opponent-quick", 4, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-double-optional-pass-resolution-turn-optional", "turnOptional", 4, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            logIncludes: ["Double optional pass resolution starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro opens turn-player chain-response priority after both optional chain-created SEGOC buckets are declined and the last selected trigger is the opponent mandatory trigger",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-double-optional-pass-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-double-optional-pass-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-double-optional-pass-resolution-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(0, "fixture-double-optional-pass-resolution-turn-quick", 1, 5), chainPassGroup(0, 1, 5)],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-double-optional-pass-resolution-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 5, windowKind: "triggerBucket", effectId: "fixture-double-optional-pass-resolution-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-double-optional-pass-resolution-opponent-quick", 5),
              absentTriggerActivationGroup(1, "fixture-double-optional-pass-resolution-opponent-optional", "opponentOptional", 5, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            logIncludes: ["Double optional pass resolution starter resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps turn-player post-decline chain-response priority restorable before handing responses to the opponent",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-double-optional-pass-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-double-optional-pass-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-double-optional-pass-resolution-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(0, "fixture-double-optional-pass-resolution-turn-quick", 1, 5), chainPassGroup(0, 1, 5)],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-double-optional-pass-resolution-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 5, windowKind: "triggerBucket", effectId: "fixture-double-optional-pass-resolution-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-double-optional-pass-resolution-opponent-quick", 5),
              absentTriggerActivationGroup(1, "fixture-double-optional-pass-resolution-opponent-optional", "opponentOptional", 5, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            logIncludes: ["Double optional pass resolution starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro hands chain-response priority to the opponent after the turn player passes the post-decline response window",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-double-optional-pass-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-double-optional-pass-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [0],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-double-optional-pass-resolution-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(1, "fixture-double-optional-pass-resolution-opponent-quick", 1, 6), chainPassGroup(1, 1, 6)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-double-optional-pass-resolution-turn-quick" },
              { type: "activateTrigger", player: 1, windowId: 6, windowKind: "triggerBucket", effectId: "fixture-double-optional-pass-resolution-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-double-optional-pass-resolution-turn-quick", 6),
              absentTriggerActivationGroup(1, "fixture-double-optional-pass-resolution-opponent-optional", "opponentOptional", 6, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps opponent post-decline chain-response priority restorable before resolving the mandatory-only chain",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-double-optional-pass-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 1, effectId: "fixture-double-optional-pass-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [0],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-double-optional-pass-resolution-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(1, "fixture-double-optional-pass-resolution-opponent-quick", 1, 6), chainPassGroup(1, 1, 6)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-double-optional-pass-resolution-turn-quick" },
              { type: "activateTrigger", player: 1, windowId: 6, windowKind: "triggerBucket", effectId: "fixture-double-optional-pass-resolution-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-double-optional-pass-resolution-turn-quick", 6),
              absentTriggerActivationGroup(1, "fixture-double-optional-pass-resolution-opponent-optional", "opponentOptional", 6, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            logIncludes: ["Double optional pass resolution starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro resolves the mandatory-only chain-created SEGOC trigger chain after both players pass the post-decline response windows",
            phase: "main1",
            windowId: 7,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            legalActionCounts: { 0: 9, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-double-optional-pass-resolution-starter", count: 1 },
              { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 7, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 7, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 7,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-double-optional-pass-resolution-starter", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "300", location: "hand" },
                { type: "normalSummon", player: 0, code: "500", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "300", location: "hand" },
                { type: "setMonster", player: 0, code: "500", location: "hand" },
              ], 1, 7),
              turnGroup(7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-double-optional-pass-resolution-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-double-optional-pass-resolution-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-double-optional-pass-resolution-turn-optional" },
              { type: "activateTrigger", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-double-optional-pass-resolution-opponent-optional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-double-optional-pass-resolution-turn-quick", 7, "open"),
              absentWindowEffectGroup(1, "fixture-double-optional-pass-resolution-opponent-quick", 7, "open"),
              absentTriggerActivationGroup(0, "fixture-double-optional-pass-resolution-turn-optional", "turnOptional", 7, "open"),
              absentTriggerActivationGroup(1, "fixture-double-optional-pass-resolution-opponent-optional", "opponentOptional", 7, "open"),
            ],
            locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            logIncludes: [
              "Double optional pass resolution opponent mandatory resolved",
              "Double optional pass resolution turn mandatory resolved",
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro final state returns to open priority after both optional chain-created SEGOC buckets are declined and both response players pass",
        phase: "main1",
        windowId: 7,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-double-optional-pass-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 7, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 7, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          openEffectGroup(0, "fixture-double-optional-pass-resolution-starter", 1, 7),
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
          ], 1, 7),
          turnGroup(7),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-double-optional-pass-resolution-turn-quick" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-double-optional-pass-resolution-opponent-quick" },
          { type: "activateTrigger", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-double-optional-pass-resolution-turn-optional" },
          { type: "activateTrigger", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-double-optional-pass-resolution-opponent-optional" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-double-optional-pass-resolution-turn-quick", 7, "open"),
          absentWindowEffectGroup(1, "fixture-double-optional-pass-resolution-opponent-quick", 7, "open"),
          absentTriggerActivationGroup(0, "fixture-double-optional-pass-resolution-turn-optional", "turnOptional", 7, "open"),
          absentTriggerActivationGroup(1, "fixture-double-optional-pass-resolution-opponent-optional", "opponentOptional", 7, "open"),
        ],
        locations: { graveyard: ["700", "200", "900"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
        logIncludes: [
          "Double optional pass resolution starter resolved",
          "Double optional pass resolution opponent mandatory resolved",
          "Double optional pass resolution turn mandatory resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
