import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainPassGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity trigger-chain response turn-response until-chain-end followup fixture", () => {
  it("keeps until-chain-end limits after the allowed trigger player adds another selected-trigger response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Trigger Until Followup Summon", kind: "monster", attack: 1000, defense: 1000 },
      { code: "200", name: "Trigger Until Followup Success Trigger", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Trigger Until Followup First Response", kind: "monster", attack: 1000, defense: 1000 },
      { code: "350", name: "Trigger Until Followup Second Response", kind: "monster", attack: 1000, defense: 1000 },
      { code: "360", name: "Trigger Until Followup Third Response", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Trigger Until Followup Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Trigger Until Followup Opponent Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Trigger Until Followup Opponent Blocked", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Trigger Until Followup Opponent Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "900", name: "Trigger Until Followup Filler", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "trigger chain open fast chain response turn response until-chain-end limit followup fixture",
      options: { seed: 619, startingHandSize: 6 },
      decks: {
        0: { main: ["100", "200", "300", "350", "360", "400"] },
        1: { main: ["500", "600", "700", "900", "900", "900"] },
      },
      setup: {
        effects: [
          {
            id: "trigger-until-followup-success",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "normalSummoned",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Trigger until followup success resolved",
          },
          {
            id: "trigger-until-followup-first-response",
            player: 0,
            code: "300",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Trigger until followup first response resolved",
          },
          {
            id: "trigger-until-followup-second-response",
            player: 0,
            code: "350",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Trigger until followup second response resolved",
          },
          {
            id: "trigger-until-followup-third-response",
            player: 0,
            code: "360",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Trigger until followup third response should not resolve",
          },
          {
            id: "trigger-until-followup-open",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            logMessage: "Trigger until followup open quick should not resolve",
          },
          {
            id: "trigger-until-followup-opponent-limiter",
            player: 1,
            code: "500",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 0 },
            logMessage: "Trigger until followup opponent limiter resolved",
          },
          {
            id: "trigger-until-followup-opponent-blocked",
            player: 1,
            code: "600",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Trigger until followup opponent blocked should not resolve",
          },
          {
            id: "trigger-until-followup-opponent-open",
            player: 1,
            code: "700",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            logMessage: "Trigger until followup opponent open quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("normalSummon", 0, { code: "100", location: "hand" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "trigger-until-followup-success" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "trigger-until-followup-opponent-limiter" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "trigger-until-followup-first-response" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "trigger-until-followup-second-response" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored trigger-player priority while SetChainLimitTillChainEnd permits the next selected-trigger response",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "trigger-until-followup-success", eventName: "normalSummoned", eventCardUid: "p0-deck-100-0" },
              { player: 1, effectId: "trigger-until-followup-opponent-limiter", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "trigger-until-followup-first-response", sourceUid: "p0-deck-300-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "trigger-until-followup-second-response", count: 1 },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "trigger-until-followup-third-response", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 4,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "trigger-until-followup-second-response", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "trigger-until-followup-third-response", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "trigger-until-followup-first-response" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "trigger-until-followup-open" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "trigger-until-followup-opponent-limiter" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "trigger-until-followup-opponent-blocked" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "trigger-until-followup-opponent-open" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "trigger-until-followup-first-response", 4),
              absentWindowEffectGroup(0, "trigger-until-followup-open", 4, "chainResponse"),
              absentChainEffectGroup(1, "trigger-until-followup-opponent-limiter", 4),
              absentChainEffectGroup(1, "trigger-until-followup-opponent-blocked", 4),
              absentWindowEffectGroup(1, "trigger-until-followup-opponent-open", 4, "chainResponse"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro keeps SetChainLimitTillChainEnd restrictions after the allowed trigger player adds another selected-trigger response",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "trigger-until-followup-success", eventName: "normalSummoned", eventCardUid: "p0-deck-100-0" },
              { player: 1, effectId: "trigger-until-followup-opponent-limiter", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "trigger-until-followup-first-response", sourceUid: "p0-deck-300-2" },
              { player: 0, effectId: "trigger-until-followup-second-response", sourceUid: "p0-deck-350-3" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-until-followup-third-response", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 5,
                windowKind: "chainResponse",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-until-followup-third-response", count: 1 }],
              },
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-until-followup-first-response" },
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-until-followup-second-response" },
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-until-followup-open" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "trigger-until-followup-opponent-limiter" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "trigger-until-followup-opponent-blocked" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "trigger-until-followup-opponent-open" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "trigger-until-followup-first-response", 5),
              absentChainEffectGroup(0, "trigger-until-followup-second-response", 5),
              absentChainEffectGroup(0, "trigger-until-followup-open", 5),
              absentChainEffectGroup(1, "trigger-until-followup-opponent-limiter", 5),
              absentChainEffectGroup(1, "trigger-until-followup-opponent-blocked", 5),
              absentChainEffectGroup(1, "trigger-until-followup-opponent-open", 5),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the continued SetChainLimitTillChainEnd response window restorable before the allowed trigger player passes",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "trigger-until-followup-success", eventName: "normalSummoned", eventCardUid: "p0-deck-100-0" },
              { player: 1, effectId: "trigger-until-followup-opponent-limiter", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "trigger-until-followup-first-response", sourceUid: "p0-deck-300-2" },
              { player: 0, effectId: "trigger-until-followup-second-response", sourceUid: "p0-deck-350-3" },
            ],
            chainLimits: [{ untilChainEnd: true }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-until-followup-third-response", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 5,
                windowKind: "chainResponse",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-until-followup-third-response", count: 1 }],
              },
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "trigger-until-followup-opponent-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "trigger-until-followup-opponent-blocked", 5)],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears until-chain-end limits and returns selected trigger chains to turn-player open priority after the allowed trigger player finishes responding",
        windowId: 6,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        legalActionCounts: { 0: 3, 1: 0 },
        legalActionGroupCounts: { 0: 2, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-until-followup-open", count: 1 },
          { type: "changePhase", player: 0, windowId: 6, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 6, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 6,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-until-followup-open", count: 1 }],
          },
          turnGroup(6),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-until-followup-first-response" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-until-followup-second-response" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-until-followup-third-response" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-until-followup-opponent-limiter" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-until-followup-opponent-blocked" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-until-followup-opponent-open" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "trigger-until-followup-first-response", 6, "open"),
          absentWindowEffectGroup(0, "trigger-until-followup-second-response", 6, "open"),
          absentWindowEffectGroup(0, "trigger-until-followup-third-response", 6, "open"),
          absentWindowEffectGroup(1, "trigger-until-followup-opponent-limiter", 6, "open"),
          absentWindowEffectGroup(1, "trigger-until-followup-opponent-blocked", 6, "open"),
          absentWindowEffectGroup(1, "trigger-until-followup-opponent-open", 6, "open"),
        ],
        logIncludes: [
          "Trigger until followup second response resolved",
          "Trigger until followup first response resolved",
          "Trigger until followup opponent limiter resolved",
          "Trigger until followup success resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
