import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chainEnded open fast-effect handoff opponent response turn response resolution fixture", () => {
  it("resolves turn-player responses after the opponent has no remaining post-chainEnded handoff response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Ended Handoff Turn Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Chain Ended Handoff Turn Resolution Solved Blocker", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Chain Ended Handoff Turn Resolution Cleanup", kind: "monster", attack: 1500, defense: 1600 },
      { code: "400", name: "Chain Ended Handoff Turn Resolution Open Quick", kind: "monster", attack: 1200, defense: 1200 },
      { code: "500", name: "Chain Ended Handoff Turn Resolution First Turn Chain", kind: "monster", attack: 1300, defense: 1300 },
      { code: "600", name: "Chain Ended Handoff Turn Resolution Opponent Chain", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Chain Ended Handoff Turn Resolution Second Turn Chain", kind: "monster", attack: 900, defense: 900 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "deferred chain ended open fast pass handoff opponent response turn response resolution fixture",
      options: { seed: 627, startingHandSize: 6 },
      decks: {
        0: { main: ["100", "200", "300", "400", "500", "700"] },
        1: { main: ["600"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "500", from: "hand", to: "graveyard" },
          { player: 0, code: "700", from: "hand", to: "graveyard" },
          { player: 1, code: "600", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "fixture-chain-ended-handoff-turn-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            logMessage: "Chain ended handoff turn resolution starter resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-resolution-solved-blocker",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainSolved",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain ended handoff turn resolution solved blocker should not resolve",
          },
          {
            id: "fixture-chain-ended-handoff-turn-resolution-cleanup",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            moveCardsOnResolve: [
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "500", from: "graveyard", to: "hand" },
              { player: 0, code: "700", from: "graveyard", to: "hand" },
              { player: 1, code: "600", from: "graveyard", to: "hand" },
            ],
            logMessage: "Chain ended handoff turn resolution cleanup resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-resolution-open-fast",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended handoff turn resolution open fast resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain",
            player: 0,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff turn resolution first turn chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain",
            player: 0,
            code: "700",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff turn resolution second turn chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-resolution-opponent-chain",
            player: 1,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff turn resolution opponent chain resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-resolution-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-chain-ended-handoff-turn-resolution-solved-blocker" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-ended-handoff-turn-resolution-cleanup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the post-chainEnded handoff open fast window restorable before the turn-resolution chain starts",
            phase: "main1",
            windowId: 3,
            windowKind: "open",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600"] },
            legalActionCounts: { 0: 14, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-starter", count: 1 },
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 3,
                windowKind: "open",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-starter", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast", count: 1 },
                ],
              },
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain" },
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain" },
            ],

            absentLegalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 3,
                windowKind: "open",
                actions: [
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain" },
                ],
              },
              {
                player: 0,
                label: "Effects",
                windowId: 3,
                windowKind: "open",
                actions: [
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain" },
                ],
              },
              {
                player: 1,
                label: "Effects",
                windowId: 3,
                windowKind: "open",
                actions: [
                  { type: "activateEffect", player: 1, windowId: 3, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain" },
                ],
              },
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro opens restored opponent responses after a post-chainEnded open fast effect before turn-response resolution",
            phase: "main1",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [{ player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast", sourceUid: "p0-deck-400-3" }],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600"] },
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain", count: 1 },
              { type: "passChain", player: 1, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-chain-ended-handoff-turn-resolution-opponent-chain", 1, 4),
              chainPassGroup(1, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-open-fast", 4, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", 4),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", 4),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent priority before the post-chainEnded turn-resolution handoff",
            phase: "main1",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [{ player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast", sourceUid: "p0-deck-400-3" }],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600"] },
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain", count: 1 },
              { type: "passChain", player: 1, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-chain-ended-handoff-turn-resolution-opponent-chain", 1, 4),
              chainPassGroup(1, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-open-fast", 4, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", 4),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", 4),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro reopens restored turn-player responses after the opponent passes the post-chainEnded chain",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [{ player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast", sourceUid: "p0-deck-400-3" }],
            chainPasses: [1],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600"] },
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", count: 1 },
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 5,
                windowKind: "chainResponse",
                actions: [
                  { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-open-fast", 5, "chainResponse"),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-turn-resolution-opponent-chain", 5),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player priority before the first post-chainEnded turn response",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [{ player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast", sourceUid: "p0-deck-400-3" }],
            chainPasses: [1],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600"] },
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", count: 1 },
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 5,
                windowKind: "chainResponse",
                actions: [
                  { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-open-fast", 5, "chainResponse"),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-turn-resolution-opponent-chain", 5),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns restored post-chainEnded response priority to the opponent after the turn player chains",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", sourceUid: "p0-deck-500-4" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600"] },
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-chain-ended-handoff-turn-resolution-opponent-chain", 1, 6),
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-open-fast", 6, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", 6),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", 6),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent response priority before the post-chainEnded opponent response",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", sourceUid: "p0-deck-500-4" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600"] },
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-chain-ended-handoff-turn-resolution-opponent-chain", 1, 6),
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-open-fast", 6, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", 6),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", 6),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro reopens restored turn-player priority after the opponent answers the post-chainEnded handoff",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", sourceUid: "p0-deck-500-4" },
              { player: 1, effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain", sourceUid: "p1-deck-600-0" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600"] },
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", 1, 7),
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast" },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-open-fast", 7, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", 7),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-turn-resolution-opponent-chain", 7),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player priority before the final post-chainEnded handoff response",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 0, effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", sourceUid: "p0-deck-500-4" },
              { player: 1, effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain", sourceUid: "p1-deck-600-0" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600"] },
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", 1, 7),
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast" },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-open-fast", 7, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", 7),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-turn-resolution-opponent-chain", 7),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro resolves turn-player post-chainEnded handoff responses after the restored final turn response",
            phase: "main1",
            windowId: 8,
            windowKind: "open",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600"] },
            legalActionCounts: { 0: 13, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-starter", count: 1 },
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "400", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "700", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "400", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "700", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 8,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-starter", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "300", location: "hand" },
                { type: "normalSummon", player: 0, code: "400", location: "hand" },
                { type: "normalSummon", player: 0, code: "500", location: "hand" },
                { type: "normalSummon", player: 0, code: "700", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "300", location: "hand" },
                { type: "setMonster", player: 0, code: "400", location: "hand" },
                { type: "setMonster", player: 0, code: "500", location: "hand" },
                { type: "setMonster", player: 0, code: "700", location: "hand" },
              ], 1, 8),
              turnGroup(8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-open-fast", 8, "open"),
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", 8, "open"),
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", 8, "open"),
              absentWindowEffectGroup(1, "fixture-chain-ended-handoff-turn-resolution-opponent-chain", 8, "open"),
            ],
            logIncludes: [
              "Chain ended handoff turn resolution second turn chain resolved",
              "Chain ended handoff turn resolution opponent chain resolved",
              "Chain ended handoff turn resolution first turn chain resolved",
              "Chain ended handoff turn resolution open fast resolved",
              "Chain ended handoff turn resolution cleanup resolved",
              "Chain ended handoff turn resolution starter resolved",
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves turn-player post-chainEnded handoff responses after the opponent has no remaining response to the turn player's final chain link",
        phase: "main1",
        windowId: 8,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600"] },
        legalActionCounts: { 0: 13, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 8,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "400", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "normalSummon", player: 0, code: "700", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "400", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "700", location: "hand" },
          ], 1, 8),
          turnGroup(8),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-open-fast" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-first-turn-chain" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-second-turn-chain" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-resolution-opponent-chain" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-open-fast", 8, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-first-turn-chain", 8, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-resolution-second-turn-chain", 8, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-handoff-turn-resolution-opponent-chain", 8, "open"),
        ],
        logIncludes: [
          "Chain ended handoff turn resolution second turn chain resolved",
          "Chain ended handoff turn resolution opponent chain resolved",
          "Chain ended handoff turn resolution first turn chain resolved",
          "Chain ended handoff turn resolution open fast resolved",
          "Chain ended handoff turn resolution cleanup resolved",
          "Chain ended handoff turn resolution starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
