import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  triggerActivationGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution cross-player later-payload restored follow-up pass chainEnded fixture", () => {
  it("opens a chainEnded trigger bucket after a restored follow-up chain resolves from an opponent pass", () => {
    const firstEventCode = 0x1000004b;
    const secondEventCode = 0x1000004c;
    const cards: DuelCardData[] = [
      { code: "100", name: "Cross Payload Follow-Up Ended Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "300", name: "Cross Payload Follow-Up Ended Turn Trigger", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Cross Payload Follow-Up Ended Opponent Trigger", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Cross Payload Follow-Up Ended Turn Body", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Cross Payload Follow-Up Ended Opponent First Chain Quick", kind: "monster", attack: 1100, defense: 1100 },
      { code: "620", name: "Cross Payload Follow-Up Ended Opponent Second Chain Quick", kind: "monster", attack: 1150, defense: 1150 },
      { code: "700", name: "Cross Payload Follow-Up Ended Opponent Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Cross Payload Follow-Up Ended Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Cross Payload Follow-Up Ended Turn Open Quick", kind: "monster", attack: 1300, defense: 1300 },
      { code: "950", name: "Cross Payload Follow-Up Ended Turn Chain Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "970", name: "Cross Payload Follow-Up Ended Turn Follow-Up Quick", kind: "monster", attack: 1450, defense: 1450 },
      { code: "980", name: "Cross Payload Follow-Up Ended ChainEnded Watcher", kind: "monster", attack: 1350, defense: 1350 },
      { code: "990", name: "Cross Payload Follow-Up Ended Opponent Open Quick", kind: "monster", attack: 700, defense: 700 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution segoc cross-player later-payload open-fast pass-handoff turn-follow-up opponent-pass chainEnded restore fixture",
      options: { seed: 405, startingHandSize: 8 },
      decks: {
        0: { main: ["100", "300", "500", "900", "950", "970", "980", "800"] },
        1: { main: ["400", "600", "620", "700", "990", "800", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-cross-payload-follow-up-ended-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "500", from: "hand", to: "graveyard", collectEvent: "customEvent", eventCode: firstEventCode },
              { player: 1, code: "700", from: "hand", to: "graveyard", collectEvent: "customEvent", eventCode: secondEventCode },
            ],
            logMessage: "Cross payload follow-up chainEnded starter resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-turn-trigger",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "customEvent",
            triggerCode: firstEventCode,
            range: ["hand"],
            logMessage: "Cross payload follow-up chainEnded turn trigger should not resolve",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-opponent-trigger",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "customEvent",
            triggerCode: secondEventCode,
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 1, code: "600", from: "hand", to: "graveyard" },
              { player: 1, code: "620", from: "hand", to: "graveyard" },
              { player: 0, code: "950", from: "hand", to: "graveyard" },
              { player: 0, code: "970", from: "hand", to: "graveyard" },
            ],
            logMessage: "Cross payload follow-up chainEnded opponent trigger resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-turn-open-quick",
            player: 0,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Cross payload follow-up chainEnded turn open quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-turn-chain-quick",
            player: 0,
            code: "950",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross payload follow-up chainEnded turn chain quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-turn-follow-up-quick",
            player: 0,
            code: "970",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            moveCardsOnResolve: [{ player: 0, code: "980", from: "hand", to: "graveyard" }],
            logMessage: "Cross payload follow-up chainEnded turn follow-up quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-chain-ended-watcher",
            player: 0,
            code: "980",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            optional: false,
            range: ["graveyard"],
            oncePerTurn: true,
            logMessage: "Cross payload follow-up chainEnded watcher resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-opponent-first-chain-quick",
            player: 1,
            code: "600",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross payload follow-up chainEnded opponent first chain quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-opponent-second-chain-quick",
            player: 1,
            code: "620",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross payload follow-up chainEnded opponent second chain quick should not resolve",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-opponent-open-quick",
            player: 1,
            code: "990",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            logMessage: "Cross payload follow-up chainEnded opponent open quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-starter" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-cross-payload-follow-up-ended-turn-trigger" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-payload-follow-up-ended-opponent-trigger" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-turn-open-quick" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-turn-chain-quick" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-cross-payload-follow-up-ended-opponent-first-chain-quick" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-turn-follow-up-quick" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro opens a chainEnded trigger bucket after a restored follow-up chain resolves from the opponent pass",
            phase: "main1",
            windowId: 9,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [{ player: 0, effectId: "fixture-cross-payload-follow-up-ended-chain-ended-watcher", eventName: "chainEnded", triggerBucket: "turnMandatory" }],
            pendingTriggerBuckets: [{ player: 0, triggerBucket: "turnMandatory" }],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-chain-ended-watcher", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-chain-ended-watcher", "turnMandatory", 1, 9)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-turn-follow-up-quick" },
              { type: "activateEffect", player: 1, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-opponent-second-chain-quick" },
              { type: "declineTrigger", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-chain-ended-watcher", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-open-quick", 9, "triggerBucket"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-chain-quick", 9, "triggerBucket"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-follow-up-quick", 9, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-opponent-second-chain-quick", 9, "triggerBucket"),
              {
                player: 0,
                label: "Trigger Declines",
                windowId: 9,
                windowKind: "triggerBucket",
                triggerBucket: { player: 0, triggerBucket: "turnMandatory" },
                actions: [{ type: "declineTrigger", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-chain-ended-watcher" }],
              },
            ],
            locations: { graveyard: ["500", "700", "600", "620", "950", "970", "980"] },
            logIncludes: [
              "Cross payload follow-up chainEnded starter resolved",
              "Cross payload follow-up chainEnded opponent trigger resolved",
              "Cross payload follow-up chainEnded turn follow-up quick resolved",
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-payload-follow-up-ended-chain-ended-watcher" }), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro gives the opponent response priority after the restored chainEnded trigger activates",
            phase: "main1",
            windowId: 10,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 0, effectId: "fixture-cross-payload-follow-up-ended-chain-ended-watcher", sourceUid: "p0-deck-980-6" }],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-opponent-second-chain-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 10, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-payload-follow-up-ended-opponent-second-chain-quick", 1, 10),
              chainPassGroup(1, 1, 10),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-turn-follow-up-quick" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-opponent-first-chain-quick" },
              { type: "activateTrigger", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-chain-ended-watcher", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-open-quick", 10, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-chain-quick", 10, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-follow-up-quick", 10, "chainResponse"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-opponent-first-chain-quick", 10, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-chain-ended-watcher", "turnMandatory", 10, "chainResponse"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent response priority before the chainEnded trigger chain resolves",
            phase: "main1",
            windowId: 10,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 0, effectId: "fixture-cross-payload-follow-up-ended-chain-ended-watcher", sourceUid: "p0-deck-980-6" }],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-opponent-second-chain-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 10, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-payload-follow-up-ended-opponent-second-chain-quick", 1, 10),
              chainPassGroup(1, 1, 10),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-turn-follow-up-quick" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-opponent-first-chain-quick" },
              { type: "activateTrigger", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-chain-ended-watcher", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-open-quick", 10, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-chain-quick", 10, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-follow-up-quick", 10, "chainResponse"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-opponent-first-chain-quick", 10, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-chain-ended-watcher", "turnMandatory", 10, "chainResponse"),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves the restored follow-up chainEnded trigger and returns to open priority",
        phase: "main1",
        windowId: 11,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        legalActionCounts: { 0: 11, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 11, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 11, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 11, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 11, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 11, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 11, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 11, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 11,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-starter", count: 1 }],
          },
          turnGroup(11),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-turn-open-quick" },
          { type: "activateEffect", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-turn-chain-quick" },
          { type: "activateEffect", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-turn-follow-up-quick" },
          { type: "activateEffect", player: 1, windowId: 11, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-opponent-first-chain-quick" },
          { type: "activateEffect", player: 1, windowId: 11, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-opponent-second-chain-quick" },
          { type: "activateTrigger", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-chain-ended-watcher", triggerBucket: "turnMandatory" },
          { type: "activateTrigger", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-turn-trigger", triggerBucket: "turnOptional" },
          { type: "activateTrigger", player: 1, windowId: 11, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-opponent-trigger", triggerBucket: "opponentOptional" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-open-quick", 11, "open"),
          absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-chain-quick", 11, "open"),
          absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-turn-follow-up-quick", 11, "open"),
          absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-opponent-first-chain-quick", 11, "open"),
          absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-opponent-second-chain-quick", 11, "open"),
          absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-chain-ended-watcher", "turnMandatory", 11, "open"),
          absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-turn-trigger", "turnOptional", 11, "open"),
          absentTriggerActivationGroup(1, "fixture-cross-payload-follow-up-ended-opponent-trigger", "opponentOptional", 11, "open"),
        ],
        locations: { graveyard: ["500", "700", "600", "620", "950", "970", "980"], hand: ["100", "300", "900", "800", "400", "990", "800", "800"] },
        logIncludes: [
          "Cross payload follow-up chainEnded starter resolved",
          "Cross payload follow-up chainEnded opponent trigger resolved",
          "Cross payload follow-up chainEnded turn follow-up quick resolved",
          "Cross payload follow-up chainEnded watcher resolved",
          "Cross payload follow-up chainEnded opponent first chain quick resolved",
          "Cross payload follow-up chainEnded turn chain quick resolved",
          "Cross payload follow-up chainEnded turn open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
