import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity end turn open fast-effect chain-response pass handoff turn response chain fixture", () => {
  it("opens previous-turn responses after the new turn player responds to an End Turn handoff chain", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Previous Turn Chain Handoff Turn Response Chain Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "200", name: "Next Turn Chain Handoff Turn Response Chain Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Next Turn Chain Handoff Turn Response Chain Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Previous Turn Chain Handoff Turn Response Chain First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Previous Turn Chain Handoff Turn Response Chain Second Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Next Turn Chain Handoff Turn Response Chain Filler", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Next Turn Chain Handoff Turn Response Chain Extra", kind: "monster", attack: 1000, defense: 1000 },
      { code: "800", name: "Previous Turn Chain Handoff Turn Response Chain Third Quick", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "end turn open fast chain response pass handoff turn response chain fixture",
      options: { seed: 280, startingHandSize: 4 },
      decks: {
        0: { main: ["100", "400", "500", "800"] },
        1: { main: ["200", "300", "600", "700"] },
      },
      setup: {
        effects: [
          {
            id: "end-turn-chain-handoff-turn-response-chain-previous-open-quick",
            player: 0,
            code: "100",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            logMessage: "Previous turn chain handoff turn response chain open quick should not be offered",
          },
          {
            id: "end-turn-chain-handoff-turn-response-chain-next-open-quick",
            player: 1,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Next turn chain handoff turn response chain open quick should not resolve yet",
          },
          {
            id: "end-turn-chain-handoff-turn-response-chain-next-chain-quick",
            player: 1,
            code: "300",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Next turn chain handoff turn response chain quick should not resolve yet",
          },
          {
            id: "end-turn-chain-handoff-turn-response-chain-previous-first-quick",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Previous turn chain handoff turn response chain first quick should not resolve yet",
          },
          {
            id: "end-turn-chain-handoff-turn-response-chain-previous-second-quick",
            player: 0,
            code: "500",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Previous turn chain handoff turn response chain second quick should not resolve yet",
          },
          {
            id: "end-turn-chain-handoff-turn-response-chain-previous-third-quick",
            player: 0,
            code: "800",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Previous turn chain handoff turn response chain third quick should not resolve yet",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("endTurn", 0), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro opens the next turn player's open fast-effect window after End Turn before chain-response turn handoff chains",
            windowId: 1,
            windowKind: "open",
            phase: "main1",
            turnPlayer: 1,
            turn: 2,
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 11 },
            legalActionGroupCounts: { 0: 0, 1: 3 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "end-turn-chain-handoff-turn-response-chain-next-open-quick", count: 1 },
              { type: "normalSummon", player: 1, windowId: 1, windowKind: "open", code: "200", location: "hand", count: 1 },
              { type: "normalSummon", player: 1, windowId: 1, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 1, windowId: 1, windowKind: "open", code: "600", location: "hand", count: 1 },
              { type: "normalSummon", player: 1, windowId: 1, windowKind: "open", code: "700", location: "hand", count: 1 },
              { type: "setMonster", player: 1, windowId: 1, windowKind: "open", code: "200", location: "hand", count: 1 },
              { type: "setMonster", player: 1, windowId: 1, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 1, windowId: 1, windowKind: "open", code: "600", location: "hand", count: 1 },
              { type: "setMonster", player: 1, windowId: 1, windowKind: "open", code: "700", location: "hand", count: 1 },
              { type: "changePhase", player: 1, windowId: 1, windowKind: "open", count: 1 },
              { type: "endTurn", player: 1, windowId: 1, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 1,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "end-turn-chain-handoff-turn-response-chain-next-open-quick", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 1, code: "200", location: "hand" },
                { type: "normalSummon", player: 1, code: "300", location: "hand" },
                { type: "normalSummon", player: 1, code: "600", location: "hand" },
                { type: "normalSummon", player: 1, code: "700", location: "hand" },
                { type: "setMonster", player: 1, code: "200", location: "hand" },
                { type: "setMonster", player: 1, code: "300", location: "hand" },
                { type: "setMonster", player: 1, code: "600", location: "hand" },
                { type: "setMonster", player: 1, code: "700", location: "hand" },
              ], 1, 1),
              {
                player: 1,
                label: "Turn",
                windowId: 1,
                windowKind: "open",
                actions: [
                  { type: "changePhase", player: 1, windowId: 1, windowKind: "open", count: 1 },
                  { type: "endTurn", player: 1, windowId: 1, windowKind: "open", count: 1 },
                ],
              },
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "end-turn-chain-handoff-turn-response-chain-previous-open-quick" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "end-turn-chain-handoff-turn-response-chain-previous-first-quick" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "end-turn-chain-handoff-turn-response-chain-previous-second-quick" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "end-turn-chain-handoff-turn-response-chain-previous-third-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "end-turn-chain-handoff-turn-response-chain-next-chain-quick" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "end-turn-chain-handoff-turn-response-chain-previous-open-quick", 1, "open"),
              absentWindowEffectGroup(0, "end-turn-chain-handoff-turn-response-chain-previous-first-quick", 1, "open"),
              absentWindowEffectGroup(0, "end-turn-chain-handoff-turn-response-chain-previous-second-quick", 1, "open"),
              absentWindowEffectGroup(0, "end-turn-chain-handoff-turn-response-chain-previous-third-quick", 1, "open"),
              absentWindowEffectGroup(1, "end-turn-chain-handoff-turn-response-chain-next-chain-quick", 1, "open"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "end-turn-chain-handoff-turn-response-chain-next-open-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "end-turn-chain-handoff-turn-response-chain-previous-first-quick" })),
        makeScriptedStep(makeResponseSelector("passChain", 1)),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "end-turn-chain-handoff-turn-response-chain-previous-second-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "end-turn-chain-handoff-turn-response-chain-next-chain-quick" }), {
          snapshotRestore: "both",
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro opens previous-turn chain responses after the new turn player responds to an End Turn chain-response pass-handoff chain",
        windowId: 6,
        windowKind: "chainResponse",
        phase: "main1",
        turnPlayer: 1,
        turn: 2,
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [
          { player: 1, effectId: "end-turn-chain-handoff-turn-response-chain-next-open-quick", sourceUid: "p1-deck-200-0" },
          { player: 0, effectId: "end-turn-chain-handoff-turn-response-chain-previous-first-quick", sourceUid: "p0-deck-400-1" },
          { player: 0, effectId: "end-turn-chain-handoff-turn-response-chain-previous-second-quick", sourceUid: "p0-deck-500-2" },
          { player: 1, effectId: "end-turn-chain-handoff-turn-response-chain-next-chain-quick", sourceUid: "p1-deck-300-1" },
        ],
        chainPasses: [],
        legalActionCounts: { 0: 2, 1: 0 },
        legalActionGroupCounts: { 0: 2, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "end-turn-chain-handoff-turn-response-chain-previous-third-quick", count: 1 },
          { type: "passChain", player: 0, windowId: 6, windowKind: "chainResponse", count: 1 },
        ],
        legalActionGroups: [
          chainEffectGroup(0, "end-turn-chain-handoff-turn-response-chain-previous-third-quick", 1, 6),
          chainPassGroup(0, 1, 6),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "end-turn-chain-handoff-turn-response-chain-next-open-quick" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "end-turn-chain-handoff-turn-response-chain-next-chain-quick" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "end-turn-chain-handoff-turn-response-chain-previous-open-quick" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "end-turn-chain-handoff-turn-response-chain-previous-first-quick" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "end-turn-chain-handoff-turn-response-chain-previous-second-quick" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(1, "end-turn-chain-handoff-turn-response-chain-next-open-quick", 6, "chainResponse"),
          absentWindowEffectGroup(1, "end-turn-chain-handoff-turn-response-chain-next-chain-quick", 6, "chainResponse"),
          absentWindowEffectGroup(0, "end-turn-chain-handoff-turn-response-chain-previous-open-quick", 6, "chainResponse"),
          absentWindowEffectGroup(0, "end-turn-chain-handoff-turn-response-chain-previous-first-quick", 6, "chainResponse"),
          absentWindowEffectGroup(0, "end-turn-chain-handoff-turn-response-chain-previous-second-quick", 6, "chainResponse"),
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
