import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity trigger-chain response turn-response chain-limit opponent-response resolution fixture", () => {
  it("resolves selected-trigger chains after one-chain limits clear and both players finish responding", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Trigger Limit Opponent Resolution Summon", kind: "monster", attack: 1000, defense: 1000 },
      { code: "200", name: "Trigger Limit Opponent Resolution Success Trigger", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Trigger Limit Opponent Resolution First Followup", kind: "monster", attack: 1000, defense: 1000 },
      { code: "350", name: "Trigger Limit Opponent Resolution Second Followup", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Trigger Limit Opponent Resolution Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Trigger Limit Opponent Resolution Opponent Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Trigger Limit Opponent Resolution Opponent Followup", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Trigger Limit Opponent Resolution Opponent Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "900", name: "Trigger Limit Opponent Resolution Filler", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "trigger chain open fast chain response turn response chain limit opponent-response resolution fixture",
      options: { seed: 620, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "350", "400"] },
        1: { main: ["500", "600", "700", "900", "900"] },
      },
      setup: {
        effects: [
          {
            id: "trigger-limit-opponent-resolution-success",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "normalSummoned",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Trigger limit opponent resolution success resolved",
          },
          {
            id: "trigger-limit-opponent-resolution-first-followup",
            player: 0,
            code: "300",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Trigger limit opponent resolution first followup resolved",
          },
          {
            id: "trigger-limit-opponent-resolution-second-followup",
            player: 0,
            code: "350",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Trigger limit opponent resolution second followup resolved",
          },
          {
            id: "trigger-limit-opponent-resolution-open",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            logMessage: "Trigger limit opponent resolution open quick should not resolve",
          },
          {
            id: "trigger-limit-opponent-resolution-opponent-limiter",
            player: 1,
            code: "500",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: false, allowPlayer: 0 },
            logMessage: "Trigger limit opponent resolution opponent limiter resolved",
          },
          {
            id: "trigger-limit-opponent-resolution-opponent-followup",
            player: 1,
            code: "600",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Trigger limit opponent resolution opponent followup resolved",
          },
          {
            id: "trigger-limit-opponent-resolution-opponent-open",
            player: 1,
            code: "700",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            logMessage: "Trigger limit opponent resolution opponent open quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("normalSummon", 0, { code: "100", location: "hand" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "trigger-limit-opponent-resolution-success" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "trigger-limit-opponent-resolution-opponent-limiter" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "trigger-limit-opponent-resolution-first-followup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "trigger-limit-opponent-resolution-opponent-followup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "trigger-limit-opponent-resolution-second-followup" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored trigger-player priority after one-chain SetChainLimit restrictions clear before the final response",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "trigger-limit-opponent-resolution-success", eventName: "normalSummoned", eventCardUid: "p0-deck-100-0", eventTriggerTiming: "if" },
              { player: 1, effectId: "trigger-limit-opponent-resolution-opponent-limiter", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "trigger-limit-opponent-resolution-first-followup", sourceUid: "p0-deck-300-2" },
              { player: 1, effectId: "trigger-limit-opponent-resolution-opponent-followup", sourceUid: "p1-deck-600-1" },
            ],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-limit-opponent-resolution-second-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "trigger-limit-opponent-resolution-second-followup", 1, 5),
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-limit-opponent-resolution-first-followup" },
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-limit-opponent-resolution-open" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "trigger-limit-opponent-resolution-opponent-limiter" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "trigger-limit-opponent-resolution-opponent-followup" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "trigger-limit-opponent-resolution-opponent-open" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "trigger-limit-opponent-resolution-first-followup", 5),
              absentWindowEffectGroup(0, "trigger-limit-opponent-resolution-open", 5, "chainResponse"),
              absentChainEffectGroup(1, "trigger-limit-opponent-resolution-opponent-limiter", 5),
              absentChainEffectGroup(1, "trigger-limit-opponent-resolution-opponent-followup", 5),
              absentWindowEffectGroup(1, "trigger-limit-opponent-resolution-opponent-open", 5, "chainResponse"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro resolves selected-trigger chains after one-chain SetChainLimit restrictions clear and both players finish responding",
            windowId: 6,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-open", count: 1 },
              { type: "changePhase", player: 0, windowId: 6, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 6, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 6,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-open", count: 1 }],
              },
              turnGroup(6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-first-followup" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-second-followup" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-opponent-limiter" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-opponent-followup" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-opponent-open" },
              { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "200", location: "hand" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "trigger-limit-opponent-resolution-first-followup", 6, "open"),
              absentWindowEffectGroup(0, "trigger-limit-opponent-resolution-second-followup", 6, "open"),
              absentWindowEffectGroup(1, "trigger-limit-opponent-resolution-opponent-limiter", 6, "open"),
              absentWindowEffectGroup(1, "trigger-limit-opponent-resolution-opponent-followup", 6, "open"),
              absentWindowEffectGroup(1, "trigger-limit-opponent-resolution-opponent-open", 6, "open"),
            ],
            logIncludes: [
              "Trigger limit opponent resolution second followup resolved",
              "Trigger limit opponent resolution opponent followup resolved",
              "Trigger limit opponent resolution first followup resolved",
              "Trigger limit opponent resolution opponent limiter resolved",
              "Trigger limit opponent resolution success resolved",
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro final state keeps turn-player open priority after selected-trigger one-chain-limit opponent-response chains resolve",
        windowId: 6,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        legalActionCounts: { 0: 3, 1: 0 },
        legalActionGroupCounts: { 0: 2, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-open", count: 1 },
          { type: "changePhase", player: 0, windowId: 6, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 6, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 6,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-open", count: 1 }],
          },
          turnGroup(6),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-first-followup" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-second-followup" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-opponent-limiter" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-opponent-followup" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-limit-opponent-resolution-opponent-open" },
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "200", location: "hand" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "trigger-limit-opponent-resolution-first-followup", 6, "open"),
          absentWindowEffectGroup(0, "trigger-limit-opponent-resolution-second-followup", 6, "open"),
          absentWindowEffectGroup(1, "trigger-limit-opponent-resolution-opponent-limiter", 6, "open"),
          absentWindowEffectGroup(1, "trigger-limit-opponent-resolution-opponent-followup", 6, "open"),
          absentWindowEffectGroup(1, "trigger-limit-opponent-resolution-opponent-open", 6, "open"),
        ],
        logIncludes: [
          "Trigger limit opponent resolution second followup resolved",
          "Trigger limit opponent resolution opponent followup resolved",
          "Trigger limit opponent resolution first followup resolved",
          "Trigger limit opponent resolution opponent limiter resolved",
          "Trigger limit opponent resolution success resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
