import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity open fast-effect chain-response handoff turn-response chain-limit fixture", () => {
  it("applies one-chain limits after the turn player responds to an open fast-effect chain-response handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Open Chain Handoff Turn Response Limit Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "200", name: "Open Chain Handoff Turn Response Limit Chain Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Open Chain Handoff Turn Response Limit Opponent First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Open Chain Handoff Turn Response Limit Opponent Second Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Open Chain Handoff Turn Response Limit Opponent Filler", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Open Chain Handoff Turn Response Limit Followup", kind: "monster", attack: 1000, defense: 1000 },
      { code: "800", name: "Open Chain Handoff Turn Response Limit Opponent Blocked Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "900", name: "Open Chain Handoff Turn Response Limit Filler", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "open fast chain-response handoff turn-response chain limit fixture",
      options: { seed: 339, startingHandSize: 4 },
      decks: {
        0: { main: ["100", "200", "700", "900"] },
        1: { main: ["300", "500", "800", "600"] },
      },
      setup: {
        effects: [
          {
            id: "open-fast-chain-handoff-turn-response-limit-open-quick",
            player: 0,
            code: "100",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            oncePerTurn: true,
            logMessage: "Open fast chain handoff turn-response limit open quick resolved",
          },
          {
            id: "open-fast-chain-handoff-turn-response-limit-chain-limiter",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            chainLimitOnTarget: { untilChainEnd: false, allowPlayer: 0 },
            logMessage: "Open fast chain handoff turn-response limit chain limiter resolved",
          },
          {
            id: "open-fast-chain-handoff-turn-response-limit-followup",
            player: 0,
            code: "700",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Open fast chain handoff turn-response limit followup should not resolve",
          },
          {
            id: "open-fast-chain-handoff-turn-response-limit-opponent-first",
            player: 1,
            code: "300",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Open fast chain handoff turn-response limit opponent first quick resolved",
          },
          {
            id: "open-fast-chain-handoff-turn-response-limit-opponent-second",
            player: 1,
            code: "500",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Open fast chain handoff turn-response limit opponent second quick resolved",
          },
          {
            id: "open-fast-chain-handoff-turn-response-limit-opponent-blocked",
            player: 1,
            code: "800",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Open fast chain handoff turn-response limit opponent blocked quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "open-fast-chain-handoff-turn-response-limit-open-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "open-fast-chain-handoff-turn-response-limit-opponent-first" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "open-fast-chain-handoff-turn-response-limit-opponent-second" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "open-fast-chain-handoff-turn-response-limit-chain-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the open fast-effect chain-response handoff turn-response window restorable before the turn player applies a one-chain limit",
            phase: "main1",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "open-fast-chain-handoff-turn-response-limit-open-quick", sourceUid: "p0-deck-100-0" },
              { player: 1, effectId: "open-fast-chain-handoff-turn-response-limit-opponent-first", sourceUid: "p1-deck-300-0" },
              { player: 1, effectId: "open-fast-chain-handoff-turn-response-limit-opponent-second", sourceUid: "p1-deck-500-1" },
            ],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-turn-response-limit-chain-limiter", count: 1 },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-turn-response-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 4,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-turn-response-limit-chain-limiter", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-turn-response-limit-followup", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 4),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-turn-response-limit-opponent-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "open-fast-chain-handoff-turn-response-limit-opponent-blocked", 4)],
          },
          after: {
            source: "edopro",
            note: "EDOPro applies one-chain SetChainLimit restrictions after the turn player responds to an open fast-effect chain-response handoff",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "open-fast-chain-handoff-turn-response-limit-open-quick", sourceUid: "p0-deck-100-0" },
              { player: 1, effectId: "open-fast-chain-handoff-turn-response-limit-opponent-first", sourceUid: "p1-deck-300-0" },
              { player: 1, effectId: "open-fast-chain-handoff-turn-response-limit-opponent-second", sourceUid: "p1-deck-500-1" },
              { player: 0, effectId: "open-fast-chain-handoff-turn-response-limit-chain-limiter", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 4 }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-turn-response-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "open-fast-chain-handoff-turn-response-limit-followup", 1, 5),
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-turn-response-limit-opponent-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "open-fast-chain-handoff-turn-response-limit-opponent-blocked", 5)],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the open fast-effect turn-response SetChainLimit window restorable before the allowed turn player passes",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "open-fast-chain-handoff-turn-response-limit-open-quick", sourceUid: "p0-deck-100-0" },
              { player: 1, effectId: "open-fast-chain-handoff-turn-response-limit-opponent-first", sourceUid: "p1-deck-300-0" },
              { player: 1, effectId: "open-fast-chain-handoff-turn-response-limit-opponent-second", sourceUid: "p1-deck-500-1" },
              { player: 0, effectId: "open-fast-chain-handoff-turn-response-limit-chain-limiter", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 4 }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-turn-response-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "open-fast-chain-handoff-turn-response-limit-followup", 1, 5),
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "open-fast-chain-handoff-turn-response-limit-opponent-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "open-fast-chain-handoff-turn-response-limit-opponent-blocked", 5)],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears one-chain limits and returns to turn-player open priority after the allowed turn player passes the open fast-effect turn-response handoff chain",
        phase: "main1",
        windowId: 6,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        legalActionCounts: { 0: 10, 1: 0 },
        legalActionGroupCounts: { 0: 2, 1: 0 },
        legalActions: [
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "200", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "200", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 6, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 6, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "200", location: "hand" },
            { type: "normalSummon", player: 0, code: "700", location: "hand" },
            { type: "normalSummon", player: 0, code: "900", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "200", location: "hand" },
            { type: "setMonster", player: 0, code: "700", location: "hand" },
            { type: "setMonster", player: 0, code: "900", location: "hand" },
          ], 1, 6),
          turnGroup(6),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "open-fast-chain-handoff-turn-response-limit-open-quick" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "open-fast-chain-handoff-turn-response-limit-chain-limiter" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "open-fast-chain-handoff-turn-response-limit-followup" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "open-fast-chain-handoff-turn-response-limit-opponent-blocked" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "open-fast-chain-handoff-turn-response-limit-open-quick", 6, "open"),
          absentWindowEffectGroup(0, "open-fast-chain-handoff-turn-response-limit-chain-limiter", 6, "open"),
          absentWindowEffectGroup(0, "open-fast-chain-handoff-turn-response-limit-followup", 6, "open"),
          absentWindowEffectGroup(1, "open-fast-chain-handoff-turn-response-limit-opponent-blocked", 6, "open"),
        ],
        logIncludes: [
          "Open fast chain handoff turn-response limit chain limiter resolved",
          "Open fast chain handoff turn-response limit opponent second quick resolved",
          "Open fast chain handoff turn-response limit opponent first quick resolved",
          "Open fast chain handoff turn-response limit open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
