import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  triggerActivationGroup,
  triggerDeclineGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity restored follow-up chainEnded response handoff fixture", () => {
  it("hands response priority back to the turn player after the opponent responds to a restored chainEnded trigger chain", () => {
    const firstEventCode = 0x1000004f;
    const secondEventCode = 0x10000050;
    const cards: DuelCardData[] = [
      { code: "100", name: "Cross Payload Follow-Up Ended Handoff Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "300", name: "Cross Payload Follow-Up Ended Handoff Turn Trigger", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Cross Payload Follow-Up Ended Handoff Opponent Trigger", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Cross Payload Follow-Up Ended Handoff Turn Body", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Cross Payload Follow-Up Ended Handoff Opponent First Chain Quick", kind: "monster", attack: 1100, defense: 1100 },
      { code: "620", name: "Cross Payload Follow-Up Ended Handoff Opponent Second Chain Quick", kind: "monster", attack: 1150, defense: 1150 },
      { code: "700", name: "Cross Payload Follow-Up Ended Handoff Opponent Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Cross Payload Follow-Up Ended Handoff Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Cross Payload Follow-Up Ended Handoff Turn Open Quick", kind: "monster", attack: 1300, defense: 1300 },
      { code: "950", name: "Cross Payload Follow-Up Ended Handoff Turn Chain Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "970", name: "Cross Payload Follow-Up Ended Handoff Turn Follow-Up Quick", kind: "monster", attack: 1450, defense: 1450 },
      { code: "975", name: "Cross Payload Follow-Up Ended Handoff Turn ChainEnded Response Quick", kind: "monster", attack: 1425, defense: 1425 },
      { code: "980", name: "Cross Payload Follow-Up Ended Handoff ChainEnded Watcher", kind: "monster", attack: 1350, defense: 1350 },
      { code: "990", name: "Cross Payload Follow-Up Ended Handoff Opponent Open Quick", kind: "monster", attack: 700, defense: 700 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution segoc cross-player later-payload open-fast pass-handoff turn-follow-up chainEnded response-handoff restore fixture",
      options: { seed: 407, startingHandSize: 9 },
      decks: {
        0: { main: ["100", "300", "500", "900", "950", "970", "975", "980", "800"] },
        1: { main: ["400", "600", "620", "700", "990", "800", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-cross-payload-follow-up-ended-handoff-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "500", from: "hand", to: "graveyard", collectEvent: "customEvent", eventCode: firstEventCode },
              { player: 1, code: "700", from: "hand", to: "graveyard", collectEvent: "customEvent", eventCode: secondEventCode },
            ],
            logMessage: "Cross payload follow-up chainEnded handoff starter resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "customEvent",
            triggerTiming: "if",
            triggerCode: firstEventCode,
            range: ["hand"],
            logMessage: "Cross payload follow-up chainEnded handoff turn trigger should not resolve",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "customEvent",
            triggerTiming: "if",
            triggerCode: secondEventCode,
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 1, code: "600", from: "hand", to: "graveyard" },
              { player: 1, code: "620", from: "hand", to: "graveyard" },
              { player: 0, code: "950", from: "hand", to: "graveyard" },
              { player: 0, code: "970", from: "hand", to: "graveyard" },
              { player: 0, code: "975", from: "hand", to: "graveyard" },
            ],
            logMessage: "Cross payload follow-up chainEnded handoff opponent trigger resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick",
            player: 0,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Cross payload follow-up chainEnded handoff turn open quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick",
            player: 0,
            code: "950",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross payload follow-up chainEnded handoff turn chain quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick",
            player: 0,
            code: "970",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 1 },
            moveCardsOnResolve: [{ player: 0, code: "980", from: "hand", to: "graveyard" }],
            logMessage: "Cross payload follow-up chainEnded handoff turn follow-up quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick",
            player: 0,
            code: "975",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross payload follow-up chainEnded handoff turn chainEnded response quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher",
            player: 0,
            code: "980",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            triggerTiming: "if",
            optional: false,
            range: ["graveyard"],
            oncePerTurn: true,
            logMessage: "Cross payload follow-up chainEnded handoff watcher resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick",
            player: 1,
            code: "600",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross payload follow-up chainEnded handoff opponent first chain quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick",
            player: 1,
            code: "620",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross payload follow-up chainEnded handoff opponent second chain quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick",
            player: 1,
            code: "990",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            logMessage: "Cross payload follow-up chainEnded handoff opponent open quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-handoff-starter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the initial open window restorable before creating follow-up chainEnded response-handoff later-payload trigger buckets",
            phase: "main1",
            windowId: 0,
            windowKind: "open",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 22, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-starter", count: 1 },
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", count: 1 },
              { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-starter", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", count: 1 },
                ],
              },
              turnGroup(0),
            ],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", triggerBucket: "turnOptional" },
              { type: "activateTrigger", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
              { type: "activateTrigger", player: 1, windowId: 0, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", triggerBucket: "opponentOptional" },
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick" },
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", "turnOptional", 0, "open"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 0, "open"),
              absentTriggerActivationGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", "opponentOptional", 0, "open"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", 0, "open"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", 0, "open"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", 0, "open"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", 0, "open"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the active turn optional follow-up chainEnded response-handoff bucket restorable while the later-payload opponent bucket waits behind it",
            phase: "main1",
            windowId: 1,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", eventName: "customEvent", eventCode: firstEventCode, triggerBucket: "turnOptional", eventCardUid: "p0-deck-500-2" },
              { player: 1, effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", eventName: "customEvent", eventCode: secondEventCode, triggerBucket: "opponentOptional", eventCardUid: "p1-deck-700-3" },
            ],
            pendingTriggerBuckets: [
              { player: 0, triggerBucket: "turnOptional" },
              { player: 1, triggerBucket: "opponentOptional" },
            ],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", triggerBucket: "turnOptional", count: 1 },
              { type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", triggerBucket: "turnOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", "turnOptional", 1, 1),
              triggerDeclineGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", "turnOptional", 1, 1),
            ],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
              { type: "activateTrigger", player: 1, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", triggerBucket: "opponentOptional" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 1, "triggerBucket"),
              absentTriggerActivationGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", "opponentOptional", 1, "triggerBucket"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", 1, "triggerBucket"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", 1, "triggerBucket"),
            ],
            locations: { graveyard: ["500", "700"], hand: ["100", "300", "900", "950", "970", "975", "980", "800", "400", "600", "620", "990", "800", "800"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the restored later-payload opponent optional follow-up chainEnded response-handoff bucket restorable before activation",
            phase: "main1",
            windowId: 2,
            windowKind: "triggerBucket",
            waitingFor: 1,
            chain: [],
            chainPasses: [],
            pendingTriggers: [{ player: 1, effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", eventName: "customEvent", eventCode: secondEventCode, triggerBucket: "opponentOptional", eventCardUid: "p1-deck-700-3", eventTriggerTiming: "if" }],
            pendingTriggerBuckets: [{ player: 1, triggerBucket: "opponentOptional" }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", triggerBucket: "opponentOptional", count: 1 },
              { type: "declineTrigger", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", triggerBucket: "opponentOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", "opponentOptional", 1, 2),
              triggerDeclineGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", "opponentOptional", 1, 2),
            ],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", triggerBucket: "turnOptional" },
              { type: "activateTrigger", player: 0, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
              { type: "activateEffect", player: 1, windowId: 2, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", "turnOptional", 2, "triggerBucket"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 2, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", 2, "triggerBucket"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps restored turn-player open-fast priority restorable before the follow-up chainEnded response-handoff open-fast effect starts a chain",
            phase: "main1",
            windowId: 3,
            windowKind: "open",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 14, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-starter", count: 1 },
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 3,
                windowKind: "open",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-starter", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", count: 1 },
                ],
              },
              turnGroup(3),
            ],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", triggerBucket: "turnOptional" },
              { type: "activateTrigger", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
              { type: "activateTrigger", player: 1, windowId: 3, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", triggerBucket: "opponentOptional" },
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick" },
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", "turnOptional", 3, "open"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 3, "open"),
              absentTriggerActivationGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", "opponentOptional", 3, "open"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", 3, "open"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", 3, "open"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", 3, "open"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick", 3, "open"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent response priority before the follow-up chainEnded response-handoff open-fast pass handoff",
            phase: "main1",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [{ player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" }],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 0, 1: 3 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", count: 1 },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 4,
                windowKind: "chainResponse",
                actions: [
                  { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", count: 1 },
                  { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", count: 1 },
                ],
              },
              chainPassGroup(1, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", 4),
              absentChainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", 4),
              absentChainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", 4),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick", 4, "chainResponse"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player response priority before chaining from the follow-up chainEnded response-handoff open-fast handoff",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [{ player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" }],
            chainPasses: [1],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 4, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", count: 1 },
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", count: 1 },
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 5,
                windowKind: "chainResponse",
                actions: [
                  { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", 5, "chainResponse"),
              absentChainEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", 5),
              absentChainEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", 5),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick", 5, "chainResponse"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent response priority after the turn player chains from the follow-up chainEnded response-handoff handoff",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 0, 1: 3 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", count: 1 },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 6,
                windowKind: "chainResponse",
                actions: [
                  { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", count: 1 },
                  { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", count: 1 },
                ],
              },
              chainPassGroup(1, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick" },
              { type: "activateTrigger", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
              { type: "activateTrigger", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", triggerBucket: "turnOptional" },
              { type: "activateTrigger", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", 6, "chainResponse"),
              absentChainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", 6),
              absentChainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", 6),
              absentChainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", 6),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick", 6, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 6, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", "turnOptional", 6, "chainResponse"),
              absentTriggerActivationGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", "opponentOptional", 6, "chainResponse"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player follow-up priority after the opponent responds to the follow-up chainEnded response-handoff chain",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
              { player: 1, effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", count: 1 },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 7,
                windowKind: "chainResponse",
                actions: [
                  { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick" },
              { type: "activateTrigger", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
              { type: "activateTrigger", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", triggerBucket: "turnOptional" },
              { type: "activateTrigger", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", 7, "chainResponse"),
              absentChainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", 7),
              absentChainEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", 7),
              absentChainEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", 7),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick", 7, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 7, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", "turnOptional", 7, "chainResponse"),
              absentTriggerActivationGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", "opponentOptional", 7, "chainResponse"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent follow-up priority before the final pass opens the response-handoff chainEnded trigger bucket",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
              { player: 1, effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" },
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", 1, 8),
              chainPassGroup(1, 1, 8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick" },
              { type: "activateTrigger", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
              { type: "activateTrigger", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", triggerBucket: "turnOptional" },
              { type: "activateTrigger", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", 8, "chainResponse"),
              absentChainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", 8),
              absentChainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", 8),
              absentChainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", 8),
              absentChainEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", 8),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-open-quick", 8, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 8, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", "turnOptional", 8, "chainResponse"),
              absentTriggerActivationGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", "opponentOptional", 8, "chainResponse"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro opens a chainEnded trigger bucket after the restored follow-up chain resolves",
            phase: "main1",
            windowId: 9,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [{ player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", eventName: "chainEnded", triggerBucket: "turnMandatory", eventTriggerTiming: "if" }],
            pendingTriggerBuckets: [{ player: 0, triggerBucket: "turnMandatory" }],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 1, 9)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick" },
              { type: "activateEffect", player: 1, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick" },
              { type: "declineTrigger", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", 9, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", 9, "triggerBucket"),
              {
                player: 0,
                label: "Trigger Declines",
                windowId: 9,
                windowKind: "triggerBucket",
                triggerBucket: { player: 0, triggerBucket: "turnMandatory" },
                actions: [{ type: "declineTrigger", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher" }],
              },
            ],
            locations: { graveyard: ["500", "700", "600", "620", "950", "970", "975", "980"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves the restored chainEnded trigger bucket before activation",
            phase: "main1",
            windowId: 9,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [{ player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", eventName: "chainEnded", triggerBucket: "turnMandatory", eventTriggerTiming: "if" }],
            pendingTriggerBuckets: [{ player: 0, triggerBucket: "turnMandatory" }],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [{ type: "activateTrigger", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory", count: 1 }],
            legalActionGroups: [triggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 1, 9)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick" },
              { type: "activateEffect", player: 1, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick" },
              { type: "declineTrigger", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", 9, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", 9, "triggerBucket"),
              {
                player: 0,
                label: "Trigger Declines",
                windowId: 9,
                windowKind: "triggerBucket",
                triggerBucket: { player: 0, triggerBucket: "turnMandatory" },
                actions: [{ type: "declineTrigger", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher" }],
              },
            ],
            locations: { graveyard: ["500", "700", "600", "620", "950", "970", "975", "980"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent response priority before the opponent responds to the chainEnded trigger chain",
            phase: "main1",
            windowId: 10,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", sourceUid: "p0-deck-980-7" }],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 10, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", 1, 10),
              chainPassGroup(1, 1, 10),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" },
              { type: "activateTrigger", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", 10, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", 10, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", 10, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", 10, "chainResponse"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", 10, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 10, "chainResponse"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro hands restored chainEnded trigger-chain response priority back to the turn player after the opponent responds",
            phase: "main1",
            windowId: 11,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", sourceUid: "p0-deck-980-7" },
              { player: 1, effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", sourceUid: "p1-deck-620-2" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 11, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", 1, 11),
              chainPassGroup(0, 1, 11),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick" },
              { type: "activateEffect", player: 1, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick" },
              { type: "activateTrigger", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", 11, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", 11, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", 11, "chainResponse"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", 11, "chainResponse"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", 11, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 11, "chainResponse"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player response priority before the turn player responds to the returned chainEnded trigger chain",
            phase: "main1",
            windowId: 11,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", sourceUid: "p0-deck-980-7" },
              { player: 1, effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", sourceUid: "p1-deck-620-2" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 11, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", 1, 11),
              chainPassGroup(0, 1, 11),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick" },
              { type: "activateEffect", player: 1, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" },
              { type: "activateEffect", player: 1, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick" },
              { type: "activateTrigger", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", 11, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", 11, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", 11, "chainResponse"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", 11, "chainResponse"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", 11, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 11, "chainResponse"),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves restored chainEnded trigger chains after the turn player responds to the opponent response",
        phase: "main1",
        windowId: 12,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        legalActionCounts: { 0: 11, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 12, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 12, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 12,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-starter", count: 1 }],
          },
          turnGroup(12),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick" },
          { type: "activateEffect", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick" },
          { type: "activateEffect", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick" },
          { type: "activateTrigger", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", triggerBucket: "turnMandatory" },
          { type: "activateTrigger", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", triggerBucket: "turnOptional" },
          { type: "activateTrigger", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", triggerBucket: "opponentOptional" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-open-quick", 12, "open"),
          absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-quick", 12, "open"),
          absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-follow-up-quick", 12, "open"),
          absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-chain-ended-response-quick", 12, "open"),
          absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-first-chain-quick", 12, "open"),
          absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-second-chain-quick", 12, "open"),
          absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-chain-ended-watcher", "turnMandatory", 12, "open"),
          absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-handoff-turn-trigger", "turnOptional", 12, "open"),
          absentTriggerActivationGroup(1, "fixture-cross-payload-follow-up-ended-handoff-opponent-trigger", "opponentOptional", 12, "open"),
        ],
        locations: { graveyard: ["500", "700", "600", "620", "950", "970", "975", "980"], hand: ["100", "300", "900", "800", "400", "990", "800", "800"] },
        logIncludes: [
          "Cross payload follow-up chainEnded handoff starter resolved",
          "Cross payload follow-up chainEnded handoff opponent trigger resolved",
          "Cross payload follow-up chainEnded handoff turn follow-up quick resolved",
          "Cross payload follow-up chainEnded handoff turn chainEnded response quick resolved",
          "Cross payload follow-up chainEnded handoff opponent second chain quick resolved",
          "Cross payload follow-up chainEnded handoff watcher resolved",
          "Cross payload follow-up chainEnded handoff opponent first chain quick resolved",
          "Cross payload follow-up chainEnded handoff turn chain quick resolved",
          "Cross payload follow-up chainEnded handoff turn open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
