import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  openEffectGroup,
  summonGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution SEGOC pass handoff chain resolution fixture", () => {
  it("resolves trigger-player post-handoff chains after the opponent passes", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Handoff Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Turn Chain Handoff Resolution Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Chain Handoff Resolution Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Opponent Chain Handoff Resolution Quick", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Chain Handoff Resolution Optional", kind: "monster", attack: 1200, defense: 1200 },
      { code: "700", name: "Chain Handoff Resolution Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Filler", kind: "monster", attack: 800, defense: 800 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution segoc pass handoff chain resolution fixture",
      options: { seed: 289, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "500", "700"] },
        1: { main: ["400", "800", "800", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-chain-handoff-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 1, code: "400", from: "hand", to: "graveyard" },
            ],
            logMessage: "Chain handoff resolution starter resolved",
          },
          {
            id: "fixture-chain-handoff-resolution-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Chain handoff resolution mandatory resolved",
          },
          {
            id: "fixture-chain-handoff-resolution-optional",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain handoff resolution optional resolved",
          },
          {
            id: "fixture-chain-handoff-resolution-turn-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Turn quick after chain-created SEGOC handoff resolved",
          },
          {
            id: "fixture-chain-handoff-resolution-opponent-quick",
            player: 1,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Opponent quick after chain-created SEGOC handoff should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-handoff-resolution-starter" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-handoff-resolution-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-handoff-resolution-optional" })),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps opponent response priority restorable before pass handoff returns to the trigger player",
            phase: "main1",
            windowId: 3,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-resolution-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-chain-handoff-resolution-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "fixture-chain-handoff-resolution-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 3, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(1, "fixture-chain-handoff-resolution-opponent-quick", 1, 3), chainPassGroup(1, 1, 3)],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "fixture-chain-handoff-resolution-turn-quick" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "fixture-chain-handoff-resolution-turn-quick", 3)],
            locations: { graveyard: ["700", "200", "400"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
            logIncludes: ["Chain handoff resolution starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns chain-created SEGOC response priority to the trigger player after the opponent passes with a response available",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-resolution-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-chain-handoff-resolution-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [1],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-handoff-resolution-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(0, "fixture-chain-handoff-resolution-turn-quick", 1, 4), chainPassGroup(0, 1, 4)],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-handoff-resolution-opponent-quick" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "fixture-chain-handoff-resolution-opponent-quick", 4)],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-handoff-resolution-turn-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps returned trigger-player response priority restorable before the trigger player chains",
            phase: "main1",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-resolution-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-chain-handoff-resolution-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
            ],
            chainPasses: [1],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-handoff-resolution-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(0, "fixture-chain-handoff-resolution-turn-quick", 1, 4), chainPassGroup(0, 1, 4)],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-handoff-resolution-opponent-quick" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "fixture-chain-handoff-resolution-opponent-quick", 4)],
            locations: { graveyard: ["700", "200", "400"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
            logIncludes: ["Chain handoff resolution starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro gives the opponent another chain-response window after the trigger player chains from chain-created SEGOC pass handoff",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-resolution-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-chain-handoff-resolution-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-chain-handoff-resolution-turn-quick", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-handoff-resolution-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(1, "fixture-chain-handoff-resolution-opponent-quick", 1, 5), chainPassGroup(1, 1, 5)],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-handoff-resolution-turn-quick" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "fixture-chain-handoff-resolution-turn-quick", 5)],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the opponent final response pass restorable before resolving the chain-created SEGOC chain",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-handoff-resolution-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-chain-handoff-resolution-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4", eventTriggerTiming: "if" },
              { player: 0, effectId: "fixture-chain-handoff-resolution-turn-quick", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-handoff-resolution-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [chainEffectGroup(1, "fixture-chain-handoff-resolution-opponent-quick", 1, 5), chainPassGroup(1, 1, 5)],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-handoff-resolution-turn-quick" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "fixture-chain-handoff-resolution-turn-quick", 5)],
            locations: { graveyard: ["700", "200", "400"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
            logIncludes: ["Chain handoff resolution starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro resolves the chain-created SEGOC trigger chain after the opponent passes on the trigger player's added chain link",
            phase: "main1",
            windowId: 6,
            windowKind: "open",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 9, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "fixture-chain-handoff-resolution-starter", count: 1 },
              { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 6, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 6, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 6,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "fixture-chain-handoff-resolution-starter", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "300", location: "hand" },
                { type: "normalSummon", player: 0, code: "500", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "300", location: "hand" },
                { type: "setMonster", player: 0, code: "500", location: "hand" },
              ], 1, 6),
              turnGroup(6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "fixture-chain-handoff-resolution-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "fixture-chain-handoff-resolution-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 6, windowKind: "open", effectId: "fixture-chain-handoff-resolution-optional" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-handoff-resolution-turn-quick", 6, "open"),
              absentWindowEffectGroup(1, "fixture-chain-handoff-resolution-opponent-quick", 6, "open"),
              absentTriggerActivationGroup(0, "fixture-chain-handoff-resolution-optional", "turnOptional", 6, "open"),
            ],
            locations: { graveyard: ["700", "200", "400"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
            logIncludes: [
              "Turn quick after chain-created SEGOC handoff resolved",
              "Chain handoff resolution optional resolved",
              "Chain handoff resolution mandatory resolved",
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro final state returns to open priority after the opponent passes the trigger player's post-handoff chain link",
        phase: "main1",
        windowId: 6,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "fixture-chain-handoff-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 6, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 6, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          openEffectGroup(0, "fixture-chain-handoff-resolution-starter", 1, 6),
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
          ], 1, 6),
          turnGroup(6),
        ],
        locations: { graveyard: ["700", "200", "400"], hand: ["100", "300", "500", "800", "800", "800", "800"] },
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "fixture-chain-handoff-resolution-turn-quick" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "fixture-chain-handoff-resolution-opponent-quick" },
          { type: "activateTrigger", player: 0, windowId: 6, windowKind: "open", effectId: "fixture-chain-handoff-resolution-optional" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-handoff-resolution-turn-quick", 6, "open"),
          absentWindowEffectGroup(1, "fixture-chain-handoff-resolution-opponent-quick", 6, "open"),
          absentTriggerActivationGroup(0, "fixture-chain-handoff-resolution-optional", "turnOptional", 6, "open"),
        ],
        logIncludes: [
          "Chain handoff resolution starter resolved",
          "Turn quick after chain-created SEGOC handoff resolved",
          "Chain handoff resolution optional resolved",
          "Chain handoff resolution mandatory resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
