import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity open fast-effect pass handoff opponent response turn response chain-limit fixture", () => {
  it("applies one-chain limits after the turn player responds to an opponent open fast-effect handoff response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Open Handoff Opponent Turn Limit Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "200", name: "Open Handoff Opponent Turn Limit First Turn Chain Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Open Handoff Opponent Turn Limit Opponent First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Open Handoff Opponent Turn Limit Chain Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Open Handoff Opponent Turn Limit Opponent Blocked Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Open Handoff Opponent Turn Limit Followup", kind: "monster", attack: 1000, defense: 1000 },
      { code: "800", name: "Open Handoff Opponent Turn Limit Opponent Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "900", name: "Open Handoff Opponent Turn Limit Filler", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "open fast pass handoff opponent response turn response chain limit fixture",
      options: { seed: 350, startingHandSize: 4 },
      decks: {
        0: { main: ["100", "200", "500", "700"] },
        1: { main: ["300", "600", "800", "900"] },
      },
      setup: {
        effects: [
          {
            id: "open-fast-handoff-opponent-turn-limit-open-quick",
            player: 0,
            code: "100",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Open fast handoff opponent turn limit open quick resolved",
          },
          {
            id: "open-fast-handoff-opponent-turn-limit-first-turn-chain-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Open fast handoff opponent turn limit first turn chain quick resolved",
          },
          {
            id: "open-fast-handoff-opponent-turn-limit-chain-limiter",
            player: 0,
            code: "500",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: false, allowPlayer: 0 },
            logMessage: "Open fast handoff opponent turn limit chain limiter resolved",
          },
          {
            id: "open-fast-handoff-opponent-turn-limit-followup",
            player: 0,
            code: "700",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Open fast handoff opponent turn limit followup should not resolve",
          },
          {
            id: "open-fast-handoff-opponent-turn-limit-opponent-first",
            player: 1,
            code: "300",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Open fast handoff opponent turn limit opponent first quick resolved",
          },
          {
            id: "open-fast-handoff-opponent-turn-limit-opponent-blocked",
            player: 1,
            code: "600",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Open fast handoff opponent turn limit opponent blocked quick should not resolve",
          },
          {
            id: "open-fast-handoff-opponent-turn-limit-opponent-open",
            player: 1,
            code: "800",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            logMessage: "Open fast handoff opponent turn limit opponent open quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "open-fast-handoff-opponent-turn-limit-open-quick" })),
        makeScriptedStep(makeResponseSelector("passChain", 1)),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "open-fast-handoff-opponent-turn-limit-first-turn-chain-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "open-fast-handoff-opponent-turn-limit-opponent-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "open-fast-handoff-opponent-turn-limit-chain-limiter" }), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro applies one-chain SetChainLimit restrictions after the turn player responds to an opponent open fast-effect pass-handoff response",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "open-fast-handoff-opponent-turn-limit-open-quick", sourceUid: "p0-deck-100-0" },
              { player: 0, effectId: "open-fast-handoff-opponent-turn-limit-first-turn-chain-quick", sourceUid: "p0-deck-200-1" },
              { player: 1, effectId: "open-fast-handoff-opponent-turn-limit-opponent-first", sourceUid: "p1-deck-300-0" },
              { player: 0, effectId: "open-fast-handoff-opponent-turn-limit-chain-limiter", sourceUid: "p0-deck-500-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 4 }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "open-fast-handoff-opponent-turn-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "open-fast-handoff-opponent-turn-limit-followup", 1, 5),
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "open-fast-handoff-opponent-turn-limit-opponent-blocked" },
            ],
            absentLegalActionGroups: [absentChainEffectGroup(1, "open-fast-handoff-opponent-turn-limit-opponent-blocked", 5)],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the open fast-effect turn-response SetChainLimit window restorable before the allowed turn player passes",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "open-fast-handoff-opponent-turn-limit-open-quick", sourceUid: "p0-deck-100-0" },
              { player: 0, effectId: "open-fast-handoff-opponent-turn-limit-first-turn-chain-quick", sourceUid: "p0-deck-200-1" },
              { player: 1, effectId: "open-fast-handoff-opponent-turn-limit-opponent-first", sourceUid: "p1-deck-300-0" },
              { player: 0, effectId: "open-fast-handoff-opponent-turn-limit-chain-limiter", sourceUid: "p0-deck-500-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 4 }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "open-fast-handoff-opponent-turn-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "open-fast-handoff-opponent-turn-limit-followup", 1, 5),
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "open-fast-handoff-opponent-turn-limit-opponent-blocked" },
            ],
            absentLegalActionGroups: [absentChainEffectGroup(1, "open-fast-handoff-opponent-turn-limit-opponent-blocked", 5)],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears one-chain limits and returns to turn-player open priority after the allowed turn player passes the open fast-effect opponent-response handoff chain",
        phase: "main1",
        windowId: 6,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        legalActionCounts: { 0: 10, 1: 0 },
        legalActionGroupCounts: { 0: 2, 1: 0 },
        legalActions: [
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "200", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 6, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "200", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 6, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 6, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 6, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "200", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "normalSummon", player: 0, code: "700", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "200", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "700", location: "hand" },
          ], 1, 6),
          turnGroup(6),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "open-fast-handoff-opponent-turn-limit-open-quick" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "open-fast-handoff-opponent-turn-limit-first-turn-chain-quick" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "open-fast-handoff-opponent-turn-limit-chain-limiter" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "open-fast-handoff-opponent-turn-limit-followup" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "open-fast-handoff-opponent-turn-limit-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "open-fast-handoff-opponent-turn-limit-opponent-blocked" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "open-fast-handoff-opponent-turn-limit-opponent-open" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "open-fast-handoff-opponent-turn-limit-open-quick", 6, "open"),
          absentWindowEffectGroup(0, "open-fast-handoff-opponent-turn-limit-first-turn-chain-quick", 6, "open"),
          absentWindowEffectGroup(0, "open-fast-handoff-opponent-turn-limit-chain-limiter", 6, "open"),
          absentWindowEffectGroup(0, "open-fast-handoff-opponent-turn-limit-followup", 6, "open"),
          absentWindowEffectGroup(1, "open-fast-handoff-opponent-turn-limit-opponent-first", 6, "open"),
          absentWindowEffectGroup(1, "open-fast-handoff-opponent-turn-limit-opponent-blocked", 6, "open"),
          absentWindowEffectGroup(1, "open-fast-handoff-opponent-turn-limit-opponent-open", 6, "open"),
        ],
        logIncludes: [
          "Open fast handoff opponent turn limit chain limiter resolved",
          "Open fast handoff opponent turn limit opponent first quick resolved",
          "Open fast handoff opponent turn limit first turn chain quick resolved",
          "Open fast handoff opponent turn limit open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
