import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentSummonGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity post-Link-Summon open fast-effect handoff turn-response until-chain-end limit fixture", () => {
  it("keeps until-chain-end limits after the turn player responds to a post-Link-Summon pass handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Post Link Until Material A", kind: "monster", attack: 1000, defense: 1000 },
      { code: "200", name: "Post Link Until Material B", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Post Link Until Turn Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Post Link Until Turn Chain Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Post Link Until Turn Followup Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Post Link Until Opponent Blocked Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "900", name: "Post Link Until Link Monster", kind: "extra", typeFlags: 0x4000001, level: 2, attack: 2000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "post link summon open fast pass handoff turn response until-chain-end limit fixture",
      options: { seed: 442, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "600", "700"], extra: ["900"] },
        1: { main: ["400"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "100", from: "hand", to: "monsterZone", position: "faceUpAttack" },
          { player: 0, code: "200", from: "hand", to: "monsterZone", position: "faceUpAttack" },
          { player: 0, code: "300", from: "hand", to: "graveyard" },
          { player: 0, code: "600", from: "hand", to: "graveyard" },
          { player: 0, code: "700", from: "hand", to: "graveyard" },
          { player: 1, code: "400", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "post-link-summon-until-turn-open-quick",
            player: 0,
            code: "300",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "open",
            oncePerTurn: true,
            logMessage: "Post Link Summon until turn open quick resolved",
          },
          {
            id: "post-link-summon-until-turn-chain-limiter",
            player: 0,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            oncePerTurn: true,
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 0 },
            logMessage: "Post Link Summon until turn chain limiter resolved",
          },
          {
            id: "post-link-summon-until-turn-followup",
            player: 0,
            code: "700",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Post Link Summon until turn followup should not resolve",
          },
          {
            id: "post-link-summon-until-opponent-blocked",
            player: 1,
            code: "400",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Post Link Summon until opponent blocked should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("linkSummon", 0, { code: "900", location: "extraDeck", materialUids: ["p0-deck-100-0", "p0-deck-200-1"] }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro exposes Link Summons beside turn-player open fast effects before the until-chain-end pass-handoff fixture begins",
            phase: "main1",
            windowId: 0,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            chainLimits: [],
            locations: { monsterZone: ["100", "200"], graveyard: ["300", "600", "700", "400"] },
            cards: [
              { uid: "p0-deck-100-0", code: "100", location: "monsterZone", position: "faceUpAttack", faceUp: true },
              { uid: "p0-deck-200-1", code: "200", location: "monsterZone", position: "faceUpAttack", faceUp: true },
            ],
            legalActionCounts: { 0: 6, 1: 0 },
            legalActionGroupCounts: { 0: 4, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-link-summon-until-turn-open-quick", count: 1 },
              { type: "changePosition", player: 0, windowId: 0, windowKind: "open", code: "100", location: "monsterZone", position: "faceUpDefense", count: 1 },
              { type: "changePosition", player: 0, windowId: 0, windowKind: "open", code: "200", location: "monsterZone", position: "faceUpDefense", count: 1 },
              { type: "linkSummon", player: 0, windowId: 0, windowKind: "open", code: "900", location: "extraDeck", materialUids: ["p0-deck-100-0", "p0-deck-200-1"], count: 1 },
              { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-link-summon-until-turn-open-quick", count: 1 }],
              },
              {
                player: 0,
                label: "Actions",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [
                  { type: "changePosition", player: 0, windowId: 0, windowKind: "open", code: "100", location: "monsterZone", position: "faceUpDefense", count: 1 },
                  { type: "changePosition", player: 0, windowId: 0, windowKind: "open", code: "200", location: "monsterZone", position: "faceUpDefense", count: 1 },
                ],
              },
              summonGroup([{ type: "linkSummon", player: 0, code: "900", location: "extraDeck", materialUids: ["p0-deck-100-0", "p0-deck-200-1"] }], 1, 0),
              turnGroup(0),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-link-summon-until-turn-chain-limiter" },
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "post-link-summon-until-turn-followup" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "post-link-summon-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "post-link-summon-until-turn-chain-limiter", 0, "open"),
              absentWindowEffectGroup(0, "post-link-summon-until-turn-followup", 0, "open"),
              absentWindowEffectGroup(1, "post-link-summon-until-opponent-blocked", 0, "open"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns triggerless Link Summons to turn-player open fast-effect priority before until-chain-end limits can be created",
            phase: "main1",
            windowId: 1,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            chainLimits: [],
            locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "600", "700", "400"] },
            cards: [
              { uid: "p0-extraDeck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
              { uid: "p0-deck-100-0", code: "100", location: "graveyard" },
              { uid: "p0-deck-200-1", code: "200", location: "graveyard" },
            ],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-link-summon-until-turn-open-quick", count: 1 },
              { type: "changePhase", player: 0, windowId: 1, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 1, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 1,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-link-summon-until-turn-open-quick", count: 1 }],
              },
              turnGroup(1),
            ],
            absentLegalActions: [
              { type: "linkSummon", player: 0, windowId: 1, windowKind: "open", code: "900", location: "extraDeck" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-link-summon-until-turn-chain-limiter" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "post-link-summon-until-turn-followup" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "post-link-summon-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentSummonGroup({ type: "linkSummon", player: 0, code: "900", location: "extraDeck" }, 1),
              absentWindowEffectGroup(0, "post-link-summon-until-turn-chain-limiter", 1, "open"),
              absentWindowEffectGroup(0, "post-link-summon-until-turn-followup", 1, "open"),
              absentWindowEffectGroup(1, "post-link-summon-until-opponent-blocked", 1, "open"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "post-link-summon-until-turn-open-quick" })),
        makeScriptedStep(makeResponseSelector("passChain", 1)),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "post-link-summon-until-turn-chain-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player pass-handoff priority before the post-Link-Summon until-chain-end limiter is chained",
            phase: "main1",
            windowId: 3,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 0, effectId: "post-link-summon-until-turn-open-quick", sourceUid: "p0-deck-300-2" }],
            chainPasses: [1],
            chainLimits: [],
            locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "600", "700", "400"] },
            cards: [
              { uid: "p0-extraDeck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
              { uid: "p0-deck-100-0", code: "100", location: "graveyard" },
              { uid: "p0-deck-200-1", code: "200", location: "graveyard" },
            ],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-link-summon-until-turn-chain-limiter", count: 1 },
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-link-summon-until-turn-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 3, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 3,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-link-summon-until-turn-chain-limiter", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-link-summon-until-turn-followup", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 3),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "post-link-summon-until-turn-open-quick" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "post-link-summon-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-link-summon-until-turn-open-quick", 3),
              absentChainEffectGroup(1, "post-link-summon-until-opponent-blocked", 3),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro applies SetChainLimitTillChainEnd restrictions when the turn player responds from a post-Link-Summon pass-handoff window",
            phase: "main1",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "post-link-summon-until-turn-open-quick", sourceUid: "p0-deck-300-2" },
              { player: 0, effectId: "post-link-summon-until-turn-chain-limiter", sourceUid: "p0-deck-600-3" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "600", "700", "400"] },
            cards: [
              { uid: "p0-extraDeck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
              { uid: "p0-deck-100-0", code: "100", location: "graveyard" },
              { uid: "p0-deck-200-1", code: "200", location: "graveyard" },
            ],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-link-summon-until-turn-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "post-link-summon-until-turn-followup", 1, 4),
              chainPassGroup(0, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-link-summon-until-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-link-summon-until-turn-chain-limiter" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "post-link-summon-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-link-summon-until-turn-open-quick", 4),
              absentChainEffectGroup(0, "post-link-summon-until-turn-chain-limiter", 4),
              absentChainEffectGroup(1, "post-link-summon-until-opponent-blocked", 4),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the post-Link-Summon SetChainLimitTillChainEnd response window restorable before the allowed player passes",
            phase: "main1",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "post-link-summon-until-turn-open-quick", sourceUid: "p0-deck-300-2" },
              { player: 0, effectId: "post-link-summon-until-turn-chain-limiter", sourceUid: "p0-deck-600-3" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "600", "700", "400"] },
            cards: [
              { uid: "p0-extraDeck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
              { uid: "p0-deck-100-0", code: "100", location: "graveyard" },
              { uid: "p0-deck-200-1", code: "200", location: "graveyard" },
            ],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-link-summon-until-turn-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "post-link-summon-until-turn-followup", 1, 4),
              chainPassGroup(0, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-link-summon-until-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "post-link-summon-until-turn-chain-limiter" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "post-link-summon-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "post-link-summon-until-turn-open-quick", 4),
              absentChainEffectGroup(0, "post-link-summon-until-turn-chain-limiter", 4),
              absentChainEffectGroup(1, "post-link-summon-until-opponent-blocked", 4),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears until-chain-end limits and returns post-Link-Summon handoff chains to turn-player open priority after the allowed player passes",
        phase: "main1",
        windowId: 5,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "600", "700", "400"] },
        cards: [
          { uid: "p0-extraDeck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
          { uid: "p0-deck-100-0", code: "100", location: "graveyard" },
          { uid: "p0-deck-200-1", code: "200", location: "graveyard" },
        ],
        legalActionCounts: { 0: 2, 1: 0 },
        legalActionGroupCounts: { 0: 1, 1: 0 },
        legalActions: [
          { type: "changePhase", player: 0, windowId: 5, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 5, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [turnGroup(5)],
        absentLegalActions: [
          { type: "linkSummon", player: 0, windowId: 5, windowKind: "open", code: "900", location: "extraDeck" },
          { type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "post-link-summon-until-turn-open-quick" },
          { type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "post-link-summon-until-turn-chain-limiter" },
          { type: "activateEffect", player: 0, windowId: 5, windowKind: "open", effectId: "post-link-summon-until-turn-followup" },
          { type: "activateEffect", player: 1, windowId: 5, windowKind: "open", effectId: "post-link-summon-until-opponent-blocked" },
        ],
        absentLegalActionGroups: [
          absentSummonGroup({ type: "linkSummon", player: 0, code: "900", location: "extraDeck" }, 5),
          absentWindowEffectGroup(0, "post-link-summon-until-turn-open-quick", 5, "open"),
          absentWindowEffectGroup(0, "post-link-summon-until-turn-chain-limiter", 5, "open"),
          absentWindowEffectGroup(0, "post-link-summon-until-turn-followup", 5, "open"),
          absentWindowEffectGroup(1, "post-link-summon-until-opponent-blocked", 5, "open"),
        ],
        logIncludes: [
          "Post Link Summon until turn chain limiter resolved",
          "Post Link Summon until turn open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
