import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity end turn chain-response pass-handoff chain-limit fixture", () => {
  it("applies one-chain limits after the previous turn player chains from an End Turn chain-response handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "End Turn Response Handoff Limit Previous Followup", kind: "monster", attack: 1000, defense: 1000 },
      { code: "200", name: "End Turn Response Handoff Limit Next Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "End Turn Response Handoff Limit Next Blocked Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "End Turn Response Handoff Limit Previous First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "End Turn Response Handoff Limit Previous Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "End Turn Response Handoff Limit Next Filler", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "end turn open fast chain response pass handoff chain limit fixture",
      options: { seed: 523, startingHandSize: 3 },
      decks: {
        0: { main: ["400", "500", "100"] },
        1: { main: ["200", "300", "600"] },
      },
      setup: {
        effects: [
          {
            id: "end-turn-response-handoff-limit-next-open-quick",
            player: 1,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            oncePerTurn: true,
            logMessage: "End Turn response handoff limit next open quick resolved",
          },
          {
            id: "end-turn-response-handoff-limit-next-blocked",
            player: 1,
            code: "300",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "End Turn response handoff limit next blocked quick should not resolve",
          },
          {
            id: "end-turn-response-handoff-limit-previous-first",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "End Turn response handoff limit previous first quick resolved",
          },
          {
            id: "end-turn-response-handoff-limit-previous-limiter",
            player: 0,
            code: "500",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            chainLimitOnTarget: { untilChainEnd: false, allowPlayer: 0 },
            logMessage: "End Turn response handoff limit previous limiter resolved",
          },
          {
            id: "end-turn-response-handoff-limit-previous-followup",
            player: 0,
            code: "100",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "End Turn response handoff limit previous followup should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("endTurn", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the previous turn player's final open fast-effect window restorable before End Turn hands priority to the next turn player",
            windowId: 0,
            windowKind: "open",
            phase: "main1",
            turnPlayer: 0,
            turn: 1,
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 8, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "400", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "400", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              summonGroup([
                { type: "normalSummon", player: 0, code: "400", location: "hand" },
                { type: "normalSummon", player: 0, code: "500", location: "hand" },
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "400", location: "hand" },
                { type: "setMonster", player: 0, code: "500", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
              ], 1, 0),
              {
                player: 0,
                label: "Turn",
                windowId: 0,
                windowKind: "open",
                actions: [
                  { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
                  { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
                ],
              },
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "end-turn-response-handoff-limit-next-open-quick" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "end-turn-response-handoff-limit-next-blocked" },
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "end-turn-response-handoff-limit-previous-first" },
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "end-turn-response-handoff-limit-previous-limiter" },
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "end-turn-response-handoff-limit-previous-followup" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(1, "end-turn-response-handoff-limit-next-open-quick", 0, "open"),
              absentWindowEffectGroup(1, "end-turn-response-handoff-limit-next-blocked", 0, "open"),
              absentWindowEffectGroup(0, "end-turn-response-handoff-limit-previous-first", 0, "open"),
              absentWindowEffectGroup(0, "end-turn-response-handoff-limit-previous-limiter", 0, "open"),
              absentWindowEffectGroup(0, "end-turn-response-handoff-limit-previous-followup", 0, "open"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro opens the next turn player's open fast-effect window after End Turn before chain-response handoff limits apply",
            windowId: 1,
            windowKind: "open",
            phase: "main1",
            turnPlayer: 1,
            turn: 2,
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 0, 1: 9 },
            legalActionGroupCounts: { 0: 0, 1: 3 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "end-turn-response-handoff-limit-next-open-quick", count: 1 },
              { type: "normalSummon", player: 1, windowId: 1, windowKind: "open", code: "200", location: "hand", count: 1 },
              { type: "normalSummon", player: 1, windowId: 1, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 1, windowId: 1, windowKind: "open", code: "600", location: "hand", count: 1 },
              { type: "setMonster", player: 1, windowId: 1, windowKind: "open", code: "200", location: "hand", count: 1 },
              { type: "setMonster", player: 1, windowId: 1, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 1, windowId: 1, windowKind: "open", code: "600", location: "hand", count: 1 },
              { type: "changePhase", player: 1, windowId: 1, windowKind: "open", count: 1 },
              { type: "endTurn", player: 1, windowId: 1, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 1,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "end-turn-response-handoff-limit-next-open-quick", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 1, code: "200", location: "hand" },
                { type: "normalSummon", player: 1, code: "300", location: "hand" },
                { type: "normalSummon", player: 1, code: "600", location: "hand" },
                { type: "setMonster", player: 1, code: "200", location: "hand" },
                { type: "setMonster", player: 1, code: "300", location: "hand" },
                { type: "setMonster", player: 1, code: "600", location: "hand" },
              ], 1, 1),
              {
                player: 1,
                label: "Turn",
                windowId: 1,
                windowKind: "open",
                actions: [
                  { type: "changePhase", player: 1, windowId: 1, windowKind: "open", count: 1 },
                  { type: "endTurn", player: 1, windowId: 1, windowKind: "open", count: 1 },
                ],
              },
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "end-turn-response-handoff-limit-next-blocked" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "end-turn-response-handoff-limit-previous-first" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "end-turn-response-handoff-limit-previous-limiter" },
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "end-turn-response-handoff-limit-previous-followup" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(1, "end-turn-response-handoff-limit-next-blocked", 1, "open"),
              absentWindowEffectGroup(0, "end-turn-response-handoff-limit-previous-first", 1, "open"),
              absentWindowEffectGroup(0, "end-turn-response-handoff-limit-previous-limiter", 1, "open"),
              absentWindowEffectGroup(0, "end-turn-response-handoff-limit-previous-followup", 1, "open"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "end-turn-response-handoff-limit-next-open-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "end-turn-response-handoff-limit-previous-first" })),
        makeScriptedStep(makeResponseSelector("passChain", 1)),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "end-turn-response-handoff-limit-previous-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro restores previous-turn-player priority before that player applies a one-chain limit to the End Turn chain-response handoff",
            windowId: 4,
            windowKind: "chainResponse",
            phase: "main1",
            turnPlayer: 1,
            turn: 2,
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 1, effectId: "end-turn-response-handoff-limit-next-open-quick", sourceUid: "p1-deck-200-0" },
              { player: 0, effectId: "end-turn-response-handoff-limit-previous-first", sourceUid: "p0-deck-400-0" },
            ],
            chainPasses: [1],
            chainLimits: [],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "end-turn-response-handoff-limit-previous-limiter", count: 1 },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "end-turn-response-handoff-limit-previous-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 4,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "end-turn-response-handoff-limit-previous-limiter", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "end-turn-response-handoff-limit-previous-followup", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "end-turn-response-handoff-limit-next-open-quick" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "end-turn-response-handoff-limit-next-blocked" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "end-turn-response-handoff-limit-previous-first" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(1, "end-turn-response-handoff-limit-next-open-quick", 4, "chainResponse"),
              absentChainEffectGroup(1, "end-turn-response-handoff-limit-next-blocked", 4),
              absentChainEffectGroup(0, "end-turn-response-handoff-limit-previous-first", 4),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro applies one-chain SetChainLimit restrictions after the previous turn player chains from an End Turn chain-response handoff",
            windowId: 5,
            windowKind: "chainResponse",
            phase: "main1",
            turnPlayer: 1,
            turn: 2,
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 1, effectId: "end-turn-response-handoff-limit-next-open-quick", sourceUid: "p1-deck-200-0" },
              { player: 0, effectId: "end-turn-response-handoff-limit-previous-first", sourceUid: "p0-deck-400-0" },
              { player: 0, effectId: "end-turn-response-handoff-limit-previous-limiter", sourceUid: "p0-deck-500-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 3 }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "end-turn-response-handoff-limit-previous-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "end-turn-response-handoff-limit-previous-followup", 1, 5),
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "end-turn-response-handoff-limit-next-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "end-turn-response-handoff-limit-next-blocked", 5)],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the End Turn chain-response handoff SetChainLimit window restorable before the allowed previous turn player passes",
            windowId: 5,
            windowKind: "chainResponse",
            phase: "main1",
            turnPlayer: 1,
            turn: 2,
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 1, effectId: "end-turn-response-handoff-limit-next-open-quick", sourceUid: "p1-deck-200-0" },
              { player: 0, effectId: "end-turn-response-handoff-limit-previous-first", sourceUid: "p0-deck-400-0" },
              { player: 0, effectId: "end-turn-response-handoff-limit-previous-limiter", sourceUid: "p0-deck-500-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 3 }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "end-turn-response-handoff-limit-previous-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "end-turn-response-handoff-limit-previous-followup", 1, 5),
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "end-turn-response-handoff-limit-next-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "end-turn-response-handoff-limit-next-blocked", 5)],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears one-chain limits and returns to the new turn player's open priority after the allowed previous turn player passes the End Turn chain-response handoff chain",
        windowId: 6,
        windowKind: "open",
        phase: "main1",
        turnPlayer: 1,
        turn: 2,
        waitingFor: 1,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        legalActionCounts: { 0: 0, 1: 8 },
        legalActionGroupCounts: { 0: 0, 1: 2 },
        legalActions: [
          { type: "normalSummon", player: 1, windowId: 6, windowKind: "open", code: "200", location: "hand", count: 1 },
          { type: "normalSummon", player: 1, windowId: 6, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 1, windowId: 6, windowKind: "open", code: "600", location: "hand", count: 1 },
          { type: "setMonster", player: 1, windowId: 6, windowKind: "open", code: "200", location: "hand", count: 1 },
          { type: "setMonster", player: 1, windowId: 6, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 1, windowId: 6, windowKind: "open", code: "600", location: "hand", count: 1 },
          { type: "changePhase", player: 1, windowId: 6, windowKind: "open", count: 1 },
          { type: "endTurn", player: 1, windowId: 6, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          summonGroup([
            { type: "normalSummon", player: 1, code: "200", location: "hand" },
            { type: "normalSummon", player: 1, code: "300", location: "hand" },
            { type: "normalSummon", player: 1, code: "600", location: "hand" },
            { type: "setMonster", player: 1, code: "200", location: "hand" },
            { type: "setMonster", player: 1, code: "300", location: "hand" },
            { type: "setMonster", player: 1, code: "600", location: "hand" },
          ], 1, 6),
          {
            player: 1,
            label: "Turn",
            windowId: 6,
            windowKind: "open",
            actions: [
              { type: "changePhase", player: 1, windowId: 6, windowKind: "open", count: 1 },
              { type: "endTurn", player: 1, windowId: 6, windowKind: "open", count: 1 },
            ],
          },
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "end-turn-response-handoff-limit-next-open-quick" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "end-turn-response-handoff-limit-next-blocked" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "end-turn-response-handoff-limit-previous-first" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "end-turn-response-handoff-limit-previous-limiter" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "end-turn-response-handoff-limit-previous-followup" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(1, "end-turn-response-handoff-limit-next-open-quick", 6, "open"),
          absentWindowEffectGroup(1, "end-turn-response-handoff-limit-next-blocked", 6, "open"),
          absentWindowEffectGroup(0, "end-turn-response-handoff-limit-previous-first", 6, "open"),
          absentWindowEffectGroup(0, "end-turn-response-handoff-limit-previous-limiter", 6, "open"),
          absentWindowEffectGroup(0, "end-turn-response-handoff-limit-previous-followup", 6, "open"),
        ],
        logIncludes: [
          "End Turn response handoff limit previous limiter resolved",
          "End Turn response handoff limit previous first quick resolved",
          "End Turn response handoff limit next open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
