import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chainEnded open fast-effect chain-response until-chain-end followup pass-resolution fixture", () => {
  it("resolves after the allowed turn player passes a continued direct post-chainEnded until-chain-end response window", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Ended Direct Until Followup Pass Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Chain Ended Direct Until Followup Pass Solved Blocker", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Chain Ended Direct Until Followup Pass Cleanup", kind: "monster", attack: 1500, defense: 1600 },
      { code: "400", name: "Chain Ended Direct Until Followup Pass Open Quick", kind: "monster", attack: 1200, defense: 1200 },
      { code: "500", name: "Chain Ended Direct Until Followup Pass Opponent Limiter", kind: "monster", attack: 1100, defense: 1100 },
      { code: "600", name: "Chain Ended Direct Until Followup Pass Opponent Blocked", kind: "monster", attack: 900, defense: 900 },
      { code: "700", name: "Chain Ended Direct Until Followup Pass First Turn Chain", kind: "monster", attack: 800, defense: 800 },
      { code: "800", name: "Chain Ended Direct Until Followup Pass Final Turn Chain", kind: "monster", attack: 700, defense: 700 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "deferred chain ended open fast chain response until-chain-end limit followup pass resolution fixture",
      options: { seed: 641, startingHandSize: 6 },
      decks: {
        0: { main: ["100", "200", "300", "400", "700", "800"] },
        1: { main: ["500", "600"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "700", from: "hand", to: "graveyard" },
          { player: 0, code: "800", from: "hand", to: "graveyard" },
          { player: 1, code: "500", from: "hand", to: "graveyard" },
          { player: 1, code: "600", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "fixture-chain-ended-direct-until-followup-pass-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            logMessage: "Chain ended direct until followup pass starter resolved",
          },
          {
            id: "fixture-chain-ended-direct-until-followup-pass-solved-blocker",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainSolved",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain ended direct until followup pass solved blocker should not resolve",
          },
          {
            id: "fixture-chain-ended-direct-until-followup-pass-cleanup",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            moveCardsOnResolve: [
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "700", from: "graveyard", to: "hand" },
              { player: 0, code: "800", from: "graveyard", to: "hand" },
              { player: 1, code: "500", from: "graveyard", to: "hand" },
              { player: 1, code: "600", from: "graveyard", to: "hand" },
            ],
            logMessage: "Chain ended direct until followup pass cleanup resolved",
          },
          {
            id: "fixture-chain-ended-direct-until-followup-pass-open-fast",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended direct until followup pass open fast resolved",
          },
          {
            id: "fixture-chain-ended-direct-until-followup-pass-first-turn",
            player: 0,
            code: "700",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct until followup pass first turn chain resolved",
          },
          {
            id: "fixture-chain-ended-direct-until-followup-pass-final-turn",
            player: 0,
            code: "800",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct until followup pass final turn chain should not resolve",
          },
          {
            id: "fixture-chain-ended-direct-until-followup-pass-limiter",
            player: 1,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 0 },
            logMessage: "Chain ended direct until followup pass limiter resolved",
          },
          {
            id: "fixture-chain-ended-direct-until-followup-pass-opponent-blocked",
            player: 1,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Chain ended direct until followup pass opponent blocked should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-until-followup-pass-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-chain-ended-direct-until-followup-pass-solved-blocker" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-ended-direct-until-followup-pass-cleanup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-until-followup-pass-open-fast" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-direct-until-followup-pass-limiter" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-until-followup-pass-first-turn" })),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps SetChainLimitTillChainEnd active before the allowed turn player passes a continued direct post-chainEnded response chain",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-direct-until-followup-pass-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 1, effectId: "fixture-chain-ended-direct-until-followup-pass-limiter", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "fixture-chain-ended-direct-until-followup-pass-first-turn", sourceUid: "p0-deck-700-4" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chainLimits: [{ untilChainEnd: true }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-until-followup-pass-final-turn", count: 1 },
              { type: "passChain", player: 0, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-ended-direct-until-followup-pass-final-turn", 1, 6),
              chainPassGroup(0, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-until-followup-pass-open-fast" },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-until-followup-pass-first-turn" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-until-followup-pass-limiter" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-until-followup-pass-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-direct-until-followup-pass-open-fast", 6, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-direct-until-followup-pass-first-turn", 6),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-until-followup-pass-limiter", 6),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-until-followup-pass-opponent-blocked", 6),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears until-chain-end limits and resolves direct post-chainEnded continued response chains after the allowed turn player passes",
        phase: "main1",
        windowId: 7,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chainLimits: [],
        locations: { graveyard: ["200"], hand: ["100", "300", "400", "700", "800", "500", "600"] },
        legalActionCounts: { 0: 13, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-until-followup-pass-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 7, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 7, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 7, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 7, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 7,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-until-followup-pass-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "400", location: "hand" },
            { type: "normalSummon", player: 0, code: "700", location: "hand" },
            { type: "normalSummon", player: 0, code: "800", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "400", location: "hand" },
            { type: "setMonster", player: 0, code: "700", location: "hand" },
            { type: "setMonster", player: 0, code: "800", location: "hand" },
          ], 1, 7),
          turnGroup(7),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-until-followup-pass-open-fast" },
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-until-followup-pass-first-turn" },
          { type: "activateEffect", player: 0, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-until-followup-pass-final-turn" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-until-followup-pass-limiter" },
          { type: "activateEffect", player: 1, windowId: 7, windowKind: "open", effectId: "fixture-chain-ended-direct-until-followup-pass-opponent-blocked" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-until-followup-pass-open-fast", 7, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-until-followup-pass-first-turn", 7, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-until-followup-pass-final-turn", 7, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-until-followup-pass-limiter", 7, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-until-followup-pass-opponent-blocked", 7, "open"),
        ],
        logIncludes: [
          "Chain ended direct until followup pass first turn chain resolved",
          "Chain ended direct until followup pass limiter resolved",
          "Chain ended direct until followup pass open fast resolved",
          "Chain ended direct until followup pass cleanup resolved",
          "Chain ended direct until followup pass starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
