import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chainEnded open fast-effect handoff opponent-response chain-limit opponent-response pass-resolution fixture", () => {
  it("resolves post-chainEnded one-chain-limit handoff chains when the turn player passes after the opponent followup", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Ended Handoff Limit Opponent Pass Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Chain Ended Handoff Limit Opponent Pass Solved Blocker", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Chain Ended Handoff Limit Opponent Pass Cleanup", kind: "monster", attack: 1500, defense: 1600 },
      { code: "400", name: "Chain Ended Handoff Limit Opponent Pass Open Quick", kind: "monster", attack: 1200, defense: 1200 },
      { code: "500", name: "Chain Ended Handoff Limit Opponent Pass First Turn Chain", kind: "monster", attack: 1300, defense: 1300 },
      { code: "600", name: "Chain Ended Handoff Limit Opponent Pass Opponent First Chain", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Chain Ended Handoff Limit Opponent Pass Second Turn Chain", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Chain Ended Handoff Limit Opponent Pass Opponent Limiter", kind: "monster", attack: 800, defense: 800 },
      { code: "850", name: "Chain Ended Handoff Limit Opponent Pass Opponent Followup", kind: "monster", attack: 750, defense: 750 },
      { code: "900", name: "Chain Ended Handoff Limit Opponent Pass Turn Followup", kind: "monster", attack: 700, defense: 700 },
      { code: "950", name: "Chain Ended Handoff Limit Opponent Pass Final Turn Followup", kind: "monster", attack: 650, defense: 650 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "deferred chain ended open fast pass handoff opponent response turn response opponent response chain limit opponent response pass resolution fixture",
      options: { seed: 635, startingHandSize: 8 },
      decks: {
        0: { main: ["100", "200", "300", "400", "500", "700", "900", "950"] },
        1: { main: ["600", "800", "850"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "500", from: "hand", to: "graveyard" },
          { player: 0, code: "700", from: "hand", to: "graveyard" },
          { player: 0, code: "900", from: "hand", to: "graveyard" },
          { player: 0, code: "950", from: "hand", to: "graveyard" },
          { player: 1, code: "600", from: "hand", to: "graveyard" },
          { player: 1, code: "800", from: "hand", to: "graveyard" },
          { player: 1, code: "850", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "fixture-chain-ended-handoff-limit-opponent-pass-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            logMessage: "Chain ended handoff limit opponent pass starter resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-pass-solved-blocker",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainSolved",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain ended handoff limit opponent pass solved blocker should not resolve",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-pass-cleanup",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            moveCardsOnResolve: [
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "500", from: "graveyard", to: "hand" },
              { player: 0, code: "700", from: "graveyard", to: "hand" },
              { player: 0, code: "900", from: "graveyard", to: "hand" },
              { player: 0, code: "950", from: "graveyard", to: "hand" },
              { player: 1, code: "600", from: "graveyard", to: "hand" },
              { player: 1, code: "800", from: "graveyard", to: "hand" },
              { player: 1, code: "850", from: "graveyard", to: "hand" },
            ],
            logMessage: "Chain ended handoff limit opponent pass cleanup resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-pass-open-fast",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended handoff limit opponent pass open fast resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-pass-first-turn",
            player: 0,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent pass first turn chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-pass-second-turn",
            player: 0,
            code: "700",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent pass second turn chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup",
            player: 0,
            code: "900",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent pass turn followup resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-pass-final-turn",
            player: 0,
            code: "950",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent pass final turn followup should not resolve",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first",
            player: 1,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent pass opponent first chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-pass-limiter",
            player: 1,
            code: "800",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: false, allowPlayer: 0 },
            logMessage: "Chain ended handoff limit opponent pass limiter resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup",
            player: 1,
            code: "850",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent pass opponent followup resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-pass-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-pass-solved-blocker" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-pass-cleanup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-pass-open-fast" })),
        makeScriptedStep(makeResponseSelector("passChain", 1)),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-pass-first-turn" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-pass-second-turn" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player priority before the second response that precedes the opponent limiter",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-first-turn", sourceUid: "p0-deck-500-4" },
              { player: 1, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first", sourceUid: "p1-deck-600-0" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "900", "950", "600", "800", "850"] },
            legalActionCounts: { 0: 4, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-second-turn", count: 1 },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup", count: 1 },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-final-turn", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 7,
                windowKind: "chainResponse",
                actions: [
                  { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-second-turn", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-final-turn", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-open-fast" },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-first-turn" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-limiter" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-open-fast", 7, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-first-turn", 7),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first", 7),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-pass-limiter", 7),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup", 7),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro reopens restored opponent priority before applying the post-chainEnded one-chain limit",
            phase: "main1",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-first-turn", sourceUid: "p0-deck-500-4" },
              { player: 1, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first", sourceUid: "p1-deck-600-0" },
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-second-turn", sourceUid: "p0-deck-700-5" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "900", "950", "600", "800", "850"] },
            legalActionCounts: { 0: 0, 1: 3 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-limiter", count: 1 },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 8,
                windowKind: "chainResponse",
                actions: [
                  { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-limiter", count: 1 },
                  { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup", count: 1 },
                ],
              },
              chainPassGroup(1, 1, 8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-open-fast" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-first-turn" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-second-turn" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-final-turn" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-open-fast", 8, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-first-turn", 8),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-second-turn", 8),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup", 8),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-final-turn", 8),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first", 8),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-handoff-limit-opponent-pass-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent priority before the post-chainEnded one-chain limiter",
            phase: "main1",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-first-turn", sourceUid: "p0-deck-500-4" },
              { player: 1, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first", sourceUid: "p1-deck-600-0" },
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-second-turn", sourceUid: "p0-deck-700-5" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "900", "950", "600", "800", "850"] },
            legalActionCounts: { 0: 0, 1: 3 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-limiter", count: 1 },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 8,
                windowKind: "chainResponse",
                actions: [
                  { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-limiter", count: 1 },
                  { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup", count: 1 },
                ],
              },
              chainPassGroup(1, 1, 8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-open-fast" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-first-turn" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-second-turn" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-final-turn" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-open-fast", 8, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-first-turn", 8),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-second-turn", 8),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup", 8),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-final-turn", 8),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first", 8),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup" })),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the turn-player response window restorable after an opponent followup to a cleared post-chainEnded one-chain limit",
            phase: "main1",
            windowId: 11,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-first-turn", sourceUid: "p0-deck-500-4" },
              { player: 1, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first", sourceUid: "p1-deck-600-0" },
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-second-turn", sourceUid: "p0-deck-700-5" },
              { player: 1, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-limiter", sourceUid: "p1-deck-800-1" },
              { player: 0, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup", sourceUid: "p0-deck-900-6" },
              { player: 1, effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup", sourceUid: "p1-deck-850-2" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chainLimits: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-final-turn", count: 1 },
              { type: "passChain", player: 0, windowId: 11, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-final-turn", 1, 11),
              chainPassGroup(0, 1, 11),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-open-fast" },
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-first-turn" },
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-second-turn" },
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup" },
              { type: "activateEffect", player: 1, windowId: 11, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first" },
              { type: "activateEffect", player: 1, windowId: 11, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-limiter" },
              { type: "activateEffect", player: 1, windowId: 11, windowKind: "chainResponse", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-open-fast", 11, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-first-turn", 11),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-second-turn", 11),
              absentChainEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup", 11),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first", 11),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-pass-limiter", 11),
              absentChainEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup", 11),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves post-chainEnded one-chain-limit handoff chains after the turn player passes the opponent followup response window",
        phase: "main1",
        windowId: 12,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chainLimits: [],
        locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "900", "950", "600", "800", "850"] },
        legalActionCounts: { 0: 17, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "950", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "950", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 12, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 12, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 12,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "400", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "normalSummon", player: 0, code: "700", location: "hand" },
            { type: "normalSummon", player: 0, code: "900", location: "hand" },
            { type: "normalSummon", player: 0, code: "950", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "400", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "700", location: "hand" },
            { type: "setMonster", player: 0, code: "900", location: "hand" },
            { type: "setMonster", player: 0, code: "950", location: "hand" },
          ], 1, 12),
          turnGroup(12),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-open-fast" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-first-turn" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-second-turn" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-final-turn" },
          { type: "activateEffect", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-limiter" },
          { type: "activateEffect", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-open-fast", 12, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-first-turn", 12, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-second-turn", 12, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-turn-followup", 12, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-pass-final-turn", 12, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-pass-opponent-first", 12, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-pass-limiter", 12, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-pass-opponent-followup", 12, "open"),
        ],
        logIncludes: [
          "Chain ended handoff limit opponent pass opponent followup resolved",
          "Chain ended handoff limit opponent pass turn followup resolved",
          "Chain ended handoff limit opponent pass limiter resolved",
          "Chain ended handoff limit opponent pass second turn chain resolved",
          "Chain ended handoff limit opponent pass opponent first chain resolved",
          "Chain ended handoff limit opponent pass first turn chain resolved",
          "Chain ended handoff limit opponent pass open fast resolved",
          "Chain ended handoff limit opponent pass cleanup resolved",
          "Chain ended handoff limit opponent pass starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
