import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, chainEffectGroup, chainPassGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution cross-player SEGOC pass-handoff turn-response until-chain-end limit fixture", () => {
  it("keeps until-chain-end limits after the turn player responds to a cross-player chain-created SEGOC handoff", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Cross Handoff Turn Until Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Cross Handoff Turn Until Chain Limiter", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Cross Handoff Turn Until Turn Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Cross Handoff Turn Until Opponent Mandatory", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Cross Handoff Turn Until Turn Optional", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Cross Handoff Turn Until Opponent Optional", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Cross Handoff Turn Until Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Cross Handoff Turn Until Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Cross Handoff Turn Until Opponent Quick", kind: "monster", attack: 1600, defense: 1000 },
      { code: "950", name: "Cross Handoff Turn Until Followup", kind: "monster", attack: 1300, defense: 1300 },
      { code: "980", name: "Cross Handoff Turn Until Opponent Blocked Quick", kind: "monster", attack: 1100, defense: 1100 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution cross-player segoc pass-handoff turn-response until-chain-end limit fixture",
      options: { seed: 494, startingHandSize: 6 },
      decks: {
        0: { main: ["100", "200", "300", "500", "700", "950"] },
        1: { main: ["400", "600", "900", "980", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-cross-handoff-turn-until-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "950", from: "hand", to: "graveyard" },
              { player: 1, code: "900", from: "hand", to: "graveyard" },
              { player: 1, code: "980", from: "hand", to: "graveyard" },
            ],
            logMessage: "Cross handoff turn until starter resolved",
          },
          {
            id: "fixture-cross-handoff-turn-until-turn-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            optional: false,
            range: ["hand"],
            logMessage: "Cross handoff turn until turn mandatory resolved",
          },
          {
            id: "fixture-cross-handoff-turn-until-opponent-mandatory",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            optional: false,
            range: ["hand"],
            logMessage: "Cross handoff turn until opponent mandatory resolved",
          },
          {
            id: "fixture-cross-handoff-turn-until-turn-optional",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            range: ["hand"],
            logMessage: "Cross handoff turn until turn optional resolved",
          },
          {
            id: "fixture-cross-handoff-turn-until-opponent-optional",
            player: 1,
            code: "600",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            range: ["hand"],
            logMessage: "Cross handoff turn until opponent optional resolved",
          },
          {
            id: "fixture-cross-handoff-turn-until-chain-limiter",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 0 },
            logMessage: "Cross handoff turn until chain limiter resolved",
          },
          {
            id: "fixture-cross-handoff-turn-until-followup",
            player: 0,
            code: "950",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Cross handoff turn until followup should not resolve",
          },
          {
            id: "fixture-cross-handoff-turn-until-opponent",
            player: 1,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross handoff turn until opponent quick resolved",
          },
          {
            id: "fixture-cross-handoff-turn-until-opponent-blocked",
            player: 1,
            code: "980",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Cross handoff turn until opponent blocked should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-handoff-turn-until-starter" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-handoff-turn-until-turn-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-handoff-turn-until-opponent-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-handoff-turn-until-turn-optional" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-handoff-turn-until-opponent-optional" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-cross-handoff-turn-until-opponent" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-handoff-turn-until-chain-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the cross-player SEGOC turn-response handoff window restorable before the turn player applies an until-chain-end limit",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-turn-until-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-turn-until-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-handoff-turn-until-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-turn-until-opponent-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-turn-until-opponent", sourceUid: "p1-deck-900-2" },
            ],
            chainPasses: [],
            chainLimits: [],
            locations: { graveyard: ["700", "200", "950", "900", "980"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-chain-limiter", count: 1 },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 7,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-chain-limiter", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-followup", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-opponent" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-cross-handoff-turn-until-opponent", 7),
              absentChainEffectGroup(1, "fixture-cross-handoff-turn-until-opponent-blocked", 7),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro applies SetChainLimitTillChainEnd restrictions after the turn player responds to an opponent response in a cross-player chain-created SEGOC handoff chain",
            phase: "main1",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-turn-until-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-turn-until-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-handoff-turn-until-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-turn-until-opponent-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-turn-until-opponent", sourceUid: "p1-deck-900-2" },
              { player: 0, effectId: "fixture-cross-handoff-turn-until-chain-limiter", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            locations: { graveyard: ["700", "200", "950", "900", "980"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-handoff-turn-until-followup", 1, 8),
              chainPassGroup(0, 1, 8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-chain-limiter" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-handoff-turn-until-chain-limiter", 8),
              absentChainEffectGroup(1, "fixture-cross-handoff-turn-until-opponent-blocked", 8),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the cross-player turn-response SetChainLimitTillChainEnd window restorable before the allowed turn player passes",
            phase: "main1",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-turn-until-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-turn-until-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-handoff-turn-until-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-turn-until-opponent-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-turn-until-opponent", sourceUid: "p1-deck-900-2" },
              { player: 0, effectId: "fixture-cross-handoff-turn-until-chain-limiter", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: true }],
            locations: { graveyard: ["700", "200", "950", "900", "980"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-handoff-turn-until-followup", 1, 8),
              chainPassGroup(0, 1, 8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-chain-limiter" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-turn-until-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-handoff-turn-until-chain-limiter", 8),
              absentChainEffectGroup(1, "fixture-cross-handoff-turn-until-opponent-blocked", 8),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears until-chain-end limits and resolves cross-player chain-created SEGOC handoff chains after the allowed turn player passes",
        phase: "main1",
        windowId: 9,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        locations: { graveyard: ["700", "200", "950", "900", "980"], hand: ["100", "300", "500", "400", "600", "800", "800"] },
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-cross-handoff-turn-until-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 9, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 9, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 9,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-cross-handoff-turn-until-starter", count: 1 }],
          },
          {
            player: 0,
            label: "Summons",
            windowId: 9,
            windowKind: "open",
            count: 1,
            actions: [
              { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
            ],
          },
          {
            player: 0,
            label: "Turn",
            windowId: 9,
            windowKind: "open",
            count: 1,
            actions: [
              { type: "changePhase", player: 0, windowId: 9, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 9, windowKind: "open", count: 1 },
            ],
          },
        ],
        logIncludes: [
          "Cross handoff turn until chain limiter resolved",
          "Cross handoff turn until opponent quick resolved",
          "Cross handoff turn until opponent optional resolved",
          "Cross handoff turn until turn optional resolved",
          "Cross handoff turn until opponent mandatory resolved",
          "Cross handoff turn until turn mandatory resolved",
          "Cross handoff turn until starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
