import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity Main Phase 2 chain-response handoff turn-response chain-limit fixture", () => {
  it("applies one-chain limits after the turn player responds to a Main Phase 2 chain-response handoff", () => {
    const cards: DuelCardData[] = [
      { code: "110", name: "Main2 Turn Response Limit Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "130", name: "Main2 Turn Response Limit Chain Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "150", name: "Main2 Turn Response Limit Followup", kind: "monster", attack: 1000, defense: 1000 },
      { code: "210", name: "Main2 Turn Response Limit Opponent First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "230", name: "Main2 Turn Response Limit Opponent Second Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "240", name: "Main2 Turn Response Limit Opponent Blocked Quick", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "main2 chain-response handoff turn-response chain limit fixture",
      options: { seed: 294, startingHandSize: 3 },
      decks: {
        0: { main: ["110", "130", "150"] },
        1: { main: ["210", "230", "240"] },
      },
      setup: {
        effects: [
          {
            id: "main2-turn-response-limit-open-quick",
            player: 0,
            code: "110",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            oncePerTurn: true,
            logMessage: "Main2 turn-response limit open quick resolved",
          },
          {
            id: "main2-turn-response-limit-chain-limiter",
            player: 0,
            code: "130",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            chainLimitOnTarget: { untilChainEnd: false, allowPlayer: 0 },
            logMessage: "Main2 turn-response limit chain limiter resolved",
          },
          {
            id: "main2-turn-response-limit-followup",
            player: 0,
            code: "150",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Main2 turn-response limit followup should not resolve",
          },
          {
            id: "main2-turn-response-limit-opponent-first",
            player: 1,
            code: "210",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Main2 turn-response limit opponent first quick resolved",
          },
          {
            id: "main2-turn-response-limit-opponent-second",
            player: 1,
            code: "230",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Main2 turn-response limit opponent second quick resolved",
          },
          {
            id: "main2-turn-response-limit-opponent-blocked",
            player: 1,
            code: "240",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Main2 turn-response limit opponent blocked quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("changePhase", 0, { phase: "battle" })),
        makeScriptedStep(makeResponseSelector("changePhase", 0, { phase: "main2" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "main2-turn-response-limit-open-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "main2-turn-response-limit-opponent-first" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "main2-turn-response-limit-opponent-second" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "main2-turn-response-limit-chain-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps Main Phase 2 turn response priority restorable before the turn player applies a one-chain limit",
            phase: "main2",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "main2-turn-response-limit-open-quick", sourceUid: "p0-deck-110-0" },
              { player: 1, effectId: "main2-turn-response-limit-opponent-first", sourceUid: "p1-deck-210-0" },
              { player: 1, effectId: "main2-turn-response-limit-opponent-second", sourceUid: "p1-deck-230-1" },
            ],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "main2-turn-response-limit-chain-limiter", count: 1 },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "main2-turn-response-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 6,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "main2-turn-response-limit-chain-limiter", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "main2-turn-response-limit-followup", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "main2-turn-response-limit-open-quick" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "main2-turn-response-limit-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "main2-turn-response-limit-open-quick", 6, "chainResponse"),
              absentChainEffectGroup(1, "main2-turn-response-limit-opponent-blocked", 6),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro keeps Main Phase 2 active and applies one-chain SetChainLimit restrictions after the turn player responds to a chain-response handoff",
            phase: "main2",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "main2-turn-response-limit-open-quick", sourceUid: "p0-deck-110-0" },
              { player: 1, effectId: "main2-turn-response-limit-opponent-first", sourceUid: "p1-deck-210-0" },
              { player: 1, effectId: "main2-turn-response-limit-opponent-second", sourceUid: "p1-deck-230-1" },
              { player: 0, effectId: "main2-turn-response-limit-chain-limiter", sourceUid: "p0-deck-130-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 4 }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "main2-turn-response-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "main2-turn-response-limit-followup", 1, 7),
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "main2-turn-response-limit-opponent-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "main2-turn-response-limit-opponent-blocked", 7)],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the Main Phase 2 turn-response SetChainLimit window restorable before the allowed turn player passes",
            phase: "main2",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "main2-turn-response-limit-open-quick", sourceUid: "p0-deck-110-0" },
              { player: 1, effectId: "main2-turn-response-limit-opponent-first", sourceUid: "p1-deck-210-0" },
              { player: 1, effectId: "main2-turn-response-limit-opponent-second", sourceUid: "p1-deck-230-1" },
              { player: 0, effectId: "main2-turn-response-limit-chain-limiter", sourceUid: "p0-deck-130-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 4 }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "main2-turn-response-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "main2-turn-response-limit-followup", 1, 7),
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "main2-turn-response-limit-opponent-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "main2-turn-response-limit-opponent-blocked", 7)],
          },
          after: {
            source: "edopro",
            note: "EDOPro keeps Main Phase 2 active and clears one-chain limits after resolving the turn-response handoff chain",
            phase: "main2",
            windowId: 8,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 8, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "110", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "130", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "150", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "110", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "130", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "150", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              summonGroup([
                { type: "normalSummon", player: 0, code: "110", location: "hand" },
                { type: "normalSummon", player: 0, code: "130", location: "hand" },
                { type: "normalSummon", player: 0, code: "150", location: "hand" },
                { type: "setMonster", player: 0, code: "110", location: "hand" },
                { type: "setMonster", player: 0, code: "130", location: "hand" },
                { type: "setMonster", player: 0, code: "150", location: "hand" },
              ], 1, 8),
              turnGroup(8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "main2-turn-response-limit-open-quick" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "main2-turn-response-limit-chain-limiter" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "main2-turn-response-limit-followup" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "main2-turn-response-limit-opponent-blocked" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "main2-turn-response-limit-open-quick", 8, "open"),
              absentWindowEffectGroup(0, "main2-turn-response-limit-chain-limiter", 8, "open"),
              absentWindowEffectGroup(0, "main2-turn-response-limit-followup", 8, "open"),
              absentWindowEffectGroup(1, "main2-turn-response-limit-opponent-blocked", 8, "open"),
            ],
            logIncludes: [
              "Main2 turn-response limit chain limiter resolved",
              "Main2 turn-response limit opponent second quick resolved",
              "Main2 turn-response limit opponent first quick resolved",
              "Main2 turn-response limit open quick resolved",
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro final state keeps Main Phase 2 active after one-chain limits clear from a turn-response handoff chain",
        phase: "main2",
        windowId: 8,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        legalActionCounts: { 0: 8, 1: 0 },
        legalActionGroupCounts: { 0: 2, 1: 0 },
        legalActions: [
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "110", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "130", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "150", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "110", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "130", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "150", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          summonGroup([
            { type: "normalSummon", player: 0, code: "110", location: "hand" },
            { type: "normalSummon", player: 0, code: "130", location: "hand" },
            { type: "normalSummon", player: 0, code: "150", location: "hand" },
            { type: "setMonster", player: 0, code: "110", location: "hand" },
            { type: "setMonster", player: 0, code: "130", location: "hand" },
            { type: "setMonster", player: 0, code: "150", location: "hand" },
          ], 1, 8),
          turnGroup(8),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "main2-turn-response-limit-open-quick" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "main2-turn-response-limit-chain-limiter" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "main2-turn-response-limit-followup" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "main2-turn-response-limit-opponent-blocked" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "main2-turn-response-limit-open-quick", 8, "open"),
          absentWindowEffectGroup(0, "main2-turn-response-limit-chain-limiter", 8, "open"),
          absentWindowEffectGroup(0, "main2-turn-response-limit-followup", 8, "open"),
          absentWindowEffectGroup(1, "main2-turn-response-limit-opponent-blocked", 8, "open"),
        ],
        logIncludes: [
          "Main2 turn-response limit chain limiter resolved",
          "Main2 turn-response limit opponent second quick resolved",
          "Main2 turn-response limit opponent first quick resolved",
          "Main2 turn-response limit open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
