import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  triggerActivationGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity restored follow-up chainEnded response pass fixture", () => {
  it("resolves the restored chainEnded trigger chain when the turn player passes after the opponent response", () => {
    const firstEventCode = 0x10000051;
    const secondEventCode = 0x10000052;
    const cards: DuelCardData[] = [
      { code: "100", name: "Cross Payload Follow-Up Ended Pass Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "300", name: "Cross Payload Follow-Up Ended Pass Turn Trigger", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Cross Payload Follow-Up Ended Pass Opponent Trigger", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Cross Payload Follow-Up Ended Pass Turn Body", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Cross Payload Follow-Up Ended Pass Opponent First Chain Quick", kind: "monster", attack: 1100, defense: 1100 },
      { code: "620", name: "Cross Payload Follow-Up Ended Pass Opponent Second Chain Quick", kind: "monster", attack: 1150, defense: 1150 },
      { code: "700", name: "Cross Payload Follow-Up Ended Pass Opponent Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Cross Payload Follow-Up Ended Pass Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Cross Payload Follow-Up Ended Pass Turn Open Quick", kind: "monster", attack: 1300, defense: 1300 },
      { code: "950", name: "Cross Payload Follow-Up Ended Pass Turn Chain Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "970", name: "Cross Payload Follow-Up Ended Pass Turn Follow-Up Quick", kind: "monster", attack: 1450, defense: 1450 },
      { code: "975", name: "Cross Payload Follow-Up Ended Pass Turn ChainEnded Response Quick", kind: "monster", attack: 1425, defense: 1425 },
      { code: "980", name: "Cross Payload Follow-Up Ended Pass ChainEnded Watcher", kind: "monster", attack: 1350, defense: 1350 },
      { code: "990", name: "Cross Payload Follow-Up Ended Pass Opponent Open Quick", kind: "monster", attack: 700, defense: 700 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution segoc cross-player later-payload open-fast pass-handoff turn-follow-up chainEnded response-pass restore fixture",
      options: { seed: 408, startingHandSize: 9 },
      decks: {
        0: { main: ["100", "300", "500", "900", "950", "970", "975", "980", "800"] },
        1: { main: ["400", "600", "620", "700", "990", "800", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-cross-payload-follow-up-ended-pass-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "500", from: "hand", to: "graveyard", collectEvent: "customEvent", eventCode: firstEventCode },
              { player: 1, code: "700", from: "hand", to: "graveyard", collectEvent: "customEvent", eventCode: secondEventCode },
            ],
            logMessage: "Cross payload follow-up chainEnded pass starter resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-pass-turn-trigger",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "customEvent",
            triggerCode: firstEventCode,
            range: ["hand"],
            logMessage: "Cross payload follow-up chainEnded pass turn trigger should not resolve",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-pass-opponent-trigger",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "customEvent",
            triggerCode: secondEventCode,
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 1, code: "600", from: "hand", to: "graveyard" },
              { player: 1, code: "620", from: "hand", to: "graveyard" },
              { player: 0, code: "950", from: "hand", to: "graveyard" },
              { player: 0, code: "970", from: "hand", to: "graveyard" },
              { player: 0, code: "975", from: "hand", to: "graveyard" },
            ],
            logMessage: "Cross payload follow-up chainEnded pass opponent trigger resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-pass-turn-open-quick",
            player: 0,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Cross payload follow-up chainEnded pass turn open quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-pass-turn-chain-quick",
            player: 0,
            code: "950",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross payload follow-up chainEnded pass turn chain quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-pass-turn-follow-up-quick",
            player: 0,
            code: "970",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: true, allowPlayer: 1 },
            moveCardsOnResolve: [{ player: 0, code: "980", from: "hand", to: "graveyard" }],
            logMessage: "Cross payload follow-up chainEnded pass turn follow-up quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick",
            player: 0,
            code: "975",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross payload follow-up chainEnded pass turn chainEnded response quick should not resolve",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher",
            player: 0,
            code: "980",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            optional: false,
            range: ["graveyard"],
            oncePerTurn: true,
            logMessage: "Cross payload follow-up chainEnded pass watcher resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-pass-opponent-first-chain-quick",
            player: 1,
            code: "600",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross payload follow-up chainEnded pass opponent first chain quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick",
            player: 1,
            code: "620",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross payload follow-up chainEnded pass opponent second chain quick resolved",
          },
          {
            id: "fixture-cross-payload-follow-up-ended-pass-opponent-open-quick",
            player: 1,
            code: "990",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            logMessage: "Cross payload follow-up chainEnded pass opponent open quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-pass-starter" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-cross-payload-follow-up-ended-pass-turn-trigger" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-trigger" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-pass-turn-open-quick" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-pass-turn-chain-quick" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-first-chain-quick" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-payload-follow-up-ended-pass-turn-follow-up-quick" }), {
          snapshotRestore: "both",
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          after: {
            source: "edopro",
            note: "EDOPro opens a chainEnded trigger bucket after the restored follow-up chain resolves",
            phase: "main1",
            windowId: 9,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [{ player: 0, effectId: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", eventName: "chainEnded", triggerBucket: "turnMandatory" }],
            pendingTriggerBuckets: [{ player: 0, triggerBucket: "turnMandatory" }],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActionGroups: [triggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", "turnMandatory", 1, 9)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick" },
              { type: "activateEffect", player: 1, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick", 9, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick", 9, "triggerBucket"),
            ],
            locations: { graveyard: ["500", "700", "600", "620", "950", "970", "975", "980"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves the restored chainEnded trigger bucket before activation",
            phase: "main1",
            windowId: 9,
            windowKind: "triggerBucket",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [{ player: 0, effectId: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", eventName: "chainEnded", triggerBucket: "turnMandatory" }],
            pendingTriggerBuckets: [{ player: 0, triggerBucket: "turnMandatory" }],
            legalActionCounts: { 0: 1, 1: 0 },
            legalActionGroupCounts: { 0: 1, 1: 0 },
            legalActions: [
              { type: "activateTrigger", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", triggerBucket: "turnMandatory", count: 1 },
            ],
            legalActionGroups: [triggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", "turnMandatory", 1, 9)],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick" },
              { type: "activateEffect", player: 1, windowId: 9, windowKind: "triggerBucket", effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick", 9, "triggerBucket"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick", 9, "triggerBucket"),
            ],
            locations: { graveyard: ["500", "700", "600", "620", "950", "970", "975", "980"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent response priority before the opponent responds to the chainEnded trigger chain",
            phase: "main1",
            windowId: 10,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [{ player: 0, effectId: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher" }],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 10, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick", 1, 10),
              chainPassGroup(1, 1, 10),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-follow-up-quick" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-first-chain-quick" },
              { type: "activateTrigger", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-open-quick", 10, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-chain-quick", 10, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-follow-up-quick", 10, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick", 10, "chainResponse"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-pass-opponent-first-chain-quick", 10, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", "turnMandatory", 10, "chainResponse"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro hands restored chainEnded trigger-chain response priority back to the turn player after the opponent responds",
            phase: "main1",
            windowId: 11,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher" },
              { player: 1, effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick", 1, 11),
              chainPassGroup(0, 1, 11),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-follow-up-quick" },
              { type: "activateEffect", player: 1, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick" },
              { type: "activateTrigger", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-open-quick", 11, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-chain-quick", 11, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-follow-up-quick", 11, "chainResponse"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick", 11, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", "turnMandatory", 11, "chainResponse"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player response priority before the returned chainEnded trigger-chain pass",
            phase: "main1",
            windowId: 11,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher" },
              { player: 1, effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 11, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick", 1, 11),
              chainPassGroup(0, 1, 11),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-open-quick" },
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-chain-quick" },
              { type: "activateEffect", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-follow-up-quick" },
              { type: "activateEffect", player: 1, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick" },
              { type: "activateTrigger", player: 0, windowId: 11, windowKind: "chainResponse", effectId: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", triggerBucket: "turnMandatory" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-open-quick", 11, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-chain-quick", 11, "chainResponse"),
              absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-follow-up-quick", 11, "chainResponse"),
              absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick", 11, "chainResponse"),
              absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", "turnMandatory", 11, "chainResponse"),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves restored chainEnded trigger chains after the turn player passes the returned response window",
        phase: "main1",
        windowId: 12,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        legalActionCounts: { 0: 11, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-open-quick" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-chain-quick" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-follow-up-quick" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick" },
          { type: "activateEffect", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-first-chain-quick" },
          { type: "activateEffect", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick" },
          { type: "activateTrigger", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", triggerBucket: "turnMandatory" },
          { type: "activateTrigger", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-pass-turn-trigger", triggerBucket: "turnOptional" },
          { type: "activateTrigger", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-cross-payload-follow-up-ended-pass-opponent-trigger", triggerBucket: "opponentOptional" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-open-quick", 12, "open"),
          absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-chain-quick", 12, "open"),
          absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-follow-up-quick", 12, "open"),
          absentWindowEffectGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-chain-ended-response-quick", 12, "open"),
          absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-pass-opponent-first-chain-quick", 12, "open"),
          absentWindowEffectGroup(1, "fixture-cross-payload-follow-up-ended-pass-opponent-second-chain-quick", 12, "open"),
          absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-pass-chain-ended-watcher", "turnMandatory", 12, "open"),
          absentTriggerActivationGroup(0, "fixture-cross-payload-follow-up-ended-pass-turn-trigger", "turnOptional", 12, "open"),
          absentTriggerActivationGroup(1, "fixture-cross-payload-follow-up-ended-pass-opponent-trigger", "opponentOptional", 12, "open"),
        ],
        locations: { graveyard: ["500", "700", "600", "620", "950", "970", "975", "980"], hand: ["100", "300", "900", "800", "400", "990", "800", "800"] },
        logIncludes: [
          "Cross payload follow-up chainEnded pass starter resolved",
          "Cross payload follow-up chainEnded pass opponent trigger resolved",
          "Cross payload follow-up chainEnded pass turn follow-up quick resolved",
          "Cross payload follow-up chainEnded pass opponent second chain quick resolved",
          "Cross payload follow-up chainEnded pass watcher resolved",
          "Cross payload follow-up chainEnded pass opponent first chain quick resolved",
          "Cross payload follow-up chainEnded pass turn chain quick resolved",
          "Cross payload follow-up chainEnded pass turn open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
