import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentWindowEffectGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chainEnded open fast-effect handoff opponent-response chain-limit opponent-response resolution fixture", () => {
  it("resolves post-chainEnded one-chain-limit handoff chains after the opponent followup is answered", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Ended Handoff Limit Opponent Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Chain Ended Handoff Limit Opponent Resolution Solved Blocker", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Chain Ended Handoff Limit Opponent Resolution Cleanup", kind: "monster", attack: 1500, defense: 1600 },
      { code: "400", name: "Chain Ended Handoff Limit Opponent Resolution Open Quick", kind: "monster", attack: 1200, defense: 1200 },
      { code: "500", name: "Chain Ended Handoff Limit Opponent Resolution First Turn Chain", kind: "monster", attack: 1300, defense: 1300 },
      { code: "600", name: "Chain Ended Handoff Limit Opponent Resolution Opponent First Chain", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Chain Ended Handoff Limit Opponent Resolution Second Turn Chain", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Chain Ended Handoff Limit Opponent Resolution Opponent Limiter", kind: "monster", attack: 800, defense: 800 },
      { code: "850", name: "Chain Ended Handoff Limit Opponent Resolution Opponent Followup", kind: "monster", attack: 750, defense: 750 },
      { code: "900", name: "Chain Ended Handoff Limit Opponent Resolution Turn Followup", kind: "monster", attack: 700, defense: 700 },
      { code: "950", name: "Chain Ended Handoff Limit Opponent Resolution Final Turn Followup", kind: "monster", attack: 650, defense: 650 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "deferred chain ended open fast pass handoff opponent response turn response opponent response chain limit opponent response resolution fixture",
      options: { seed: 634, startingHandSize: 8 },
      decks: {
        0: { main: ["100", "200", "300", "400", "500", "700", "900", "950"] },
        1: { main: ["600", "800", "850"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "500", from: "hand", to: "graveyard" },
          { player: 0, code: "700", from: "hand", to: "graveyard" },
          { player: 0, code: "900", from: "hand", to: "graveyard" },
          { player: 0, code: "950", from: "hand", to: "graveyard" },
          { player: 1, code: "600", from: "hand", to: "graveyard" },
          { player: 1, code: "800", from: "hand", to: "graveyard" },
          { player: 1, code: "850", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "fixture-chain-ended-handoff-limit-opponent-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            logMessage: "Chain ended handoff limit opponent resolution starter resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-resolution-solved-blocker",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainSolved",
            range: ["hand"],
            logMessage: "Chain ended handoff limit opponent resolution solved blocker should not resolve",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-resolution-cleanup",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            moveCardsOnResolve: [
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "500", from: "graveyard", to: "hand" },
              { player: 0, code: "700", from: "graveyard", to: "hand" },
              { player: 0, code: "900", from: "graveyard", to: "hand" },
              { player: 0, code: "950", from: "graveyard", to: "hand" },
              { player: 1, code: "600", from: "graveyard", to: "hand" },
              { player: 1, code: "800", from: "graveyard", to: "hand" },
              { player: 1, code: "850", from: "graveyard", to: "hand" },
            ],
            logMessage: "Chain ended handoff limit opponent resolution cleanup resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-resolution-open-fast",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended handoff limit opponent resolution open fast resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-resolution-first-turn",
            player: 0,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent resolution first turn chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-resolution-second-turn",
            player: 0,
            code: "700",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent resolution second turn chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-resolution-turn-followup",
            player: 0,
            code: "900",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent resolution turn followup resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-resolution-final-turn",
            player: 0,
            code: "950",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent resolution final turn followup resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-resolution-opponent-first",
            player: 1,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent resolution opponent first chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-resolution-limiter",
            player: 1,
            code: "800",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: false, allowPlayer: 0 },
            logMessage: "Chain ended handoff limit opponent resolution limiter resolved",
          },
          {
            id: "fixture-chain-ended-handoff-limit-opponent-resolution-opponent-followup",
            player: 1,
            code: "850",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff limit opponent resolution opponent followup resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-solved-blocker" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-cleanup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-open-fast" })),
        makeScriptedStep(makeResponseSelector("passChain", 1)),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-first-turn" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-opponent-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-second-turn" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-limiter" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-turn-followup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-opponent-followup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-final-turn" }), {
          snapshotRestore: "both",
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves post-chainEnded one-chain-limit handoff chains after the opponent followup is answered and no response remains",
        phase: "main1",
        windowId: 12,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chainLimits: [],
        locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "900", "950", "600", "800", "850"] },
        legalActionCounts: { 0: 17, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 12, windowKind: "open", code: "950", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 12, windowKind: "open", code: "950", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 12, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 12, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 12,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "400", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "normalSummon", player: 0, code: "700", location: "hand" },
            { type: "normalSummon", player: 0, code: "900", location: "hand" },
            { type: "normalSummon", player: 0, code: "950", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "400", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "700", location: "hand" },
            { type: "setMonster", player: 0, code: "900", location: "hand" },
            { type: "setMonster", player: 0, code: "950", location: "hand" },
          ], 1, 12),
          turnGroup(12),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-open-fast" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-first-turn" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-second-turn" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-turn-followup" },
          { type: "activateEffect", player: 0, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-final-turn" },
          { type: "activateEffect", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-limiter" },
          { type: "activateEffect", player: 1, windowId: 12, windowKind: "open", effectId: "fixture-chain-ended-handoff-limit-opponent-resolution-opponent-followup" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-resolution-open-fast", 12, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-resolution-first-turn", 12, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-resolution-second-turn", 12, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-resolution-turn-followup", 12, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-limit-opponent-resolution-final-turn", 12, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-resolution-opponent-first", 12, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-resolution-limiter", 12, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-handoff-limit-opponent-resolution-opponent-followup", 12, "open"),
        ],
        logIncludes: [
          "Chain ended handoff limit opponent resolution final turn followup resolved",
          "Chain ended handoff limit opponent resolution opponent followup resolved",
          "Chain ended handoff limit opponent resolution turn followup resolved",
          "Chain ended handoff limit opponent resolution limiter resolved",
          "Chain ended handoff limit opponent resolution second turn chain resolved",
          "Chain ended handoff limit opponent resolution opponent first chain resolved",
          "Chain ended handoff limit opponent resolution first turn chain resolved",
          "Chain ended handoff limit opponent resolution open fast resolved",
          "Chain ended handoff limit opponent resolution cleanup resolved",
          "Chain ended handoff limit opponent resolution starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
