import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chainEnded open fast-effect chain-response turn-response opponent-response turn-response opponent-response turn-response resolution fixture", () => {
  it("resolves when the turn player chains again after the opponent returns a direct post-chainEnded turn response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Ended Direct Opponent Turn Opponent Turn Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Chain Ended Direct Opponent Turn Opponent Turn Resolution Solved Blocker", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Chain Ended Direct Opponent Turn Opponent Turn Resolution Cleanup", kind: "monster", attack: 1500, defense: 1600 },
      { code: "400", name: "Chain Ended Direct Opponent Turn Opponent Turn Resolution Open Quick", kind: "monster", attack: 1200, defense: 1200 },
      { code: "500", name: "Chain Ended Direct Opponent Turn Opponent Turn Resolution First Opponent Chain", kind: "monster", attack: 1100, defense: 1100 },
      { code: "600", name: "Chain Ended Direct Opponent Turn Opponent Turn Resolution First Turn Chain", kind: "monster", attack: 900, defense: 900 },
      { code: "700", name: "Chain Ended Direct Opponent Turn Opponent Turn Resolution Opponent Open Quick", kind: "monster", attack: 800, defense: 800 },
      { code: "800", name: "Chain Ended Direct Opponent Turn Opponent Turn Resolution Second Opponent Chain", kind: "monster", attack: 700, defense: 700 },
      { code: "900", name: "Chain Ended Direct Opponent Turn Opponent Turn Resolution Second Turn Chain", kind: "monster", attack: 650, defense: 650 },
      { code: "1000", name: "Chain Ended Direct Opponent Turn Opponent Turn Resolution Third Opponent Chain", kind: "monster", attack: 600, defense: 600 },
      { code: "1100", name: "Chain Ended Direct Opponent Turn Opponent Turn Resolution Third Turn Chain", kind: "monster", attack: 550, defense: 550 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "deferred chain ended open fast chain response turn response opponent-response turn-response opponent-response turn-response resolution fixture",
      options: { seed: 652, startingHandSize: 7 },
      decks: {
        0: { main: ["100", "200", "300", "400", "600", "900", "1100"] },
        1: { main: ["500", "800", "1000", "700"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "600", from: "hand", to: "graveyard" },
          { player: 0, code: "900", from: "hand", to: "graveyard" },
          { player: 0, code: "1100", from: "hand", to: "graveyard" },
          { player: 1, code: "500", from: "hand", to: "graveyard" },
          { player: 1, code: "800", from: "hand", to: "graveyard" },
          { player: 1, code: "1000", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            logMessage: "Chain ended direct opponent turn opponent turn resolution starter resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-solved-blocker",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainSolved",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain ended direct opponent turn opponent turn resolution solved blocker should not resolve",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-cleanup",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            moveCardsOnResolve: [
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "600", from: "graveyard", to: "hand" },
              { player: 0, code: "900", from: "graveyard", to: "hand" },
              { player: 0, code: "1100", from: "graveyard", to: "hand" },
              { player: 1, code: "500", from: "graveyard", to: "hand" },
              { player: 1, code: "800", from: "graveyard", to: "hand" },
              { player: 1, code: "1000", from: "graveyard", to: "hand" },
            ],
            logMessage: "Chain ended direct opponent turn opponent turn resolution cleanup resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-open-fast",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended direct opponent turn opponent turn resolution open fast resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-first-turn",
            player: 0,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn resolution first turn chain resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-second-turn",
            player: 0,
            code: "900",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn resolution second turn chain resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-third-turn",
            player: 0,
            code: "1100",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn resolution third turn chain resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-first",
            player: 1,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn resolution opponent first resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-open",
            player: 1,
            code: "700",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended direct opponent turn opponent turn resolution opponent open should not resolve",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-second",
            player: 1,
            code: "800",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn resolution opponent second resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-third",
            player: 1,
            code: "1000",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn resolution opponent third resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-solved-blocker" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-cleanup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-open-fast" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-first-turn" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-second" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-second-turn" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-third" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-third-turn" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player priority before the final alternating direct post-chainEnded response",
            phase: "main1",
            windowId: 9,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-first", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-first-turn", sourceUid: "p0-deck-600-4" },
              { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-second", sourceUid: "p1-deck-800-1" },
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-second-turn", sourceUid: "p0-deck-900-5" },
              { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-third", sourceUid: "p1-deck-1000-2" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chainLimits: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "600", "900", "1100", "500", "800", "1000", "700"] },
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 9, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-third-turn", count: 1 },
              { type: "passChain", player: 0, windowId: 9, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-third-turn", 1, 9),
              chainPassGroup(0, 1, 9),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 9, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-open-fast" },
              { type: "activateEffect", player: 0, windowId: 9, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-first-turn" },
              { type: "activateEffect", player: 0, windowId: 9, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-second-turn" },
              { type: "activateEffect", player: 1, windowId: 9, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-first" },
              { type: "activateEffect", player: 1, windowId: 9, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-second" },
              { type: "activateEffect", player: 1, windowId: 9, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-third" },
              { type: "activateEffect", player: 1, windowId: 9, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-open" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-open-fast", 9, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-first-turn", 9),
              absentChainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-second-turn", 9),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-first", 9),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-second", 9),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-third", 9),
              absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-open", 9, "chainResponse"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro resolves direct post-chainEnded response chains after the restored final alternating turn response",
            phase: "main1",
            windowId: 10,
            windowKind: "open",
            waitingFor: 0,
            chain: [],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chainLimits: [],
            locations: { graveyard: ["200"], hand: ["100", "300", "400", "600", "900", "1100", "500", "800", "1000", "700"] },
            legalActionCounts: { 0: 15, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-starter", count: 1 },
              { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "400", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "600", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "900", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "1100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "400", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "600", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "900", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "1100", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 10, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 10, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 10,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-starter", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "300", location: "hand" },
                { type: "normalSummon", player: 0, code: "400", location: "hand" },
                { type: "normalSummon", player: 0, code: "600", location: "hand" },
                { type: "normalSummon", player: 0, code: "900", location: "hand" },
                { type: "normalSummon", player: 0, code: "1100", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "300", location: "hand" },
                { type: "setMonster", player: 0, code: "400", location: "hand" },
                { type: "setMonster", player: 0, code: "600", location: "hand" },
                { type: "setMonster", player: 0, code: "900", location: "hand" },
                { type: "setMonster", player: 0, code: "1100", location: "hand" },
              ], 1, 10),
              turnGroup(10),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-open-fast" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-first-turn" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-second-turn" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-third-turn" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-first" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-second" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-third" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-open" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-open-fast", 10, "open"),
              absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-first-turn", 10, "open"),
              absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-second-turn", 10, "open"),
              absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-third-turn", 10, "open"),
              absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-first", 10, "open"),
              absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-second", 10, "open"),
              absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-third", 10, "open"),
              absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-open", 10, "open"),
            ],
            logIncludes: [
              "Chain ended direct opponent turn opponent turn resolution third turn chain resolved",
              "Chain ended direct opponent turn opponent turn resolution opponent third resolved",
              "Chain ended direct opponent turn opponent turn resolution second turn chain resolved",
              "Chain ended direct opponent turn opponent turn resolution opponent second resolved",
              "Chain ended direct opponent turn opponent turn resolution first turn chain resolved",
              "Chain ended direct opponent turn opponent turn resolution opponent first resolved",
              "Chain ended direct opponent turn opponent turn resolution open fast resolved",
              "Chain ended direct opponent turn opponent turn resolution cleanup resolved",
              "Chain ended direct opponent turn opponent turn resolution starter resolved",
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves direct post-chainEnded opponent-response chains after the turn player answers the response window returned by the opponent",
        phase: "main1",
        windowId: 10,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chainLimits: [],
        locations: { graveyard: ["200"], hand: ["100", "300", "400", "600", "900", "1100", "500", "800", "1000", "700"] },
        legalActionCounts: { 0: 15, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "600", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 10, windowKind: "open", code: "1100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "600", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 10, windowKind: "open", code: "1100", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 10, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 10, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 10,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "400", location: "hand" },
            { type: "normalSummon", player: 0, code: "600", location: "hand" },
            { type: "normalSummon", player: 0, code: "900", location: "hand" },
            { type: "normalSummon", player: 0, code: "1100", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "400", location: "hand" },
            { type: "setMonster", player: 0, code: "600", location: "hand" },
            { type: "setMonster", player: 0, code: "900", location: "hand" },
            { type: "setMonster", player: 0, code: "1100", location: "hand" },
          ], 1, 10),
          turnGroup(10),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-open-fast" },
          { type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-first-turn" },
          { type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-second-turn" },
          { type: "activateEffect", player: 0, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-third-turn" },
          { type: "activateEffect", player: 1, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-second" },
          { type: "activateEffect", player: 1, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-third" },
          { type: "activateEffect", player: 1, windowId: 10, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-open" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-open-fast", 10, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-first-turn", 10, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-second-turn", 10, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-third-turn", 10, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-first", 10, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-second", 10, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-third", 10, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-resolution-opponent-open", 10, "open"),
        ],
        logIncludes: [
          "Chain ended direct opponent turn opponent turn resolution third turn chain resolved",
          "Chain ended direct opponent turn opponent turn resolution opponent third resolved",
          "Chain ended direct opponent turn opponent turn resolution second turn chain resolved",
          "Chain ended direct opponent turn opponent turn resolution opponent second resolved",
          "Chain ended direct opponent turn opponent turn resolution first turn chain resolved",
          "Chain ended direct opponent turn opponent turn resolution opponent first resolved",
          "Chain ended direct opponent turn opponent turn resolution open fast resolved",
          "Chain ended direct opponent turn opponent turn resolution cleanup resolved",
          "Chain ended direct opponent turn opponent turn resolution starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
