import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentWindowEffectGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chainEnded open fast-effect handoff opponent response turn response chain resolution fixture", () => {
  it("resolves after the opponent chains from the post-chainEnded turn-response window", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Ended Handoff Turn Chain Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Chain Ended Handoff Turn Chain Resolution Solved Blocker", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Chain Ended Handoff Turn Chain Resolution Cleanup", kind: "monster", attack: 1500, defense: 1600 },
      { code: "400", name: "Chain Ended Handoff Turn Chain Resolution Open Quick", kind: "monster", attack: 1200, defense: 1200 },
      { code: "500", name: "Chain Ended Handoff Turn Chain Resolution First Turn Chain", kind: "monster", attack: 1300, defense: 1300 },
      { code: "600", name: "Chain Ended Handoff Turn Chain Resolution Opponent First Chain", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Chain Ended Handoff Turn Chain Resolution Second Turn Chain", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Chain Ended Handoff Turn Chain Resolution Opponent Second Chain", kind: "monster", attack: 800, defense: 800 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "deferred chain ended open fast pass handoff opponent response turn response chain resolution fixture",
      options: { seed: 626, startingHandSize: 6 },
      decks: {
        0: { main: ["100", "200", "300", "400", "500", "700"] },
        1: { main: ["600", "800"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "500", from: "hand", to: "graveyard" },
          { player: 0, code: "700", from: "hand", to: "graveyard" },
          { player: 1, code: "600", from: "hand", to: "graveyard" },
          { player: 1, code: "800", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "fixture-chain-ended-handoff-turn-chain-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            logMessage: "Chain ended handoff turn chain resolution starter resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-chain-resolution-solved-blocker",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainSolved",
            range: ["hand"],
            logMessage: "Chain ended handoff turn chain resolution solved blocker should not resolve",
          },
          {
            id: "fixture-chain-ended-handoff-turn-chain-resolution-cleanup",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            moveCardsOnResolve: [
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "500", from: "graveyard", to: "hand" },
              { player: 0, code: "700", from: "graveyard", to: "hand" },
              { player: 1, code: "600", from: "graveyard", to: "hand" },
              { player: 1, code: "800", from: "graveyard", to: "hand" },
            ],
            logMessage: "Chain ended handoff turn chain resolution cleanup resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-chain-resolution-open-fast",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended handoff turn chain resolution open fast resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-chain-resolution-first-turn-chain",
            player: 0,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff turn chain resolution first turn chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-chain-resolution-second-turn-chain",
            player: 0,
            code: "700",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff turn chain resolution second turn chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-chain-resolution-opponent-first",
            player: 1,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff turn chain resolution opponent first chain resolved",
          },
          {
            id: "fixture-chain-ended-handoff-turn-chain-resolution-opponent-second",
            player: 1,
            code: "800",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended handoff turn chain resolution opponent second chain resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-chain-resolution-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-chain-ended-handoff-turn-chain-resolution-solved-blocker" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-ended-handoff-turn-chain-resolution-cleanup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-chain-resolution-open-fast" })),
        makeScriptedStep(makeResponseSelector("passChain", 1)),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-chain-resolution-first-turn-chain" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-handoff-turn-chain-resolution-opponent-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-handoff-turn-chain-resolution-second-turn-chain" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-handoff-turn-chain-resolution-opponent-second" }), {
          snapshotRestore: "both",
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves post-chainEnded handoff chains after the opponent chains from the response window reopened by the turn player's answer",
        phase: "main1",
        windowId: 9,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        locations: { graveyard: ["200"], hand: ["100", "300", "400", "500", "700", "600", "800"] },
        legalActionCounts: { 0: 13, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-chain-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "700", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 9, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 9, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 9,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-chain-resolution-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "400", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "normalSummon", player: 0, code: "700", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "400", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "700", location: "hand" },
          ], 1, 9),
          turnGroup(9),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-chain-resolution-open-fast" },
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-chain-resolution-first-turn-chain" },
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-chain-resolution-second-turn-chain" },
          { type: "activateEffect", player: 1, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-chain-resolution-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 9, windowKind: "open", effectId: "fixture-chain-ended-handoff-turn-chain-resolution-opponent-second" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-chain-resolution-open-fast", 9, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-chain-resolution-first-turn-chain", 9, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-handoff-turn-chain-resolution-second-turn-chain", 9, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-handoff-turn-chain-resolution-opponent-first", 9, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-handoff-turn-chain-resolution-opponent-second", 9, "open"),
        ],
        logIncludes: [
          "Chain ended handoff turn chain resolution opponent second chain resolved",
          "Chain ended handoff turn chain resolution second turn chain resolved",
          "Chain ended handoff turn chain resolution opponent first chain resolved",
          "Chain ended handoff turn chain resolution first turn chain resolved",
          "Chain ended handoff turn chain resolution open fast resolved",
          "Chain ended handoff turn chain resolution cleanup resolved",
          "Chain ended handoff turn chain resolution starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
