import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution cross-player SEGOC pass-handoff turn response opponent response resolution fixture", () => {
  it("resolves after the opponent responds to the turn player's cross-player SEGOC handoff response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Cross Handoff Pingpong Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Turn Cross Handoff Pingpong Resolution Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Cross Handoff Pingpong Resolution Turn Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Cross Handoff Pingpong Resolution Opponent Mandatory", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Cross Handoff Pingpong Resolution Turn Optional", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Cross Handoff Pingpong Resolution Opponent Optional", kind: "monster", attack: 1100, defense: 1100 },
      { code: "700", name: "Cross Handoff Pingpong Resolution Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Opponent Cross Handoff Pingpong Resolution First Quick", kind: "monster", attack: 1600, defense: 1000 },
      { code: "950", name: "Opponent Cross Handoff Pingpong Resolution Second Quick", kind: "monster", attack: 1300, defense: 1300 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution cross-player segoc pass handoff turn response opponent response resolution fixture",
      options: { seed: 495, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "500", "700"] },
        1: { main: ["400", "600", "900", "950", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-cross-handoff-pingpong-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 1, code: "900", from: "hand", to: "graveyard" },
              { player: 1, code: "950", from: "hand", to: "graveyard" },
            ],
            logMessage: "Cross handoff pingpong resolution starter resolved",
          },
          {
            id: "fixture-cross-handoff-pingpong-resolution-turn-mandatory",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Cross handoff pingpong resolution turn mandatory resolved",
          },
          {
            id: "fixture-cross-handoff-pingpong-resolution-opponent-mandatory",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Cross handoff pingpong resolution opponent mandatory resolved",
          },
          {
            id: "fixture-cross-handoff-pingpong-resolution-turn-optional",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Cross handoff pingpong resolution turn optional resolved",
          },
          {
            id: "fixture-cross-handoff-pingpong-resolution-opponent-optional",
            player: 1,
            code: "600",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Cross handoff pingpong resolution opponent optional resolved",
          },
          {
            id: "fixture-cross-handoff-pingpong-resolution-turn-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross handoff pingpong resolution turn quick resolved",
          },
          {
            id: "fixture-cross-handoff-pingpong-resolution-first-opponent-quick",
            player: 1,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross handoff pingpong resolution first opponent quick resolved",
          },
          {
            id: "fixture-cross-handoff-pingpong-resolution-second-opponent-quick",
            player: 1,
            code: "950",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Cross handoff pingpong resolution second opponent quick resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-handoff-pingpong-resolution-starter" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-handoff-pingpong-resolution-turn-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-handoff-pingpong-resolution-opponent-mandatory" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-cross-handoff-pingpong-resolution-turn-optional" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-cross-handoff-pingpong-resolution-opponent-optional" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-cross-handoff-pingpong-resolution-first-opponent-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-cross-handoff-pingpong-resolution-turn-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the turn-player response window restorable before the turn player responds to the opponent's post-handoff chain link",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-pingpong-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-pingpong-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-handoff-pingpong-resolution-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-pingpong-resolution-opponent-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-pingpong-resolution-first-opponent-quick", sourceUid: "p1-deck-900-2" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-pingpong-resolution-turn-quick", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-cross-handoff-pingpong-resolution-turn-quick", 1, 7),
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-pingpong-resolution-first-opponent-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-cross-handoff-pingpong-resolution-second-opponent-quick" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-cross-handoff-pingpong-resolution-first-opponent-quick", 7),
              absentChainEffectGroup(1, "fixture-cross-handoff-pingpong-resolution-second-opponent-quick", 7),
            ],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "500", "400", "600", "800"] },
          },
          after: {
            source: "edopro",
            note: "EDOPro gives the opponent another chain-response window when they still have a legal response after the turn player responds to a cross-player chain-created SEGOC handoff chain",
            phase: "main1",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-pingpong-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-pingpong-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-handoff-pingpong-resolution-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-pingpong-resolution-opponent-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-pingpong-resolution-first-opponent-quick", sourceUid: "p1-deck-900-2" },
              { player: 0, effectId: "fixture-cross-handoff-pingpong-resolution-turn-quick", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-pingpong-resolution-second-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-handoff-pingpong-resolution-second-opponent-quick", 1, 8),
              chainPassGroup(1, 1, 8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-pingpong-resolution-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-pingpong-resolution-first-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 8, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-pingpong-resolution-turn-optional", triggerBucket: "turnOptional" },
              { type: "activateTrigger", player: 1, windowId: 8, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-pingpong-resolution-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-handoff-pingpong-resolution-turn-quick", 8),
              absentChainEffectGroup(1, "fixture-cross-handoff-pingpong-resolution-first-opponent-quick", 8),
              absentTriggerActivationGroup(0, "fixture-cross-handoff-pingpong-resolution-turn-optional", "turnOptional", 8, "triggerBucket"),
              absentTriggerActivationGroup(1, "fixture-cross-handoff-pingpong-resolution-opponent-optional", "opponentOptional", 8, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "500", "400", "600", "800"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-cross-handoff-pingpong-resolution-second-opponent-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the opponent response window restorable before the opponent adds the final response to the post-handoff pingpong chain",
            phase: "main1",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-cross-handoff-pingpong-resolution-turn-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-pingpong-resolution-opponent-mandatory", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 0, effectId: "fixture-cross-handoff-pingpong-resolution-turn-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-pingpong-resolution-opponent-optional", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-4" },
              { player: 1, effectId: "fixture-cross-handoff-pingpong-resolution-first-opponent-quick", sourceUid: "p1-deck-900-2" },
              { player: 0, effectId: "fixture-cross-handoff-pingpong-resolution-turn-quick", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-pingpong-resolution-second-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-cross-handoff-pingpong-resolution-second-opponent-quick", 1, 8),
              chainPassGroup(1, 1, 8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-pingpong-resolution-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-cross-handoff-pingpong-resolution-first-opponent-quick" },
              { type: "activateTrigger", player: 0, windowId: 8, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-pingpong-resolution-turn-optional", triggerBucket: "turnOptional" },
              { type: "activateTrigger", player: 1, windowId: 8, windowKind: "triggerBucket", effectId: "fixture-cross-handoff-pingpong-resolution-opponent-optional", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-cross-handoff-pingpong-resolution-turn-quick", 8),
              absentChainEffectGroup(1, "fixture-cross-handoff-pingpong-resolution-first-opponent-quick", 8),
              absentTriggerActivationGroup(0, "fixture-cross-handoff-pingpong-resolution-turn-optional", "turnOptional", 8, "triggerBucket"),
              absentTriggerActivationGroup(1, "fixture-cross-handoff-pingpong-resolution-opponent-optional", "opponentOptional", 8, "triggerBucket"),
            ],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "500", "400", "600", "800"] },
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves the cross-player chain-created SEGOC handoff chain after the opponent's final response when the turn player has no remaining response",
        phase: "main1",
        windowId: 9,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-cross-handoff-pingpong-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 9, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 9, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 9,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-cross-handoff-pingpong-resolution-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
          ], 1, 9),
          turnGroup(9),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-cross-handoff-pingpong-resolution-turn-quick" },
          { type: "activateEffect", player: 1, windowId: 9, windowKind: "open", effectId: "fixture-cross-handoff-pingpong-resolution-first-opponent-quick" },
          { type: "activateEffect", player: 1, windowId: 9, windowKind: "open", effectId: "fixture-cross-handoff-pingpong-resolution-second-opponent-quick" },
          { type: "activateTrigger", player: 0, windowId: 9, windowKind: "open", effectId: "fixture-cross-handoff-pingpong-resolution-turn-optional" },
          { type: "activateTrigger", player: 1, windowId: 9, windowKind: "open", effectId: "fixture-cross-handoff-pingpong-resolution-opponent-optional" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-cross-handoff-pingpong-resolution-turn-quick", 9, "open"),
          absentWindowEffectGroup(1, "fixture-cross-handoff-pingpong-resolution-first-opponent-quick", 9, "open"),
          absentWindowEffectGroup(1, "fixture-cross-handoff-pingpong-resolution-second-opponent-quick", 9, "open"),
          absentTriggerActivationGroup(0, "fixture-cross-handoff-pingpong-resolution-turn-optional", "turnOptional", 9, "open"),
          absentTriggerActivationGroup(1, "fixture-cross-handoff-pingpong-resolution-opponent-optional", "opponentOptional", 9, "open"),
        ],
        locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "500", "400", "600", "800"] },
        logIncludes: [
          "Cross handoff pingpong resolution starter resolved",
          "Cross handoff pingpong resolution second opponent quick resolved",
          "Cross handoff pingpong resolution turn quick resolved",
          "Cross handoff pingpong resolution first opponent quick resolved",
          "Cross handoff pingpong resolution opponent optional resolved",
          "Cross handoff pingpong resolution turn optional resolved",
          "Cross handoff pingpong resolution opponent mandatory resolved",
          "Cross handoff pingpong resolution turn mandatory resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
