import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity trigger-chain response turn-response chain-limit fixture", () => {
  it("clears one-chain limits after the allowed trigger player responds to an opponent selected-trigger response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Trigger Limit Turn Response Summon", kind: "monster", attack: 1000, defense: 1000 },
      { code: "200", name: "Trigger Limit Turn Response Success Trigger", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Trigger Limit Turn Response First Followup", kind: "monster", attack: 1000, defense: 1000 },
      { code: "350", name: "Trigger Limit Turn Response Second Followup", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Trigger Limit Turn Response Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Trigger Limit Turn Response Opponent Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "600", name: "Trigger Limit Turn Response Opponent Followup", kind: "monster", attack: 1000, defense: 1000 },
      { code: "700", name: "Trigger Limit Turn Response Opponent Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "900", name: "Trigger Limit Turn Response Filler", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "trigger chain open fast chain response turn response chain limit fixture",
      options: { seed: 617, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "350", "400"] },
        1: { main: ["500", "600", "700", "900", "900"] },
      },
      setup: {
        effects: [
          {
            id: "trigger-limit-turn-response-success",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "normalSummoned",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Trigger limit turn response success resolved",
          },
          {
            id: "trigger-limit-turn-response-first-followup",
            player: 0,
            code: "300",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Trigger limit turn response first followup resolved",
          },
          {
            id: "trigger-limit-turn-response-second-followup",
            player: 0,
            code: "350",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Trigger limit turn response second followup should not resolve",
          },
          {
            id: "trigger-limit-turn-response-open",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            logMessage: "Trigger limit turn response open quick should not resolve",
          },
          {
            id: "trigger-limit-turn-response-opponent-limiter",
            player: 1,
            code: "500",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: false, allowPlayer: 0 },
            logMessage: "Trigger limit turn response opponent limiter resolved",
          },
          {
            id: "trigger-limit-turn-response-opponent-followup",
            player: 1,
            code: "600",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Trigger limit turn response opponent followup should not resolve",
          },
          {
            id: "trigger-limit-turn-response-opponent-open",
            player: 1,
            code: "700",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            logMessage: "Trigger limit turn response opponent open quick should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("normalSummon", 0, { code: "100", location: "hand" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "trigger-limit-turn-response-success" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "trigger-limit-turn-response-opponent-limiter" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "trigger-limit-turn-response-first-followup" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored trigger-player priority while the selected-trigger one-chain limit allows that player to respond",
            windowId: 3,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "trigger-limit-turn-response-success", eventName: "normalSummoned", eventCardUid: "p0-deck-100-0", eventTriggerTiming: "if" },
              { player: 1, effectId: "trigger-limit-turn-response-opponent-limiter", sourceUid: "p1-deck-500-0" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 2 }],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-first-followup", count: 1 },
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-second-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 3, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 3,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-first-followup", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-second-followup", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 3),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 3, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-open" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-opponent-limiter" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-opponent-followup" },
              { type: "activateEffect", player: 1, windowId: 3, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-opponent-open" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "trigger-limit-turn-response-open", 3, "chainResponse"),
              absentChainEffectGroup(1, "trigger-limit-turn-response-opponent-limiter", 3),
              absentChainEffectGroup(1, "trigger-limit-turn-response-opponent-followup", 3),
              absentWindowEffectGroup(1, "trigger-limit-turn-response-opponent-open", 3, "chainResponse"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro clears one-chain SetChainLimit restrictions after the allowed trigger player responds to an opponent selected-trigger response",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "trigger-limit-turn-response-success", eventName: "normalSummoned", eventCardUid: "p0-deck-100-0", eventTriggerTiming: "if" },
              { player: 1, effectId: "trigger-limit-turn-response-opponent-limiter", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "trigger-limit-turn-response-first-followup", sourceUid: "p0-deck-300-2" },
            ],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "trigger-limit-turn-response-opponent-followup", 1, 4),
              chainPassGroup(1, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-first-followup" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-second-followup" },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-open" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-opponent-limiter" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-opponent-open" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "trigger-limit-turn-response-first-followup", 4),
              absentChainEffectGroup(0, "trigger-limit-turn-response-second-followup", 4),
              absentChainEffectGroup(0, "trigger-limit-turn-response-open", 4),
              absentChainEffectGroup(1, "trigger-limit-turn-response-opponent-limiter", 4),
              absentChainEffectGroup(1, "trigger-limit-turn-response-opponent-open", 4),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the post-SetChainLimit selected-trigger turn-response window restorable after the one-chain limit clears",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "trigger-limit-turn-response-success", eventName: "normalSummoned", eventCardUid: "p0-deck-100-0", eventTriggerTiming: "if" },
              { player: 1, effectId: "trigger-limit-turn-response-opponent-limiter", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "trigger-limit-turn-response-first-followup", sourceUid: "p0-deck-300-2" },
            ],
            chainLimits: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "trigger-limit-turn-response-opponent-followup", 1, 4),
              chainPassGroup(1, 1, 4),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-second-followup" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "trigger-limit-turn-response-second-followup", 4)],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns priority to the trigger player after the opponent passes the cleared one-chain selected-trigger response window",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "trigger-limit-turn-response-success", eventName: "normalSummoned", eventCardUid: "p0-deck-100-0", eventTriggerTiming: "if" },
              { player: 1, effectId: "trigger-limit-turn-response-opponent-limiter", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "trigger-limit-turn-response-first-followup", sourceUid: "p0-deck-300-2" },
            ],
            chainPasses: [1],
            chainLimits: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-second-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "trigger-limit-turn-response-second-followup", 1, 5),
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-first-followup" },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-opponent-followup" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "trigger-limit-turn-response-first-followup", 5),
              absentChainEffectGroup(1, "trigger-limit-turn-response-opponent-followup", 5),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the trigger-player pass-resolution window restorable after a one-chain limit has cleared",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "trigger-limit-turn-response-success", eventName: "normalSummoned", eventCardUid: "p0-deck-100-0", eventTriggerTiming: "if" },
              { player: 1, effectId: "trigger-limit-turn-response-opponent-limiter", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "trigger-limit-turn-response-first-followup", sourceUid: "p0-deck-300-2" },
            ],
            chainPasses: [1],
            chainLimits: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-second-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "trigger-limit-turn-response-second-followup", 1, 5),
              chainPassGroup(0, 1, 5),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "trigger-limit-turn-response-opponent-followup" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "trigger-limit-turn-response-opponent-followup", 5)],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro returns selected trigger chains to turn-player open priority after both cleared one-chain limit response players pass",
        windowId: 6,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        legalActionCounts: { 0: 3, 1: 0 },
        legalActionGroupCounts: { 0: 2, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-turn-response-open", count: 1 },
          { type: "changePhase", player: 0, windowId: 6, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 6, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 6,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-turn-response-open", count: 1 }],
          },
          turnGroup(6),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-turn-response-first-followup" },
          { type: "activateEffect", player: 0, windowId: 6, windowKind: "open", effectId: "trigger-limit-turn-response-second-followup" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-limit-turn-response-opponent-limiter" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-limit-turn-response-opponent-followup" },
          { type: "activateEffect", player: 1, windowId: 6, windowKind: "open", effectId: "trigger-limit-turn-response-opponent-open" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "trigger-limit-turn-response-first-followup", 6, "open"),
          absentWindowEffectGroup(0, "trigger-limit-turn-response-second-followup", 6, "open"),
          absentWindowEffectGroup(1, "trigger-limit-turn-response-opponent-limiter", 6, "open"),
          absentWindowEffectGroup(1, "trigger-limit-turn-response-opponent-followup", 6, "open"),
          absentWindowEffectGroup(1, "trigger-limit-turn-response-opponent-open", 6, "open"),
        ],
        logIncludes: [
          "Trigger limit turn response first followup resolved",
          "Trigger limit turn response opponent limiter resolved",
          "Trigger limit turn response success resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
