import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentTriggerActivationGroup, summonGroup, triggerActivationGroup, triggerDeclineGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity recovered-life-points missed timing fixtures", () => {
  it("keeps optional if triggers while optional when recovered-life-points triggers miss timing", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Recovery Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "400", name: "Recovery Optional When", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Recovery Optional If", kind: "monster", attack: 1200, defense: 1200 },
      { code: "600", name: "Boundary Body", kind: "monster", attack: 900, defense: 900 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "recovered-life-points missed timing fixture",
      options: { seed: 93, startingHandSize: 4 },
      decks: {
        0: { main: ["100", "400", "500", "600"] },
        1: { main: ["600", "600", "600", "600"] },
      },
      setup: {
        moveCards: [{ player: 0, code: "600", from: "hand", to: "monsterZone", position: "faceUpAttack" }],
        effects: [
          {
            id: "recovered-life-points-multistep",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            collectEventsOnResolve: [{
              collectEvent: "recoveredLifePoints",
              eventIsLast: false,
              eventPlayer: 0,
              eventValue: 900,
              eventReason: 0x40,
              eventReasonPlayer: 0,
              eventReasonCardUid: "p0-deck-100-0",
              eventReasonEffectId: 21,
            }],
            moveCardsOnResolve: [{ player: 0, code: "600", from: "monsterZone", to: "graveyard", collectEvent: "sentToGraveyard" }],
            logMessage: "Recovered-life-points multi step resolved",
          },
          {
            id: "recovered-life-points-optional-when",
            player: 0,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "recoveredLifePoints",
            triggerTiming: "when",
            range: ["hand"],
            logMessage: "Recovered-life-points optional when should not resolve",
          },
          {
            id: "recovered-life-points-optional-if",
            player: 0,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "recoveredLifePoints",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Recovered-life-points optional if resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "recovered-life-points-multistep" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the open ignition effect restorable before the multi-step life recovery event checks missed timing",
            windowId: 0,
            windowKind: "open",
            waitingFor: 0,
            phase: "main1",
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            legalActionCounts: { 0: 10, 1: 0 },
            legalActionGroupCounts: { 0: 4, 1: 0 },
            legalActions: [{ type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "recovered-life-points-multistep", count: 1 }],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "recovered-life-points-multistep", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "400", location: "hand" },
                { type: "normalSummon", player: 0, code: "500", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "400", location: "hand" },
                { type: "setMonster", player: 0, code: "500", location: "hand" },
              ], 1, 0),
              turnGroup(0),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro drops optional when recovered-life-points triggers when that recovery event is followed by another event, while optional if remains available",
            windowId: 1,
            windowKind: "triggerBucket",
            waitingFor: 0,
            pendingTriggers: [
              {
                player: 0,
                effectId: "recovered-life-points-optional-if",
                eventName: "recoveredLifePoints",
                eventCode: 1112,
                eventPlayer: 0,
                eventValue: 900,
                eventReason: 0x40,
                eventReasonPlayer: 0,
                eventReasonCardUid: "p0-deck-100-0",
                eventReasonEffectId: 21,
              },
            ],
            pendingTriggerBuckets: [{ player: 0, triggerBucket: "turnOptional" }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "recovered-life-points-optional-if", triggerBucket: "turnOptional", count: 1 },
              { type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "recovered-life-points-optional-if", triggerBucket: "turnOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(0, "recovered-life-points-optional-if", "turnOptional", 1, 1),
              triggerDeclineGroup(0, "recovered-life-points-optional-if", "turnOptional", 1, 1),
            ],
            absentLegalActions: [{ type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "recovered-life-points-optional-when" }],
            absentLegalActionGroups: [absentTriggerActivationGroup(0, "recovered-life-points-optional-when", "turnOptional", 1, "triggerBucket")],
            logIncludes: ["Recovered-life-points multi step resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "recovered-life-points-optional-if" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the surviving optional if recovered-life-points trigger restorable without resurrecting the missed optional when trigger",
            windowId: 1,
            windowKind: "triggerBucket",
            waitingFor: 0,
            pendingTriggers: [
              {
                player: 0,
                effectId: "recovered-life-points-optional-if",
                eventName: "recoveredLifePoints",
                eventCode: 1112,
                eventPlayer: 0,
                eventValue: 900,
                eventReason: 0x40,
                eventReasonPlayer: 0,
                eventReasonCardUid: "p0-deck-100-0",
                eventReasonEffectId: 21,
              },
            ],
            pendingTriggerBuckets: [{ player: 0, triggerBucket: "turnOptional" }],
            locationCounts: { graveyard: { "600": 1 }, hand: { "100": 1, "400": 1, "500": 1, "600": 4 } },
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "recovered-life-points-optional-if", triggerBucket: "turnOptional", count: 1 },
              { type: "declineTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "recovered-life-points-optional-if", triggerBucket: "turnOptional", count: 1 },
            ],
            legalActionGroups: [
              triggerActivationGroup(0, "recovered-life-points-optional-if", "turnOptional", 1, 1),
              triggerDeclineGroup(0, "recovered-life-points-optional-if", "turnOptional", 1, 1),
            ],
            absentLegalActions: [{ type: "activateTrigger", player: 0, windowId: 1, windowKind: "triggerBucket", effectId: "recovered-life-points-optional-when" }],
            absentLegalActionGroups: [absentTriggerActivationGroup(0, "recovered-life-points-optional-when", "turnOptional", 1, "triggerBucket")],
            logIncludes: ["Recovered-life-points multi step resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro resolves the surviving optional if recovered-life-points trigger after restore without resurrecting missed optional when triggers",
            windowId: 2,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [],
            chainPasses: [],
            legalActionCounts: { 0: 9, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 2, windowKind: "open", effectId: "recovered-life-points-multistep", count: 1 },
              { type: "normalSummon", player: 0, windowId: 2, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 2, windowKind: "open", code: "400", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 2, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 2, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 2, windowKind: "open", code: "400", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 2, windowKind: "open", code: "500", location: "hand", count: 1 },
              { type: "changePhase", player: 0, windowId: 2, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 2, windowKind: "open", count: 1 },
            ],
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 2,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 2, windowKind: "open", effectId: "recovered-life-points-multistep", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "400", location: "hand" },
                { type: "normalSummon", player: 0, code: "500", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "400", location: "hand" },
                { type: "setMonster", player: 0, code: "500", location: "hand" },
              ], 1, 2),
              turnGroup(2),
            ],
            absentLegalActions: [
              { type: "activateTrigger", player: 0, windowId: 2, windowKind: "open", effectId: "recovered-life-points-optional-when" },
              { type: "activateTrigger", player: 0, windowId: 2, windowKind: "open", effectId: "recovered-life-points-optional-if" },
            ],
            absentLegalActionGroups: [
              absentTriggerActivationGroup(0, "recovered-life-points-optional-when", "turnOptional", 2, "open"),
              absentTriggerActivationGroup(0, "recovered-life-points-optional-if", "turnOptional", 2, "open"),
            ],
            logIncludes: ["Recovered-life-points optional if resolved"],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro final state resolves the optional if recovered-life-points trigger without resurrecting the missed optional when trigger",
        windowId: 2,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        chain: [],
        chainPasses: [],
        locationCounts: { graveyard: { "600": 1 }, hand: { "100": 1, "400": 1, "500": 1, "600": 4 } },
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 2, windowKind: "open", effectId: "recovered-life-points-multistep", count: 1 },
          { type: "normalSummon", player: 0, windowId: 2, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 2, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 2, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 2, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 2, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 2, windowKind: "open", code: "500", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 2, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 2, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 2,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 2, windowKind: "open", effectId: "recovered-life-points-multistep", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "400", location: "hand" },
            { type: "normalSummon", player: 0, code: "500", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "400", location: "hand" },
            { type: "setMonster", player: 0, code: "500", location: "hand" },
          ], 1, 2),
          turnGroup(2),
        ],
        absentLegalActions: [{ type: "activateTrigger", player: 0, windowId: 2, windowKind: "open", effectId: "recovered-life-points-optional-when" }],
        absentLegalActionGroups: [absentTriggerActivationGroup(0, "recovered-life-points-optional-when", "turnOptional", 2, "open")],
        logIncludes: ["Recovered-life-points optional if resolved"],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
