import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  chainEffectGroup,
  chainPassGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution opponent same-bucket mandatory pass-handoff turn-response chain-limit fixture", () => {
  it("applies one-chain limits after the turn player answers a restored opponent mandatory handoff response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Opponent Mandatory Turn Limit Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Opponent Mandatory Turn Limit Turn Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Opponent Mandatory Turn Limit Turn Mandatory", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Opponent Mandatory Turn Limit First Opponent", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Opponent Mandatory Turn Limit Second Opponent", kind: "monster", attack: 1200, defense: 1200 },
      { code: "700", name: "Opponent Mandatory Turn Limit Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Mandatory Turn Limit Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Opponent Mandatory Turn Limit First Opponent Quick", kind: "monster", attack: 1600, defense: 1000 },
      { code: "950", name: "Opponent Mandatory Turn Limit Second Opponent Quick", kind: "monster", attack: 1300, defense: 1300 },
      { code: "970", name: "Opponent Mandatory Turn Limit Followup", kind: "monster", attack: 1200, defense: 1200 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution opponent same-bucket mandatory pass-handoff turn-response chain-limit fixture",
      options: { seed: 394, startingHandSize: 6 },
      decks: {
        0: { main: ["100", "200", "300", "700", "970", "800"] },
        1: { main: ["400", "500", "900", "950", "800", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "970", from: "hand", to: "graveyard" },
              { player: 1, code: "900", from: "hand", to: "graveyard" },
              { player: 1, code: "950", from: "hand", to: "graveyard" },
            ],
            logMessage: "Chain resolution opponent mandatory turn limit starter resolved",
          },
          {
            id: "fixture-chain-resolution-turn-mandatory-turn-response-chain-limit",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Chain resolution turn mandatory turn limit resolved",
          },
          {
            id: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Chain resolution first opponent mandatory turn limit resolved",
          },
          {
            id: "fixture-chain-resolution-second-opponent-mandatory-turn-response-chain-limit",
            player: 1,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            logMessage: "Chain resolution second opponent mandatory turn limit resolved",
          },
          {
            id: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            chainLimitOnTarget: { untilChainEnd: false, allowPlayer: 0 },
            logMessage: "Chain resolution opponent mandatory turn limit turn quick limiter resolved",
          },
          {
            id: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-followup",
            player: 0,
            code: "970",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            activationChain: "chain",
            logMessage: "Chain resolution opponent mandatory turn limit followup should not resolve",
          },
          {
            id: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick",
            player: 1,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain resolution opponent mandatory turn limit first opponent quick resolved",
          },
          {
            id: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-second-opponent-quick",
            player: 1,
            code: "950",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain resolution opponent mandatory turn limit second opponent quick should not resolve yet",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-starter" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-resolution-turn-mandatory-turn-response-chain-limit" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-chain-resolution-second-opponent-mandatory-turn-response-chain-limit" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit" })),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps restored opponent mandatory trigger-chain turn-response priority restorable before the turn player passes",
            phase: "main1",
            windowId: 4,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-resolution-turn-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-second-opponent-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
            ],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick", count: 1 },
              { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 4, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 4,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-followup", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 4),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick" },
              { type: "activateEffect", player: 1, windowId: 4, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-second-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 4, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick", 4),
              absentChainEffectGroup(1, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-second-opponent-quick", 4),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", "opponentMandatory", 4, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "970", "900", "950"], hand: ["100", "300", "800", "400", "500", "800", "800"] },
            logIncludes: ["Chain resolution opponent mandatory turn limit starter resolved"],
          },
          after: {
            source: "edopro",
            note: "EDOPro hands restored opponent mandatory trigger-chain responses to the opponent before any opponent handoff response is chosen",
            phase: "main1",
            windowId: 5,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-resolution-turn-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-second-opponent-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
            ],
            chainPasses: [0],
            chainLimits: [],
            legalActionCounts: { 0: 0, 1: 3 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick", count: 1 },
              { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-second-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 5, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 5,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick", count: 1 },
                  { type: "activateEffect", player: 1, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-second-opponent-quick", count: 1 },
                ],
              },
              chainPassGroup(1, 1, 5),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 5, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick" },
              { type: "activateTrigger", player: 1, windowId: 5, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick", 5),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", "opponentMandatory", 5, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "970", "900", "950"], hand: ["100", "300", "800", "400", "500", "800", "800"] },
            logIncludes: ["Chain resolution opponent mandatory turn limit starter resolved"],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps turn-player priority restorable before the restored opponent mandatory handoff SetChainLimit response is chosen",
            phase: "main1",
            windowId: 6,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-resolution-turn-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-second-opponent-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick", sourceUid: "p1-deck-900-2" },
            ],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick", count: 1 },
              { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 6, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 6,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick", count: 1 },
                  { type: "activateEffect", player: 0, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-followup", count: 1 },
                ],
              },
              chainPassGroup(0, 1, 6),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick" },
              { type: "activateEffect", player: 1, windowId: 6, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-second-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 6, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(1, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick", 6),
              absentChainEffectGroup(1, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-second-opponent-quick", 6),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", "opponentMandatory", 6, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "970", "900", "950"], hand: ["100", "300", "800", "400", "500", "800", "800"] },
          },
          after: {
            source: "edopro",
            note: "EDOPro applies one-chain SetChainLimit restrictions after the turn player answers a restored opponent mandatory handoff chain",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-resolution-turn-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-second-opponent-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick", sourceUid: "p1-deck-900-2" },
              { player: 0, effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 5 }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-followup", 1, 7),
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-second-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 7, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick", 7),
              absentChainEffectGroup(1, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick", 7),
              absentChainEffectGroup(1, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-second-opponent-quick", 7),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", "opponentMandatory", 7, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "970", "900", "950"], hand: ["100", "300", "800", "400", "500", "800", "800"] },
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 0), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the restored opponent mandatory turn-response SetChainLimit window restorable before the allowed turn player passes",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "fixture-chain-resolution-turn-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-second-opponent-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick", sourceUid: "p1-deck-900-2" },
              { player: 0, effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 5 }],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-followup", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-followup", 1, 7),
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-second-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 7, windowKind: "triggerBucket", effectId: "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", triggerBucket: "opponentMandatory" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-turn-quick", 7),
              absentChainEffectGroup(1, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-first-opponent-quick", 7),
              absentChainEffectGroup(1, "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-second-opponent-quick", 7),
              absentTriggerActivationGroup(1, "fixture-chain-resolution-first-opponent-mandatory-turn-response-chain-limit", "opponentMandatory", 7, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "970", "900", "950"], hand: ["100", "300", "800", "400", "500", "800", "800"] },
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro clears one-chain limits and resolves restored opponent mandatory handoff chains after the allowed turn player passes",
        phase: "main1",
        windowId: 8,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        locations: { graveyard: ["700", "200", "970", "900", "950"], hand: ["100", "300", "800", "400", "500", "800", "800"] },
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 8,
            windowKind: "open",
            count: 1,
            actions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-chain-resolution-opponent-mandatory-turn-response-chain-limit-starter", count: 1 },
            ],
          },
          {
            player: 0,
            label: "Summons",
            windowId: 8,
            windowKind: "open",
            count: 1,
            actions: [
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "800", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "800", location: "hand", count: 1 },
            ],
          },
          {
            player: 0,
            label: "Turn",
            windowId: 8,
            windowKind: "open",
            count: 1,
            actions: [
              { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
            ],
          },
        ],
        logIncludes: [
          "Chain resolution opponent mandatory turn limit turn quick limiter resolved",
          "Chain resolution opponent mandatory turn limit first opponent quick resolved",
          "Chain resolution first opponent mandatory turn limit resolved",
          "Chain resolution second opponent mandatory turn limit resolved",
          "Chain resolution turn mandatory turn limit resolved",
          "Chain resolution opponent mandatory turn limit starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
