import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity Main Phase 2 chain-response handoff opponent-response chain-limit fixture", () => {
  it("applies one-chain limits after the opponent responds to a Main Phase 2 chain-response handoff", () => {
    const cards: DuelCardData[] = [
      { code: "110", name: "Main2 Opponent Response Limit Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "130", name: "Main2 Opponent Response Limit Turn First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "140", name: "Main2 Opponent Response Limit Turn Blocked Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "150", name: "Main2 Opponent Response Limit Turn Filler", kind: "monster", attack: 1000, defense: 1000 },
      { code: "210", name: "Main2 Opponent Response Limit Opponent First Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "230", name: "Main2 Opponent Response Limit Opponent Second Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "240", name: "Main2 Opponent Response Limit Opponent Chain Limiter", kind: "monster", attack: 1000, defense: 1000 },
      { code: "250", name: "Main2 Opponent Response Limit Opponent Followup", kind: "monster", attack: 1000, defense: 1000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "main2 chain-response handoff opponent-response chain limit fixture",
      options: { seed: 296, startingHandSize: 4 },
      decks: {
        0: { main: ["110", "130", "140", "150"] },
        1: { main: ["210", "230", "240", "250"] },
      },
      setup: {
        effects: [
          {
            id: "main2-opponent-response-limit-open-quick",
            player: 0,
            code: "110",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "open",
            oncePerTurn: true,
            logMessage: "Main2 opponent-response limit open quick resolved",
          },
          {
            id: "main2-opponent-response-limit-turn-first",
            player: 0,
            code: "130",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Main2 opponent-response limit turn first quick resolved",
          },
          {
            id: "main2-opponent-response-limit-turn-blocked",
            player: 0,
            code: "140",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Main2 opponent-response limit turn blocked quick should not resolve",
          },
          {
            id: "main2-opponent-response-limit-opponent-first",
            player: 1,
            code: "210",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Main2 opponent-response limit opponent first quick resolved",
          },
          {
            id: "main2-opponent-response-limit-opponent-second",
            player: 1,
            code: "230",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            logMessage: "Main2 opponent-response limit opponent second quick resolved",
          },
          {
            id: "main2-opponent-response-limit-opponent-chain-limiter",
            player: 1,
            code: "240",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            oncePerTurn: true,
            chainLimitOnTarget: { untilChainEnd: false, allowPlayer: 1 },
            logMessage: "Main2 opponent-response limit opponent chain limiter resolved",
          },
          {
            id: "main2-opponent-response-limit-opponent-followup",
            player: 1,
            code: "250",
            location: "hand",
            event: "quick",
            range: ["hand"],
            activationChain: "chain",
            logMessage: "Main2 opponent-response limit opponent followup should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("changePhase", 0, { phase: "battle" })),
        makeScriptedStep(makeResponseSelector("changePhase", 0, { phase: "main2" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "main2-opponent-response-limit-open-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "main2-opponent-response-limit-opponent-first" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "main2-opponent-response-limit-opponent-second" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "main2-opponent-response-limit-turn-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "main2-opponent-response-limit-opponent-chain-limiter" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps Main Phase 2 opponent response priority restorable before the opponent applies a one-chain limit",
            phase: "main2",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "main2-opponent-response-limit-open-quick", sourceUid: "p0-deck-110-0" },
              { player: 1, effectId: "main2-opponent-response-limit-opponent-first", sourceUid: "p1-deck-210-0" },
              { player: 1, effectId: "main2-opponent-response-limit-opponent-second", sourceUid: "p1-deck-230-1" },
              { player: 0, effectId: "main2-opponent-response-limit-turn-first", sourceUid: "p0-deck-130-1" },
            ],
            chainPasses: [],
            chainLimits: [],
            legalActionCounts: { 0: 0, 1: 3 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "main2-opponent-response-limit-opponent-chain-limiter", count: 1 },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "main2-opponent-response-limit-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 1,
                label: "Effects",
                windowId: 7,
                windowKind: "chainResponse",
                count: 1,
                actions: [
                  { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "main2-opponent-response-limit-opponent-chain-limiter", count: 1 },
                  { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "main2-opponent-response-limit-opponent-followup", count: 1 },
                ],
              },
              chainPassGroup(1, 1, 7),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "main2-opponent-response-limit-turn-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "main2-opponent-response-limit-turn-blocked", 7)],
          },
          after: {
            source: "edopro",
            note: "EDOPro keeps Main Phase 2 active and applies one-chain SetChainLimit restrictions after the opponent responds to a chain-response handoff",
            phase: "main2",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "main2-opponent-response-limit-open-quick", sourceUid: "p0-deck-110-0" },
              { player: 1, effectId: "main2-opponent-response-limit-opponent-first", sourceUid: "p1-deck-210-0" },
              { player: 1, effectId: "main2-opponent-response-limit-opponent-second", sourceUid: "p1-deck-230-1" },
              { player: 0, effectId: "main2-opponent-response-limit-turn-first", sourceUid: "p0-deck-130-1" },
              { player: 1, effectId: "main2-opponent-response-limit-opponent-chain-limiter", sourceUid: "p1-deck-240-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 5 }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "main2-opponent-response-limit-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "main2-opponent-response-limit-opponent-followup", 1, 8),
              chainPassGroup(1, 1, 8),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "main2-opponent-response-limit-turn-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "main2-opponent-response-limit-turn-blocked", 8)],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the Main Phase 2 opponent-response SetChainLimit response window restorable before the allowed opponent passes",
            phase: "main2",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 0, effectId: "main2-opponent-response-limit-open-quick", sourceUid: "p0-deck-110-0" },
              { player: 1, effectId: "main2-opponent-response-limit-opponent-first", sourceUid: "p1-deck-210-0" },
              { player: 1, effectId: "main2-opponent-response-limit-opponent-second", sourceUid: "p1-deck-230-1" },
              { player: 0, effectId: "main2-opponent-response-limit-turn-first", sourceUid: "p0-deck-130-1" },
              { player: 1, effectId: "main2-opponent-response-limit-opponent-chain-limiter", sourceUid: "p1-deck-240-2" },
            ],
            chainPasses: [],
            chainLimits: [{ untilChainEnd: false, expiresAtChainLength: 5 }],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "main2-opponent-response-limit-opponent-followup", count: 1 },
              { type: "passChain", player: 1, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "main2-opponent-response-limit-opponent-followup", 1, 8),
              chainPassGroup(1, 1, 8),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "main2-opponent-response-limit-turn-blocked" }],
            absentLegalActionGroups: [absentChainEffectGroup(0, "main2-opponent-response-limit-turn-blocked", 8)],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro keeps Main Phase 2 active and clears one-chain limits after the allowed opponent passes the opponent-response handoff chain",
        phase: "main2",
        windowId: 9,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        chainLimits: [],
        legalActionCounts: { 0: 10, 1: 0 },
        legalActionGroupCounts: { 0: 2, 1: 0 },
        legalActions: [
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "110", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "130", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "140", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 9, windowKind: "open", code: "150", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "110", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "130", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "140", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 9, windowKind: "open", code: "150", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 9, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 9, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          summonGroup([
            { type: "normalSummon", player: 0, code: "110", location: "hand" },
            { type: "normalSummon", player: 0, code: "130", location: "hand" },
            { type: "normalSummon", player: 0, code: "140", location: "hand" },
            { type: "normalSummon", player: 0, code: "150", location: "hand" },
            { type: "setMonster", player: 0, code: "110", location: "hand" },
            { type: "setMonster", player: 0, code: "130", location: "hand" },
            { type: "setMonster", player: 0, code: "140", location: "hand" },
            { type: "setMonster", player: 0, code: "150", location: "hand" },
          ], 1, 9),
          turnGroup(9),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "main2-opponent-response-limit-open-quick" },
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "main2-opponent-response-limit-turn-first" },
          { type: "activateEffect", player: 0, windowId: 9, windowKind: "open", effectId: "main2-opponent-response-limit-turn-blocked" },
          { type: "activateEffect", player: 1, windowId: 9, windowKind: "open", effectId: "main2-opponent-response-limit-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 9, windowKind: "open", effectId: "main2-opponent-response-limit-opponent-second" },
          { type: "activateEffect", player: 1, windowId: 9, windowKind: "open", effectId: "main2-opponent-response-limit-opponent-chain-limiter" },
          { type: "activateEffect", player: 1, windowId: 9, windowKind: "open", effectId: "main2-opponent-response-limit-opponent-followup" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "main2-opponent-response-limit-open-quick", 9, "open"),
          absentWindowEffectGroup(0, "main2-opponent-response-limit-turn-first", 9, "open"),
          absentWindowEffectGroup(0, "main2-opponent-response-limit-turn-blocked", 9, "open"),
          absentWindowEffectGroup(1, "main2-opponent-response-limit-opponent-first", 9, "open"),
          absentWindowEffectGroup(1, "main2-opponent-response-limit-opponent-second", 9, "open"),
          absentWindowEffectGroup(1, "main2-opponent-response-limit-opponent-chain-limiter", 9, "open"),
          absentWindowEffectGroup(1, "main2-opponent-response-limit-opponent-followup", 9, "open"),
        ],
        logIncludes: [
          "Main2 opponent-response limit opponent chain limiter resolved",
          "Main2 opponent-response limit turn first quick resolved",
          "Main2 opponent-response limit opponent second quick resolved",
          "Main2 opponent-response limit opponent first quick resolved",
          "Main2 opponent-response limit open quick resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
