import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup, summonGroup, turnGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chainEnded open fast-effect chain-response turn-response opponent-response turn-response opponent-response turn-response opponent-response pass-resolution fixture", () => {
  it("resolves when the opponent passes after the turn player chains a third time to a direct post-chainEnded opponent response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass Solved Blocker", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass Cleanup", kind: "monster", attack: 1500, defense: 1600 },
      { code: "400", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass Open Quick", kind: "monster", attack: 1200, defense: 1200 },
      { code: "500", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass First Opponent Chain", kind: "monster", attack: 1100, defense: 1100 },
      { code: "600", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass First Turn Chain", kind: "monster", attack: 900, defense: 900 },
      { code: "700", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass Opponent Open Quick", kind: "monster", attack: 800, defense: 800 },
      { code: "800", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass Second Opponent Chain", kind: "monster", attack: 700, defense: 700 },
      { code: "900", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass Second Turn Chain", kind: "monster", attack: 650, defense: 650 },
      { code: "1000", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass Third Opponent Chain", kind: "monster", attack: 600, defense: 600 },
      { code: "1100", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass Third Turn Chain", kind: "monster", attack: 550, defense: 550 },
      { code: "1200", name: "Chain Ended Direct Opponent Turn Opponent Turn Opponent Pass Fourth Opponent Chain", kind: "monster", attack: 500, defense: 500 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "deferred chain ended open fast chain response turn response opponent-response turn-response opponent-response turn-response opponent-response pass-resolution fixture",
      options: { seed: 654, startingHandSize: 7 },
      decks: {
        0: { main: ["100", "200", "300", "400", "600", "900", "1100"] },
        1: { main: ["500", "800", "1000", "1200", "700"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "600", from: "hand", to: "graveyard" },
          { player: 0, code: "900", from: "hand", to: "graveyard" },
          { player: 0, code: "1100", from: "hand", to: "graveyard" },
          { player: 1, code: "500", from: "hand", to: "graveyard" },
          { player: 1, code: "800", from: "hand", to: "graveyard" },
          { player: 1, code: "1000", from: "hand", to: "graveyard" },
          { player: 1, code: "1200", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass starter resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-solved-blocker",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainSolved",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass solved blocker should not resolve",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-cleanup",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            moveCardsOnResolve: [
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "600", from: "graveyard", to: "hand" },
              { player: 0, code: "900", from: "graveyard", to: "hand" },
              { player: 0, code: "1100", from: "graveyard", to: "hand" },
              { player: 1, code: "500", from: "graveyard", to: "hand" },
              { player: 1, code: "800", from: "graveyard", to: "hand" },
              { player: 1, code: "1000", from: "graveyard", to: "hand" },
              { player: 1, code: "1200", from: "graveyard", to: "hand" },
            ],
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass cleanup resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-open-fast",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass open fast resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-first-turn",
            player: 0,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass first turn chain resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-second-turn",
            player: 0,
            code: "900",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass second turn chain resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-third-turn",
            player: 0,
            code: "1100",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass third turn chain resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-first",
            player: 1,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass opponent first resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-open",
            player: 1,
            code: "700",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass opponent open should not resolve",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-second",
            player: 1,
            code: "800",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass opponent second resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-third",
            player: 1,
            code: "1000",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass opponent third resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-fourth",
            player: 1,
            code: "1200",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent turn opponent pass opponent fourth should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-solved-blocker" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-cleanup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-open-fast" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-first-turn" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-second" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-second-turn" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-third" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-third-turn" })),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the opponent response window restorable after the turn player chains a third time to a direct post-chainEnded opponent response",
            phase: "main1",
            windowId: 10,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-first", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-first-turn", sourceUid: "p0-deck-600-4" },
              { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-second", sourceUid: "p1-deck-800-1" },
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-second-turn", sourceUid: "p0-deck-900-5" },
              { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-third", sourceUid: "p1-deck-1000-2" },
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-third-turn", sourceUid: "p0-deck-1100-6" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chainLimits: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-fourth", count: 1 },
              { type: "passChain", player: 1, windowId: 10, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-fourth", 1, 10),
              chainPassGroup(1, 1, 10),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-open-fast" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-first-turn" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-second-turn" },
              { type: "activateEffect", player: 0, windowId: 10, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-third-turn" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-first" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-second" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-third" },
              { type: "activateEffect", player: 1, windowId: 10, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-open" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-open-fast", 10, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-first-turn", 10),
              absentChainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-second-turn", 10),
              absentChainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-third-turn", 10),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-first", 10),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-second", 10),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-third", 10),
              absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-open", 10, "chainResponse"),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves direct post-chainEnded opponent-response chains after the opponent passes the response window returned by the turn player",
        phase: "main1",
        windowId: 11,
        windowKind: "open",
        waitingFor: 0,
        chain: [],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chainLimits: [],
        locations: { graveyard: ["200"], hand: ["100", "300", "400", "600", "900", "1100", "500", "800", "1000", "1200", "700"] },
        legalActionCounts: { 0: 15, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 11, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 11, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 11, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 11, windowKind: "open", code: "600", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 11, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 11, windowKind: "open", code: "1100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 11, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 11, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 11, windowKind: "open", code: "400", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 11, windowKind: "open", code: "600", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 11, windowKind: "open", code: "900", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 11, windowKind: "open", code: "1100", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 11, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 11, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 11,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "400", location: "hand" },
            { type: "normalSummon", player: 0, code: "600", location: "hand" },
            { type: "normalSummon", player: 0, code: "900", location: "hand" },
            { type: "normalSummon", player: 0, code: "1100", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "400", location: "hand" },
            { type: "setMonster", player: 0, code: "600", location: "hand" },
            { type: "setMonster", player: 0, code: "900", location: "hand" },
            { type: "setMonster", player: 0, code: "1100", location: "hand" },
          ], 1, 11),
          turnGroup(11),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-open-fast" },
          { type: "activateEffect", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-first-turn" },
          { type: "activateEffect", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-second-turn" },
          { type: "activateEffect", player: 0, windowId: 11, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-third-turn" },
          { type: "activateEffect", player: 1, windowId: 11, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 11, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-second" },
          { type: "activateEffect", player: 1, windowId: 11, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-third" },
          { type: "activateEffect", player: 1, windowId: 11, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-fourth" },
          { type: "activateEffect", player: 1, windowId: 11, windowKind: "open", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-open" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-open-fast", 11, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-first-turn", 11, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-second-turn", 11, "open"),
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-third-turn", 11, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-first", 11, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-second", 11, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-third", 11, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-fourth", 11, "open"),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-turn-opponent-pass-opponent-open", 11, "open"),
        ],
        logIncludes: [
          "Chain ended direct opponent turn opponent turn opponent pass third turn chain resolved",
          "Chain ended direct opponent turn opponent turn opponent pass opponent third resolved",
          "Chain ended direct opponent turn opponent turn opponent pass second turn chain resolved",
          "Chain ended direct opponent turn opponent turn opponent pass opponent second resolved",
          "Chain ended direct opponent turn opponent turn opponent pass first turn chain resolved",
          "Chain ended direct opponent turn opponent turn opponent pass opponent first resolved",
          "Chain ended direct opponent turn opponent turn opponent pass open fast resolved",
          "Chain ended direct opponent turn opponent turn opponent pass cleanup resolved",
          "Chain ended direct opponent turn opponent turn opponent pass starter resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
