import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentSummonGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity Ritual Summon open fast-effect chain fixture", () => {
  it("opens opponent chain responses after a triggerless Ritual Summon open fast effect", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Open Fast Ritual Chain Material A", kind: "monster", attack: 1000, defense: 1000 },
      { code: "200", name: "Open Fast Ritual Chain Material B", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Turn Ritual Chain Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Opponent Ritual Chain Response", kind: "monster", attack: 1000, defense: 1000 },
      { code: "500", name: "Opponent Ritual Chain Open Quick", kind: "monster", attack: 1000, defense: 1000 },
      { code: "900", name: "Open Fast Ritual Chain Monster", kind: "monster", ritualMaterials: ["100", "200"], attack: 2000, defense: 2000 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "ritual summon open fast chain-response fixture",
      options: { seed: 370, startingHandSize: 4 },
      decks: {
        0: { main: ["900", "100", "200", "300"] },
        1: { main: ["400", "500", "400"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "300", from: "hand", to: "graveyard" },
          { player: 1, code: "400", from: "hand", to: "graveyard" },
          { player: 1, code: "500", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "ritual-summon-turn-open-chain-quick",
            player: 0,
            code: "300",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Turn open quick after Ritual Summon chain resolved",
          },
          {
            id: "ritual-summon-opponent-chain-response-quick",
            player: 1,
            code: "400",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Opponent chain quick after Ritual Summon should not resolve",
          },
          {
            id: "ritual-summon-opponent-open-chain-filtered",
            player: 1,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["graveyard"],
            activationChain: "open",
            logMessage: "Opponent open quick after Ritual Summon chain should not resolve",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("ritualSummon", 0, { code: "900", location: "hand", materialUids: ["p0-deck-100-1", "p0-deck-200-2"] }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro exposes Ritual Summons beside turn-player open fast effects before the Ritual Summon is performed",
            phase: "main1",
            windowId: 0,
            windowKind: "open",
            waitingFor: 0,
            legalActionCounts: { 0: 10, 1: 0 },
            legalActionGroupCounts: { 0: 3, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "ritual-summon-turn-open-chain-quick", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "900", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "normalSummon", player: 0, windowId: 0, windowKind: "open", code: "200", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "900", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "100", location: "hand", count: 1 },
              { type: "setMonster", player: 0, windowId: 0, windowKind: "open", code: "200", location: "hand", count: 1 },
              { type: "ritualSummon", player: 0, windowId: 0, windowKind: "open", code: "900", location: "hand", materialUids: ["p0-deck-100-1", "p0-deck-200-2"], count: 1 },
              { type: "changePhase", player: 0, windowId: 0, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 0, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 0,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 0, windowKind: "open", effectId: "ritual-summon-turn-open-chain-quick", count: 1 }],
              },
              summonGroup([
                { type: "normalSummon", player: 0, code: "900", location: "hand" },
                { type: "normalSummon", player: 0, code: "100", location: "hand" },
                { type: "normalSummon", player: 0, code: "200", location: "hand" },
                { type: "setMonster", player: 0, code: "900", location: "hand" },
                { type: "setMonster", player: 0, code: "100", location: "hand" },
                { type: "setMonster", player: 0, code: "200", location: "hand" },
                { type: "ritualSummon", player: 0, code: "900", location: "hand", materialUids: ["p0-deck-100-1", "p0-deck-200-2"] },
              ], 1, 0),
              turnGroup(0),
            ],
            locations: { hand: ["900", "100", "200"], graveyard: ["300", "400", "500"] },
            absentLegalActions: [
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "ritual-summon-opponent-chain-response-quick" },
              { type: "activateEffect", player: 1, windowId: 0, windowKind: "open", effectId: "ritual-summon-opponent-open-chain-filtered" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(1, "ritual-summon-opponent-chain-response-quick", 0, "open"),
              absentWindowEffectGroup(1, "ritual-summon-opponent-open-chain-filtered", 0, "open"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns triggerless Ritual Summons to turn-player open priority with that player's open fast effects available",
            phase: "main1",
            windowId: 1,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            chain: [],
            chainPasses: [],
            locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "400", "500"] },
            cards: [
              { uid: "p0-deck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
              { uid: "p0-deck-100-1", code: "100", location: "graveyard" },
              { uid: "p0-deck-200-2", code: "200", location: "graveyard" },
            ],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "ritual-summon-turn-open-chain-quick", count: 1 },
              { type: "changePhase", player: 0, windowId: 1, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 1, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 1,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "ritual-summon-turn-open-chain-quick", count: 1 }],
              },
              turnGroup(1),
            ],
            absentLegalActions: [
              { type: "ritualSummon", player: 0, windowId: 1, windowKind: "open", code: "900", location: "hand" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "ritual-summon-opponent-chain-response-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "ritual-summon-opponent-open-chain-filtered" },
            ],
            absentLegalActionGroups: [
              absentSummonGroup({ type: "ritualSummon", player: 0, code: "900", location: "hand" }, 1),
              absentWindowEffectGroup(1, "ritual-summon-opponent-chain-response-quick", 1, "open"),
              absentWindowEffectGroup(1, "ritual-summon-opponent-open-chain-filtered", 1, "open"),
            ],
          },
        }),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "ritual-summon-turn-open-chain-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves post-Ritual-Summon turn-player open priority before a fast effect starts a chain",
            phase: "main1",
            windowId: 1,
            windowKind: "open",
            waitingFor: 0,
            pendingTriggers: [],
            chain: [],
            chainPasses: [],
            locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "400", "500"] },
            cards: [
              { uid: "p0-deck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
              { uid: "p0-deck-100-1", code: "100", location: "graveyard" },
              { uid: "p0-deck-200-2", code: "200", location: "graveyard" },
            ],
            legalActionCounts: { 0: 3, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "ritual-summon-turn-open-chain-quick", count: 1 },
              { type: "changePhase", player: 0, windowId: 1, windowKind: "open", count: 1 },
              { type: "endTurn", player: 0, windowId: 1, windowKind: "open", count: 1 },
            ],
            legalActionGroups: [
              {
                player: 0,
                label: "Effects",
                windowId: 1,
                windowKind: "open",
                count: 1,
                actions: [{ type: "activateEffect", player: 0, windowId: 1, windowKind: "open", effectId: "ritual-summon-turn-open-chain-quick", count: 1 }],
              },
              turnGroup(1),
            ],
            absentLegalActions: [
              { type: "ritualSummon", player: 0, windowId: 1, windowKind: "open", code: "900", location: "hand" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "ritual-summon-opponent-chain-response-quick" },
              { type: "activateEffect", player: 1, windowId: 1, windowKind: "open", effectId: "ritual-summon-opponent-open-chain-filtered" },
            ],
            absentLegalActionGroups: [
              absentSummonGroup({ type: "ritualSummon", player: 0, code: "900", location: "hand" }, 1),
              absentWindowEffectGroup(1, "ritual-summon-opponent-chain-response-quick", 1, "open"),
              absentWindowEffectGroup(1, "ritual-summon-opponent-open-chain-filtered", 1, "open"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro gives the opponent chain-response priority after a post-Ritual-Summon open fast effect starts a chain",
            phase: "main1",
            windowId: 2,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            chain: [{ player: 0, effectId: "ritual-summon-turn-open-chain-quick", sourceUid: "p0-deck-300-3" }],
            chainPasses: [],
            locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "400", "500"] },
            cards: [
              { uid: "p0-deck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
              { uid: "p0-deck-100-1", code: "100", location: "graveyard" },
              { uid: "p0-deck-200-2", code: "200", location: "graveyard" },
            ],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 2, windowKind: "chainResponse", effectId: "ritual-summon-opponent-chain-response-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 2, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "ritual-summon-opponent-chain-response-quick", 1, 2),
              chainPassGroup(1, 1, 2),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 2, windowKind: "chainResponse", effectId: "ritual-summon-opponent-open-chain-filtered" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "ritual-summon-opponent-open-chain-filtered", 2)],
          },
        }),
        makeScriptedStep(makeResponseSelector("passChain", 1), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored opponent chain-response priority before passing the post-Ritual-Summon fast-effect chain",
            phase: "main1",
            windowId: 2,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            chain: [{ player: 0, effectId: "ritual-summon-turn-open-chain-quick", sourceUid: "p0-deck-300-3" }],
            chainPasses: [],
            locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "400", "500"] },
            cards: [
              { uid: "p0-deck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
              { uid: "p0-deck-100-1", code: "100", location: "graveyard" },
              { uid: "p0-deck-200-2", code: "200", location: "graveyard" },
            ],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 2, windowKind: "chainResponse", effectId: "ritual-summon-opponent-chain-response-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 2, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "ritual-summon-opponent-chain-response-quick", 1, 2),
              chainPassGroup(1, 1, 2),
            ],
            absentLegalActions: [{ type: "activateEffect", player: 1, windowId: 2, windowKind: "chainResponse", effectId: "ritual-summon-opponent-open-chain-filtered" }],
            absentLegalActionGroups: [absentChainEffectGroup(1, "ritual-summon-opponent-open-chain-filtered", 2)],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro keeps turn-player open priority after resolving a post-Ritual-Summon open fast-effect chain",
        phase: "main1",
        windowId: 3,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        chain: [],
        chainPasses: [],
        locations: { monsterZone: ["900"], graveyard: ["100", "200", "300", "400", "500"] },
        cards: [
          { uid: "p0-deck-900-0", code: "900", location: "monsterZone", position: "faceUpAttack", faceUp: true },
          { uid: "p0-deck-100-1", code: "100", location: "graveyard" },
          { uid: "p0-deck-200-2", code: "200", location: "graveyard" },
        ],
        legalActionCounts: { 0: 2, 1: 0 },
        legalActionGroupCounts: { 0: 1, 1: 0 },
        legalActions: [
          { type: "changePhase", player: 0, windowId: 3, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 3, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [turnGroup(3)],
        absentLegalActions: [
          { type: "ritualSummon", player: 0, windowId: 3, windowKind: "open", code: "900", location: "hand" },
          { type: "activateEffect", player: 0, windowId: 3, windowKind: "open", effectId: "ritual-summon-turn-open-chain-quick" },
          { type: "activateEffect", player: 1, windowId: 3, windowKind: "open", effectId: "ritual-summon-opponent-chain-response-quick" },
          { type: "activateEffect", player: 1, windowId: 3, windowKind: "open", effectId: "ritual-summon-opponent-open-chain-filtered" },
        ],
        absentLegalActionGroups: [
          absentSummonGroup({ type: "ritualSummon", player: 0, code: "900", location: "hand" }, 3),
          absentWindowEffectGroup(0, "ritual-summon-turn-open-chain-quick", 3, "open"),
          absentWindowEffectGroup(1, "ritual-summon-opponent-chain-response-quick", 3, "open"),
          absentWindowEffectGroup(1, "ritual-summon-opponent-open-chain-filtered", 3, "open"),
        ],
        logIncludes: ["Turn open quick after Ritual Summon chain resolved"],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
