import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import {
  absentChainEffectGroup,
  absentTriggerActivationGroup,
  absentWindowEffectGroup,
  chainEffectGroup,
  chainPassGroup,
  summonGroup,
  turnGroup,
} from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chain-resolution opponent same-bucket optional decline pass-handoff turn-response opponent-response resolution fixture", () => {
  it("resolves after the opponent uses the final response reopened by the turn player", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Opponent Optional Decline Turn Opponent Resolution Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Opponent Optional Decline Turn Opponent Resolution Turn Quick", kind: "monster", attack: 1400, defense: 1400 },
      { code: "300", name: "Opponent Optional Decline Turn Opponent Resolution Turn Optional", kind: "monster", attack: 1000, defense: 1000 },
      { code: "400", name: "Opponent Optional Decline Turn Opponent Resolution First Opponent", kind: "monster", attack: 1500, defense: 1600 },
      { code: "500", name: "Opponent Optional Decline Turn Opponent Resolution Second Opponent", kind: "monster", attack: 1200, defense: 1200 },
      { code: "700", name: "Opponent Optional Decline Turn Opponent Resolution Moved Body", kind: "monster", attack: 900, defense: 900 },
      { code: "800", name: "Opponent Optional Decline Turn Opponent Resolution Filler", kind: "monster", attack: 800, defense: 800 },
      { code: "900", name: "Opponent Optional Decline Turn Opponent Resolution First Opponent Quick", kind: "monster", attack: 1600, defense: 1000 },
      { code: "950", name: "Opponent Optional Decline Turn Opponent Resolution Second Opponent Quick", kind: "monster", attack: 1300, defense: 1300 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "chain resolution opponent same-bucket optional decline pass-handoff turn-response opponent-response resolution fixture",
      options: { seed: 364, startingHandSize: 5 },
      decks: {
        0: { main: ["100", "200", "300", "700", "800"] },
        1: { main: ["400", "500", "900", "950", "800"] },
      },
      setup: {
        effects: [
          {
            id: "fixture-opponent-optional-decline-turn-opponent-resolution-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            moveCardsOnResolve: [
              { player: 0, code: "700", from: "hand", to: "graveyard", collectEvent: "sentToGraveyard" },
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 1, code: "900", from: "hand", to: "graveyard" },
              { player: 1, code: "950", from: "hand", to: "graveyard" },
            ],
            logMessage: "Opponent optional decline turn opponent resolution starter resolved",
          },
          {
            id: "fixture-opponent-optional-decline-turn-opponent-resolution-turn-optional",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Opponent optional decline turn opponent resolution turn optional should not resolve",
          },
          {
            id: "fixture-opponent-optional-decline-turn-opponent-resolution-first-opponent",
            player: 1,
            code: "400",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Opponent optional decline turn opponent resolution first opponent resolved",
          },
          {
            id: "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent",
            player: 1,
            code: "500",
            location: "hand",
            event: "trigger",
            triggerEvent: "sentToGraveyard",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Opponent optional decline turn opponent resolution second opponent should not resolve",
          },
          {
            id: "fixture-opponent-optional-decline-turn-opponent-resolution-turn-quick",
            player: 0,
            code: "200",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Opponent optional decline turn opponent resolution turn quick resolved",
          },
          {
            id: "fixture-opponent-optional-decline-turn-opponent-resolution-first-opponent-quick",
            player: 1,
            code: "900",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Opponent optional decline turn opponent resolution first opponent quick resolved",
          },
          {
            id: "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent-quick",
            player: 1,
            code: "950",
            location: "hand",
            event: "quick",
            range: ["graveyard"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Opponent optional decline turn opponent resolution second opponent quick resolved",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-turn-optional" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 1, { effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 1, { effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-first-opponent" })),
        makeScriptedStep(makeResponseSelector("passChain", 0)),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-first-opponent-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-turn-quick" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent-quick" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro keeps the decline-first restored opponent optional turn-response opponent-response window restorable before the opponent's final response",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 1,
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chain: [
              { player: 1, effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-first-opponent", eventName: "sentToGraveyard", eventCardUid: "p0-deck-700-3" },
              { player: 1, effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-first-opponent-quick", sourceUid: "p1-deck-900-2" },
              { player: 0, effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-turn-quick", sourceUid: "p0-deck-200-1" },
            ],
            chainPasses: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent-quick", count: 1 },
              { type: "passChain", player: 1, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent-quick", 1, 7),
              chainPassGroup(1, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-turn-quick" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-first-opponent-quick" },
              { type: "activateTrigger", player: 1, windowId: 7, windowKind: "triggerBucket", effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent", triggerBucket: "opponentOptional" },
            ],
            absentLegalActionGroups: [
              absentChainEffectGroup(0, "fixture-opponent-optional-decline-turn-opponent-resolution-turn-quick", 7),
              absentChainEffectGroup(1, "fixture-opponent-optional-decline-turn-opponent-resolution-first-opponent-quick", 7),
              absentTriggerActivationGroup(1, "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent", "opponentOptional", 7, "chainResponse"),
            ],
            locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "800", "400", "500", "800"] },
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro resolves decline-first restored opponent optional handoff chains after the opponent's final response when the turn player has no remaining response",
        phase: "main1",
        windowId: 8,
        windowKind: "open",
        waitingFor: 0,
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chain: [],
        chainPasses: [],
        legalActionCounts: { 0: 9, 1: 0 },
        legalActionGroupCounts: { 0: 3, 1: 0 },
        legalActions: [
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-starter", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "normalSummon", player: 0, windowId: 8, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "100", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "300", location: "hand", count: 1 },
          { type: "setMonster", player: 0, windowId: 8, windowKind: "open", code: "800", location: "hand", count: 1 },
          { type: "changePhase", player: 0, windowId: 8, windowKind: "open", count: 1 },
          { type: "endTurn", player: 0, windowId: 8, windowKind: "open", count: 1 },
        ],
        legalActionGroups: [
          {
            player: 0,
            label: "Effects",
            windowId: 8,
            windowKind: "open",
            count: 1,
            actions: [{ type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-starter", count: 1 }],
          },
          summonGroup([
            { type: "normalSummon", player: 0, code: "100", location: "hand" },
            { type: "normalSummon", player: 0, code: "300", location: "hand" },
            { type: "normalSummon", player: 0, code: "800", location: "hand" },
            { type: "setMonster", player: 0, code: "100", location: "hand" },
            { type: "setMonster", player: 0, code: "300", location: "hand" },
            { type: "setMonster", player: 0, code: "800", location: "hand" },
          ], 1, 8),
          turnGroup(8),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-turn-quick" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-first-opponent-quick" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "open", effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent-quick" },
          { type: "activateTrigger", player: 0, windowId: 8, windowKind: "open", effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-turn-optional" },
          { type: "activateTrigger", player: 1, windowId: 8, windowKind: "open", effectId: "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-opponent-optional-decline-turn-opponent-resolution-turn-quick", 8, "open"),
          absentWindowEffectGroup(1, "fixture-opponent-optional-decline-turn-opponent-resolution-first-opponent-quick", 8, "open"),
          absentWindowEffectGroup(1, "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent-quick", 8, "open"),
          absentTriggerActivationGroup(0, "fixture-opponent-optional-decline-turn-opponent-resolution-turn-optional", "turnOptional", 8, "open"),
          absentTriggerActivationGroup(1, "fixture-opponent-optional-decline-turn-opponent-resolution-second-opponent", "opponentOptional", 8, "open"),
        ],
        locations: { graveyard: ["700", "200", "900", "950"], hand: ["100", "300", "800", "400", "500", "800"] },
        logIncludes: [
          "Opponent optional decline turn opponent resolution starter resolved",
          "Opponent optional decline turn opponent resolution second opponent quick resolved",
          "Opponent optional decline turn opponent resolution turn quick resolved",
          "Opponent optional decline turn opponent resolution first opponent quick resolved",
          "Opponent optional decline turn opponent resolution first opponent resolved",
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
