import { describe, expect, it } from "vitest";
import { createCardReader } from "#engine/data-loaders.js";
import { makeResponseSelector, makeScriptedStep, runScriptedDuelFixture } from "#engine/parity.js";
import type { DuelCardData, ScriptedDuelFixture } from "#duel/types.js";
import { absentChainEffectGroup, absentWindowEffectGroup, chainEffectGroup, chainPassGroup } from "./parity-legal-action-group-helpers.js";

describe("EDOPro parity chainEnded open fast-effect chain-response turn-response opponent-response turn-response opponent-response fixture", () => {
  it("returns opponent priority after the turn player chains again to a direct post-chainEnded opponent response", () => {
    const cards: DuelCardData[] = [
      { code: "100", name: "Chain Ended Direct Opponent Turn Opponent Starter", kind: "monster", attack: 1800, defense: 1200 },
      { code: "200", name: "Chain Ended Direct Opponent Turn Opponent Solved Blocker", kind: "monster", attack: 1000, defense: 1000 },
      { code: "300", name: "Chain Ended Direct Opponent Turn Opponent Cleanup", kind: "monster", attack: 1500, defense: 1600 },
      { code: "400", name: "Chain Ended Direct Opponent Turn Opponent Open Quick", kind: "monster", attack: 1200, defense: 1200 },
      { code: "500", name: "Chain Ended Direct Opponent Turn Opponent First Opponent Chain", kind: "monster", attack: 1100, defense: 1100 },
      { code: "600", name: "Chain Ended Direct Opponent Turn Opponent First Turn Chain", kind: "monster", attack: 900, defense: 900 },
      { code: "700", name: "Chain Ended Direct Opponent Turn Opponent Opponent Open Quick", kind: "monster", attack: 800, defense: 800 },
      { code: "800", name: "Chain Ended Direct Opponent Turn Opponent Second Opponent Chain", kind: "monster", attack: 700, defense: 700 },
      { code: "900", name: "Chain Ended Direct Opponent Turn Opponent Second Turn Chain", kind: "monster", attack: 650, defense: 650 },
      { code: "1000", name: "Chain Ended Direct Opponent Turn Opponent Third Opponent Chain", kind: "monster", attack: 600, defense: 600 },
    ];
    const fixture: ScriptedDuelFixture = {
      name: "deferred chain ended open fast chain response turn response opponent-response turn-response opponent-response fixture",
      options: { seed: 648, startingHandSize: 6 },
      decks: {
        0: { main: ["100", "200", "300", "400", "600", "900"] },
        1: { main: ["500", "800", "1000", "700"] },
      },
      setup: {
        moveCards: [
          { player: 0, code: "600", from: "hand", to: "graveyard" },
          { player: 0, code: "900", from: "hand", to: "graveyard" },
          { player: 1, code: "500", from: "hand", to: "graveyard" },
          { player: 1, code: "800", from: "hand", to: "graveyard" },
          { player: 1, code: "1000", from: "hand", to: "graveyard" },
        ],
        effects: [
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-starter",
            player: 0,
            code: "100",
            location: "hand",
            event: "ignition",
            range: ["hand"],
            logMessage: "Chain ended direct opponent turn opponent starter resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-solved-blocker",
            player: 0,
            code: "200",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainSolved",
            triggerTiming: "if",
            range: ["hand"],
            logMessage: "Chain ended direct opponent turn opponent solved blocker should not resolve",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-cleanup",
            player: 0,
            code: "300",
            location: "hand",
            event: "trigger",
            triggerEvent: "chainEnded",
            triggerTiming: "if",
            optional: false,
            range: ["hand"],
            oncePerTurn: true,
            moveCardsOnResolve: [
              { player: 0, code: "200", from: "hand", to: "graveyard" },
              { player: 0, code: "600", from: "graveyard", to: "hand" },
              { player: 0, code: "900", from: "graveyard", to: "hand" },
              { player: 1, code: "500", from: "graveyard", to: "hand" },
              { player: 1, code: "800", from: "graveyard", to: "hand" },
              { player: 1, code: "1000", from: "graveyard", to: "hand" },
            ],
            logMessage: "Chain ended direct opponent turn opponent cleanup resolved",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-open-fast",
            player: 0,
            code: "400",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended direct opponent turn opponent open fast should not resolve yet",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-first-turn",
            player: 0,
            code: "600",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent first turn chain should not resolve yet",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-second-turn",
            player: 0,
            code: "900",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent second turn chain should not resolve yet",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-first",
            player: 1,
            code: "500",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent opponent first should not resolve yet",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-open",
            player: 1,
            code: "700",
            location: "hand",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "open",
            logMessage: "Chain ended direct opponent turn opponent opponent open should not resolve",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-second",
            player: 1,
            code: "800",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent opponent second should not resolve yet",
          },
          {
            id: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-third",
            player: 1,
            code: "1000",
            location: "graveyard",
            event: "quick",
            range: ["hand"],
            oncePerTurn: true,
            activationChain: "chain",
            logMessage: "Chain ended direct opponent turn opponent opponent third should not resolve yet",
          },
        ],
      },
      responses: [
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-starter" })),
        makeScriptedStep(makeResponseSelector("declineTrigger", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-solved-blocker" })),
        makeScriptedStep(makeResponseSelector("activateTrigger", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-cleanup" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-open-fast" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-first" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-first-turn" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 1, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-second" })),
        makeScriptedStep(makeResponseSelector("activateEffect", 0, { effectId: "fixture-chain-ended-direct-opponent-turn-opponent-second-turn" }), {
          snapshotRestore: "both",
          before: {
            source: "edopro",
            note: "EDOPro preserves restored turn-player priority before the second direct post-chainEnded turn response",
            phase: "main1",
            windowId: 7,
            windowKind: "chainResponse",
            waitingFor: 0,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-first", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-first-turn", sourceUid: "p0-deck-600-4" },
              { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-second", sourceUid: "p1-deck-800-1" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chainLimits: [],
            legalActionCounts: { 0: 2, 1: 0 },
            legalActionGroupCounts: { 0: 2, 1: 0 },
            legalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-second-turn", count: 1 },
              { type: "passChain", player: 0, windowId: 7, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-second-turn", 1, 7),
              chainPassGroup(0, 1, 7),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-open-fast" },
              { type: "activateEffect", player: 0, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-first-turn" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-first" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-second" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-third" },
              { type: "activateEffect", player: 1, windowId: 7, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-open" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-open-fast", 7, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-first-turn", 7),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-first", 7),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-second", 7),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-third", 7),
              absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-open", 7, "chainResponse"),
            ],
          },
          after: {
            source: "edopro",
            note: "EDOPro returns direct post-chainEnded response priority to the opponent after the restored turn response",
            phase: "main1",
            windowId: 8,
            windowKind: "chainResponse",
            waitingFor: 1,
            chain: [
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-open-fast", sourceUid: "p0-deck-400-3" },
              { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-first", sourceUid: "p1-deck-500-0" },
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-first-turn", sourceUid: "p0-deck-600-4" },
              { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-second", sourceUid: "p1-deck-800-1" },
              { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-second-turn", sourceUid: "p0-deck-900-5" },
            ],
            chainPasses: [],
            pendingTriggers: [],
            pendingTriggerBuckets: [],
            chainLimits: [],
            legalActionCounts: { 0: 0, 1: 2 },
            legalActionGroupCounts: { 0: 0, 1: 2 },
            legalActions: [
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-third", count: 1 },
              { type: "passChain", player: 1, windowId: 8, windowKind: "chainResponse", count: 1 },
            ],
            legalActionGroups: [
              chainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-third", 1, 8),
              chainPassGroup(1, 1, 8),
            ],
            absentLegalActions: [
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-open-fast" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-first-turn" },
              { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-second-turn" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-first" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-second" },
              { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-open" },
            ],
            absentLegalActionGroups: [
              absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-open-fast", 8, "chainResponse"),
              absentChainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-first-turn", 8),
              absentChainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-second-turn", 8),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-first", 8),
              absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-second", 8),
              absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-open", 8, "chainResponse"),
            ],
          },
        }),
      ],
      expected: {
        source: "edopro",
        note: "EDOPro returns direct post-chainEnded response priority to the opponent after the turn player chains again to an opponent-restored response",
        phase: "main1",
        windowId: 8,
        windowKind: "chainResponse",
        waitingFor: 1,
        chain: [
          { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-open-fast", sourceUid: "p0-deck-400-3" },
          { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-first", sourceUid: "p1-deck-500-0" },
          { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-first-turn", sourceUid: "p0-deck-600-4" },
          { player: 1, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-second", sourceUid: "p1-deck-800-1" },
          { player: 0, effectId: "fixture-chain-ended-direct-opponent-turn-opponent-second-turn", sourceUid: "p0-deck-900-5" },
        ],
        chainPasses: [],
        pendingTriggers: [],
        pendingTriggerBuckets: [],
        chainLimits: [],
        legalActionCounts: { 0: 0, 1: 2 },
        legalActionGroupCounts: { 0: 0, 1: 2 },
        legalActions: [
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-third", count: 1 },
          { type: "passChain", player: 1, windowId: 8, windowKind: "chainResponse", count: 1 },
        ],
        legalActionGroups: [
          chainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-third", 1, 8),
          chainPassGroup(1, 1, 8),
        ],
        absentLegalActions: [
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-open-fast" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-first-turn" },
          { type: "activateEffect", player: 0, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-second-turn" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-first" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-second" },
          { type: "activateEffect", player: 1, windowId: 8, windowKind: "chainResponse", effectId: "fixture-chain-ended-direct-opponent-turn-opponent-opponent-open" },
        ],
        absentLegalActionGroups: [
          absentWindowEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-open-fast", 8, "chainResponse"),
          absentChainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-first-turn", 8),
          absentChainEffectGroup(0, "fixture-chain-ended-direct-opponent-turn-opponent-second-turn", 8),
          absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-first", 8),
          absentChainEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-second", 8),
          absentWindowEffectGroup(1, "fixture-chain-ended-direct-opponent-turn-opponent-opponent-open", 8, "chainResponse"),
        ],
      },
    };

    expect(runScriptedDuelFixture(fixture, { cardReader: createCardReader(cards) })).toEqual({ ok: true, failures: [] });
  });
});
