import type { DuelEventName } from "#duel/types.js";

const duelEventNameRecord: Record<DuelEventName, true> = {
  normalSummoning: true,
  normalSummonNegated: true,
  normalSummoned: true,
  flipSummoning: true,
  flipSummonNegated: true,
  specialSummoning: true,
  specialSummonNegated: true,
  specialSummoned: true,
  monsterSet: true,
  spellTrapSet: true,
  activated: true,
  moved: true,
  destroying: true,
  destroyed: true,
  becameTarget: true,
  sentToGraveyard: true,
  sentToHand: true,
  sentToDeck: true,
  released: true,
  discarded: true,
  leftField: true,
  banished: true,
  phaseChanged: true,
  phaseDraw: true,
  phaseStandby: true,
  phaseMain1: true,
  phaseBattle: true,
  phaseMain2: true,
  phaseEnd: true,
  phaseStartDraw: true,
  phaseStartStandby: true,
  phaseStartMain1: true,
  phaseStartBattle: true,
  phaseStartMain2: true,
  phaseStartEnd: true,
  turnEnded: true,
  turnStarted: true,
  startup: true,
  adjust: true,
  chainSolved: true,
  chainSolving: true,
  chainActivating: true,
  chaining: true,
  chainNegated: true,
  chainDisabled: true,
  chainEnded: true,
  breakEffect: true,
  damageDealt: true,
  recoveredLifePoints: true,
  lifePointCostPaid: true,
  detachedMaterial: true,
  returnedToGraveyard: true,
  confirmed: true,
  sentToHandConfirmed: true,
  levelChanged: true,
  counterAdded: true,
  counterRemoved: true,
  customEvent: true,
  cardsDrawn: true,
  preDraw: true,
  controlChanged: true,
  equipped: true,
  coinTossed: true,
  diceTossed: true,
  coinTossNegated: true,
  diceTossNegated: true,
  preUsedAsMaterial: true,
  usedAsMaterial: true,
  attackDeclared: true,
  battleTargeted: true,
  battleStarted: true,
  battleConfirmed: true,
  attackDisabled: true,
  battleDestroyed: true,
  beforeDamageCalculation: true,
  damageCalculating: true,
  afterDamageCalculation: true,
  beforeBattleDamage: true,
  battleDamageDealt: true,
  damageStepEnded: true,
  positionChanged: true,
  flipSummoned: true,
};

export const duelEventNames = new Set<DuelEventName>(Object.keys(duelEventNameRecord) as DuelEventName[]);

export function isDuelEventName(value: unknown): value is DuelEventName {
  return duelEventNames.has(value as DuelEventName);
}
